AND-3550/3655 added promo views
tangem/tangem-app-android-old pull request #1003
Opened 2023-06-01 20:37 UTC by gbixahue

2023-06-06 01:35 UTC, Mama1emon requested changes

2023-06-06 01:35 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/compose/StoriesScreen.kt
> +                    TangemTheme {
Хорошо бы вынести на родительскую компоузовскую функцию

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/component/Gradient.kt
> +internal fun GradientCircle(
Можно ли обойтись обычным `Box`?
`Box(Modifier.background(Brush.radialGradient()))`

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +        verticalArrangement = Arrangement.Top,
Состояние по-умолчанию, поэтому можно было явно не писать. На твоем усмотрение

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            style = TangemTheme.typography.h1.copy(
Как мне кажется, по данному вопросу надо написать Яну. У нас есть ДС, по которой мы работаем, а такие конструкции - палки в колеса

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            textAlign = TextAlign.Center,
Нужен ли здесь Align?

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +        Text(
Этот текст должен быть в одну строчку?

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +        Text(
1) Align нужен?
2) maxLines нужен?

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            startColor = Color(0xCE164594),
Цветов тоже нет из ДС?

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            modifier = modifier
А почему modifier используется здесь?

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +fun OneInchStoriesContent(onLearnClick: () -> Unit, modifier: Modifier = Modifier) {
1) internal?
2) Не хватает превью

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/build.gradle.kts
> +    // implementation(deps.tangem.card.core)
Удалить?

2023-06-06 01:35 UTC, Mama1emon commented on features/learn2earn/impl/build.gradle.kts
> +plugins {
Можешь, пожалуйста, дизайн дать?
Я просто не совсем понимаю, почему мы это делаем отдельной фичей

2023-06-06 01:35 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/redux/HomeState.kt
> +        fun initDefaultStories(): List<Stories> = listOf(
В принципе можно было `Stories` сделать `enum` и использовать метод `.values()`

2023-06-06 01:35 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/compose/StoriesScreen.kt
> +                        .padding(start = 16.dp, top = 0.dp, end = 16.dp, bottom = 37.dp)
1) TangemDimens?
2) Предлагаю вместо 37 использовать 36. Скорее всего, дизайн немного поплыл. Не хочется такие значения тащить

2023-06-06 13:09 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/home/compose/StoriesScreen.kt
> +                        .padding(start = 16.dp, top = 0.dp, end = 16.dp, bottom = 37.dp)
Можео

2023-06-06 13:12 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/home/redux/HomeState.kt
> +        fun initDefaultStories(): List<Stories> = listOf(
Но тогда нельзя менять порядок, удалить, добавить...

2023-06-06 13:14 UTC, gbixahue commented on features/learn2earn/impl/build.gradle.kts
> +plugins {
https://www.figma.com/file/91bpyCrISuWSvUzTLmcYRc/iOS-%E2%80%93-Draft?type=design&node-id=7868%3A48071&t=6chCVllHljgixj2j-1

Можно созвониться...

2023-06-06 13:15 UTC, gbixahue commented on features/learn2earn/impl/build.gradle.kts
> +    // implementation(deps.tangem.card.core)
Пока что нет, поставлю TODO

2023-06-06 13:16 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +fun OneInchStoriesContent(onLearnClick: () -> Unit, modifier: Modifier = Modifier) {
Пока что нет интерфейса, пусть останется так... Когда появится, сделаем интернал. Поставлю todo

2023-06-06 13:17 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            modifier = modifier
Чтобы передать фону те же параметры, что и для главного контейнера

2023-06-06 13:19 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            startColor = Color(0xCE164594),
В ДС их нет, они уходят за рамки компонентов... Тем более их частично пришлось подбирать, чтоб воспроизвелась задумка авторм

2023-06-06 13:20 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +        Text(
Нет, в 2, в 3, в зависимости от устройства

2023-06-06 13:26 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/component/Gradient.kt
> +internal fun GradientCircle(
Прям так в лоб - не получается заданный эффект. При использовании background фон неправильно обрезается.

2023-06-06 14:00 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/home/compose/StoriesScreen.kt
> +                    TangemTheme {
fixed

2023-06-06 14:00 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            style = TangemTheme.typography.h1.copy(
Написано, ждем...

2023-06-06 14:00 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            textAlign = TextAlign.Center,
обязательно

2023-06-06 14:00 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +        Text(
1. обязательно
2. не нужен

2023-06-07 02:20 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/component/Gradient.kt
> +internal fun GradientCircle(
Что именно не так обрезается? `clip` пробовал?

2023-06-07 02:21 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            textAlign = TextAlign.Center,
Если я правильно понимаю, то в контейнере выставляется выравнивание по центу, а данный текст имеет размер в зависимости от его контента, поэтому не совсем понятно, что здесь он выравнивает

2023-06-07 02:32 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/compose/StoriesScreen.kt
> +                            top = TangemTheme.dimens.size0,
Вроде по-умолчанию ноль

2023-06-07 02:32 UTC, Mama1emon commented on core/ui/src/main/res/drawable/img_1inch_logo_401_378.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Данная иллюстрация есть в ДС? Если нет, то можно разместить ее в рамках фичи. Слишком специфический размер, чтобы она была переиспользуемой

2023-06-07 02:32 UTC, Mama1emon commented on features/learn2earn/impl/build.gradle.kts
> +    // implementation(deps.tangem.card.core)
Как мне кажется, что при необходимости это легче добавить, чем сейчас плодить комменты о том, что это когда-то может понадобиться.
Если в каждом билд файле так делать, то они станут нечитаемыми.

2023-06-07 02:32 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +fun OneInchStoriesContent(onLearnClick: () -> Unit, modifier: Modifier = Modifier) {
Заведи, пожалуйста, тогда задачу на себя. Будет как техдолг в беклоге, чтобы точно не потерять

2023-06-07 02:32 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            modifier = modifier
Выходит необычная ситуация. Детект тоже об этом намекает.
Мб создать общий `Box`, который будет принимать модифаер?

2023-06-07 05:58 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +fun OneInchStoriesContent(onLearnClick: () -> Unit, modifier: Modifier = Modifier) {
Этого не нужно делать, т.к. интерфейс появится в последующих ПРах

2023-06-07 05:59 UTC, gbixahue commented on features/learn2earn/impl/build.gradle.kts
> +    // implementation(deps.tangem.card.core)
Это понадобиться тогда, когда разработка фичи дойдет до того этапа, где нужно будет сканировать карту. 
Но ок, если это смущает - уберу

2023-06-07 06:01 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/component/Gradient.kt
> +internal fun GradientCircle(
Много вариантов испробовал - этот рабочий

2023-06-07 06:03 UTC, gbixahue commented on core/ui/src/main/res/drawable/img_1inch_logo_401_378.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
хорошая идея

2023-06-07 06:09 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            textAlign = TextAlign.Center,
Центрирует текст
![Uploading Снимок экрана 2023-06-07 в 09.05.37.png…]()

2023-06-07 06:09 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            modifier = modifier
Хм, думаю ты прав... верхнеуровневый Box должен все решить

2023-06-07 08:35 UTC, Mama1emon approved these changes

2023-06-07 09:34 UTC, iiiburnyiii commented on features/learn2earn/api/build.gradle.kts
> +}
Тут точно нужен android, кажется тут можно без него обойтись?
```suggestion
plugins {
    alias(deps.plugins.kotlin.jvm)
    id("configuration")
}
```

2023-06-07 09:34 UTC, iiiburnyiii commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +fun OneInchStoriesContent(onLearnClick: () -> Unit, modifier: Modifier = Modifier) {
nit: `Content` обычно отображает какое-то конкретное состояние экрана, а `Screen` это корневой компонент и контейнер для контента. Так как тут состояний нет, но это корневой компонент, то, кажется, лучше назвать `OneInchStoriesScreen`

2023-06-07 09:34 UTC, iiiburnyiii commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            bodyText = stringResource(id = R.string.story_learn_description),
nit: Лучше придерживаться одного подхода для выставления размеров и отступов на экране, для `ContentBackground` размер выставляется снаружи компонента, через modifier, а для `StoryDescription` размер и отступы выставляются внутри компонента. Мне кажется лучше выставлять это снаружи, через modifier, как это сделано для `ContentBackground`

2023-06-07 09:35 UTC, iiiburnyiii commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/OneInchStoriesScreen.kt
> +            modifier = modifier
Переданный через аргументы modifier лучше не шарить между корневым и дочерним компонентами, так верстка летит

2023-06-08 07:49 UTC, iiiburnyiii approved these changes

2023-06-08 07:49 UTC, iiiburnyiii commented on features/learn2earn/api/src/main/AndroidManifest.xml
> +<manifest package="com.tangem.features.learn2earn.api" />
Манифест можно выпилить, так как android плагина нет в этом модуле

2023-06-08 09:08 UTC, gbixahue commented on features/learn2earn/api/src/main/AndroidManifest.xml
> +<manifest package="com.tangem.features.learn2earn.api" />
fix

2023-06-08 09:56 UTC, merged