AND-3651 Add organize tokens screen initial implementation
tangem/tangem-app-android-old pull request #1006
Opened 2023-06-05 07:06 UTC by iiiburnyiii

2023-06-05 07:30 UTC, Mama1emon requested changes

2023-06-05 07:30 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/OrganizeTokensStateHolder.kt
> +internal data class HeaderConfig(
Предлагаю добавить приставку OrganizeTokens, либо переместить в скоуп StateHolder, иначе класс имеет общее название, что потом затруднит нам поиск разных компонентов проекта

2023-06-05 07:30 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/TokenListState.kt
> +    val tokens: ImmutableList<TokenV2Config>,
Немного зарефачил данную модель, чтобы стейты корректно выделялись, поэтому, скорее всего, будет траблы при мердже

2023-06-05 07:30 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +            TopBar(state.header)
Не получится ли использовать компоненты material3?

2023-06-05 07:30 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +    Column(
А для чего мы оборачиваем в колумн?

2023-06-05 07:59 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +            TopBar(state.header)
Можно, но нужно будет вынести в отдельный компонент и переопределить цвета. Кажется, оно того не стоит

2023-06-05 08:01 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +    Column(
В данном случае это не нужно, но и не мешает. Я, просто, live template для превью юзаю и мне его лениво редактировать)

2023-06-05 11:35 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/TokenListState.kt
> +    val tokens: ImmutableList<TokenV2Config>,
Окс, пока заберу эту модельку из твоего МРа

2023-06-06 01:43 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/OrganizeTokensStateHolder.kt
> +    internal data class HeaderConfig(
Вроде необязательно помечать их internal, так как они уже лежат в скоупе internal класса

2023-06-06 01:43 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +                text = "Organize tokens", // TODO: Move to resources
Мб сразу вынести?

2023-06-06 01:43 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +            Text(
Текст вроде только в одну строчку, добавим maxLines?

2023-06-06 01:43 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +    Column(
Предлагаю тогда сейчас оставить как есть, но в будущем также определиться с целевым решением и зафиксировать в доке.
Просто лично мне не очень нравится подход с Sample, потому что в превью отображается НЕ ЧИСТЫЙ компонент, а с некоторыми изменениями в Sample. Я больше за вариант, когда превью является исключительными отображением компонента

2023-06-06 01:43 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +    Column(
Можно закрывать

2023-06-06 05:34 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +    Column(
Согласен, что стоит обсудить

2023-06-06 05:35 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/OrganizeTokensStateHolder.kt
> +    internal data class HeaderConfig(
Да, забыл убрать

2023-06-06 05:53 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/OrgranizeTokensScreen.kt
> +                text = "Organize tokens", // TODO: Move to resources
Хочу сразу все строки добавить чуть позже

2023-06-08 07:22 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +                text = "Organize tokens", // TODO: Move to resources
Заменяем на ресы?

2023-06-08 07:22 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    Column(
Избыточно получается

2023-06-08 07:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +                text = "Organize tokens", // TODO: Move to resources
Отписал уже ранее, я добавил сразу все ресы тут https://github.com/tangem/tangem-app-android/pull/1010

2023-06-08 07:29 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    Column(
Поправил

2023-06-08 07:36 UTC, Mama1emon submitted a review, later dismissed

2023-06-08 08:12 UTC, Sateetas requested changes

2023-06-08 08:12 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensViewModel.kt
> +    var router: InnerWalletRouter by Delegates.notNull()
мб в конструктор?

2023-06-08 08:12 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +
почему data class?

относится ко всем трем классам

2023-06-08 09:08 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensViewModel.kt
> +    var router: InnerWalletRouter by Delegates.notNull()
Тогда не получится через хилт вью модель создавать

2023-06-08 09:09 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +
Как у же отвечал на ПР Роме для компоуза очень важен функционал сравнения по всем полям класса, а также функционал Clonable

2023-06-08 09:13 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensViewModel.kt
> +    var router: InnerWalletRouter by Delegates.notNull()
Не получиться, к сожалению, роутера нет в DI графе. Когда будем уходить от навигации в редаксе, то можно будет перепилить

2023-06-08 09:35 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +
Если ты про функциональный тип, то тут не очень кайфовый момент, но пока остановились на этом. Если в data class положить не лямбду, а референс, то он нормально сравнивается
<img width="1243" alt="изображение" src="https://github.com/tangem/tangem-app-android/assets/26351057/dd92bb1a-baf9-4ec3-a5b5-beb0c56957d9">

Если ты в общем, то это стейт compose скрина, и он должен быть data class'ом, так как он должен переопределять equals

2023-06-08 09:37 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +
В целом тема с доставкой возможных намерений до вьюхи ещё открыта, так что если есть идеи, то предлагай

2023-06-08 10:01 UTC, Mama1emon approved these changes, later dismissed

2023-06-08 10:02 UTC, Sateetas approved these changes, later dismissed

2023-06-08 13:12 UTC, Mama1emon approved these changes

2023-06-08 13:19 UTC, merged