AND-3642 Design a body with tokens
tangem/tangem-app-android-old pull request #1007
Opened 2023-06-05 07:41 UTC by Mama1emon

2023-06-05 09:33 UTC, iiiburnyiii requested changes

2023-06-05 09:33 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/extensions/Navigation.kt
> +import com.tangem.tap.features.walletSelector.ui.*
Стили опять слетели 😞

2023-06-05 09:33 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/tokens/impl/presentation/states/TokenItemState.kt
> +@Immutable
Мыж договорились не ставить immutable, после того, как я везде его пихал) Кажется это и правда лишняя штука

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/WalletContentState.kt
> +        val groups: ImmutableList<Group>,
На этом скрине токены могут отображаться без группировки, простым списком. Стоит добавить стейт под это

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/MulticurrencyContent.kt
> +    Column(
Лучше использовать `LazyColumn` - токенов может быть очень много и сразу все рисовать будет больно

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletScreen.kt
> +    SystemBarsEffect {
Может это стоит вынест во фрагмент, либо создать какой-то общий скрин для фичи? Установка цвета баров ломает превью, да и гемморно для каждого экрана это добавлять

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletScreen.kt
> +    ) { scaffoldPaddings ->
Думаю content лучше вынести в именованый аргумент, немного сбивает с толку

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletScreen.kt
> +        CompositionLocalProvider(LocalOverscrollConfiguration provides null) {
Стоит оставить overscroll, это нативная анимация и, если она ни с чем не конфликтует, то она должна быть

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletCardsList.kt
> +    CompositionLocalProvider(LocalOverscrollConfiguration provides null) {
Тут тож стоит оставить overscroll

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletCardsList.kt
> +                        LocalConfiguration.current.screenWidthDp.dp - TangemTheme.dimens.size32,
Можно вынести в отдельные переменные
```
val horizontalCardPadding = TangemTheme.dimens.spacing16
val cardWidth = LocalConfiguration.current.screenWidthDp.dp - (horizontalCardPadding * 2)
```

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletContent.kt
> +            is WalletContentState.Multicurrency -> {
Стоит добавить остальные стейты, либо переписать с `if`

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletContent.kt
> +                SpacerH(height = TangemTheme.dimens.spacing14)
nit: Может лучше через `Arrangement.spacedBy(...)`?

2023-06-05 09:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletContent.kt
> +    Button(
nit: Стоит добавит в ui-core > `Buttons.kt` > `fun ActionButton(...)`, это элемент из ДС

2023-06-05 09:33 UTC, iiiburnyiii commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/ConfigurationPlugin.kt
> +        target.configure()
Это не относиться к задаче и уже есть в МРе с добавлением метрик

2023-06-05 09:33 UTC, iiiburnyiii commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/ConfigurationPlugin.kt
> +        if (target.plugins.hasPlugin(AppPlugin::class.java)) {
Предыдущая реализация оптимальней, так как тут для каждого плагина его поиск будет начинаться сначала. В старой логике плагины конфигурировались за один проход по списку плагинов

2023-06-05 09:33 UTC, iiiburnyiii commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/configurations/DetektConfigurations.kt
> +        jvmTarget = JavaVersion.VERSION_11.toString()
Зочем?)

2023-06-05 14:29 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/tokens/impl/presentation/states/TokenItemState.kt
> +@Immutable
Я недавно в android-universe кидал доклады по оптимизации компоуз. Прочекал на метриках экран, который я уже оптимизировал и решил поправить проблему с `sealed class` - несмотря на стабильность наследников, он не понимает, что интерфейс стабильный, что влияет на количество перерисовок. В доке специально указал

2023-06-05 14:29 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/WalletContentState.kt
> +        val groups: ImmutableList<Group>,
Я не видел такой стейт, можешь, пожалуйста, ссылку дать?

2023-06-05 14:30 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/MulticurrencyContent.kt
> +    Column(
С одной стороны, согласен, но с другой, придется сразу у нескольких вертикальных списков синкать скролл. Поэтому предлагаю использовать так.

2023-06-05 14:30 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletScreen.kt
> +    SystemBarsEffect {
Да, согласен.

2023-06-05 14:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletScreen.kt
> +    ) { scaffoldPaddings ->
Как мне кажется, это дело вкуса. В большинство компоуз функций мы передаем контент через лямбду - это создает вложенность, с помощью которой упрощается восприятие ui. Типо одни ui компоненты входят в другие

2023-06-05 14:36 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletScreen.kt
> +        CompositionLocalProvider(LocalOverscrollConfiguration provides null) {
Не понимаю, почему она должна быть? В дизайне этого нет, поэтому я так и сделал.
Согласен, что лучше вернуть, потому что тогда разные экраны будут разниться

2023-06-05 14:37 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletCardsList.kt
> +    CompositionLocalProvider(LocalOverscrollConfiguration provides null) {
Уже обсуждали этот момент. Хочу сделать, как в дизайне

2023-06-05 14:37 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletCardsList.kt
> +                        LocalConfiguration.current.screenWidthDp.dp - TangemTheme.dimens.size32,
Ты уже все расписал, трудно отказаться...

2023-06-05 14:41 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletContent.kt
> +            is WalletContentState.Multicurrency -> {
Да, это обязательно случится в следующей задаче https://tangem.atlassian.net/browse/AND-3643

2023-06-05 14:42 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletContent.kt
> +                SpacerH(height = TangemTheme.dimens.spacing14)
Если для стейта с транзакциями тоже будет нужно, то вынесу в колумн

2023-06-05 14:43 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletContent.kt
> +    Button(
Да, точно. Давай запилю тогда нормальный компонент

2023-06-05 14:43 UTC, Mama1emon commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/ConfigurationPlugin.kt
> +        target.configure()
Я давно закоммитил, поэтому и прилетело

2023-06-05 14:45 UTC, Mama1emon commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/ConfigurationPlugin.kt
> +        if (target.plugins.hasPlugin(AppPlugin::class.java)) {
Проверка на наличие данного плагина разве не будет эффективней? Тогда не придется пробегаться по всем плагинами, а достаточно сделать проверку, и если там плагин есть, то сразу сконфигурировать

2023-06-05 14:46 UTC, Mama1emon commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/configurations/DetektConfigurations.kt
> +        jvmTarget = JavaVersion.VERSION_11.toString()
Пока изучал плагин быренько заменил на константу

2023-06-05 14:58 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/common/extensions/Navigation.kt
> +import com.tangem.tap.features.walletSelector.ui.*
Поправил

2023-06-05 14:58 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletScreen.kt
> +    SystemBarsEffect {
Вынес

2023-06-05 14:59 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletScreen.kt
> +        CompositionLocalProvider(LocalOverscrollConfiguration provides null) {
Убрал

2023-06-05 14:59 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletCardsList.kt
> +                        LocalConfiguration.current.screenWidthDp.dp - TangemTheme.dimens.size32,
Вынес

2023-06-06 05:01 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/WalletContentState.kt
> +        val groups: ImmutableList<Group>,
Сам экран тут в состоянии редактирования, но список разгруппирован

https://www.figma.com/file/Vs6SkVsFnUPsSCNwlnVf5U/Android-%E2%80%93-UI?type=design&node-id=3058-15096&t=SDjUZpM0eD8BtchM-4

2023-06-06 05:05 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/MulticurrencyContent.kt
> +    Column(
Можно положить токены группы в `Column`, по дефолту он не скролиться, а сами группы в `LazyColumn` котрый скролиться. Получается у нас один скролящийся список и синкать их не надо.

Можно тут глянуть в `OrganizeTokensScreen.kt > TokenList` и `NetworkGroupItem.kt`
https://github.com/tangem/tangem-app-android/pull/1010/files

2023-06-06 05:11 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletContent.kt
> +    Button(
Тож нужно было, добавил в https://github.com/tangem/tangem-app-android/pull/1010/files `Buttons.kt`

2023-06-06 05:12 UTC, iiiburnyiii commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/ConfigurationPlugin.kt
> +        if (target.plugins.hasPlugin(AppPlugin::class.java)) {
Подозреваю поиск осуществляется просто проходом по списку плагинов проекта

2023-06-06 05:12 UTC, iiiburnyiii commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/ConfigurationPlugin.kt
> +        target.configure()
Надо бы выпилить, конфликты будут

2023-06-06 07:12 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/MulticurrencyContent.kt
> +    Column(
Также еще есть общий скролл

2023-06-06 07:12 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/components/WalletContent.kt
> +    Button(
И я добавил

2023-06-06 07:31 UTC, Sateetas approved these changes, later dismissed

2023-06-09 09:23 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/state/WalletContentState.kt
> +        val groups: ImmutableList<Group>,
Добавил

2023-06-09 09:24 UTC, Mama1emon commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/ConfigurationPlugin.kt
> +        target.configure()
Выпилил

2023-06-13 06:33 UTC, Sateetas approved these changes, later dismissed

2023-06-13 06:52 UTC, iiiburnyiii requested changes

2023-06-13 06:52 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/tokens/impl/presentation/states/TokenItemState.kt
> + * Network item state.
Это же стейт токена, а не сети

2023-06-13 06:52 UTC, iiiburnyiii commented on features/wallet/impl/build.gradle.kts
> +    implementation(deps.kotlin.immutable.collections)
Ниже эта зависимость уже добавляется

2023-06-13 06:52 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/components/WalletContent.kt
> +                    text = "Organize tokens", // TODO replace with resource id
Уже есть `organize_tokens_title`

2023-06-13 06:52 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletContentState.kt
> +    sealed interface OrganizeTokensAvailability {
А зачем этот интерфейс нужен? Вроде можно без него обойтись

2023-06-14 06:45 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/tokens/impl/presentation/states/TokenItemState.kt
> + * Network item state.
Исправил

2023-06-14 06:45 UTC, Mama1emon commented on features/wallet/impl/build.gradle.kts
> +    implementation(deps.kotlin.immutable.collections)
Убрал

2023-06-14 07:01 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/components/WalletContent.kt
> +                    text = "Organize tokens", // TODO replace with resource id
Исправил

2023-06-14 07:02 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletContentState.kt
> +    sealed interface OrganizeTokensAvailability {
Легче разделять стейты с одинаковыми полями при отрисовке UI

2023-06-14 07:47 UTC, iiiburnyiii requested changes

2023-06-14 07:47 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletContentState.kt
> +    sealed interface OrganizeTokensAvailability {
Это же нужно для разделения состояния одновалюток и многовалюток?

2023-06-14 07:47 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/WalletScreen.kt
> +        }
На этом экране может быть достаточно много элементов, лучше попробовать это все засунуть в `LazyColumn`

2023-06-14 07:47 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/components/WalletCardsList.kt
> +    CompositionLocalProvider(LocalOverscrollConfiguration provides null) {
Стоит выпилить отключение overscroll'а

2023-06-14 07:51 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletContentState.kt
> +    sealed interface OrganizeTokensAvailability {
Тут нет привязки на бизнесовую состовляющую. Этот интерфейс обобщает стейты, которые имеют один и тот же функционал. Что позволяет легче реализовывать функционал и UI. Условно говоря, когда ты обрабатываешь uiState, то тебя не интересует два отдельных стейта, у которых есть обработчик кнопки - тебя интересуют все стейты, у которых есть кнопка

2023-06-14 07:53 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/components/WalletCardsList.kt
> +    CompositionLocalProvider(LocalOverscrollConfiguration provides null) {
"Третье восхождение оверскролла" ))
И третий ответ... Я хочу оставить данный горизонтальный скролл, как в дизайне.

2023-06-14 07:54 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/WalletScreen.kt
> +        }
Справедливо

2023-06-14 09:04 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletContentState.kt
> +    sealed interface OrganizeTokensAvailability {
Звучит как вещь, которую будет тяжко разруливать в коде, но давай попробуем так, посмотрим, что выйдет

2023-06-14 09:04 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletContentState.kt
> +    sealed interface OrganizeTokensAvailability {
Можно резолвить

2023-06-14 09:05 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/components/WalletCardsList.kt
> +    CompositionLocalProvider(LocalOverscrollConfiguration provides null) {
Чорт, и в третий раз не прокатило :(
nit: А можешь закинуть видос с ним и без в личку?

2023-06-14 09:43 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/WalletScreen.kt
> +        }
И `WalletContent` тоже стоит разбить на элементы

2023-06-14 11:36 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/WalletFragment.kt
> +                        setStatusBarColor(statusBarColor)
Стоит и для navigation bar тоже цвет поменять
```suggestion
                        setSystemBarsColor(systemBarsColor)
```

2023-06-20 11:15 UTC, kozarezvlad submitted a review, later dismissed

2023-06-20 12:20 UTC, Sateetas submitted a review, later dismissed

2023-06-21 04:53 UTC, iiiburnyiii requested changes

2023-06-21 04:53 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/components/WalletTopBar.kt
> +            IconButton(onClick = config.onScanCardClick) {
Стоит выставить минимальный размер кнопки в 32dp. Если кнопка меньше, то по ней кликать бывает неудобно.

2023-06-21 04:53 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletContentItemState.kt
> +}
Можно сделать так и можно будет убрать `when` в установке `id` элемента в списке

```suggestion
internal sealed interface WalletContentItemState {
    val id: String

    data class NetworkGroupTitle(val text: String) : WalletContentItemState {
       override val id = text
    }

    data class Token(val tokenItemState: TokenItemState) : WalletContentItemState {
        override val id = tokenItemState.id
    }
}
```

2023-06-21 04:53 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/WalletScreen.kt
> +                if (index == 0) NetworkGroupHeader()
Такая конструкция не прокатит, скорее всего, так как по дизайну верхний и нижний элементы имеют высоту обычного элемента списка. А в такой реализации элементы будут увеличиваться на высоту хидера и футера.
Можно попробовать сделать через modifier, как у элементов `OrganizeTokensScreen`

2023-06-21 04:53 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/WalletScreen.kt
> +                        )
Лучше использовать `NetworkGropItem` так как там уже выставлены все размеры и отступы, плюс так хидеры будут точно одинаковые для этого и organize tokens скринов

2023-06-21 05:12 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/components/WalletTopBar.kt
> +            IconButton(onClick = config.onScanCardClick) {
IconButton выставляет нужные размеры под капотом. Больше информации можешь найти в доке

2023-06-21 06:27 UTC, iiiburnyiii approved these changes

2023-06-21 06:54 UTC, kozarezvlad approved these changes

2023-06-21 06:54 UTC, merged