AND-3652 Add organize tokens screen content
tangem/tangem-app-android-old pull request #1010
Opened 2023-06-05 15:06 UTC by iiiburnyiii

2023-06-09 07:08 UTC, Sateetas approved these changes, later dismissed

2023-06-15 02:35 UTC, Mama1emon requested changes

2023-06-15 02:35 UTC, Mama1emon commented on core/res/src/main/res/values-ru/strings.xml
> +    <string name="common_apply">Применить</string>
А эта текстовка изначально появилась, как `common_`? Обычно такие текстовки заменяют другие, так как используются в нескольких местах.

2023-06-15 02:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    modifier: Modifier = Modifier,
`modifier` избыточен в данном месте

2023-06-15 02:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    val isElevationEnabled by remember {
`Scaffold` сам должен уметь проставлять тень, если список скролящийся

2023-06-15 02:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +                onClick = { config.onSortByBalanceClick() },
Можно не создавать новую лямбду, а просто ссылку передать.
`onClick = config.onSortByBalanceClick,`

2023-06-15 02:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +                onClick = { config.onGroupByNetworkClick() },
Здесь тоже

2023-06-15 02:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +            onClick = { config.onCancelClick() },
Здесь тоже

2023-06-15 02:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +            onClick = { config.onApplyClick() },
Здесь тоже

2023-06-15 02:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +private fun TokenList(listState: LazyListState, state: TokenListState, modifier: Modifier = Modifier) {
Выходит достаточно большой класс, мб вынести некоторые компоненты?

2023-06-15 02:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +        Box(
Подскажи, а что это за градиент полупрозрачный?

2023-06-15 04:47 UTC, iiiburnyiii commented on core/res/src/main/res/values-ru/strings.xml
> +    <string name="common_apply">Применить</string>
Да, я добвалял как common

2023-06-15 04:49 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    modifier: Modifier = Modifier,
Много раз обсуждали, но когда я пилил core компоненты решили оставлять, даже если избыточен
С `modifier` в параметрах код легче поддерживать, возможно не в конкретном случае, а в целом

2023-06-15 04:49 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    val isElevationEnabled by remember {
Я немного поискал, но не нашел. Есть ссылка под рукой?

2023-06-15 04:51 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +                onClick = { config.onSortByBalanceClick() },
Странно, вродь поправлял раньше
Поправил

2023-06-15 04:56 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +        Box(
Его нет на ios скринах, но есть у нас
<img width="432" alt="изображение" src="https://github.com/tangem/tangem-app-android/assets/26351057/faf5a694-3992-4fcd-a156-ec337e4c6ee0">

2023-06-15 04:59 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +private fun TokenList(listState: LazyListState, state: TokenListState, modifier: Modifier = Modifier) {
Мне кажется в случае UI не стоит, потом гемморно по ним перемещаться. Если у тебя компонент либо переиспользуется, либо он больше 70 строк, то стоит выносить. Кучу мелких файлов сложнее поддерживать, чем несколько средних

2023-06-15 06:18 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    modifier: Modifier = Modifier,
Компонент пилится под определенную фичу и используется исключительно в одном месте. Не понимаю смысл кода, который не используется. Просто что бы он был?

2023-06-15 06:20 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    val isElevationEnabled by remember {
Аа, я понял. Ты используешь TopAppBar не из `material`.
Предлагаю затащить его, так как он уже имеет этот функционал из коробки.

2023-06-15 06:23 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +private fun TokenList(listState: LazyListState, state: TokenListState, modifier: Modifier = Modifier) {
Я предлагаю вынести большую функцию / набор функций, так как поддерживать файл из большого количества мелких функций на 250 строк тоже не просто.
А когда видишь файл, который реализует какой-то большой компонент экрана, то сразу понимешь, что там ничего лишнего

2023-06-15 06:24 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +        Box(
Можешь, пожалуйста, уточнить у Яна, так как iOS макет самый свежий?

2023-06-15 11:02 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    val isElevationEnabled by remember {
Его не получиться затащить из-за нестандартного положения кнопок

2023-06-15 11:04 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    modifier: Modifier = Modifier,
В данном случае да, он тут только для единообразия

2023-06-15 11:12 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +private fun TokenList(listState: LazyListState, state: TokenListState, modifier: Modifier = Modifier) {
Тут вопрос вкусовщины и привычек, мне комфортнее когда достаточно сильно связанные UI компоненты лежат в одном файле. Офк в разумных пределах, если получается файл на 500 строк и там большие компоненты, то это нужно растаскивать на разные файлы
Если это для тебя важно, то предлагаю вынести на обсуждение

2023-06-15 11:13 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +        Box(
Ошибся на ios он тоже есть

2023-06-15 11:20 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    modifier: Modifier = Modifier,
Единообразия с чем?

2023-06-15 11:21 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +private fun TokenList(listState: LazyListState, state: TokenListState, modifier: Modifier = Modifier) {
Я тебя понял, предлагаю скипнуть данный вопрос

2023-06-15 11:22 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    modifier: Modifier = Modifier,
Единообразия с остальными компонентами

2023-06-15 11:23 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    val isElevationEnabled by remember {
В material2 есть компонент `TopAppBar`, который позволяет добавить любой контент. В чем именно проблема возникает?

2023-06-19 13:24 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    val isElevationEnabled by remember {
Он не подходит, так как выставляет максимальную высоту внутри себя и получается, что кнопки не влезают

2023-06-19 14:26 UTC, Mama1emon approved these changes

2023-06-20 08:47 UTC, kozarezvlad approved these changes

2023-06-20 09:21 UTC, merged