AND-3402: allow custom derivation in adding custom tokens
tangem/tangem-app-android-old pull request #1011
Opened 2023-06-06 08:53 UTC by roman-pv

2023-06-06 09:12 UTC, Sateetas requested changes

2023-06-06 09:12 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> +    data class DerivationPath(
какой смысл делать дата-класс? у тебя же в полях есть не serializable поля, на них equals и hash code сломается

2023-06-06 09:12 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/viewmodels/AddCustomTokenViewModel.kt
> +                placeholder = TextReference.Str(value = "m/44'/0'/0'/0/0"),
я бы вынес m/44'/0'/0'/0/0 в отдельную переменную

2023-06-06 13:37 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> +    data class DerivationPath(
для стейтов почти всегда удобнее использовать data classes,  потому что copy реализовано сразу

2023-06-06 13:40 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/viewmodels/AddCustomTokenViewModel.kt
> +                placeholder = TextReference.Str(value = "m/44'/0'/0'/0/0"),
можно, для плейсхолдеров на мой взгляд не обязательно, но можно. Только тогда надо будет по всему файлу пройтись остальные плейсхолдеры вынести.

2023-06-07 02:19 UTC, Mama1emon requested changes

2023-06-07 02:19 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> +    data class DerivationPath(
@Sateetas компоуз сравнивает данные, которые поступают в функцию, по `equals`. Если сравнивать по ссылке, то количество перерисовок увеличится во много раз, так как вся родительская функция будет думать, что все данные изменились.

@roman-pv Но тут возникает вопрос со стабильностью данных, надо бы прогнать метрики и убрать unstable поля.

2023-06-07 02:19 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> + * @property showTokenFields             if token fields should be shown
Правильно понимаю, что если `showTokenFields = false`, то данные поля не будут отрисовываться?
```
val networkSelectorField: AddCustomTokenSelectorField.Network,
val tokenNameInputField: AddCustomTokenInputField.TokenName,
val tokenSymbolInputField: AddCustomTokenInputField.TokenSymbol,
val decimalsInputField: AddCustomTokenInputField.Decimals,
```

2023-06-07 02:19 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> +            val type: DerivationPathSelectorType = DerivationPathSelectorType.BLOCKCHAIN,
В `NetworkSelector` это поле тоже нужно?

2023-06-07 06:35 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> + * @property showTokenFields             if token fields should be shown
да не будут показываться, но только поля, связанные с токенами: 
contractAddressInputField
tokenNameInputField
 tokenSymbolInputField
 decimalsInputField

2023-06-07 06:37 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> +            val type: DerivationPathSelectorType = DerivationPathSelectorType.BLOCKCHAIN,
нет, но TitleWithSubtitle используется только в DerivationPathSelector

2023-06-07 06:38 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> +    data class DerivationPath(
@Mama1emon здесь те же поля, как в окружающих дата классах, ничего дополнительного нестабильного не добавлено

2023-06-07 08:51 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> + * @property showTokenFields             if token fields should be shown
Получается, что это совершенно новый стейт экрана. Предлагаю вынести в отдельный стейт

2023-06-07 09:36 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> + * @property showTokenFields             if token fields should be shown
Логично. Посмотрю, насколько легко это переделать

2023-06-08 06:52 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> + * @property showTokenFields             if token fields should be shown
Я посмотрел, это как-то сильно во многих местах код усложняет, я не уверен, что оправдано. Плюс мне кажется, что это будет только затруднять дальнейшие изменения, не сделает код более гибким

2023-06-08 06:55 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/models/AddCustomTokenViewsModels.kt
> + * @property showTokenFields             if token fields should be shown
у нас тут уже файл с ViewModel на 800+ строк, если еще обработку этих стейтов добавлять, он еще разрастется. Его было бы хорошо почистить, но у меня и так маленькая задачка вылилась в довольно большой ПР

2023-06-08 07:55 UTC, iiiburnyiii approved these changes

2023-06-08 07:55 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/presentation/viewmodels/AddCustomTokenViewModel.kt
> +    private fun updateStateWithDerivationError(uiState: AddCustomTokenStateHolder): AddCustomTokenStateHolder {
nit: кажется `updateStateWith` можно просто заменить на `show`

2023-06-08 10:21 UTC, Mama1emon approved these changes

2023-06-08 13:04 UTC, Sateetas approved these changes

2023-06-08 13:04 UTC, merged