AND-3649 1inch: made an intent handler for appropriate monitoring of …
tangem/tangem-app-android-old pull request #1015
Opened 2023-06-07 01:35 UTC by gbixahue

…external intents

2023-06-07 03:31 UTC, Mama1emon requested changes

2023-06-07 03:31 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
А `MainIntentHandler` не должен ли наследоваться от `IntentHandler`?

2023-06-07 03:31 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/intentHandler/handlers/SellCurrencyIntentHandler.kt
> +    companion object {
Можно было повесить `private` модификатор сразу на компаньон

2023-06-07 03:31 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/welcome/redux/WelcomeMiddleware.kt
> +            else -> Unit
Как мне кажется, прошлая форма с перечислением была лучше, потому что если ты добавишь новый `WelcomeAction`, то `when` явным образом тебе не скажет, что ты забыл добавить обработку

2023-06-07 03:35 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
Тогда лучше его закрыть более широким интерфейсом, который бы покрывал его как хэндлера и как держателя хендлеров

2023-06-07 03:39 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/welcome/redux/WelcomeMiddleware.kt
> +            else -> Unit
Если подходить со стороны "забыл", то в этом варианте должно присутствовать слово "обязательно к реализации", чего в данном случае нет. Плюс в новом варианте при поиске по Action ты сразу видишь, что у него нет реализации в middleware и нет нужды проваливаться и смотреть, что там за код.

2023-06-07 03:41 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
Ок, пока в DI не выносим, оставим так

2023-06-07 03:42 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
Можно закрывать

2023-06-07 03:42 UTC, Mama1emon approved these changes

2023-06-07 05:50 UTC, iiiburnyiii requested changes

2023-06-07 05:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +        intentHandlers.toList().forEach {
Зачем тут `.toList()` хандлеры же и так в листе хранятся?

2023-06-07 05:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
Немного смущает, что один хендлер может подключать в себя другие хендлеры и упарвлять ими, кажется стоит как-то по другому назвать эту сущность. Если не ходить далеко, то можно что-то типа `CompoundIntenHandler`

2023-06-07 05:52 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +        intentHandlers.toList().forEach {
для того, чтобы уйти от ConcurrentModificationException

2023-06-07 05:52 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
Можно и так

2023-06-07 07:20 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +        intentHandlers.toList().forEach {
Тут лучше использовать потокобезопасный список, тогда точно проблем не будет. `CopyOnWriteList` как-то так называется

2023-06-07 07:21 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
`Handler` - все одно. Лучше, конечно, использовать что-то другое, чтобы отличить от реализаций хендлеров

2023-06-07 07:38 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
Предлагайте

2023-06-08 07:26 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/intentHandler/MainIntentHandler.kt
> +class MainIntentHandler {
Остановились на IntentProcessor

2023-06-08 10:30 UTC, Sateetas approved these changes

2023-06-08 12:55 UTC, iiiburnyiii approved these changes

2023-06-08 12:57 UTC, merged