AND-3739 Amplitude/Send screen/Add address events
tangem/tangem-app-android-old pull request #1019
Opened 2023-06-08 12:58 UTC by Mama1emon

2023-06-08 13:28 UTC, iiiburnyiii requested changes

2023-06-08 13:28 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/qrCodeScan/ScanQrCodeActivity.kt
> +        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
Это ничего не ломает?

2023-06-08 13:28 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/send/ui/EditTextCustomPaste.kt
> +    constructor(context: Context, attrs: AttributeSet?, defStyle: Int) : super(context, attrs, defStyle)
Лучше использовать аннотацию JvmOverloads, пример можно глянуть в `TotalBalanceCard`

2023-06-08 13:30 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/send/ui/EditTextCustomPaste.kt
> +        if (id == R.id.paste) Analytics.send(Token.Send.AddressEntered())
Странно, что вьюха отправляет аналитку, надо уходить от этого подхода. Может получиться пока перенести это во фрагмент? В дальнейшм стоит кидать аналитику только из view model

2023-06-09 07:59 UTC, Sateetas approved these changes, later dismissed

2023-06-13 08:53 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/common/qrCodeScan/ScanQrCodeActivity.kt
> +        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
Откатил

2023-06-13 14:12 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/send/ui/EditTextCustomPaste.kt
> +    constructor(context: Context, attrs: AttributeSet?, defStyle: Int) : super(context, attrs, defStyle)
Исправил

2023-06-13 14:12 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/send/ui/EditTextCustomPaste.kt
> +        if (id == R.id.paste) Analytics.send(Token.Send.AddressEntered())
Исправил

2023-06-13 14:16 UTC, iiiburnyiii approved these changes

2023-06-13 14:17 UTC, Sateetas approved these changes

2023-06-13 14:25 UTC, merged