AND-3654 Implement drag-n-drop sorting on organize tokens screen
tangem/tangem-app-android-old pull request #1034
Opened 2023-06-14 07:37 UTC by iiiburnyiii

2023-06-20 12:47 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +        is TokenItemState.Draggable -> DraggableTokenItem(state, reorderableTokenListState = null, modifier)
мб сделать в `reorderableTokenListState` `DraggableTokenItem` последним параметром и добавить значение по умолчанию `null`?

2023-06-20 12:59 UTC, Sateetas submitted a review, later dismissed

2023-06-20 12:59 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +    onDragStart: ((DraggableItem) -> Unit)?,
почему nullable?

2023-06-21 06:47 UTC, Mama1emon requested changes

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/NetworkGroupItem.kt
> +                modifier = Modifier.detectReorder(reorderableTokenListState),
Получается для перемещения нужно зажать иконку, а не любую точку итема?

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +                    .let {
На мой взгляд, `apply` подходит здесь больше, так как вся работа заключается в вызове метода при определенном условии (паттерн билдер)

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +    reorderableTokenListState: ReorderableLazyListState?,
А для чего происходит данное разделение? Могут быть объекты, которые нельзя двигать, но они являются `Draggable`?

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +                    Box(modifier = Modifier.fillMaxWidth())
Невидимое пространство с нулевой высотой? Не совсем понял, как это работает

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    data class DragConfig(
На мой взгляд - это является частью списка и не имеет отдельное представление, стоит совместить со стейтом списка

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    data class GroupDivider(
Разделитель как отдельный итем?

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensViewModel.kt
> +    @Volatile
Не будет ли оптимальнее использовать потокобезопасный словарь?

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensViewModel.kt
> +            ?: return true
Если это не итем со сгруппированными по сетям токенами, то мы можем перемещать итем?

2023-06-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensViewModel.kt
> +            .groupBy { it.groupId }
Дело вкуса, но можно заюзать `method reference`

2023-06-21 08:20 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/NetworkGroupItem.kt
> +                modifier = Modifier.detectReorder(reorderableTokenListState),
Да, если на весь item повесить, то не удобно скролить список. Можно ещё на long press, но тогда смысл иконки теряется, как по мне

2023-06-21 08:25 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +    reorderableTokenListState: ReorderableLazyListState?,
`Draggable` тут просто определяет стиль элемента. В данный момент этот элемент можно двигать во всех местах вызова и это парметр nullable только для превью

2023-06-21 08:27 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +                    Box(modifier = Modifier.fillMaxWidth())
Это небольшой костыль для DND, он используется для опеределения позиции куда может быть перемещена группа. Добавлю коммент в код

2023-06-21 08:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    data class DragConfig(
Тоже так снала сделал, но тогда сложнее менять состояние списка из-за того, что это sealed class

2023-06-21 08:29 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    data class GroupDivider(
Уже отписал выше зачем он нужен, добавлю доку

2023-06-21 08:30 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensViewModel.kt
> +            ?: return true
Если токены не сгруппированы, то элемент может быть помещен куда угодно

2023-06-21 08:54 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensViewModel.kt
> +    @Volatile
Это переедет в domain, поставил todo

2023-06-21 09:29 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +                    .let {
Тут `apply` не подойдет, так как методы modifier'а не изменяют существующий объект, а создают новый

2023-06-21 12:41 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/NetworkGroupItem.kt
> +                modifier = Modifier.detectReorder(reorderableTokenListState),
Синкал с iOS?

2023-06-21 12:42 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +    reorderableTokenListState: ReorderableLazyListState?,
Превью компоуза?

2023-06-21 12:42 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    data class DragConfig(
В чем именно сложность заключается?

2023-06-21 13:24 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/NetworkGroupItem.kt
> +                modifier = Modifier.detectReorder(reorderableTokenListState),
Да

2023-06-21 13:24 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +    reorderableTokenListState: ReorderableLazyListState?,
Да

2023-06-21 13:32 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    data class DragConfig(
Все эти колбеки дублируются при переключении между стейтами, нужно писать кастомный `copy`, есть шанс того, что где-то компоуз запомнит ламбду от другого, например в `rememberReorderableLazyListState()`

2023-06-21 13:36 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +    reorderableTokenListState: ReorderableLazyListState?,
На мой взгляд, создавать дополнительные поля в стейте ради превью - не очень правильной затеей. Получается у нас прод логика перемешивается с дев. Почему нельзя обойтись без перемешивания?

2023-06-21 13:42 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    data class DragConfig(
Компоуз не запомнит лябмду от другого, так как стейт поменяется полностью. Не понимаю реальных сложностей, так как создание четко структуированного стейт позволит верстать UI удобно и оптимизированно (для компоуз). Плюс соотношение один стейт - одна функция (которая его принимает) сделает код чище

2023-06-21 13:48 UTC, Mama1emon requested changes, later dismissed

2023-06-21 13:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +        val lastItemIndex = remember(state.items) {
Лучше сравнивать не по ссылке на список, а по его размеру, так как ссылка может измениться, а количество объектов остатся одним и тем же

2023-06-22 10:54 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    data class DragConfig(
Этот подход не всегда делает код чище, как и многоие другие практики) В данном случае такой подход не сильно упрощает реализацию UI, но сильно усложнает манипуляции со стейтом во view model
Плюс `rememberReorderableLazyListState()` реализван так, что этот стейт не пересоздается при измении лямбд, которые в него переданы, получается, что лямбда внутри `ReorderableLazyListState()` вызывает немерение из уже устаревшего стейта

2023-06-22 10:55 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +    reorderableTokenListState: ReorderableLazyListState?,
Тут конечно можно обмазаться дополнительными абстракциями, но мне кажется это излишне, так как не сильно аффектит "прод" логику

2023-06-22 11:03 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensScreen.kt
> +        val lastItemIndex = remember(state.items) {
remember можно вообще выпилить

2023-06-26 06:59 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +    reorderableTokenListState: ReorderableLazyListState?,
А что тут решилось в итоге?

2023-06-26 07:03 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/component/TokenItem.kt
> +    reorderableTokenListState: ReorderableLazyListState?,
Пока ничего)

2023-06-26 11:19 UTC, Sateetas approved these changes, later dismissed

2023-06-26 13:10 UTC, gbixahue commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/WalletPreviewData.kt
>              val n = index + 1
Можно дать более развернутое название для `n`. 
Это `nextIndex` ?

2023-06-26 13:11 UTC, gbixahue submitted a review, later dismissed

2023-06-26 13:56 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/WalletPreviewData.kt
>              val n = index + 1
Поправил

2023-06-27 07:13 UTC, gbixahue approved these changes

2023-06-27 07:14 UTC, Sateetas approved these changes

2023-06-27 09:02 UTC, merged