AND-3661 made a business logic for the new and the old card holders
tangem/tangem-app-android-old pull request #1046
Opened 2023-06-19 05:53 UTC by gbixahue

2023-06-19 11:50 UTC, kozarezvlad requested changes

2023-06-19 11:50 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        runBlocking {
в init же идет запрос в сеть, а runBlocking - Runs a new coroutine and blocks the current thread until its completion. This function should not be used from a coroutine. It is designed to bridge regular blocking code to libraries that are written in suspending style, to be used in main functions and in tests.

2023-06-19 12:05 UTC, Mama1emon requested changes

2023-06-19 12:05 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/redux/HomeReducer.kt
> +                stories = state.stories.toMutableList().apply {
Можно заменить на компактный вариант: `listOf(action.story) + state.stories`

2023-06-19 12:05 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/network/auth/di/AuthModule.kt
> +    fun provideTangemBasicAuthProvider(configManager: ConfigManager): com.tangem.lib.auth.BasicAuthProvider {
Стоит добавить импорт

2023-06-19 12:05 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/PromotionApi.kt
> +interface PromotionApi {
Предлагаю тэг автора писать последним.
```
/**
 * Promotion API
 *
 * @see <a href = "https://www.notion.so/tangem/Promotion-Program-API-0907159c3fdb4975aac761be632f44da">Documentation<a/>
 *
 * @author Anton Zhilenkov on 05.06.2023.
 */
```

2023-06-19 12:05 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/PromotionApi.kt
> +    /**
Английский язык?

2023-06-19 12:05 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/PromotionApi.kt
> +    companion object {
private?

2023-06-19 12:05 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/models/AbstractPromotionResponse.kt
> +        companion object
Для чего компаньон нужен?

2023-06-19 12:05 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/models/AbstractPromotionResponse.kt
> +abstract class AbstractPromotionResponse {
Мб использовать вместо `Abstract` приставку `Base`.
Как мне кажется, использование ключевых слов в названиях - это антипаттерн.

2023-06-19 12:05 UTC, Mama1emon commented on core/utils/src/main/java/com/tangem/utils/extensions/Any.kt
> +fun <T> T.toWeakReference(): WeakReference<T> {
А где это используется?

2023-06-19 12:05 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    private val promotionInfoAdapter = moshi.adapter(PromotionInfoResponse::class.java)
Может быть сразу адаптер передавать в конструктор репозитория?

2023-06-19 12:05 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +        return runCatching {
Хорошей практикой main-safety является реализовывать функции компонентов так, чтобы они сами устанавливали нужный им поток. В данном случае IO

2023-06-19 12:05 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultPreferenceStorage.kt
> +internal class DefaultPreferenceStorage(
А почему не используешь единое решение, которое у нас уже есть?

2023-06-19 12:05 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/api/Learn2earnRepository.kt
> +    fun isHadActivatedCards(): Boolean
Хорошо бы добавить пустые строки, иначе код сложночитаемый

2023-06-19 12:05 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/api/Learn2earnRepository.kt
> +    suspend fun codeValidate(walletId: String, code: String?): CodeValidateResponse
Хорошей практикой считаешься использовать глаголы в названиях функций

2023-06-19 12:05 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +    basicAuthProvider: BasicAuthProvider,
Может быть сразу передавать здесь значение из конфига? `BasicAuthProvider` кажется лишней оберткой

2023-06-19 12:16 UTC, kozarezvlad commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +        return runCatching {
https://developer.android.com/kotlin/coroutines/coroutines-best-practices

2023-06-20 11:50 UTC, Sateetas requested changes

2023-06-20 11:50 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +            preferencesStorage.promotionInfo = null
а смысл занулять персистент сторадж при ошибке?

2023-06-20 11:50 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/Learn2earnInteractor.kt
> +    suspend fun init()
переносы строк просятся

2023-06-20 11:50 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/di/Learn2earnDomainModule.kt
> +        return Learn2earnRouter(context.toWeakReference())
а зачем морочиться с weakreference, если application context передаешь?

конкретно тут нет смысла беспокоиться об утечке памяти, потому что application у тебя существует всегда, он не утечет

2023-06-20 11:50 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/di/Learn2earnDomainModule.kt
> +            userCountryCodeProvider = { "ru" },
хардкод "ru"?

2023-06-21 10:04 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/PromotionApi.kt
> +    companion object {
Можно только 1 переменную

2023-06-21 10:04 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/PromotionApi.kt
> +    /**
Это был для себя комменты. Пусть останется только документация

2023-06-21 10:16 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +    basicAuthProvider: BasicAuthProvider,
Переделал немного, чтоб не было просто прокладкой для строки.

2023-06-21 10:17 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +            preferencesStorage.promotionInfo = null
в том, чтобы удалить в сторедже не валидный джсон

2023-06-21 10:18 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/di/Learn2earnDomainModule.kt
> +            userCountryCodeProvider = { "ru" },
исправим в след ПРах. Пока не нашел хорошего способа поставить туда локаль

2023-06-21 10:20 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/di/Learn2earnDomainModule.kt
> +        return Learn2earnRouter(context.toWeakReference())
Хорошее замечание, но Learn2earnRouter может работать с любым контекстом, он не знает, что это ApplicationContext

2023-06-21 10:23 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultPreferenceStorage.kt
> +internal class DefaultPreferenceStorage(
Не хотел вшиваться временной фичей в него, поэтому решил создать внутреннее хранилище

2023-06-21 10:36 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        runBlocking {
В этой ситуации мне нужно заблокировать главный поток для инициализации 1inch интерактора, т.к. только после этого можно отпустить application а дать возможно запуститься сторисам, на которых то ли должен быть 1inch экран, то ли нет.

Открыт для обсуждения

2023-06-21 10:38 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +            preferencesStorage.promotionInfo = null
хм, секунду, это сохранение. Да, ты прав, тут оно ни к чему!

2023-06-21 11:37 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/PromotionApi.kt
> +    companion object {
В таком случае вопрос касательно объявления данной переменной в рамках ретрофит интерфейса. Объявлять именно там, где она нужна.

2023-06-21 11:42 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/di/Learn2earnDomainModule.kt
> +        return Learn2earnRouter(context.toWeakReference())
Будет странно передавать контекст активити для хранения в другой компонент, такое следует строго избегать. Дополнительное защитой здесь является как раз таки ревью кода.

2023-06-21 11:52 UTC, Mama1emon requested changes

2023-06-21 11:52 UTC, Mama1emon commented on .idea/codeStyles/Project.xml
>        <option name="ALLOW_TRAILING_COMMA" value="true" />
Вероятно, ты не добавил данные правила в свой кодстал. Проверь, пожалуйста. Эти строчки нельзя удалять

2023-06-21 11:52 UTC, Mama1emon commented on app/src/main/assets/tangem-app-config
> +Subproject commit fad890b2a0b552be60d124949ca0a3a4d672dac1
Точно обновлен сабмодуль до последней версии?

2023-06-21 11:52 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/redux/HomeAction.kt
> +    data class InsertStory(val position: Int, val story: Stories) : HomeAction()
А для чего position передается?

2023-06-21 11:52 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/api/UsedCardsPreferenceStorage.kt
> +interface UsedCardsPreferenceStorage {
Данный компонент уйдет вместе с уходом акции? Если да, то можно объединить с Learn2earnPreferenceStorage

2023-06-21 11:52 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +    userCountryCodeProvider: () -> String,
А зачем из вне это получать?

2023-06-21 11:55 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +    basicAuthProvider: BasicAuthProvider,
Вопрос с созданием компонента остается. На мой взгляд, получить из конфиг менеджера данные можно без создания отдельного компонента

2023-06-23 05:25 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +    basicAuthProvider: BasicAuthProvider,
В следующем ПРе он удален

2023-06-23 05:32 UTC, gbixahue commented on app/src/main/assets/tangem-app-config
> +Subproject commit fad890b2a0b552be60d124949ca0a3a4d672dac1
На момент написания - да была последняя, где присутствуют нужные данные для авторизации

2023-06-23 05:34 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +    userCountryCodeProvider: () -> String,
Ты предлагаешь делать дополнительный запрос?

2023-06-23 05:34 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/api/UsedCardsPreferenceStorage.kt
> +interface UsedCardsPreferenceStorage {
В следующем ПР его уже нет. Оказался не нужен, т.к. пересмотрели способ определения старого пользователя

2023-06-23 05:37 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/home/redux/HomeAction.kt
> +    data class InsertStory(val position: Int, val story: Stories) : HomeAction()
Сторисы отображаются в зависимости от того, как они добавлены в список. 
position дает возможность вставить сторю в любое место.

2023-06-23 05:52 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/models/AbstractPromotionResponse.kt
> +abstract class AbstractPromotionResponse {
Не хотел как раз использовать `Base`, т.к. во многих случаях `Base` подразумевает то, что объект этого класса можно создать, а `Abstract` дает четкое понимание того, что создать его невозможно и для использования нужно смотреть наследников или расширять его своим классом

2023-06-23 05:52 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/models/AbstractPromotionResponse.kt
> +        companion object
Уже не нужен. Рудимент

2023-06-23 05:52 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    private val promotionInfoAdapter = moshi.adapter(PromotionInfoResponse::class.java)
В следующем ПРе будет 2 адаптера. Не хочется из-за этого раздувать конструктор

2023-06-23 06:13 UTC, gbixahue commented on .idea/codeStyles/Project.xml
>        <option name="ALLOW_TRAILING_COMMA" value="true" />
Видимо версия студии не знает об этих параметрах и каждый раз пытается их стереть. В этот раз не досмотрел.

2023-06-23 06:42 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/redux/HomeAction.kt
> +    data class InsertStory(val position: Int, val story: Stories) : HomeAction()
Я не нашел реализацию логики вставки по определенной позиции

2023-06-23 06:42 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/models/AbstractPromotionResponse.kt
> +abstract class AbstractPromotionResponse {
В таком случае, можно снова вернуться к использованию суффикса `Impl`. Но мы делать этого не будем, так как ранее доказали, что это антипаттерн ))

Не буду блочить МР этим, если коллегам будет норм, то лайкайте

2023-06-23 06:49 UTC, Mama1emon requested changes

2023-06-23 06:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +    userCountryCodeProvider: () -> String,
Я предлагаю на уровне репозитория хардкодить, а не передавать из вне

2023-06-23 06:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +        // return Promotion.dummyActive()
Лишнее?

2023-06-23 06:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/api/Learn2earnRepository.kt
> +    suspend fun codeValidate(walletId: String, code: String?): CodeValidateResponse
Поправится?

2023-06-23 06:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +        return withContext(dispatchers.io) {
Можно упростить `runCatching(dispatchers.io) { }`

2023-06-23 07:13 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/api/Learn2earnRepository.kt
> +    suspend fun codeValidate(walletId: String, code: String?): CodeValidateResponse
Да, уже поправлено в следующем ПРе

2023-06-23 07:18 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/home/redux/HomeAction.kt
> +    data class InsertStory(val position: Int, val story: Stories) : HomeAction()
Была...
Нашел. Это следствие упрощения добавления сторисов по предложенным комментам. Согласился на них совсем упустив логику вставки по позиции
```
state = state.copy(
                stories = listOf(action.story) + state.stories,
            )
```
stories = state.stories.toMutableList().apply {
                    add(action.position, action.story)
                },
```

2023-06-23 07:22 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +    userCountryCodeProvider: () -> String,
В момент инициализации DefaultLearn2earnInteractor `userCountryCode` еще не сушествует

2023-06-23 07:28 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +        return withContext(dispatchers.io) {
В следующем ПРе уже сделано

2023-06-23 07:50 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/Learn2earnInteractor.kt
> +    suspend fun init()
done

2023-06-23 07:50 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/di/Learn2earnDomainModule.kt
> +        return Learn2earnRouter(context.toWeakReference())
done

2023-06-23 07:53 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +        // return Promotion.dummyActive()
done

2023-06-23 07:54 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +        return withContext(dispatchers.io) {
done

2023-06-23 09:36 UTC, Mama1emon approved these changes

2023-06-26 07:41 UTC, kozarezvlad commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/di/Learn2earnDomainModule.kt
> +            userCountryCodeProvider = { "ru" },
Запровайдить локаль приложения можно в граф

2023-06-26 07:42 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        runBlocking {
Что тут в итоге вышло, есть видео мб?

2023-06-26 08:32 UTC, Sateetas approved these changes

2023-06-26 09:24 UTC, kozarezvlad approved these changes

2023-06-26 10:53 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        runBlocking {
Решили пока что сделать так
https://tangem.atlassian.net/browse/AND-3859

2023-06-26 10:55 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/di/Learn2earnDomainModule.kt
> +            userCountryCodeProvider = { "ru" },
В следуюещем ПРе будет провайдинг от глобального состояния

2023-06-26 10:55 UTC, merged