AND-3816 changed conditions disabling send btn
tangem/tangem-app-android-old pull request #1054
Opened 2023-06-20 12:45 UTC by kozarezvlad

2023-06-20 13:05 UTC, Sateetas requested changes

2023-06-20 13:05 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/wallet/ui/utils/WalletDataOperations.kt
> +        && hasPendingTransactions() //status.pendingTransactions.isEmpty()
коммент нужен?

2023-06-20 13:05 UTC, Sateetas commented on gradle/dependencies.toml
> +#tangemBlockchainSdk = "develop-240"
зацепил лишнее?

2023-06-21 03:55 UTC, kozarezvlad commented on gradle/dependencies.toml
> +#tangemBlockchainSdk = "develop-240"
Это как зальется связанный в сдк ПР поправлю на версию

2023-06-21 03:55 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/wallet/ui/utils/WalletDataOperations.kt
> +        && hasPendingTransactions() //status.pendingTransactions.isEmpty()
забыл, уберу

2023-06-21 06:53 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/ui/utils/WalletDataOperations.kt
> +        (currency.blockchain == Blockchain.Bitcoin || currency.blockchain == Blockchain.BitcoinTestnet)) {
Если вынести в локальную переменную, то улучшится читаемость.
`val isBitcoinBlockchain = currency.blockchain == Blockchain.Bitcoin || currency.blockchain == Blockchain.BitcoinTestnet`

2023-06-21 06:53 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/ui/utils/WalletDataOperations.kt
> +        (currency.blockchain == Blockchain.Bitcoin || currency.blockchain == Blockchain.BitcoinTestnet)) {
`if (currency.isBlockchain() && isBitcoinBlockchain) {`

2023-06-22 10:20 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/wallet/ui/utils/WalletDataOperations.kt
> +        (currency.blockchain == Blockchain.Bitcoin || currency.blockchain == Blockchain.BitcoinTestnet)) {
Поправил

2023-06-22 10:20 UTC, kozarezvlad commented on gradle/dependencies.toml
> +#tangemBlockchainSdk = "develop-240"
поставил нужный

2023-06-22 10:20 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/wallet/ui/utils/WalletDataOperations.kt
> +        && hasPendingTransactions() //status.pendingTransactions.isEmpty()
удалил

2023-06-22 10:21 UTC, Mama1emon approved these changes

2023-06-22 10:24 UTC, iiiburnyiii approved these changes

2023-06-22 10:30 UTC, Sateetas approved these changes

2023-06-22 10:34 UTC, merged