AND-3803 Design a transaction UI component
tangem/tangem-app-android-old pull request #1061
Opened 2023-06-21 11:26 UTC by Mama1emon

2023-06-21 12:59 UTC, Sateetas requested changes

2023-06-21 12:59 UTC, Sateetas commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionState.kt
> +sealed interface TransactionState {
why an interface and not a class?

2023-06-21 13:03 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionState.kt
> +sealed interface TransactionState {
Because TransactionState have not required fields that inheritance classes should override.

2023-06-21 13:22 UTC, Sateetas commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionState.kt
> +sealed interface TransactionState {
Ok, but conceptually we should use interface when there is "is a" relation and not "has a" relation

In above code relation between TransactionState and it's derivatives is  "is a"

2023-06-21 13:29 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionState.kt
> +sealed interface TransactionState {
I didnt catch. Firstly, you say "we should use interface when there is "is a" relation". Then, you say "TransactionState and it's derivatevis has "is a" relation". You proved why I use a interface ))

2023-06-21 13:35 UTC, Sateetas commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionState.kt
> +sealed interface TransactionState {
No, I mean here semantically is "is a" a relationship between TransactionState and (***Content, Sending, Approving, etc) but you are using an interface ("has a")

2023-06-22 01:15 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionState.kt
> +sealed interface TransactionState {
If I understand correctly you think: 
* if I use interface so I use "has a" relative
* If I use class so I use "is a" relative.

I didn't agree with this opinion - [both class and interface can be "is a" relative](https://www.examclouds.com/java/java-core-russian/class-relations).
In code above `*Content` is a `TransactionState`.

2023-06-22 07:50 UTC, Sateetas commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionState.kt
> +sealed interface TransactionState {
"has a" here means "has quality"

Anyway, we had a call, discussed about it, there are some advantages to use interface in this local case

Approve

2023-06-22 07:50 UTC, Sateetas approved these changes

2023-06-22 08:40 UTC, kozarezvlad approved these changes

2023-06-22 08:40 UTC, merged