AND-3839 Add notifications list UI component
tangem/tangem-app-android-old pull request #1076
Opened 2023-06-26 12:04 UTC by Mama1emon

2023-06-26 12:44 UTC, Sateetas approved these changes

2023-06-26 13:03 UTC, iiiburnyiii requested changes

2023-06-26 13:03 UTC, iiiburnyiii commented on core/ui/src/main/java/com/tangem/core/ui/components/notifications/NotificationState.kt
> +sealed class NotificationState(
Immutable?

2023-06-26 13:03 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletNotification.kt
> +sealed class WalletNotification(open val state: NotificationState) {
Immutable?

2023-06-26 13:03 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletNotification.kt
> +sealed class WalletNotification(open val state: NotificationState) {
Может лучше использовать не классы, а ReadOnlyComposable функции? Кажется это тут лучше подходит, будет меньше всего генерироваться и тут не нужен copy у WalletNotification

2023-06-27 06:13 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/notifications/NotificationState.kt
> +sealed class NotificationState(
В этом нет необходимости, так как используется `sealed class`

2023-06-27 06:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletNotification.kt
> +sealed class WalletNotification(open val state: NotificationState) {
См. выше

2023-06-27 06:15 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/WalletNotification.kt
> +sealed class WalletNotification(open val state: NotificationState) {
Если я правильно понял вопрос, то так сделать не получится.
Список всех нотификаций управляется из вью модели. Сколько их и какие - для UI не важно. А `ReadOnlyComposable` не вызовешь из не компоузовского контекста.

2023-06-27 07:41 UTC, iiiburnyiii approved these changes

2023-06-27 07:52 UTC, merged