1inch/and 3401 changed busines logic
tangem/tangem-app-android-old pull request #1081
Opened 2023-06-26 17:31 UTC by gbixahue

2023-06-27 05:48 UTC, Mama1emon requested changes

2023-06-27 05:48 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        learn2ernInteractor.setupDependencies(
А почему не из DI графа?

2023-06-27 05:48 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +    private fun learn2earnSetupAdditionalDependencies(config: Config) {
Хорошей практикой считается называть функции с глагола

2023-06-27 05:48 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/network/auth/LazyAuthProviderImpl.kt
> +class LazyAuthProviderImpl(private val appStateHolder: AppStateHolder) : LazyAuthProvider {
А зачем создавать прослойку, если можно запровайдить `appStateHolder` в нужное место?

2023-06-27 05:48 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +            .addLazyHeaders(
Расскажи, пожалуйста, зачем здесь необходима "Lazy" реализация?

2023-06-27 05:48 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/models/PromoUserData.kt
> +    val alreadyReceivedAward: Boolean,
Предлагаю также назвать с приставки `is`

2023-06-27 05:48 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/webView/WebViewViewModel.kt
> +        val rawHeaders = intent.getStringArrayListExtra(Learn2earnWebViewActivity.EXTRA_WEB_HEADERS) ?: ArrayList()
`emptyList()` ?

2023-06-27 05:48 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/webView/WebViewViewModel.kt
> +        val uriString = intent.getStringExtra(Learn2earnWebViewActivity.EXTRA_WEB_URI)!!
Предлагаю избегать опасного оператора `!!` в пользу `requireNotNull()`

2023-06-27 05:48 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/webView/WebViewViewModel.kt
> +class WebViewViewModel @Inject constructor(
internal?

2023-06-27 05:48 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/state/StateBuilder.kt
> +@Suppress("MagicNumber")
Лишнее?

2023-06-27 05:48 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/Learn2earnMainPageScreen.kt
> +fun Learn2earnMainPageScreen(viewModel: Learn2earnViewModel, modifier: Modifier = Modifier) {
`viewModel` не реуомендуется передавать во компоуз функцию, так как она по определению не стабильна

2023-06-27 08:03 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        learn2ernInteractor.setupDependencies(
Пришлось прибегнуть к этому способу, т.к. в момент инициализации learn2ernInteractor данные этих структур равны null или пустые (т.к. не инициализированы). Поэтому пока что не по красоте, до тех пор пока мы не выстроим систему инициализации.

2023-06-27 08:22 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/network/auth/LazyAuthProviderImpl.kt
> +class LazyAuthProviderImpl(private val appStateHolder: AppStateHolder) : LazyAuthProvider {
Здесь все тот же момент, что и выше `learn2earnSetupAdditionalDependencies`

На момент создания Retrofit.OkHttpClient для PromotionApi в `AppStateHolder` не содержит данных о карте. `LazyAuthProvider` прослойка позволяет держать хидеры для запросов к api в актуализированном виде. Также  `AppStateHolder` является легаси структурой, которую будет проще подменить здесь, чем в остальных OkHttpClient, где потребуется авторизация через карту.

2023-06-27 08:23 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +            .addLazyHeaders(
Вот здесь постарался прояснить эту ситуацию
https://github.com/tangem/tangem-app-android/pull/1081#discussion_r1243331964

2023-06-27 08:26 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/webView/WebViewViewModel.kt
> +        val rawHeaders = intent.getStringArrayListExtra(Learn2earnWebViewActivity.EXTRA_WEB_HEADERS) ?: ArrayList()
Дело в том, что emptyList перекроет возможность положить этот список в Bundle, который настоятельно требует ArraList.

2023-06-27 08:30 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/webView/WebViewViewModel.kt
> +        val uriString = intent.getStringExtra(Learn2earnWebViewActivity.EXTRA_WEB_URI)!!
Можешь по подробней об опасности?

Если по действию, то NPE выглядит более приемлемым:
`!!` - бросает `NullPointerException`
`requireNotNull` - бросает `IllegalArgumentException`

2023-06-27 08:31 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/state/StateBuilder.kt
> +@Suppress("MagicNumber")
Да, не замеченные остатки

2023-06-27 10:06 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/models/AbstractPromotionResponse.kt
> +        @Json(name = "description") val message: String,
а зачем такая правка? чем description не угодил?

2023-06-27 10:07 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +            preferencesStorage.userData = null
это уже было в соседнем ревью — зачем занулять при неудаче?

2023-06-27 10:07 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    private fun createNewUser(): PromoUserData = PromoUserData(
почему создается new user, а возвращается promo user data?

2023-06-27 11:29 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/api/promotion/models/AbstractPromotionResponse.kt
> +        @Json(name = "description") val message: String,
Спасибо, что заметил... 
Изменилась модель на стороне сервера, забыл изменить Json name

2023-06-27 11:30 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +            preferencesStorage.userData = null
Да, фиксилось. Спасибо! Видимо при мерже упустил

2023-06-27 11:31 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    private fun createNewUser(): PromoUserData = PromoUserData(
Тут вопрос к названию метода?
`createDefaultUserData` ?

2023-06-27 11:34 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    private fun createNewUser(): PromoUserData = PromoUserData(
надо в суть смотреть, если это по смыслу new user, то и сущность и метод называть подобным образом

если promo user, то аналогично

2023-06-27 11:44 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    private fun createNewUser(): PromoUserData = PromoUserData(
Здесь хотелось передать контекст того, что создается модель данных (дефолтная, пустая) `createEmptyUserData`. 
Если же добавление приставки promo повысит восприимчивость кода, почему бы и нет. `createEmptyPromoUserData`

2023-06-27 12:06 UTC, Sateetas approved these changes

2023-06-27 15:46 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/network/auth/LazyAuthProviderImpl.kt
> +class LazyAuthProviderImpl(private val appStateHolder: AppStateHolder) : LazyAuthProvider {
AppStateHolder писался как раз как прослойка старого и нового, в нем будут актуальные данные, LazyAuthProvider как будто еще одна прослойка сверху

2023-06-27 15:47 UTC, kozarezvlad commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +            .addLazyHeaders(
authProvider будет иметь актуальные хедеры когда они появятся, в lazy нет необходимости, когда появятся, то подтянутся нужные

2023-06-27 15:48 UTC, kozarezvlad commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/webView/WebViewViewModel.kt
> +        val uriString = intent.getStringExtra(Learn2earnWebViewActivity.EXTRA_WEB_URI)!!
в IllegalArgumentException обычно кладется ошибка и разработчик сразу по логам понимает в чем дело

2023-06-27 16:41 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/network/auth/LazyAuthProviderImpl.kt
> +class LazyAuthProviderImpl(private val appStateHolder: AppStateHolder) : LazyAuthProvider {
`AppStateHolder` лежит в `app` модуле. Ниже о нем никто не знает.

Хидеры, которые могут быть построены на основе данных из `AppStateHolder` должны попасть модуль `dataSource`, а именно в `PromotionApi.OkHttpClient` в момент инициализации `Learn2earnInteractor` в `TapApplication`

Т.к. `LazyAuthProvider` лежит в `libs.auth` модуле, который подключен к `app` и `dataSource`, то он создается  через DI в `app` (класс `AuthModule`) и инжектиться `dataSource` модуль в момент инициализации `PromotionApi.OkHttpClient`

2023-06-27 17:22 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +            .addLazyHeaders(
authProvider - будет иметь, а `RequestHeader.AuthenticationHeader` - нет.

2023-06-27 17:31 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +            .addLazyHeaders(
После удаления `LazyAuthProvider` предлагаю переделать на `RequestHeader.AuthenticationHeader` внутри которого будет реализация из `LazyRequestHeader.LazyAuthenticationHeader`, а `LazyRequestHeader.LazyAuthenticationHeader` - тоже удалить

2023-06-28 01:48 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        learn2ernInteractor.setupDependencies(
Да, я понимаю, что граф инитится быстрее, чем асинхронные операции по парсингу. Я хочу предложить другое решение, которое, на мой взгляд, упростит данную логику.

`config.tangemComAuthorization`, `store.state.globalState.userCountryCode` не имеют данных сразу, но они нам нужны для инициализации `WebViewUriBuilder`.
`WebViewUriBuilder` используется только при открытии веб вью, с самого начала он не нужен, следовательно, его можно не инить сразу.

Решить это можно путем создания данного билдера, через реализацию кастомного геттера.
```
override val webViewResultHandler: WebViewResultHandler
        get() {
            WebViewUriBuilder(
                authCredentials = configManager.config.tangemComAuthorization,
                userCountryCodeProvider = store.state.globalState.userCountryCode ?: Locale.current.language,
                promoCodeProvider = { repository.getUserData().promoCode },
            )
        }
```

2023-06-28 01:48 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/ui/WalletFragment.kt
> +            setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)
Пояни момент со статегией, пожалуйста

2023-06-28 02:49 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +            .addLazyHeaders(
Я не совсем понимаю разницу. Метод `addLazyHeaders()` вызывается при инициализации `PromotionAPI` через DI. Следовательно, данный код `.forEach { addHeader(it.first, _it.second.invoke()_) }` из `addLazyHeaders()` тоже вызывается сразу. Получается при инициализации через DI из `AuthProvider` возьмутся данные. Не понимаю. в чем заключается Lazy

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +        return userData
А для чего хранить в рантайме данные?

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/HeadersConverter.kt
> +internal class HeadersConverter : TwoWayConverter<Map<String, String>, ArrayList<String>> {
А зачем привязка именно к реализации `ArrayList`

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/WebViewRedirectHandler.kt
> +interface WebViewRedirectHandler {
internal?

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/WebViewResultHandler.kt
> +interface WebViewResultHandler {
internal?

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/Learn2earnRouter.kt
> +    fun openWebView(uri: Uri, rawHeaders: ArrayList<String>) {
Зачем привязка к `ArrayList`?

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/Learn2earnViewModel.kt
> +                buttonStoryClick = ::buttonStoryClick,
Предлагаю называть функции с глагола

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/Learn2earnViewModel.kt
> +        viewModelScope.launch(dispatchers.io) {
А почему в целом и обновление стейта и запрос делаются на IO потоке? Почему не только запрос?

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/GetBonusView.kt
> +                        color = Color.White,
TangemColorPalette

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/GetBonusView.kt
> +private fun makePreviewState(): MainScreenState = MainScreenState(
Предлагаю сделать через CollectionPreviewParameterProvider

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/Learn2earnMainPageScreen.kt
> +fun Learn2earnMainPageScreen(state: Learn2earnState, modifier: Modifier = Modifier) {
Зачем модифаер?

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/state/Learn2earnState.kt
> +    companion object
Лишнее?

2023-06-28 02:49 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/state/Learn2earnState.kt
> +class UiActions(
Предлагаю добавить приставку фичи или экрана, чтобы было понятно к чему это относится. Иначе поиск по проекту будет труднее осуществлять

2023-06-28 07:59 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        learn2ernInteractor.setupDependencies(
С `СonfigManager` так можно решить вопрос, а вот `store` затягивать в фичу не хотелось бы

2023-06-28 08:06 UTC, gbixahue commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +            .addLazyHeaders(
В том, что данные в `AuthenticationHeader` возвращаются те данные, который были туда положены в момент инициализации `AuthenticationHeader` - .forEach { addHeader(it.first, `it.second`) }.

А в `LazyAuthenticationHeader` поле инициализиуются функцией, которая выгребает значения каждый раз при .forEach { addHeader(it.first, `_it.second.invoke()`) }

2023-06-28 08:10 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +        return userData
чтобы каждый раз при запросе к userData не лезть в преференсы и не декодировать из json

2023-06-28 08:13 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/HeadersConverter.kt
> +internal class HeadersConverter : TwoWayConverter<Map<String, String>, ArrayList<String>> {
Чтобы при передачи данных в Bundle не кастовать их к `ArrayList`

2023-06-28 08:14 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/WebViewRedirectHandler.kt
> +interface WebViewRedirectHandler {
Не получится, т.к. его используют и в domain и в presentation слое

2023-06-28 08:18 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/WebViewResultHandler.kt
> +interface WebViewResultHandler {
Не получится, т.к. он используется, как публичное поле интерфейса `Learn2earnInteractor`

2023-06-28 08:19 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/state/Learn2earnState.kt
> +    companion object
Нет, через него реализован stateBuilder

2023-06-28 08:21 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/Learn2earnMainPageScreen.kt
> +fun Learn2earnMainPageScreen(state: Learn2earnState, modifier: Modifier = Modifier) {
Если нужно будет переделать отображение `GetBonusView` на главном экране - это нам поможет. 
На данный момент не используется.

2023-06-28 08:43 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/wallet/ui/WalletFragment.kt
> +            setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)
Стратегию рекомендуют использовать в тех местах, где композ вью встраиваются в существующий xml, особенно если она используется во фрагменте. Стратегия определяет момент, когда композ вью должна уничтожиться.

DisposeOnLifecycleDestroyed - вот эта стратегия в данном месте подходит больше, чем указанная.

2023-06-28 10:45 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/ui/WalletFragment.kt
> +            setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)
Можно закрывать

2023-06-28 11:25 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        learn2ernInteractor.setupDependencies(
Обсудили, и решили инициализировать `Learn2ernInteractor` c `AppStateHolder`

2023-06-28 14:01 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/Learn2earnViewModel.kt
> +        viewModelScope.launch(dispatchers.io) {
updateUi suspend функция, которая сама переключается на требуемые потоки

2023-06-28 14:27 UTC, Mama1emon approved these changes

2023-06-28 14:42 UTC, merged