AND-3811 Add dummy implementation of tokens domain layer
tangem/tangem-app-android-old pull request #1094
Opened 2023-06-29 19:07 UTC by iiiburnyiii

2023-07-03 10:00 UTC, Sateetas requested changes

2023-07-03 10:00 UTC, Sateetas commented on domain/models/src/main/kotlin/com/tangem/domain/models/userwallet/UserWalletId.kt
> +class UserWalletId(
а почему не data-class?

2023-07-03 10:00 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/TokenList.kt
> +    abstract val isLoading: Boolean
isLoading точно должен быть частью TokenList?

2023-07-03 10:41 UTC, iiiburnyiii commented on domain/models/src/main/kotlin/com/tangem/domain/models/userwallet/UserWalletId.kt
> +class UserWalletId(
Он тут не нужен. Copy тут точно не будет использоваться, а equals переопределен вручную

2023-07-03 10:42 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/TokenList.kt
> +    abstract val isLoading: Boolean
Спорно, но думаю да. Так будет проще определить, что какие-то токены ещё загружаются, без дополнительных проходов по списку

2023-07-04 07:55 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/TokenList.kt
> +    abstract val isLoading: Boolean
Но шиммер нужно вешать на части конкретного загружаемого токена, проходить все равно придется. Для общего листа актуально когда общий запрос на токены юзера идет, дальше балансы и тп внутри нужно все равно

2023-07-04 10:29 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/TokenList.kt
> +    abstract val isLoading: Boolean
Это да, добавил это поле по большей части для определения когда можно начинать считать общий баланс. Думаю тогда вместо этого флага можно добавить сразу стейт общего баланса

2023-07-04 13:09 UTC, Mama1emon commented on domain/models/src/main/kotlin/com/tangem/domain/models/userwallet/UserWalletId.kt
> +        fun mock(n: Int = Random.nextInt(from = 0, until = 1_000)): UserWalletId {
Тестовая тема?

2023-07-04 13:09 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/FetchTokensUseCase.kt
> +@file:Suppress("UNUSED", "UNUSED_PARAMETER")
?

2023-07-04 13:09 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +@file:Suppress("UNUSED", "UNUSED_PARAMETER")
?

2023-07-04 14:40 UTC, iiiburnyiii commented on domain/models/src/main/kotlin/com/tangem/domain/models/userwallet/UserWalletId.kt
> +        fun mock(n: Int = Random.nextInt(from = 0, until = 1_000)): UserWalletId {
Да, для превьюх и моковых данных

2023-07-04 14:41 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/FetchTokensUseCase.kt
> +@file:Suppress("UNUSED", "UNUSED_PARAMETER")
Это уберу в следующих МРах

2023-07-04 18:17 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/FetchTokensUseCase.kt
> +@file:Suppress("UNUSED", "UNUSED_PARAMETER")
Оставил коммент

2023-07-05 06:36 UTC, Mama1emon commented on domain/models/src/main/kotlin/com/tangem/domain/models/userwallet/UserWalletId.kt
> +        fun mock(n: Int = Random.nextInt(from = 0, until = 1_000)): UserWalletId {
Тогда нужно выносить это в тест модуль

2023-07-05 06:42 UTC, kozarezvlad commented on domain/models/src/main/kotlin/com/tangem/domain/models/userwallet/UserWalletId.kt
> +        fun mock(n: Int = Random.nextInt(from = 0, until = 1_000)): UserWalletId {
Моковые данные сейчас юзаются на уровне приложения, не в тестах? Тогда вынести не получится пока заглушки на приле

2023-07-05 06:45 UTC, iiiburnyiii commented on domain/models/src/main/kotlin/com/tangem/domain/models/userwallet/UserWalletId.kt
> +        fun mock(n: Int = Random.nextInt(from = 0, until = 1_000)): UserWalletId {
Этот метод используется для генерации превью, так что его не вариант туда вынести. Возможно стоит создать аннотацию для detekt, по аналогии с `@TestOnly` только для compose превью, что-бы detekt падал, если этот код вызван не из превью

2023-07-05 06:48 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/FetchTokensUseCase.kt
> +    private val networksRepository: NetworksRepository,
Имеет ли смысл дробить на столько маленьких репозиториев, они нужны такие атомарные? В чем профит?
Например tokensRepository и organizeTokensRepository выглядят по смыслу одинакоко - работа с токенами

2023-07-05 06:48 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private val networksRepository: NetworksRepository,
Немного ломается когда читаешь GetTokenList, а видишь внутри networksRepository. Что за Networks?

2023-07-05 06:48 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/repository/NetworksRepository.kt
> +interface NetworksRepository {
Дока не помешала бы, у нас много где модели сетей и хорошо бы описать что это и какой/для чего контент дает в этом случае

2023-07-05 06:54 UTC, Yoggam1 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/FetchTokensUseCase.kt
> +    private val networksRepository: NetworksRepository,
Разделение юзкейсов - ок. Но репозитории лучше всего не делать атомарными

2023-07-05 07:00 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/FetchTokensUseCase.kt
> +    private val networksRepository: NetworksRepository,
Там разная работа с токенами, в первом они просто достаются, во втором достаются параметры группировки и обновляется сортировка, так у use case'а есть только необходимая инфа. В месте имплементации их можно в одном классе реализовать

2023-07-05 07:19 UTC, Sateetas commented on domain/models/src/main/kotlin/com/tangem/domain/models/userwallet/UserWalletId.kt
> +class UserWalletId(
не совсем понимаю, а в чем смысл руками писать такой же equals, что и data-class  генерит?

можно же написать data-класс с еще одним конструктором и переопределить `toString()`

2023-07-05 07:39 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/NetworkStatus.kt
> +        abstract val amounts: Map<Token.ID, BigDecimal>?
зачем делать amounts abstract-полем, если оно используется только в 2 из 5 наследников?

2023-07-05 07:39 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/TokenList.kt
> +        open val amount: BigDecimal? = null
аналогично

2023-07-05 07:40 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/TokenState.kt
> +    sealed class State {
и здесь тоже

2023-07-06 10:34 UTC, closed without merging