AND-3896 1inch: added feature toggle
tangem/tangem-app-android-old pull request #1104
Opened 2023-07-03 09:01 UTC by gbixahue

2023-07-03 10:16 UTC, Sateetas requested changes

2023-07-03 10:16 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/api/Learn2earnRepository.kt
> +    val featureToggleManager: Learn2earnFeatureToggleManager
а мб инкапсулировать так, чтобы не `featureToggleManager ` наружу смотрел, а метод `isFeatureEnabled()`?

2023-07-03 10:28 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/api/Learn2earnRepository.kt
> +    val featureToggleManager: Learn2earnFeatureToggleManager
Да, хорошая идея. Изначально из интерфейса `Learn2earnFeatureToggleManager`  торчало 2 атрибута, поэтому проще было его отдать.

2023-07-03 13:57 UTC, Mama1emon requested changes

2023-07-03 13:57 UTC, Mama1emon commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "undefined"
Мы в 4.8 не выпускаем 1inch?

2023-07-03 13:57 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/toggles/DefaultLearn2earnFeatureToggleManager.kt
> +class DefaultLearn2earnFeatureToggleManager(
internal?

2023-07-03 13:57 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    override fun isFeatureToggleEnabled(): Boolean {
Кажется излишним, можно напрямую в интеракторе заюзать

2023-07-03 13:57 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/di/Learn2earnDataModule.kt
>  class Learn2earnDataModule {
interal

2023-07-04 07:04 UTC, gbixahue commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "undefined"
Мы еще не уверены, в какой версии будем его выпускать

2023-07-04 07:04 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    override fun isFeatureToggleEnabled(): Boolean {
Является провайдером данных, поэтому в data слое

2023-07-04 08:41 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    override fun isFeatureToggleEnabled(): Boolean {
Фича тогглы специально проектировались таким образом, чтобы не быть привязанными к конкретному слою. Чтобы мы могли брать менеджер и использовать везде, где это необходимо.
Я согласен с тем, что фича тогглы у нас читаются из файла, но это особенность реализации, которую из вне никто не знает. Именно поэтому не стоит рассматривать фича тоггл менеджер, как компонент дата слоя. Он служит в наших целях, не стоит его тащить под одну гребенку с другими датасорсами

2023-07-04 12:00 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    override fun isFeatureToggleEnabled(): Boolean {
Если избавляться от прослойки, то особо она и не нужна, но хочется поддерживать парадигму

2023-07-04 18:06 UTC, iiiburnyiii commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    override fun isFeatureToggleEnabled(): Boolean {
Мне кажется тоглы это штука скорее относящаяся к domain слою, но лучше её вообще отдельно деражать

2023-07-05 07:20 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/data/DefaultLearn2earnRepository.kt
> +    override fun isFeatureToggleEnabled(): Boolean {
Переварил фича тоглы и пришел к выводу, что вы правы... Лучше использовать его в том слое, где он непосредственно нужен

2023-07-05 07:26 UTC, Sateetas approved these changes, later dismissed

2023-07-05 10:25 UTC, kozarezvlad approved these changes

2023-07-05 10:26 UTC, Yoggam1 approved these changes

2023-07-05 11:00 UTC, Sateetas approved these changes

2023-07-05 11:21 UTC, Mama1emon approved these changes

2023-07-05 11:33 UTC, merged