Bugfix/and 3927 1inch fix screens content for small devices
tangem/tangem-app-android-old pull request #1118
Opened 2023-07-04 18:49 UTC by gbixahue

2023-07-05 06:50 UTC, Mama1emon requested changes

2023-07-05 06:50 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/Learn2earnStoriesScreen.kt
> +                    .weight(weight = 1.2f),
Интересно... Не будет ли искажений изображения на разных экранах? Все-таки нет конкретного `scale`

2023-07-05 07:13 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/Learn2earnStoriesScreen.kt
> +                    .weight(weight = 1.2f),
Как раз этот параметр подбирал на 4х разных экранах. На 1м маленьком и на 3х, более менее стандартных размерах.

2023-07-05 07:26 UTC, kozarezvlad commented on app/src/main/AndroidManifest.xml
> -            android:theme="@style/Theme.MaterialComponents.Light.NoActionBar" />
Кажется это не просто так убирали. @Sateetas ты вроде правил?

2023-07-05 08:03 UTC, gbixahue commented on app/src/main/AndroidManifest.xml
> -            android:theme="@style/Theme.MaterialComponents.Light.NoActionBar" />
Так это же `Learn2earnWebViewActivity`

2023-07-05 13:18 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/Learn2earnStoriesScreen.kt
> +                    .weight(weight = 1.2f),
Но я предлагаю все равно content scale указать, дабы гарантировать поведение

2023-07-06 13:02 UTC, kozarezvlad approved these changes

2023-07-06 13:37 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/presentation/ui/Learn2earnStoriesScreen.kt
> +                    .weight(weight = 1.2f),
Я изначально тебя не правильно понял... `contentScale`  допишем

2023-07-07 04:42 UTC, Mama1emon approved these changes

2023-07-07 07:08 UTC, roman-pv approved these changes

2023-07-07 14:17 UTC, merged