AND-3932 1inch: added analytics
tangem/tangem-app-android-old pull request #1127
Opened 2023-07-07 13:58 UTC by gbixahue

2023-07-07 14:35 UTC, kozarezvlad submitted a review, later dismissed

2023-07-07 15:17 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +sealed class Learn2earnEvents(
internal?

2023-07-07 15:17 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +        class ButtonLearn : IntroductionProcess("Button - Learn")
object?

2023-07-07 15:17 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +        class NoticeClaimSuccess : MainScreen("Notice - Claim Successed")
object?

2023-07-07 15:17 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +sealed class AnalyticsParam {
internal?

2023-07-07 15:17 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +private fun WebViewResult.toWebViewAction(): WebViewAction {
Может в рамках скоупа интерактора объявить?

2023-07-07 15:28 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +        class ButtonLearn : IntroductionProcess("Button - Learn")
Нет, я не хочу эвенты делать object, потому что они остаются в памяти после одного использования и никогда не удалятся. А так, эвент улетел и объект стерся

2023-07-07 15:38 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +private fun WebViewResult.toWebViewAction(): WebViewAction {
Не принципиально, можно и так

2023-07-07 16:07 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +        object New : ClientType("New")
тогда и тут без object можно

2023-07-07 16:08 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +        object New : ClientType("New")
вообще я как-то на прошлом проекта все дескрипторы для аналитики на енумах делал, казалось неплохим решением

2023-07-07 16:10 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +            else -> Unit
давай вместо else объявим руками все остальное, отстрелит ведь потом при расширении

2023-07-07 16:12 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/WebViewResultHandler.kt
> +    data class PromoCode(val promoCode: String) : WebViewResult()
зачем data class? почему не просто class?

2023-07-07 16:13 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/WebViewResultHandler.kt
> +    data class AnalyticsEvent(val event: com.tangem.core.analytics.AnalyticsEvent) : WebViewResult()
мб import alias заюзать, чтобы коллизии этой не было?

2023-07-07 16:13 UTC, Sateetas commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/WebViewResultHandler.kt
> +    data class AnalyticsEvent(val event: com.tangem.core.analytics.AnalyticsEvent) : WebViewResult()
или переназвать класс

2023-07-07 16:13 UTC, Sateetas requested changes
ветка называется не через feature/

2023-07-07 16:21 UTC, kozarezvlad commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/api/WebViewResultHandler.kt
> +    data class PromoCode(val promoCode: String) : WebViewResult()
Имхо, это класс для хранения данных, логики в нем не будет никакой, чисто transport object - дата класс тут абсолютно оправдан

2023-07-07 16:26 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +        object New : ClientType("New")
Можно, но enum не позволяет делать вложенность.

2023-07-07 16:28 UTC, gbixahue commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/domain/DefaultLearn2earnInteractor.kt
> +            else -> Unit
Мне здесь только 1 эвент нужен. Можно на if переделать

2023-07-07 16:33 UTC, gbixahue commented
> ветка называется не через feature/

ветка называется по названию фичи. Так проще отслеживать все, что конкретно для этой фичи делается. А в feature/ будут лежать все фичи, в которых ничего не найдешь.
Можно подумать над тем, чтобы называть feature/1inch/

2023-07-07 17:08 UTC, Mama1emon approved these changes

2023-07-07 17:09 UTC, Mama1emon approved these changes

2023-07-07 17:11 UTC, kozarezvlad commented
> > ветка называется не через feature/
> 
> Так проще отслеживать все, что конкретно для этой фичи делается. А в feature/ будут лежать все фичи, в которых ничего не найдешь. Можно подумать над тем, чтобы называть feature/1inch/

Мы все нейминги обсудили с командой ios и зафиналили, есть описанная дока, все окнули. Все ищется не сложно

2023-07-07 17:32 UTC, gbixahue commented
> > > ветка называется не через feature/
> > 
> > 
> > Так проще отслеживать все, что конкретно для этой фичи делается. А в feature/ будут лежать все фичи, в которых ничего не найдешь. Можно подумать над тем, чтобы называть feature/1inch/
> 
> Мы все нейминги обсудили с командой ios и зафиналили, есть описанная дока, все окнули. Все ищется не сложно

Я так именовал бранчи еще до того, как было все зафиналено, да и 1inch фича стартовала раньше... Поэтому не хотелось бы портить картину маслом - закончу эту фичу - буду делать по докам

2023-07-07 17:40 UTC, kozarezvlad commented
> > > > ветка называется не через feature/
> > > 
> > > 
> > > Так проще отслеживать все, что конкретно для этой фичи делается. А в feature/ будут лежать все фичи, в которых ничего не найдешь. Можно подумать над тем, чтобы называть feature/1inch/
> > 
> > 
> > Мы все нейминги обсудили с командой ios и зафиналили, есть описанная дока, все окнули. Все ищется не сложно
> 
> Я так именовал бранчи еще до того, как было все зафиналено, да и 1inch фича стартовала раньше... Поэтому не хотелось бы портить картину маслом - закончу эту фичу - буду делать по докам

Согласен, сейчас не критично

2023-07-10 05:40 UTC, Mama1emon commented on features/learn2earn/impl/src/main/java/com/tangem/feature/learn2earn/analytics/Learn2earnEvents.kt
> +        class ButtonLearn : IntroductionProcess("Button - Learn")
Не так давно читал статью, что не стоит упарываться в оптимизацию, которая идёт в ущерб удобства и поддерживаемости кода. От того, что будут объекты ивентов в памяти лежать, которые не содержат жирный стейт, ничего глобального не произойдет. Приложения работать хуже не станет.

2023-07-10 08:08 UTC, Sateetas approved these changes

2023-07-10 08:17 UTC, merged