AND-3811 Added tokens domain base entities
tangem/tangem-app-android-old pull request #1131
Opened 2023-07-07 18:25 UTC by iiiburnyiii

2023-07-10 05:46 UTC, Mama1emon requested changes

2023-07-10 05:46 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +    fun provedDefaultTokensRepository(): TokensRepository = DefaultTokensRepository()
Везде именовали по названию объекта, который возвращает, то есть - `provideTokensRepository`

2023-07-10 05:46 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultTokensRepository.kt
> +    override fun getQuotes(tokensIds: Set<Token.ID>, refresh: Boolean): Flow<Either<TokensError, Set<Quote>>> {
Мб в отдельный репо вынести?

2023-07-10 05:46 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokensError.kt
> +data class UnknownTokensError(val cause: Throwable) : TokensError()
А зачем передавать `cause`? Вроде получается строгая типизация ошибок, но все равно смотрим на исключения

2023-07-10 05:46 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokensError.kt
> +sealed class TokensError
`interface`

2023-07-10 05:46 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
А для чего именно делать inline класс?

2023-07-11 07:09 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
Тут просто стринга оборачивается для более строгой типизации, другие типы классов тут меньше подходят
https://kotlinlang.org/docs/inline-classes.html

2023-07-11 07:13 UTC, iiiburnyiii commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultTokensRepository.kt
> +    override fun getQuotes(tokensIds: Set<Token.ID>, refresh: Boolean): Flow<Either<TokensError, Set<Quote>>> {
Тогда стоит `getNetworks` и `getNetworksStatuses` тоже вынести в другой репозиторий. Мне это ок, но @Yoggam1 и @kozarezvlad хотели, что-бы все было в одном репо

2023-07-11 07:36 UTC, iiiburnyiii commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +    fun provedDefaultTokensRepository(): TokensRepository = DefaultTokensRepository()
Поправил

2023-07-11 07:36 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokensError.kt
> +sealed class TokensError
Поправил

2023-07-11 07:36 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokensError.kt
> +data class UnknownTokensError(val cause: Throwable) : TokensError()
Поправил

2023-07-11 07:39 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokensError.kt
> +sealed interface TokensError
может все-таки класс?)

2023-07-11 07:46 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultTokensRepository.kt
> +    override fun getQuotes(tokensIds: Set<Token.ID>, refresh: Boolean): Flow<Either<TokensError, Set<Quote>>> {
Давайте обсудим

2023-07-11 07:48 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
Лично мне такой подход не очень симпатизирует, так как выглядит, как избыточная строгая типизация.
Если захочешь потом передать такую стрингу в другое место, то не получится так легко это сделать, так как она обернута в класс

2023-07-11 07:49 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
Одно дело, если бы класс накладывал какие-то проверки на саму строку (правила, по которым эта строка точно ID), но по сути - любая строка уже ID.

2023-07-11 07:51 UTC, kozarezvlad commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultTokensRepository.kt
> +    override fun getQuotes(tokensIds: Set<Token.ID>, refresh: Boolean): Flow<Either<TokensError, Set<Quote>>> {
С одной стороны не хочется плодить репозитории и изначально казалось, что котировки - стейт токена. Сейчас глядя уже на код и то что котировки получаются по id токенов, кажется, что это отдельный репозитории. 
Про один репо говорили, но там имел ввиду, что все что относится к токенам держать в одном и казалось котировки таковыми будут, но в коде сейчас понятно, что это отдельный источник данных. Сорян, что изначально запутал

2023-07-11 07:55 UTC, Mama1emon requested changes

2023-07-11 07:55 UTC, Mama1emon commented on app/build.gradle.kts
> +    implementation(project(":domain:tokens"))
Достон затянул прикольную тему с синтаксисом импорта наших проджектов. Мб здесь тоже ее заиспользовать?
На твое усмотрение.

2023-07-11 07:55 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +    fun provideGetTokenListUseCase(tokensRepository: TokensRepository, dispatchers: CoroutineDispatcherProvider) =
Если в одну строчку не умещается, предлагаю использовать block body

2023-07-11 07:55 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +object TokensDomainModule {
internal?

2023-07-11 07:55 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +@InstallIn(SingletonComponent::class)
Мб ограничить скоуп ViewModel?

2023-07-11 07:55 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +@InstallIn(SingletonComponent::class)
TokensRepository вроде не должен держать стейт, мб тогда сделать ViewModelScope?

2023-07-11 07:55 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokensError.kt
> +object EmptyTokens : TokensError
Я предлагаю загнать в скоуп `TokensError`, чтобы можно было использовать ошибки, как `TokensError.EmptyTokens` или `TokensError.UnknownTokensError`. Это позволяет по коду легче понимать, что данная ошибка является одной из возможных ошибок данного пула ошгибок

2023-07-11 07:59 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokensError.kt
> +sealed interface TokensError
Вынес на обсуждение

2023-07-11 08:04 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
Используя этот класс, ты явно даешь понять, что эта строка уже провалидированный ID токена. Да, ты можешь использовать его конструктор не из domain слоя, но на свой страх и риск, и это будет гораздо более заметно на ревью

2023-07-11 08:17 UTC, iiiburnyiii commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +@InstallIn(SingletonComponent::class)
Думаю репозитории все таки лучше в сниглтоне держать, в отличии от use case`ов, так как они будут использоваться в большом количестве фичей

2023-07-11 08:29 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +@InstallIn(SingletonComponent::class)
кмк фича слишком базовая, чтобы к viewmodel привязываться

2023-07-11 08:32 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/router/DefaultWalletRouter.kt
> +                        .apply { router = this@DefaultWalletRouter }
а мы вообще никак не можем передавать роутер в параметр конструктора вьюмодели?

нет никакого хака, чтобы в дагерный инжект пролезть с этого уровня?

2023-07-11 08:32 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +@InstallIn(SingletonComponent::class)
Вообще обсуждали ж, что домейны не синглтоны, а живут в скоупе фичи/viewModel. А то что под ними - store например, уже синглтон

2023-07-11 08:35 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/router/DefaultWalletRouter.kt
> +                        .apply { router = this@DefaultWalletRouter }
Вообще на уровне конструктора viewModel засунуть можно, но тут проблема видимо с navigationStateHolder который инитится позже графа из старого функционала, поэтому просовывается так

2023-07-11 08:39 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/router/DefaultWalletRouter.kt
> +                        .apply { router = this@DefaultWalletRouter }
Плюсую за вопрос, но не в рамках этого МРа

2023-07-11 11:13 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +@InstallIn(SingletonComponent::class)
Репозитории будут использоваться столько раз, сколько и usecase)
Но я не буду блочить

2023-07-11 11:15 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/router/DefaultWalletRouter.kt
> +                        .apply { router = this@DefaultWalletRouter }
Роутер привязан к жизненному циклу активити. А скоуп активити и вью модели в графе находится на одной ступени. Хилт не позволяет инжектить зависимости между скоупами одной ступени

2023-07-11 11:19 UTC, Mama1emon requested changes

2023-07-11 11:19 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +package com.tangem.tap.di.domain
Предлагаю сделать под папку, чтобы было соответствие с модулями. /di/domain/tokens/

2023-07-11 11:19 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +    ) = GetTokenListUseCase(tokensRepository, quotesRepository, networksRepository, dispatchers)
Предлагаю использовать block body так как не умещается в одну строчку

2023-07-11 11:19 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +    fun provideQuotesRepository(): QuotesRepository = DefaultQuotesRepository()
На мой взгляд - котировки и сети - это другой дата слой (модуль)

2023-07-11 11:19 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
Что значит провалидированный айди токена? А где валидация?

2023-07-11 11:19 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultTokensRepository.kt
> +    override fun getQuotes(tokensIds: Set<Token.ID>, refresh: Boolean): Flow<Either<TokensError, Set<Quote>>> {
Можно закрывать

2023-07-11 11:24 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
я это понимаю не как "провалидированный", а как "законтрактованный" что ли

2023-07-11 11:26 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
@iiiburnyiii кстати, а у нас генерация equals/hashcode в data-классе не сломается от наличия инлайн внутри?

2023-07-11 11:31 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +package com.tangem.tap.di.domain
Зачем? На каждую доменную фичу будет свой модуль, получиться, что в пакете будет только один файл

2023-07-11 11:37 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/Network.kt
> +    value class ID(val value: String)
Нет, не сломается. У value класса сравнение идет по значению

2023-07-11 11:39 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +    ) = GetTokenListUseCase(tokensRepository, quotesRepository, networksRepository, dispatchers)
Помещается 🗿

2023-07-11 11:41 UTC, iiiburnyiii commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +    fun provideQuotesRepository(): QuotesRepository = DefaultQuotesRepository()
Котировки связаны с токенами и отдельно использоваться вряд-ли будут, зачем их выносить в отдельный модуль?

2023-07-11 12:58 UTC, kozarezvlad approved these changes

2023-07-11 14:28 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/TokensDomainModule.kt
> +package com.tangem.tap.di.domain
Легче искать.
Но пусть на твое усмотрение

2023-07-11 14:29 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +    fun provideQuotesRepository(): QuotesRepository = DefaultQuotesRepository()
Я сегодня кидал кейсс компонентом, когда нужно получить инфу об изменении токена за 24 часа

2023-07-11 14:54 UTC, iiiburnyiii commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/di/TokensDataModule.kt
> +    fun provideQuotesRepository(): QuotesRepository = DefaultQuotesRepository()
Так как там нужно получить не только квоту, а ещё и данные по балансу токена, то лучше написать use case для получения статуса токена, модель статуса токена есть в этом мре

2023-07-12 06:20 UTC, Mama1emon approved these changes

2023-07-12 06:52 UTC, merged