AND-3812 Implemented get tokens list use case
tangem/tangem-app-android-old pull request #1132
Opened 2023-07-09 12:17 UTC by iiiburnyiii

2023-07-10 11:10 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/context/TokenStatusContext.kt
> +    val networkStatus: NetworkStatus?,
можем без нулабельности обойтись?

2023-07-12 07:12 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/context/TokenStatusContext.kt
> +    val networkStatus: NetworkStatus?,
Тут нет, можно разве что `Option` из arrow использвать, но мне кажется null нативней смотриться. Если что этот класс содержит контекст для создания `TokenStatus` и наружу не выходит.

2023-07-12 07:28 UTC, Mama1emon requested changes

2023-07-12 07:28 UTC, Mama1emon commented on core/utils/src/main/java/com/tangem/utils/extensions/Collection.kt
> +    val mutable = this.toMutableList()
На мой взгляд - `mutableList` или `sourceList` выглядит лучше, чем прилагательное

2023-07-12 07:28 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/context/TokenListContext.kt
> +internal class TokenListContext(
На мой взгляд - лучше не использовать наименование `Context` в данном кейсе. Сбивает с толку

2023-07-12 07:34 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/context/TokenListContext.kt
> +internal class TokenListContext(
Что предлагаешь: `Scope`, `Resources`?

2023-07-12 08:42 UTC, kozarezvlad commented on core/utils/src/main/java/com/tangem/utils/extensions/Collection.kt
> +inline fun <T> List<T>.addOrReplace(item: T, selector: (T) -> Boolean): List<T> {
Чем не подходит написанная ранее replaceByOrAdd?

2023-07-12 08:47 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokensError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
Не нашел сходу доки по Raise, можешь описать что тут происходит? Почему экстеншен на дженерик с ошибкой и возвращение флоу листа? И смысл экстеншена в принципе тут?

2023-07-12 08:50 UTC, iiiburnyiii commented on core/utils/src/main/java/com/tangem/utils/extensions/Collection.kt
> +inline fun <T> List<T>.addOrReplace(item: T, selector: (T) -> Boolean): List<T> {
Она медленнее работает, там больше проходов по спику, ну и ещё она в app модуле

2023-07-12 08:50 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
Только меня напрягает, что мы через одну пишем экстешнены? почему просто не положить эту функцию в TotalFiatBalanceContext если мы сами этот контекст пишем, а потом тут же расширяем

2023-07-12 08:52 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListOperations.kt
> +internal fun TokenListContext.createTokenList(tokens: Set<TokenStatus>): Flow<TokenList> {
Тут такой же коммент как выше. 
Kotlin provides the ability to extend a class or an interface with new functionality without having to inherit from the class or use design patterns such as Decorator.

Мы сами проектируем класс TokenListContext, имеем все возможности его изменять, но делаем потом к нему расширения зачем то.

2023-07-12 08:55 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListOperations.kt
> +    return groups!!
Или это всё для моков?

2023-07-12 08:59 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokensError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
`Raise<...>` позволяет прокинуть ошибку выше и писать код императивно в блоке билдера, например, `either { ... }`
С этой штукой не нужно везде возвращать `Either<L, R>`/`Effect<L, R>`/etc., так же не нужно вызывать `bind()`
То есть вместо:
```
fun a(): Either<L, R>

fun b(v: R): Either<L, T>

fun main() {
 val result1 = either<L, T> { // this Raise<L>
  val a = a().bind()
  b(a).bind()
 }
 
 // or
 
 val result2 = a().flatMap { b(it) }
}
```

Можно написать:
```
fun Raise<L>.a(): R

fun Raise<L>.b(v: R): T

fun main() {
 val result = either<L, T> { // this Raise<L>
  val a = a()
  b(a)
 }
}
```

2023-07-12 09:03 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
Можно вынести в класс, но зачем, это же ФП 🤓 
В дальнейшем `Context` можно вынести в context receivers и нормально расширять другие сущности

```
context(SomeOperationContext)
fun SomeClass.operation(): Result { ... }
```

2023-07-12 09:11 UTC, kozarezvlad commented on core/utils/src/main/java/com/tangem/utils/extensions/Collection.kt
> +inline fun <T> List<T>.addOrReplace(item: T, selector: (T) -> Boolean): List<T> {
Можно в целом эти экстеншены что лежат в аппе вынести в utils, чтоб все в одном месте было

2023-07-12 09:15 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
Ну мы не уходим полностью от ООП, а тут получается что мы почти все пишем в функциях, раскидываем их по проекту и дергаем откуда то. Весь проект превращается в расширение нескольких классов. Я против такого подхода использования не по прямому назначению расширений

2023-07-12 09:41 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/context/TokenListContext.kt
> +internal class TokenListContext(
Не совсем понял идею данных классов. Какую функцию они выполняют?

2023-07-12 09:42 UTC, Mama1emon commented on core/utils/src/main/java/com/tangem/utils/extensions/Collection.kt
> +inline fun <T> List<T>.addOrReplace(item: T, selector: (T) -> Boolean): List<T> {
Давайте тогда старую версию пометим устаревшей и заведем задачу на рефакторинг. Много мусора в проекте скапливается только потому, что каждый пишет свою версию

2023-07-12 09:50 UTC, Sateetas approved these changes, later dismissed

2023-07-12 09:55 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
В ООП получается примерно то же самое, просто обмазанное абстракциями, зачастую не очевидными с первого раза, особено в домене (может я не шарю?). Легче держать одну точку входа в виде use case'а в нашем случае, который будет просто создавать контексты/скоупы и дергать нужные методы. Я не совсем понимаю зачем дробить эту логику на классы, просто увеличивая количество бойлерплейта, учитвая, что эти методы разбиты по скоупам с помощью расширений. Плюс эту логику гораздо легче масштабировать на другие use case'ы.
Предлагаю оставить эту логику плюс-минус в таком виде, если будет много вопросов, то её всегда можно перепилить в более ООПешном подходе

2023-07-12 10:06 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/context/TokenListContext.kt
> +internal class TokenListContext(
Конкретно этот содержит ресурсы необходимые для создания `TokenList`

2023-07-12 10:08 UTC, iiiburnyiii commented on core/utils/src/main/java/com/tangem/utils/extensions/Collection.kt
> +inline fun <T> List<T>.addOrReplace(item: T, selector: (T) -> Boolean): List<T> {
Не в рамках этого МРа, он и так уже большой

2023-07-12 10:17 UTC, iiiburnyiii commented on core/utils/src/main/java/com/tangem/utils/extensions/Collection.kt
> +inline fun <T> List<T>.addOrReplace(item: T, selector: (T) -> Boolean): List<T> {
Сори, этот метод вообще не используется в этом МРе, удалил

2023-07-12 10:38 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
Просто мне не понятно зачем экстеншен там, где можно без него обойтись. По факту ты используешь тот же this объекта, и экстеншен метод для того же объекта точно также, что ты положил бы его внутрь и вызвал у него, просто он кладется в другое место (зачем?).

2023-07-12 10:40 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
Не вижу никакой обмазки абстракцией. 
У тебя есть объект TotalFiatBalanceContext у него есть метод - ты его юзаешь.
Подход с экстеншен:
У тебя есть объект TotalFiatBalanceContext, ты заведомо не добавляешь ему нужный метод, затем говоришь "хочу его расширить, че то не хватает" добавляешь этот метод, но кладешь в другой файл и точно также вызываешь его.

2023-07-12 10:42 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
Выглядит так, что заведомо ограничиваем скоуп объекта, урезаем методы, чтобы вынести их в расширение, но зачем? Это другая логика? Тогда почему она к этому объекту. Это логика этого класса? Тогда зачем ее отдельно писать?

2023-07-12 11:02 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
да, если присмотреться, тоже не очень понятно, зачем юзать хак для закрытых для модификации классов в открытых для модификации классов

2023-07-12 11:20 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
Если ты говоришь просто положить эти методы внутрь класса, то да, так лишних абстракций не будет. Но так пропадает масштабируемость, мне кажется. Но окей, давай попробуем так

2023-07-12 12:00 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/utils/TokenListFiatBalanceOperations.kt
> +internal suspend fun TotalFiatBalanceContext.calculateFiatBalance(): TokenList.FiatBalance {
Кажется что масштабируемость не страдает от этого, ведь если вдруг придется - можно расширить, а в остальном пусть следует принципу O из солида

2023-07-12 12:01 UTC, kozarezvlad approved these changes

2023-07-12 12:59 UTC, Sateetas approved these changes

2023-07-12 13:10 UTC, Mama1emon approved these changes

2023-07-12 14:37 UTC, merged