AND-3979 Merge first part of refactoring
tangem/tangem-app-android-old pull request #1140
Opened 2023-07-11 10:21 UTC by Sateetas

2023-07-12 07:18 UTC, Mama1emon requested changes

2023-07-12 07:18 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/ui/MultipleAddressUiHelper.kt
> +        return when (blockchain) {
На мой взгляд - if здесь более уместен

2023-07-12 07:18 UTC, Mama1emon commented on buildSrc/build/tmp/jar/MANIFEST.MF
> +Manifest-Version: 1.0
А это что такое?

2023-07-12 07:18 UTC, Mama1emon commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "1.0.0"
Почему понизил?

2023-07-12 07:18 UTC, Mama1emon commented on gradle/dependencies.toml
> +#tangemBlockchainSdk = "develop-240"
Почему понизил?

2023-07-12 08:19 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/wallet/ui/MultipleAddressUiHelper.kt
> +        return when (blockchain) {
а я стараюсь избегать вложенных if

2023-07-12 08:22 UTC, Sateetas commented on buildSrc/build/tmp/jar/MANIFEST.MF
> +Manifest-Version: 1.0
некий кодген, я уже добавил это в гитигнор недели 2-3 назад, но видимо в одной из ранних веток файл уже добавился в репу

в общем, удалил :)

2023-07-12 08:24 UTC, Sateetas commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "1.0.0"
по мотивам обсуждения с Владом, планируем выпиливать этот тогл в будущем

@kozarezvlad как сейчас поступаем при влитии в дев?

2023-07-12 08:24 UTC, Sateetas commented on gradle/dependencies.toml
> +#tangemBlockchainSdk = "develop-240"
сюда пока что не смотреть, мне нужна залитая в дев sdk, чтобы тут подставить актуальную версию

ревью параллельно идут

2023-07-12 08:31 UTC, kozarezvlad commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "1.0.0"
в дев оставляем пока 4.3.1

2023-07-12 08:33 UTC, kozarezvlad submitted a review, later dismissed
Ток удали лишнее что подтянулось вместе с проставлением версии сдк

2023-07-12 08:50 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect/WalletConnectSdkHelper.kt
> +            fee = Fee.Common(Amount(fee, wallet.blockchain)),
тут ничего не сломается, что мы передаем Fee.Common, а не Fee.Ethereum?

2023-07-12 09:38 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/ui/MultipleAddressUiHelper.kt
> +        return when (blockchain) {
Но ты используешь вложнные `if`))
Просто он лежит внутри `when`, который имеет две ветки и не предполагает расширения

2023-07-12 09:54 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletconnect/WalletConnectSdkHelper.kt
> +            fee = Fee.Common(Amount(fee, wallet.blockchain)),
сейчас работает, в дальнейшем подумаю, что можно сделать

пока что из разных мест gaslimit передается либо в fee (что идейно более правильно), либо в extras (как здесь)

2023-07-12 09:54 UTC, Sateetas commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "1.0.0"
ревертнул

2023-07-12 10:01 UTC, roman-pv submitted a review, later dismissed

2023-07-12 10:10 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/wallet/ui/MultipleAddressUiHelper.kt
> +        return when (blockchain) {
поменял — строчек меньше стало да, поправлю

во втором методе лучше особо не стало, поэтому оставлю как есть

2023-07-12 14:52 UTC, Sateetas commented on gradle/dependencies.toml
> +#tangemBlockchainSdk = "develop-240"
@Mama1emon готово, теперь tangemBlockchainSdk = "develop-281"

2023-07-13 04:48 UTC, Mama1emon approved these changes

2023-07-13 07:30 UTC, kozarezvlad approved these changes

2023-07-13 07:36 UTC, gbixahue approved these changes

2023-07-13 08:51 UTC, merged