AND-3986 Add ScanCardProcessor to DI graph
tangem/tangem-app-android-old pull request #1144
Opened 2023-07-11 14:27 UTC by Mama1emon

2023-07-11 16:15 UTC, Sateetas commented on domain/card/src/main/kotlin/com/tangem/domain/card/ScanCardProcessor.kt
> +interface ScanCardProcessor {
по желанию: мб сделать разное именование, к примеру scan/scanAsync?

2023-07-11 16:18 UTC, Sateetas commented on domain/card/src/main/kotlin/com/tangem/domain/card/ScanCardProcessor.kt
> +        analyticsEvent: AnalyticsEvent? = null,
я бы сделал реордер параметров по убыванию их значимости, к примеру, `onFailure`, `onSuccess` имеют куда большую значимось, чем `analyticsEvent` или `disclaimerWillShow`

2023-07-12 06:54 UTC, Mama1emon commented on domain/card/src/main/kotlin/com/tangem/domain/card/ScanCardProcessor.kt
> +        analyticsEvent: AnalyticsEvent? = null,
Данный компонент в будущем будет удален, так как в перспективе будет использоваться `ScanCardUseCase`.

2023-07-12 07:16 UTC, iiiburnyiii commented on domain/card/src/main/kotlin/com/tangem/domain/card/ScanCardProcessor.kt
> +        analyticsEvent: AnalyticsEvent? = null,
Да, это временная штука, Андрей просто скопировал его из app модуля. Как снимем тогл для новой логики скана, этот объект будет удален

2023-07-12 07:21 UTC, iiiburnyiii requested changes

2023-07-12 07:21 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/di/domain/card/CardDomainModule.kt
> +package com.tangem.tap.di.domain.card
Зачем нужен отдельный пакет `card`? В нем будет лежать только один файл, думаю в нём нет смысла

2023-07-12 07:21 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    }
Что мешает ловить клики назад в роутере, по аналогии в `OrganizeTokensViewModel`? Так можно избавиться от коллбека в стейте

<img width="683" alt="изображение" src="https://github.com/tangem/tangem-app-android/assets/26351057/66a75270-f916-46f0-936c-369569ae4e83">

2023-07-12 09:30 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/card/CardDomainModule.kt
> +package com.tangem.tap.di.domain.card
На мой взгляд так проще навигироваться, когда все разбито по пакетам.
```
domain
     card
     tokens
     wallets
```

Чем когда так.
```
CardDomainModule
TokensDomainModule
WalletsDomainModule
```

2023-07-12 09:31 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/card/CardDomainModule.kt
> +package com.tangem.tap.di.domain.card
При втором варианте, когда у нас будет большое кол0во таких классов, то трудно будет искать то, что нужно. Глаза будут в кучку собираться

2023-07-12 09:36 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    }
Данный коллбек имеет прямое отношение к состоянию экрана. А все данные, которые связаны с определнным экраном, должны описываться в его стейте. 

В твоем же случае получается так, что любой другой программист, который не знает твой код, будет ожидать, что все данные описаны в стейте. И при поиске обработчика назад или фикса бага с этим обработчиком ему придется бегать по всей фиче, чтобы понять, где это инициализируется, вместо того, чтобы заглянуть во вью модель

2023-07-12 09:58 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/di/domain/card/CardDomainModule.kt
> +package com.tangem.tap.di.domain.card
Про себя могу сказать, что я не ищу файлы по дереву, обычно, я ищу их поиском по проекту. Но если не получается найти поиском, то просто зайти в пакет `.domain` и найти там нужный файл займет гораздо меньше кликов, чем открывать каждый пакет внутри `.domain` и смотреть, что там лежит

2023-07-12 09:59 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    }
В целом согласен, можно закрывать

2023-07-12 10:33 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    }
В OrganizeTokens вынесешь в стейт?

2023-07-12 10:34 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    }
Да, потом

2023-07-12 10:38 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/domain/card/CardDomainModule.kt
> +package com.tangem.tap.di.domain.card
Поправил

2023-07-12 12:21 UTC, Sateetas approved these changes

2023-07-12 12:56 UTC, kozarezvlad approved these changes

2023-07-12 13:08 UTC, iiiburnyiii approved these changes

2023-07-12 13:09 UTC, merged