AND-3919 fixed cutting of seedPhrase suggestion buttons
tangem/tangem-app-android-old pull request #1146
Opened 2023-07-12 07:41 UTC by gbixahue

2023-07-12 09:27 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/Buttons.kt
> +fun SuggestionPrimaryButton(
Прикрепи, пожалуйста, ссылку на фигму в доке

2023-07-13 04:45 UTC, Mama1emon requested changes, later dismissed

2023-07-13 04:45 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/Buttons.kt
> +fun SuggestionPrimaryButton(
Кажись, это не ссылка на кнопку из ДС. У меня открывается Android UI / Onboarding

2023-07-13 09:50 UTC, gbixahue commented on core/ui/src/main/java/com/tangem/core/ui/components/Buttons.kt
> +fun SuggestionPrimaryButton(
Я не досмотрел компонент... Поправлю

2023-07-13 15:28 UTC, gbixahue commented on core/ui/src/main/java/com/tangem/core/ui/components/Buttons.kt
> +fun SuggestionPrimaryButton(
Исправил

2023-07-14 10:59 UTC, iiiburnyiii approved these changes
Если меняются/добавляются UI компоненты, то было бы круто прикладывать скрины preview

2023-07-17 12:12 UTC, Yoggam1 approved these changes

2023-07-17 12:45 UTC, roman-pv approved these changes

2023-07-18 05:29 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/Notifier.kt
> +    backgroundColor: Color = TangemTheme.colors.icon.inactive,
Стоит ли выносить отдельным параметром, то что будет передаваться через `modifier`?

2023-07-18 07:09 UTC, gbixahue commented on core/ui/src/main/java/com/tangem/core/ui/components/Notifier.kt
> +    backgroundColor: Color = TangemTheme.colors.icon.inactive,
То, что сейчас передается - дает возможность построить ряд из кнопок с соответсвтующими паддингами.

2023-07-19 10:01 UTC, merged