AND-3920 fixed showing import seedPhrase errors
tangem/tangem-app-android-old pull request #1150
Opened 2023-07-12 12:21 UTC by gbixahue

2023-07-12 12:53 UTC, Mama1emon approved these changes

2023-07-12 13:22 UTC, iiiburnyiii approved these changes

2023-07-13 10:35 UTC, Sateetas approved these changes

2023-07-14 05:02 UTC, Mama1emon requested changes

2023-07-14 05:02 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
>  import kotlinx.collections.immutable.toImmutableList
В коммитах увидел, что подмерживаешь дев в ветку. Это нарушит прямую историю коммитов.

2023-07-14 07:09 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
>  import kotlinx.collections.immutable.toImmutableList
Это был гитхабовский updateBranch - не переключил на ребейз

2023-07-14 07:21 UTC, Mama1emon approved these changes

2023-07-14 07:28 UTC, merged