AND-3814 Added the token list receiving for the wallet screen
tangem/tangem-app-android-old pull request #1155
Opened 2023-07-13 07:07 UTC by iiiburnyiii

2023-07-13 13:16 UTC, Yoggam1 requested changes

2023-07-13 13:16 UTC, Yoggam1 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +internal object DecimalsFormatter {
Можем вынести этот форматтер куда-то в common, если он будет форматировать currency. Такой форматтер нужен не только в экране wallet

2023-07-13 13:18 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +        return "$formattedAmount $currencySymbol"
Неправильный формат, надо по локали позицию

2023-07-13 13:18 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +            currency = Currency.getInstance(fiatCurrencyCode)
Крашнет когда юзер выберет валюту приложения satoshi и тп

2023-07-13 13:26 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +            currency = Currency.getInstance(fiatCurrencyCode)
Можно в целом костыльную как в тотал балансе сделал, форматнуть на любой валюте и потом сделать replace на нужную в строке уже прошедшей форматтер

2023-07-13 17:13 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +        return "$formattedAmount $currencySymbol"
Это для баланса в крипте, если судить по coin gecko, то у них код валюты идёт после балансе, но если у валюты есть символ, то он ставится перед балансом

2023-07-13 17:14 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +            currency = Currency.getInstance(fiatCurrencyCode)
Точняк, забыл, что у нас не только фиатные валюты

2023-07-14 10:36 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +            currency = Currency.getInstance(fiatCurrencyCode)
Поправил

2023-07-14 10:37 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +        return "$formattedAmount $currencySymbol"
Поправил

2023-07-14 10:37 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/DecimalsFormatter.kt
> +internal object DecimalsFormatter {
Вынес в `core.ui.utils` > `BigDecimalFormatter`

2023-07-14 10:38 UTC, Yoggam1 approved these changes, later dismissed

2023-07-14 14:19 UTC, kozarezvlad approved these changes

2023-07-14 15:11 UTC, Yoggam1 approved these changes

2023-07-14 21:25 UTC, merged