AND-4004 Restored ducatus.
tangem/tangem-app-android-old pull request #1156
Opened 2023-07-13 07:58 UTC by Sateetas

2023-07-13 11:25 UTC, Mama1emon submitted a review, later dismissed

2023-07-14 05:00 UTC, Mama1emon requested changes

2023-07-14 05:00 UTC, Mama1emon commented on gradle/dependencies.toml
>  # endregion Other libraries
В коммитах увидел мердж девелопа в эту ветке. Это нарушение договоренности. Прямая история коммитов нарушится

2023-07-18 12:17 UTC, Sateetas commented on gradle/dependencies.toml
>  # endregion Other libraries
мой косяк, да

буду следить за этим

2023-07-18 13:39 UTC, Yoggam1 approved these changes

2023-07-18 13:52 UTC, Mama1emon approved these changes

2023-07-18 15:02 UTC, merged