AND-4019 Add scan card logic
tangem/tangem-app-android-old pull request #1163
Opened 2023-07-14 08:29 UTC by Mama1emon

2023-07-14 10:03 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                    if (userWallet != null) {
из кода не совсем понятно в каком случае userWallet == null и почему если он null вызываем то, что вызываем

2023-07-14 10:51 UTC, iiiburnyiii requested changes

2023-07-14 10:51 UTC, iiiburnyiii commented on domain/card/src/main/kotlin/com/tangem/domain/card/repository/AccessCodeSavingRepository.kt
> +interface AccessCodeSavingRepository {
Думаю лучше `CardAccessCodeRepository`

2023-07-14 10:51 UTC, iiiburnyiii commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Лучше всю логику создания user wallet инкапсулировать здесь

2023-07-14 10:51 UTC, iiiburnyiii commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +class SaveWalletUseCase(private val walletsStateHolder: WalletsStateHolder) {
Может можно менеджер напрямую отдать? Use case все равно без него работать не будет

2023-07-14 10:51 UTC, iiiburnyiii commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Это результат из sdk, стоит использовать `Either`. Перемапить не сильно сложно

2023-07-14 11:11 UTC, Mama1emon commented on domain/card/src/main/kotlin/com/tangem/domain/card/repository/AccessCodeSavingRepository.kt
> +interface AccessCodeSavingRepository {
Тут спорный момент возникает. Access code - это часть `TangemSdk`, а значит ответственность `CardSdkConfigRepository`. А данный репозиторий берет ответственность за возвращение флага включения сохранения access code

2023-07-14 11:12 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Типо принимать на вход `scanResponse`?

2023-07-14 11:14 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +class SaveWalletUseCase(private val walletsStateHolder: WalletsStateHolder) {
По моей памяти мы договорились в будущем данный менеджер разбить на use case, так как сейчас нет на это ресурсов. Именно поэтому я пока что его просто переиспользую

2023-07-14 11:15 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Сделаю. Хорошо бы в будущем возвращать сразу Either из SDK

2023-07-14 11:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                    if (userWallet != null) {
Обновил

2023-07-14 11:47 UTC, iiiburnyiii commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Агась

2023-07-14 11:47 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Готово

2023-07-14 11:50 UTC, iiiburnyiii commented on domain/card/src/main/kotlin/com/tangem/domain/card/repository/AccessCodeSavingRepository.kt
> +interface AccessCodeSavingRepository {
Может объединить эти репозитории? Они же используются только в domain фиче

2023-07-14 11:53 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Тогда, по сути, мы начинаем связывать два домейна: карт и воллетов, что не очень хорошо.
Но я и не вижу ничего плохого, что мы отдаем готовую домейн модель для сохранения. Единственное, что я бы хотел улучшить, это создать фактори для создания UserWallet, которую мы будем использовать снаружи

2023-07-14 11:53 UTC, Mama1emon commented on domain/card/src/main/kotlin/com/tangem/domain/card/repository/AccessCodeSavingRepository.kt
> +interface AccessCodeSavingRepository {
В принципе пофиг, давай объединю

2023-07-14 12:03 UTC, Mama1emon commented on domain/card/src/main/kotlin/com/tangem/domain/card/repository/AccessCodeSavingRepository.kt
> +interface AccessCodeSavingRepository {
Сделал

2023-07-14 13:53 UTC, kozarezvlad submitted a review, later dismissed

2023-07-14 14:07 UTC, iiiburnyiii commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    @Throws(IllegalArgumentException::class)
Тут throws лучше убрать и обрабатывать эту ошибку в either.
А ещё лучше сделать что-то такое для `CompletitionResult` в `:domain:core` https://arrow-kt.io/learn/typed-errors/own-error-types/, тогда будет нормальный retrun

2023-07-14 14:10 UTC, iiiburnyiii commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Ну, вообще они достаточно сильно связаны и так. Возможно их вообще стоит обеденить, так как одно без другого не существует в рамках приложения.
Мне кажется лучше передать сюда scan response и создавать user wallet тут, можем это в пн командой обсудить

2023-07-14 14:18 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet, canOverride: Boolean = false): CompletionResult<Unit> {
Давайте обсудим в ПН

2023-07-14 14:23 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/SaveWalletUseCase.kt
> +    @Throws(IllegalArgumentException::class)
Аннотации здесь быть не должно. Забыл удалить. А вот как улучшить `return` я не понял

2023-07-18 11:32 UTC, Yoggam1 approved these changes

2023-07-18 12:32 UTC, iiiburnyiii approved these changes

2023-07-18 13:11 UTC, merged