AND-4020 added pull to refresh on main wallet screen
tangem/tangem-app-android-old pull request #1168
Opened 2023-07-14 13:49 UTC by kozarezvlad

https://github.com/tangem/tangem-app-android/assets/8160279/70a7389b-8c2f-4d42-b850-24fcd6f11715

2023-07-14 15:17 UTC, Mama1emon requested changes

2023-07-14 15:17 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/WalletScreen.kt
> +import androidx.compose.material.pullrefresh.PullRefreshIndicator
В material3 нет случайно такого компонента?

2023-07-14 15:17 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/PullToRefreshConfig.kt
> +data class PullToRefreshConfig(val isRefreshing: Boolean, val onRefresh: () -> Unit)
Предлагаю добавить приставку `Wallet` подобно другим конфигам стейта экрана воллета. Это позволит легче навигироваться в проекте. Особенно, если на другом экране появится такой же конфиг.

2023-07-17 07:45 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/WalletScreen.kt
> +import androidx.compose.material.pullrefresh.PullRefreshIndicator
Нет

2023-07-17 08:23 UTC, Mama1emon submitted a review, later dismissed

2023-07-18 07:17 UTC, Yoggam1 submitted a review, later dismissed

2023-07-18 13:18 UTC, Yoggam1 submitted a review, later dismissed

2023-07-18 13:48 UTC, Mama1emon approved these changes, later dismissed

2023-07-18 14:24 UTC, Yoggam1 approved these changes

2023-07-18 14:25 UTC, Mama1emon approved these changes

2023-07-18 14:36 UTC, merged