Token details redesign: Token title and icon block
tangem/tangem-app-android-old pull request #1169
Opened 2023-07-16 02:19 UTC by Yoggam1

2023-07-17 07:35 UTC, Mama1emon requested changes

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/TokenDetailsFragment.kt
> +                    val viewModel = hiltViewModel<TokenDetailsViewModel>().also { vm ->
Почему именно `also`? `apply` больше подходит, так как выполняется действие подобно билдеру

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenInfoBlockState.kt
> +    sealed class Network {
`TokenNetwork` - имеет не совсем понятный смысл.
Что думаешь насчет того, чтобы использовать название `Currency`? Тогда потомки будут - `Native`, `Token`.

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +                .padding(horizontal = 16.dp)
dimens

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenDetailsTopAppBar.kt
> +                Icon(painter = painterResource(id = R.drawable.ic_more_vertical_24), contentDescription = "More")
tint?

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +import androidx.compose.material.Icon
material3?

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +                painter = painterResource(id = R.drawable.img_stellar_22),
Не убрал мок?

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +                modifier = Modifier.size(48.dp),
dimens?

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +            AsyncImage(
Если я не ошибаюсь, то есть более свежая штука, которая позволяет передавать ссылку для загрузки через painter. Тогда удастся использовать только один Image компонент

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +                text = "Main network",
TODO?

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +            Text(
color?

2023-07-17 07:35 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +                horizontalArrangement = Arrangement.spacedBy(4.dp),
dimens?

2023-07-17 09:58 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +                painter = painterResource(id = R.drawable.img_stellar_22),
Это чисто для превью. Поэтому стоит мок, так как превью не может загружать изображения

2023-07-17 10:02 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/TokenDetailsFragment.kt
> +                    val viewModel = hiltViewModel<TokenDetailsViewModel>().also { vm ->
1. С apply идет стирание контекста, поэтому я стараюсь избегать его. Несколько раз стреляло.
2. Как по мне, это не билдер. Создаем объект, `а так же` задаем значение поле которое внутри объекта

2023-07-18 06:24 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenInfoBlockState.kt
> +    sealed class Network {
Отличное предложение!

2023-07-18 06:25 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +                .padding(horizontal = 16.dp)
сделал

2023-07-18 06:31 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenDetailsTopAppBar.kt
> +                Icon(painter = painterResource(id = R.drawable.ic_more_vertical_24), contentDescription = "More")
добавил

2023-07-18 06:31 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +import androidx.compose.material.Icon
Заменил

2023-07-18 06:32 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +                modifier = Modifier.size(48.dp),
Сделал

2023-07-18 06:32 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +            AsyncImage(
Сделал

2023-07-18 06:32 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +                text = "Main network",
Заменил

2023-07-18 06:33 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +                horizontalArrangement = Arrangement.spacedBy(4.dp),
Сделал

2023-07-18 06:34 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenInfoBlock.kt
> +            Text(
Было внутри стиля, вынес

2023-07-18 07:24 UTC, kozarezvlad submitted a review, later dismissed

2023-07-18 08:25 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/TokenDetailsFragment.kt
> +    internal lateinit var tokenDetailsRouter: TokenDetailsRouter
`internal` необязательно вроде как указывать, так как класс уже `internal`

2023-07-18 08:25 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/TokenDetailsFragment.kt
> +            "internalTokenDetailsRouter should be instance of InnerWalletRouter"
Ошибка в комменте - `InnerWalletRouter`

2023-07-18 08:25 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenInfoBlockState.kt
> +            val network: String,
А чем `network` от `blockchain` отличается? По названию не совсем понятно

2023-07-18 08:25 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +        Column(
Скролл хорошо бы добавить - экран может быть очень длинный

2023-07-18 08:34 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +        Column(
Добавлю когда занесу блок с историей транзакции

2023-07-18 08:38 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenInfoBlockState.kt
> +            val network: String,
network: ERC20, blockchain: Ethereum

2023-07-18 08:58 UTC, kozarezvlad commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenInfoBlockState.kt
> +            val network: String,
Это маппится на ту модель json токенов что нам приходят?

2023-07-18 09:37 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenInfoBlockState.kt
> +            val network: String,
В данный момент не очень ясно, откуда и что будет мапиться. Это чисто UI стейт, и тут описаны поля которые нужны для отрисовки UI

2023-07-18 09:37 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenInfoBlockState.kt
> +            val network: String,
Все равно непонятно, чем `networkName` отличается от `blockchainName`

2023-07-18 11:08 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenInfoBlockState.kt
> +            val network: String,
Добавил доку

2023-07-18 11:23 UTC, Mama1emon approved these changes

2023-07-18 11:58 UTC, kozarezvlad approved these changes

2023-07-18 16:55 UTC, merged