AND-3813 Updated tokens operations
tangem/tangem-app-android-old pull request #1171
Opened 2023-07-16 15:32 UTC by iiiburnyiii

2023-07-17 09:14 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
зачем экстеншн?

2023-07-17 09:15 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/operations/TokenListSortingOperations.kt
> +            .toNonEmptySetOrNull()!! // Can not be empty here
requireNotNull?

2023-07-17 09:20 UTC, kozarezvlad requested changes

2023-07-17 09:20 UTC, kozarezvlad commented on domain/core/src/main/kotlin/com/tangem/domain/core/error/DataError.kt
> +    object NetworkError : DataError()
NetworkError предполагает ошибку сети при отсутствии инета или например 400 или 500?
Как-то это расширить бы немного

2023-07-17 09:20 UTC, kozarezvlad commented on domain/core/src/main/kotlin/com/tangem/domain/core/error/DataError.kt
> +    // TODO
todo кажется излишним, понятно что можно расширить - это можно указать в kd к классу

2023-07-17 09:20 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
Где это используется?

2023-07-17 09:20 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokensStatuses(
И это?

2023-07-17 09:20 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.createTokenList(
И это?

2023-07-17 09:20 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
Не понимаю, чем тут оправданы экстеншены. 80% кода получается статическим и загружается сразу на старте прилы вися в памяти

2023-07-17 09:20 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/operations/TokenListSortingOperations.kt
> +            .toNonEmptySetOrNull()!! // Can not be empty here
может тогда лучше error с комментов в ошибку?

2023-07-17 09:20 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/operations/TokenListSortingOperations.kt
> +                val tokens = group.tokens.toNonEmptySetOrNull()!! // Can not be empty
Лучше error использовать тогда и написать "Can not be empty" в нем

2023-07-17 09:20 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/operations/TokenListSortingOperations.kt
> +                .toNonEmptySetOrNull()!! // Can not be empty here
и тут

2023-07-17 09:32 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
Уже отвечал в предыдущем МРе: https://github.com/tangem/tangem-app-android/pull/1132#discussion_r1260851476

2023-07-17 09:32 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
Уже отвечал в предыдущем МРе: https://github.com/tangem/tangem-app-android/pull/1132#discussion_r1260851476

2023-07-17 09:45 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
И почему статическим? Эти методы лежат внутри класса

2023-07-17 09:50 UTC, iiiburnyiii commented on domain/core/src/main/kotlin/com/tangem/domain/core/error/DataError.kt
> +    // TODO
Убрал

2023-07-17 12:22 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
Да, тут не статик будет, а в байткоде как метод класса принимающий параметром Raise.
Тогда предлагаю вынести из ПР обсуждение по использованию расширений и зафиксировать где они оправданы, где нет. Если тут добавляет удобство в обмазывании функциональщиной, то окей. Но например глядя на расширения UserWalletsListManager не понятно, зачем они отделены от основного класса, ведь вызов все равно через объект идет

2023-07-17 12:39 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenListUseCase.kt
> +    private fun Raise<TokenListError>.getTokenList(userWalletId: UserWalletId, refresh: Boolean): Flow<TokenList> {
В целом да, тут raise можно просто вынести в аргументы, но тогда при выходе context receivers из беты это будет чуть сложнее рефакторить

2023-07-19 04:19 UTC, Mama1emon commented on domain/core/src/main/kotlin/com/tangem/domain/core/error/DataError.kt
> +sealed class DataError : Exception() {
А где посмотреть, как это используется?

2023-07-19 04:19 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokenListError.kt
> +    data class DataError(val cause: Throwable) : TokenListError()
А зачем исключение передается? Теряется же строгая типизация

2023-07-19 05:53 UTC, iiiburnyiii commented on domain/core/src/main/kotlin/com/tangem/domain/core/error/DataError.kt
> +sealed class DataError : Exception() {
Сейчас только в тестах use case'а) Решил не убирать что-бы не переписывать уже и так переписанные тест кейсы. Но в дальнейшем предлагаю тут собрать какой-то основной пул ошибок слоя данных, что-бы было удобнее обрабатывать их в presentation

2023-07-19 06:00 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/error/TokenListError.kt
> +    data class DataError(val cause: Throwable) : TokenListError()
Так, мы же обсудили и решили убрать типизацию ошибок слоя данных. Теперь вызовы методов из репозитория оборачиваются в `catch` и, в случае возникновения ошибки, выбрасывается эта ошибка:
<img width="693" alt="изображение" src="https://github.com/tangem/tangem-app-android/assets/26351057/bcc63c88-df81-4b54-a37e-f23e641ad691">

В дальнейшем эта ошибка может быть обработана в фиче, как ей угодно

2023-07-19 07:49 UTC, Mama1emon approved these changes

2023-07-19 09:10 UTC, kozarezvlad approved these changes

2023-07-19 09:45 UTC, Sateetas approved these changes

2023-07-19 10:58 UTC, merged