AND-3855 shopify dynamic products
tangem/tangem-app-android-old pull request #1189
Opened 2023-07-19 15:22 UTC by kozarezvlad

2023-07-20 09:37 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/shop/domain/GetShopifySalesProductsUseCase.kt
> + * use case to get shopify available products
use -> Use

2023-07-20 09:37 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/shop/domain/models/ProductType.kt
> +const val TANGEM_WALLET_3_CARDS_SKU = "TG115X3-S"
Они больше нигде не используются? Может объявить приватными?

2023-07-20 09:37 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/shop/ui/ShopFragment.kt
> +        } else {
Можно убрать одну вложенность
```
getSelectedSalesProduct(state)?.notification?.let { 
    binding.tvSoldOutDesc.text = it.description
}
```

2023-07-20 09:42 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/shop/ui/ShopFragment.kt
> +                    binding.tvSoldOutDesc.text = notification.description
Можно убрать одну вложенность
```
getSelectedSalesProduct(state)?.notification?.let { 
    binding.tvSoldOutDesc.text = it.description
}
```

2023-07-20 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/shop/data/DefaultShopRepository.kt
> +        }
Это, кажется, лишнее. И так вернется `kotlin.Result` или тут какой-то другой Result возвращается?

2023-07-20 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/shop/data/DefaultShopRepository.kt
> +            return Result.success(salesProductConverter.convert(it))
Тут return не нужен

2023-07-20 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/shop/data/SalesProductConverter.kt
> +class SalesProductConverter : Converter<SalesResponse, List<SalesProduct>> {
Кажется лучше это отдать в moshi, он умеет из коробки конвертировать enum'ы. Нужно только полю в `SalesResponse` поменять тип на нужный enum.

2023-07-20 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/shop/domain/GetShopifySalesProductsUseCase.kt
> +    }
```suggestion
        return shopRepository.getSalesProductInfo().fold(
            onSuccess = {
                it.right()
            },
            onFailure = {
                SalesError.GeneralSalesError(it).left()
            },
        )
    }
```

2023-07-20 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/shop/data/DefaultShopRepository.kt
> +    override suspend fun getSalesProductInfo(): Result<List<SalesProduct>> {
Зачем тут `Result`? Кажетсяь тут от него нет никакой выгоды, только лишние манипуляции с `map`. `Throwable` можно просто поймать в use case через `catch` или `try {} catch {}`

2023-07-20 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/shop/domain/models/SalesError.kt
> +    data class GeneralSalesError(val cause: Throwable) : SalesError()
Думаю стоит явно дать понять, что эта ошибка из слоя данных
```suggestion
    data class DataError(val cause: Throwable) : SalesError()
```

2023-07-20 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/shop/presentation/ShopViewModel.kt
> +    }
```suggestion
            val action = getShopifySalesProductsUseCase().fold(
                ShopAction::SalesProductsLoaded, 
                ShopAction::SalesProductsError,
            )
            
            appStateHolder.mainStore?.dispatch(action)
        }
    }
```

2023-07-21 08:50 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/domain/GetShopifySalesProductsUseCase.kt
> + * use case to get shopify available products
поправил

2023-07-21 08:50 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/domain/models/ProductType.kt
> +const val TANGEM_WALLET_3_CARDS_SKU = "TG115X3-S"
поправил

2023-07-21 08:51 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/ui/ShopFragment.kt
> +                    binding.tvSoldOutDesc.text = notification.description
не заметил что одно и то же там, поправил

2023-07-21 08:51 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/data/DefaultShopRepository.kt
> +        }
убрал Result

2023-07-21 08:51 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/data/DefaultShopRepository.kt
> +            return Result.success(salesProductConverter.convert(it))
убрал Result

2023-07-21 08:52 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/data/SalesProductConverter.kt
> +class SalesProductConverter : Converter<SalesResponse, List<SalesProduct>> {
Не стал, чтобы енумы не перекладывать и на уровне домейна обработать руками непредвиденную строку

2023-07-21 08:52 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/domain/GetShopifySalesProductsUseCase.kt
> +    }
Поправил

2023-07-21 08:52 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/data/DefaultShopRepository.kt
> +    override suspend fun getSalesProductInfo(): Result<List<SalesProduct>> {
убрал Result

2023-07-21 08:52 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/domain/models/SalesError.kt
> +    data class GeneralSalesError(val cause: Throwable) : SalesError()
ок

2023-07-21 08:52 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/presentation/ShopViewModel.kt
> +    }
Поправил, но не совсем так вышло

2023-07-24 15:26 UTC, iiiburnyiii submitted a review, later dismissed

2023-07-24 15:26 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/shop/data/DefaultShopRepository.kt
> +        return if (Locale.getDefault().language == "ru") {
Точно других стран не будет?

2023-07-25 02:08 UTC, Mama1emon requested changes

2023-07-25 02:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/shop/data/SalesProductConverter.kt
> +class SalesProductConverter : Converter<SalesResponse, List<SalesProduct>> {
internal?

2023-07-25 02:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/shop/data/SalesProductConverter.kt
> +            val productState = when (it.state) {
Много `it`, предлагаю дать имя

2023-07-25 02:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/shop/domain/GetShopifySalesProductsUseCase.kt
> +internal class GetShopifySalesProductsUseCase(
Почему internal?

2023-07-25 02:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/shop/toggles/DefaultShopifyFeatureToggleManager.kt
> +class DefaultShopifyFeatureToggleManager @Inject constructor(
1. internal
2. Лучше создавать объект через конструктор в DI модуле, чтобы не провайдить лишнюю зависимость

2023-07-25 02:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/shop/ui/ShopFragment.kt
> +        return null
```suggestion
        return  state.salesProducts.any { it.productType == state.selectedProduct }
```

2023-07-25 07:10 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/shop/data/DefaultShopRepository.kt
> +        return if (Locale.getDefault().language == "ru") {
Вообще будут, но на данный момент переводов нет на бэке и саппорта других языков, так что пока так

2023-07-26 02:17 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/shop/toggles/DefaultShopifyFeatureToggleManager.kt
> +class DefaultShopifyFeatureToggleManager @Inject constructor(
`Inject` аннотация осталась

2023-07-26 09:53 UTC, iiiburnyiii approved these changes

2023-07-26 10:01 UTC, Mama1emon approved these changes

2023-07-26 10:01 UTC, merged