AND-3640 Develop WalletViewModel
tangem/tangem-app-android-old pull request #1194
Opened 2023-07-20 13:03 UTC by Mama1emon

2023-07-20 13:10 UTC, gbixahue submitted a review, later dismissed

2023-07-20 13:25 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/WalletPreviewData.kt
> +        id = UserWalletId(UUID.randomUUID().toString()),
мб в утил вынести `UUID.randomUUID().toString())`?

2023-07-21 06:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/WalletPreviewData.kt
> +        id = UserWalletId(UUID.randomUUID().toString()),
Это моки для инициализации превью, поэтому не так критично

2023-07-21 07:02 UTC, iiiburnyiii requested changes

2023-07-21 07:02 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +) : ViewModel(), DefaultLifecycleObserver {
Мне очень не нравиться, что для нас стало нормой связывать view model и ЖЦ фрагмента, несмотря на то, что мы юзаем компоуз и у него свой ЖЦ. Чем предыдущий вариант не устраивал? Загрузка инициализировалась при первом запросе стейта от UI, как это и должно быть

2023-07-21 07:44 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +) : ViewModel(), DefaultLifecycleObserver {
1. Мы не связываем вью модель с ЖЦ фрагмента. Мы говорим, что вью модель, которую использует экран (НЕ ФРАГМЕНТ), может знать о том, когда он создается и разрушается.
2. Данный вариант сам знает, когда ему слушать данные из флоу, а когда отписываться от этих данных.
3. Я не считаю, что твой вариант был плохой. Извини, если тебе показалось иначе. Я уже давно ношу в локальных изменениях вью модель, которая работала именно так. Я просто преобразовал твой код так, чтобы внутренние механизмы из коробки безопасно вызывали его.
4. На одном из созвонов обсуждали данный механизм. Всем было ок.

2023-07-21 07:51 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +) : ViewModel(), DefaultLifecycleObserver {
1. Предлагаю рассматривать DefaultLifecycleObserver как те же action происходящие на экране, просто не по инициализации пользователя, а по причинам ЖЦ. Тут нет привязки к ЖЦ как мне кажется, а также ты говоришь "реагирую на эти вот события UI", как клик кнопки.
2. Вопрос в том должна ли viewModel на них реагировать и зачем? В большинстве случаев, данные нам нужны на ините, а дальнейший апдейт зависит от действий пользователя. В таком случае нет смысла слушать эти события

2023-07-21 08:20 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +) : ViewModel(), DefaultLifecycleObserver {
1. Тут используется lifecycle фрагмента, а не compose экрана, у них разный ЖЦ. Я не говорю, что мы их напрямую связываем и в этом и проблема, пожалуй. Вместо фрагмента тут может быть activity и это может вылется в неприятности в дальнейшем. Например, в момент когда мы откажемся от фрагментов коллбек `onCreate` не будет вызван.
2. Для этого можно исползовать state flow вместо mutable state, для стейта. compose уже умеет на него нормально подписываться.
3. Я не обижаюсь, просто не понимаю, но спасибо за заботу)
4. Насколько помню я был за, как за временное решение, но не постоянную практику. Если это не так, значит я успел поменять свое мнение)

Итого, если мы хотим как-то мониторить создание вьюхи (начало работы со стейтом) и её смерть, то я предлагаю использовать state flow для стейта, у него есть необходимый набор инстрементов (напирмер, метод `onSubscribtion { ... }`) и его можно слушать с подвязкой на ЖЦ компоуза. Вопрос в том, нужно ли нам это сдесь?

2023-07-21 08:28 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +) : ViewModel(), DefaultLifecycleObserver {
> Тут используется lifecycle фрагмента, а не compose экрана, у них разный ЖЦ.
В файле фрагмента я подписываюсь именно на данную компоуз сущность.

> Например, в момент когда мы откажемся от фрагментов коллбек onCreate не будет вызван.
Этого не произойдет. У меня был опыт миграции проекта на чистый компоуз. Данный механизм отрабатывает верно. Нет никакой привязки на ЖЦ фрагмента

2023-07-21 08:30 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +) : ViewModel(), DefaultLifecycleObserver {
И получится вариант подобно моему. Только я говорю именно вью моделе, что она может откликаться на данные ивенты
> Для этого можно исползовать state flow вместо mutable state, для стейта. compose уже умеет на него нормально подписываться.

2023-07-21 08:32 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +) : ViewModel(), DefaultLifecycleObserver {
Для компоуза есть нативные средства для изменения стейта, которые мы уже используем.
На моей практике был кейс, когда флоу работал некорректно и не все данные долетали до экрана. Как раз таки лечил использованием MutableState
> то я предлагаю использовать state flow для стейта

2023-07-21 11:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/builder/WalletStateFactory.kt
> +        val cardTypeResolver = wallets.first().scanResponse.cardTypesResolver
Тут точно безопасно так делать? Думаю лучше явно передавать в аргументах метода ID выбранного кошелька, либо его индекс

2023-07-21 11:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/decorations/WalletContentItemDecoration.kt
> +        currentIndex == 0 && lastIndex == 0 -> {
Стоит вынести в переменную

2023-07-21 11:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/decorations/WalletContentItemDecoration.kt
> +                )
Такой шейп должен быть в теме

2023-07-21 11:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +) : ViewModel(), DefaultLifecycleObserver {
Обсудили, можно резолвить

2023-07-21 11:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                )
Стоит вынести в отдельный метод

2023-07-21 11:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                updateContentItems()
Стоит вынести в отдельный метод

2023-07-21 11:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +            .flowOn(dispatchers.io)
Лучше мапинг на default диспатчере делать. use case должен сам определять в каком он flow крутиться

2023-07-21 11:28 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +            .flowOn(dispatchers.io)
Тут тоже про диспатчер

2023-07-23 04:49 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/builder/WalletStateFactory.kt
> +        val cardTypeResolver = wallets.first().scanResponse.cardTypesResolver
1) Забыл при переносе добавить еще одну проверку. При вызове как раз список проверяется на пустоту.
2) Пока не буду передавать выбранный кошелек, так как сейчас это не нужно и я не совсем до конца продумал, как это будет в конечном варианте выглядеть. Точно будут еще доработки.

2023-07-23 04:51 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/decorations/WalletContentItemDecoration.kt
> +        currentIndex == 0 && lastIndex == 0 -> {
На мой взгляд - условия достаточно простые, чтобы выносить в отдельную переменную, но если очень хочется, то давай

2023-07-23 04:54 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/ui/decorations/WalletContentItemDecoration.kt
> +                )
Хорошее замечание, спасибо

2023-07-23 05:00 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                )
Да, согласен, спасибо

2023-07-23 05:04 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                updateContentItems()
Что именно вынести в отдельный метод? Лямбду, которую я передаю в `onEach`?
На мой взгляд - это излишне. Функция небольшая и читается код легко

2023-07-23 05:10 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +            .flowOn(dispatchers.io)
Здесь тоже спорный момент. Я слышал, что использовать дефолтный диспатчер только для маппинга - это плохая практика, так как не происходит сложных вычислений, требуемых больших ресурсов процессора. На переключение диспатчера уйдет больше ресов.

2023-07-24 07:43 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +            .flowOn(dispatchers.io)
В таком случае можно вообще ничего не переключать и вызывать функцию на мейне. Внутренняя логика сама должна знать, что и на что переключать

2023-07-24 07:49 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +            .flowOn(dispatchers.io)
Окей, давай пока оставим так. На IO все равно не должно фризить, если что потом поправим

2023-07-24 07:50 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                updateContentItems()
В целом чем меньше работы происходит внутри лямбд тем лучше код читается, мне кажется. Но тут да, кода не много, пока-что, можно пока оставить так

2023-07-24 07:50 UTC, iiiburnyiii approved these changes

2023-07-24 07:55 UTC, Sateetas approved these changes

2023-07-24 08:02 UTC, merged