AND-4048 Added cache registry
tangem/tangem-app-android-old pull request #1200
Opened 2023-07-20 17:23 UTC by iiiburnyiii

Добавил реестр кеша, он нужен для оборачивания запросов в сеть, что-бы они вызвались только если ключ кеша протух. 
Пример:
```
private suspend fun fetchTokensIfCacheExpire(userWalletId: UserWalletId, refresh: Boolean) {
    cacheRegistry.invokeOnExpire(
        key = getTokensCacheKey(userWalletId),
        skipCache = refresh,
        block = { fetchTokens(userWalletId) },
    )
}
```

Метод `fetchTokens(userWalletId)` будет вызван если: 
- refresh == true
- такого ключа нет
- с момента предыдущего вызова с этим ключем прошло больше 5 минут
- предыдущий вызов с этим ключем упал с ошибкой

2023-07-21 06:58 UTC, Mama1emon requested changes

2023-07-21 06:58 UTC, Mama1emon commented on settings.gradle.kts
> +include(":data:source:local")
Вроде как договаривались не дробить

2023-07-21 06:58 UTC, Mama1emon commented on gradle/dependencies.toml
> +kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDatetime" }
Вроде как йоду используем в проекте

2023-07-21 06:58 UTC, Mama1emon commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/store/RuntimeStore.kt
> +    // TODO: Uncomment if needed
А почему сразу не расскоменчено?

2023-07-21 06:58 UTC, Mama1emon commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/cache/di/CacheKeyStoreModule.kt
> +    fun provideCacheKeyStore(): CacheKeysStore {
`provideCacheKey**s**Store`

2023-07-21 06:58 UTC, Mama1emon commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/cache/RuntimeCacheKeysStore.kt
> +    private val store = RuntimeStore(keyProvider = CacheKey::id)
Нарушение принципа инверсии зависимостей, происходит привязка конкретной реализации. Нужно извне сеттить зависимости

2023-07-21 06:58 UTC, Mama1emon commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/store/RuntimeStore.kt
> +internal class RuntimeStore<Key, Data>(private val keyProvider: (Data) -> Key) {
Не совсем понял идею с написанием данной сущности. CacheKeysStore выглядит как абстракция, которая просто перемапливает функции этого компонента

2023-07-21 07:08 UTC, iiiburnyiii commented on gradle/dependencies.toml
> +kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDatetime" }
Забыл, поправлю

2023-07-21 07:08 UTC, iiiburnyiii commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/store/RuntimeStore.kt
> +    // TODO: Uncomment if needed
Сейчас не используется

2023-07-21 07:11 UTC, iiiburnyiii commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/store/RuntimeStore.kt
> +internal class RuntimeStore<Key, Data>(private val keyProvider: (Data) -> Key) {
Так и есть, этот store не завязан на конкретные модели, тут только логика хранения. Более верхнеуровненвые сторы добавляют работу с конкретными моделями.

2023-07-21 07:35 UTC, iiiburnyiii commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/cache/RuntimeCacheKeysStore.kt
> +    private val store = RuntimeStore(keyProvider = CacheKey::id)
У этого `RuntimeStore` и есть одна реализация, тут нет смысла его инверсировать

2023-07-21 09:02 UTC, iiiburnyiii commented on settings.gradle.kts
> +include(":data:source:local")
Вынес в `:core:datasource`

2023-07-24 07:23 UTC, kozarezvlad approved these changes

2023-07-24 07:35 UTC, Mama1emon commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/cache/RuntimeCacheKeysStore.kt
> +    private val store = RuntimeStore(keyProvider = CacheKey::id)
Я не могу согласиться с данным решением. Несмотря на то, что сейчас мы явно заявляем, что используется только эта реализация, но также:
1) мы теряем гибкость при тестируемости
2) мы теряем гибкость для расширения в будущем без изменения реализации

2023-07-24 07:40 UTC, Mama1emon commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/store/RuntimeStore.kt
> +internal class RuntimeStore<Key, Data>(private val keyProvider: (Data) -> Key) {
Я не понимаю отличий между этими двумя сущностями. Я вижу простое перемапливание. Давай созвонимся, обсудим

2023-07-24 07:46 UTC, iiiburnyiii commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/cache/RuntimeCacheKeysStore.kt
> +    private val store = RuntimeStore(keyProvider = CacheKey::id)
Мы бы теряли гибкость если бы все низкоуровненвые сторы переопределяли один интерфейс, возможно так и стоит сделать, но сейчас это не так, так как логика хранения может по разному работать. Давай заведу таску и потом поресерчу, сейчас есть проблема со сроками

2023-07-24 07:49 UTC, kozarezvlad commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/cache/RuntimeCacheKeysStore.kt
> +    private val store = RuntimeStore(keyProvider = CacheKey::id)
Тут может быть проблема, что если вдруг кэш будет работать медленно и мы подумаем что давайте другую реализицию сделаем, то да. Но кажется сейчас это меньшая из наших проблем. Приходится балансировать между скоростью и качеством

2023-07-24 07:53 UTC, iiiburnyiii commented on data/source/local/src/main/kotlin/com/tangem/data/source/local/store/RuntimeStore.kt
> +internal class RuntimeStore<Key, Data>(private val keyProvider: (Data) -> Key) {
Тут логика такая, что в дальнейшем тоже появятся сторы, которые будут переиспользовать `RuntimeStore`, что-бы эту логику не копипастить, вынес её в отдельный класс

2023-07-24 08:05 UTC, Mama1emon approved these changes

2023-07-24 08:15 UTC, merged