AND-3757 Implemented domain for transaction history
tangem/tangem-app-android-old pull request #1215
Opened 2023-07-24 05:21 UTC by Yoggam1

2023-07-24 06:48 UTC, Mama1emon requested changes

2023-07-24 06:48 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/proxy/TxHistoryManagerImpl.kt
> +        val walletManager = appStateHolder.walletState?.getWalletManager(blockchainNetwork)
По моей памяти - это легаси. Сейчас лучше юзать WalletStoresManager, надо у Антона Ткачева уточнить

2023-07-24 06:48 UTC, Mama1emon commented on data/txhistory/src/main/kotlin/com/tangem/data/txhistory/mock/MockTxHistoryItems.kt
> +object MockTxHistoryItems {
internal?

2023-07-24 06:48 UTC, Mama1emon commented on data/txhistory/src/main/kotlin/com/tangem/data/txhistory/repository/MockTxHistoryRepository.kt
> +    ): Flow<List<TxHistoryItem>> {
А как же пагинация?
Flow<PagingData<List<TxHistoryItem>>

2023-07-24 06:48 UTC, Mama1emon commented on domain/txhistory/src/main/kotlin/com/tangem/domain/txhistory/usecase/GetTxHistoryItemsCountUseCase.kt
> +        return withContext(dispatchers.io) {
На мой взгляд - репозиторий, которому явно надо использовать io операцию, должен переключать поток. Иначе мы здесь явно раскрываем факт того, что репозиторий должен ее делать.

2023-07-24 06:48 UTC, Mama1emon commented on domain/txhistory/src/main/kotlin/com/tangem/domain/txhistory/usecase/GetTxHistoryItemsUseCase.kt
> +            .flowOn(dispatcherProvider.io)
Такой же вопрос, как и выше

2023-07-24 06:48 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/proxy/TxHistoryManagerImpl.kt
> +    private val appStateHolder: AppStateHolder,
Чтобы не класть реализацию в app можно в DomainStateHolder затащить зависимости необходимые

2023-07-24 07:27 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/proxy/TxHistoryManagerImpl.kt
> +        val walletManager = appStateHolder.walletState?.getWalletManager(blockchainNetwork)
Лучше не стоит, это тоже легаси уже. Пока, возможно, стоит закинуть в TODO, я добавлю логику хранения и создания `WalletManager`'ов вот тут https://tangem.atlassian.net/browse/AND-4050

2023-07-24 17:15 UTC, Yoggam1 commented on domain/txhistory/src/main/kotlin/com/tangem/domain/txhistory/usecase/GetTxHistoryItemsCountUseCase.kt
> +        return withContext(dispatchers.io) {
Точно. Оно и под капотом использует IO, тут явно лишнее

2023-07-24 17:15 UTC, Yoggam1 commented on domain/txhistory/src/main/kotlin/com/tangem/domain/txhistory/usecase/GetTxHistoryItemsUseCase.kt
> +            .flowOn(dispatcherProvider.io)
удалил

2023-07-24 17:17 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/proxy/TxHistoryManagerImpl.kt
> +    private val appStateHolder: AppStateHolder,
И так много подходов завелось. А некоторые новые подходы уже легаси. Поэтому лучше оставить так, к тому же принцып работы остальных менеджеров которые рядом, точно такие.

2023-07-24 17:18 UTC, Yoggam1 commented on data/txhistory/src/main/kotlin/com/tangem/data/txhistory/repository/MockTxHistoryRepository.kt
> +    ): Flow<List<TxHistoryItem>> {
добавил пагинацию

2023-07-24 17:18 UTC, Yoggam1 commented on data/txhistory/src/main/kotlin/com/tangem/data/txhistory/mock/MockTxHistoryItems.kt
> +object MockTxHistoryItems {
точно. добавил

2023-07-24 17:39 UTC, kozarezvlad approved these changes

2023-07-25 01:13 UTC, Mama1emon approved these changes

2023-07-25 05:52 UTC, merged