AND-4048 Added user tokens store
tangem/tangem-app-android-old pull request #1216
Opened 2023-07-24 09:51 UTC by iiiburnyiii

Этот стор будет использоваться в репозитории для получения токенов пользователя

2023-07-24 09:55 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/UserTokensResponse.kt
> +    @Json(name = "group") val group: GroupType,
давай везде в две строки сделаем, как в GroupType и SortType

2023-07-24 10:01 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/UserTokensResponse.kt
> +    @Json(name = "group") val group: GroupType,
Это надо во всех моделях тогда править, не в рамках этого МРа, предлагаю пока оставить так

2023-07-24 10:01 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
а почему nullable?

это ведь тянется до UserTokenStore

в чем смысл и бросать исключение, если что-то идет не так, и делать возможность вернуть null?

2023-07-24 10:03 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
Тут данные могут быть просто пустыми, если они ещё не сохранялись. Такое лучше в репозитории обработать

2023-07-24 10:04 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/UserTokensResponse.kt
> +    @Json(name = "group") val group: GroupType,
давай в пределах одного файла консистентно сделаем

не вижу проблем с тем, чтобы делать улучшения постепенно

2023-07-24 10:06 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
такой кейс тоже выкинет эксепшн, разве нет?

только на 47 строке, а не на 45

2023-07-24 10:07 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
и есть ли вообще для внешнего потребителя разница — данные пустые или файл не создан?

2023-07-24 10:32 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
плюс в данном кейсе (если ошибка вылезает при парсинге, в 47 строке) ты маскируешь ошибку парсинга в unableToReadFile, которая означает невозможность прочесть файл (а не распарсить его содержимое)

2023-07-24 11:40 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/UserTokensResponse.kt
> +    @Json(name = "group") val group: GroupType,
Если поправить только тут, то в разных моделях будут разные стили, это не круто. По хорошему лучше всего просто добавить правило в детект для этого, но это точно в рамках этого МРа

2023-07-24 12:02 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
> такой кейс тоже выкинет эксепшн, разве нет?

Нет, если в адаптер передали null, то он и отдаст null

> и есть ли вообще для внешнего потребителя разница — данные пустые или файл не создан?

Это просто обертка для хранилища, логика для определения, что делать если данные не были сохранены должна быть в репозитории

> плюс в данном кейсе (если ошибка вылезает при парсинге, в 47 строке) ты маскируешь ошибку парсинга в UnableToReadFile, которая означает невозможность прочесть файл (а не распарсить его содержимое)

Нет разницы почему файл не прочитался, из-за парсера или другой ошибки, и не думаю, что она появится

2023-07-24 13:50 UTC, Yoggam1 commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/UserTokensResponse.kt
> +    @Json(name = "group") val group: GroupType,
Поддерживаю идею правила для детекта. А то такое, вручную проверять не очень удобно.

2023-07-24 13:56 UTC, Yoggam1 requested changes

2023-07-24 13:56 UTC, Yoggam1 commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    fun get(key: String): Flow<Data> {
Почему единаразовое чтение идет через Flow а не suspend функция? Нужно либо нейминг подправить либо изменить возвращаемый тип.

По хорошему я бы добавил еще одну функцию, которая будет читать только по ключу и возвращать либо данные, либо null

2023-07-24 13:58 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    fun get(key: String): Flow<Data> {
Есть метод `get` - возвращяет `Flow` и там ниже есть метод `getSync` - просто возвращает данные, либо null

2023-07-24 13:59 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/UserTokensResponse.kt
> +    @Json(name = "group") val group: GroupType,
не, давай хотя бы в пределах одного файла будем одного стиля придерживаться

сейчас же у нас 2 стиля на 1 файл

2023-07-24 14:00 UTC, Yoggam1 approved these changes

2023-07-24 14:06 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/UserTokensResponse.kt
> +    @Json(name = "group") val group: GroupType,
Это детект уже поправил, так как это enum)

2023-07-24 14:13 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
> Нет, если в адаптер передали null, то он и отдаст null

где именно в адаптер передали null? ты про 47 строку? если да, то в текущей реализации у нас существует только `FileDataStore<UserTokensResponse>`, где `UserTokensResponse` not nullable, 
в качестве меры предосторожности можно тогда сделать `internal class FileDataStore<Data: Any>` вместо `internal class FileDataStore<Data>`, чтобы при попытке параметризовать стор нулабельным (`FileDataStore<UserTokensResponse?>`) мы получали бы ошибку компиляции

 
> Нет разницы почему файл не прочитался, из-за парсера или другой ошибки, и не думаю, что она появится

раз нет разницы, зачем делать и nullable, и эксепшн?..

к тому же флоу (в методе `get()`) оперирует (и это правильно) только not-nullable данными, а тот же по смыслу метод, только синхронный, может и nullable отдать — несогласованность получается

2023-07-24 14:40 UTC, Mama1emon approved these changes

2023-07-24 14:40 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/di/MoshiModule.kt
> +            .add(KotlinJsonAdapterFactory())
🤔

2023-07-24 15:08 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/di/MoshiModule.kt
> +            .add(KotlinJsonAdapterFactory())
На моей памяти этот адаптер должен быть внизу списка, были баги из-за этого, но могу ошибаться

2023-07-24 15:15 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
Про ограничение скоупа дженерика ты прав, в следующем МРе добавлю. `null` в адаптер может попасть, если такого файла нет, метод `store` не должен принимать `null`.

> раз нет разницы, зачем делать и nullable, и эксепшн?..

Как уже писал `null` значит, что нет сохраненных данных, это не ошибка как таковая, как мне кажется здесь он не должен обрабатываться.

> к тому же флоу (в методе get()) оперирует (и это правильно) только not-nullable данными, а тот же по смыслу метод, только синхронный, может и nullable отдать — несогласованность получается

`Flow` тоже может быть пустым

2023-07-24 15:24 UTC, merged

2023-07-24 15:46 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
> Flow тоже может быть пустым

Flow может быть пустым, но Flow не может возвращать nullable, почему тогда логика другая?
т.е. для флоу мы сейчас игнорируем null, для синхронного метода не игнорируем, зачем так? 

> Как уже писал null значит, что нет сохраненных данных, это не ошибка как таковая, как мне кажется здесь он не должен обрабатываться.

какая разница для внешнего наблюдателя — нет ли данных, или есть, но сломанные, и их все равно не вытащить? кмк ты переусложняешь


> null в адаптер может попасть, если такого файла нет, метод store не должен принимать null.

если такого файла нет, мы получим выброшенное исключение при попытке открыть несуществующий файл, а не json = null
то есть я все еще не вижу вариант, при котором у нас из метода может вернуться действительно null

2023-07-24 15:48 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
ну и сам json у нас не может быть nullable, это же в наших контрактах `FileReader.readFile()` указано

2023-07-24 16:07 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
`null` это более интуитивный способ понять, что хранилище пустое, для `Flow` можно сделать проверку `flow.onEmpty { ... }`. Я вижу переусложнение в твоем решении, так как пользователю хранилища придется ловить ошибку, что-бы понять, что данных просто нет, вместо обычной проверки на `null`

2023-07-24 16:46 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
так в твоем случае пользователь помимо отлова исключения должен будет еще и на null проверять, это ли не переусложнение?
а для клиента ведь нет разницы — хранилище пустое или поломанное

и приведи плиз пример, когда у нас этот метод вообще null вернет, а не эксепшн кинет

2023-07-24 17:24 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
`null` будет, только если нет файла с таким именем, т.е. данные не сохранялись до этого. 
В данном случае ошибка означает, что-то фатальное, для чего понадобиться действие пользователя, а `null` просто отсутсвие данных. Так это получается более явно и разрабу не нужно лезть в реализацию, что-бы узнать, что этот стор может не вернуть данные и кинуть ошибку

2023-07-24 17:52 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
почему `null` будет? попытка читать из несуществующего файла — это выброс `FileNotFoundException`

2023-07-24 18:01 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
ну и даже если в детали реализации не лезть — `json` у нас not-nullable в любом случае, 
`adapter.fromJson(json)` если и вернет null, то не по причине файла с отсутствующим именем, а по причине поломанного жсона

я бы все это делал проще и обходился возвратом Data и парой общих ошибок типа "не могу прочесть", и "не могу записать"

причина нам сейчас не важна (да и вряд ли пригодится в будущем), если пригодится, то легко будет расширить, дописав еще пару-тройку конерктизирующих ошибок

я правда упорно не понимаю, почему ты топишь за null, он здесь вносит немало сумятицы
меньшее количество сущностей даст нам более четкую картину без ущерба логике

2023-07-25 06:13 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +    private fun getInternal(fileName: String): Data? {
Про `FileNotFoundException` ты прав, не досмотрел, поправлю в следующем МРе. Но по поводу `null` не отступлю, мне кажется так интуитивнее) Просто потому-что так работают все хранилища, которые я знаю (SharedPrefrences, DataStore, Room, etc.)
Например рассмотрим кейс с токенами, если файл сломан и выкидывается ошибка, то репозиторий её не ловит, так как он ничего не может с этим сделать, нужно сказать об этом пользователю. Но если приходит `null`, то просто записывается файл с дефолтными токенами