AND-4048 Added factories for domain tokens
tangem/tangem-app-android-old pull request #1225
Opened 2023-07-25 07:08 UTC by iiiburnyiii

2023-07-25 07:25 UTC, Yoggam1 requested changes

2023-07-25 07:25 UTC, Yoggam1 commented on data/tokens/src/main/AndroidManifest.xml
> +<manifest package="com.tangem.data.tokens" />
```
android {
    namespace = "com.tangem.data.tokens"
}
```

в build.gradle.kts

2023-07-25 07:28 UTC, Mama1emon requested changes

2023-07-25 07:28 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            .onEmpty { emit(Unit) }
Поясни, пожалуйста, а зачем нам эммитить Unit?

2023-07-25 07:28 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            .onEmpty { emit(Unit) }
И сам факт того, что мы храним `Unit`. Зачем это нужно?

2023-07-25 07:28 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            val json = try {
Лучше использовать функцию `.use()` (`try-resources`) для гарантии, что поток закроется точно

2023-07-25 07:28 UTC, Mama1emon commented on data/tokens/src/main/AndroidManifest.xml
> +<manifest package="com.tangem.data.tokens" />
Лучше `namespace` для новых андройд модулей объявлять в `build.gradle`

2023-07-25 07:30 UTC, Yoggam1 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/utils/TokensOperations.kt
> +    val extension = "png"
Можем вынести в константы?

2023-07-25 08:05 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            .onEmpty { emit(Unit) }
>И сам факт того, что мы храним Unit. Зачем это нужно?

Это триггер записи в стор, в него эммититься `Unit` при записи, в методе `store()`. А в методе `get()` все эммиты в него маппаться в получение данных из стора.

>Поясни, пожалуйста, а зачем нам эммитить Unit?

Если кто-то вызвал `get`, но триггер пустой, так как не было записей в стор, то данные все равно нужно отдать

2023-07-25 08:28 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            val json = try {
Если я тебя правильно понял, то это стоит в file reader править. Можешь код приложить?

2023-07-25 08:54 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            val json = try {
Поправил в `AndroidFileReader`

2023-07-25 12:57 UTC, kozarezvlad approved these changes, later dismissed

2023-07-26 01:47 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            .onEmpty { emit(Unit) }
Что думаешь насчет того, чтобы добавить `typealias` для типа `Unit`. На мой взгляд, если там будет написано, что-то типа `TriggerAction`, то код станет более читаемый и не будут возникать лишние вопросы

2023-07-26 02:09 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/files/AndroidFileReader.kt
> +            }
Дело вкуса, но я знаю, что ты тоже любитель)
```suggestion
            stream.bufferedReader().use(BufferedReader::readText)
```

2023-07-26 02:09 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/files/AndroidFileReader.kt
> +            }
На твое усмотрение)

2023-07-26 02:09 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            val json = try {
Спасибо, что проверил реализацию и доработал. Безопасность - это важно!)

2023-07-26 02:09 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            } catch (e: FileNotFoundException) {
Кмк, лучше отлавливать `Exception`, так как по сути нам нет разницы, какая ошибка произошла. Так точно мы гарантируем, что, если вылетит что-то другое, у нас ничего не крашнет, а также не раскрываем детали реализации (мы неявно знаем, что такой эксепшен функция может выкидывать)

2023-07-26 04:59 UTC, Yoggam1 approved these changes, later dismissed

2023-07-26 05:01 UTC, Yoggam1 commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            } catch (e: FileNotFoundException) {
чуть ниже на втором кетче отлавливается же

2023-07-26 06:41 UTC, roman-pv commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/utils/ResponseTokensFactory.kt
> +        var blockchain = requireNotNull(Blockchain.fromNetworkId(token.networkId)) {
Тут точно будет ок, если кидать exception, если не найден блокчейн?

2023-07-26 06:41 UTC, roman-pv approved these changes, later dismissed

2023-07-26 07:17 UTC, iiiburnyiii commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/utils/ResponseTokensFactory.kt
> +        var blockchain = requireNotNull(Blockchain.fromNetworkId(token.networkId)) {
Да, ты прав лучше не крашить прилу из-за одного блокчейна, поправлю тут https://github.com/tangem/tangem-app-android/pull/1227

2023-07-26 07:18 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +            .onEmpty { emit(Unit) }
Попробую поправить тут https://github.com/tangem/tangem-app-android/pull/1227

2023-07-26 07:31 UTC, Mama1emon submitted a review, later dismissed

2023-07-26 08:19 UTC, kozarezvlad approved these changes

2023-07-26 08:23 UTC, roman-pv approved these changes

2023-07-26 08:25 UTC, merged