AND-4105 Added store for wallet managers
tangem/tangem-app-android-old pull request #1237
Opened 2023-07-26 19:45 UTC by iiiburnyiii

2023-07-27 08:09 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletStores/repository/implementation/DefaultWalletAmountsRepository.kt
> +                    .plusOrReplace(walletManager) {
а мы set никак не можем заюзать для этих целей?

2023-07-27 08:52 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/walletStores/repository/implementation/DefaultWalletAmountsRepository.kt
> +                    .plusOrReplace(walletManager) {
Ты про метод? Если да, то мы не знаем есть ли этот элемент в списке или нет. Если нет, то не понял)

2023-07-27 09:32 UTC, kozarezvlad commented on core/datasource/src/main/java/com/tangem/datasource/local/walletmanager/RuntimeWalletManagersStore.kt
> +    private val store = RuntimeDataStore(
А как это мокнуть при тестировании RuntimeWalletManagersStore?

2023-07-27 09:32 UTC, kozarezvlad commented on core/datasource/src/main/java/com/tangem/datasource/local/walletmanager/RuntimeWalletManagersStore.kt
> +internal class RuntimeWalletManagersStore : WalletManagersStore {
RuntimeWalletManagersStore будет отличаться от не Runtime только тем, что работа идет через RuntimeDataStore? В таком случае может реализацию разделить на уровне интерфейса DataStore?
Например WalletManagersStore умеет сохранять воллеты, сохраняет с помощью DataStore, а дальше уже куда сохранится зависит от реализации переданного стора.
А то сейчас получается как будто разделение ради разделения interface/impl посколько возможности которые открываются не использованы

2023-07-27 11:30 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletStores/repository/implementation/DefaultWalletAmountsRepository.kt
> +                    .plusOrReplace(walletManager) {
нене, я про коллекцию Set

ведь одна из ее фишек — это plusOrReplace из коробки

2023-07-27 12:20 UTC, kozarezvlad submitted a review, later dismissed

2023-07-27 12:29 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/walletStores/repository/implementation/DefaultWalletAmountsRepository.kt
> +                    .plusOrReplace(walletManager) {
Так он же не заменяет элемент, а просто не добавляет его, если он уже есть в множестве. Или там какой-то другой метод кроме `plus` и `add` есть?

2023-07-27 13:15 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletStores/repository/implementation/DefaultWalletAmountsRepository.kt
> +                    .plusOrReplace(walletManager) {
а, там условие..

кмк все равно как-то проще можно написать, без цепочки вызовов на три метода

к примеру
```
fun <T> Collection<T>.addOrReplace(element: T, predicate: (T) -> Boolean): Collection<T> {
            val existingElement = find(predicate)
            return if (existingElement != null) {
                map { if (predicate(it)) element else it }
            } else {
                plus(element)
            }
        }
```

2023-07-27 15:35 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/walletStores/repository/implementation/DefaultWalletAmountsRepository.kt
> +                    .plusOrReplace(walletManager) {
Так 2 прохода по списку получается, тот что я написал за один проход делает, в худшем случае

2023-07-28 02:34 UTC, Mama1emon requested changes

2023-07-28 02:34 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +        TODO("Implement if needed")
Будет крешить всегда, когда вызываем?

2023-07-28 06:50 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/local/datastore/FileDataStore.kt
> +        TODO("Implement if needed")
Точно, забыл закоментить

2023-07-28 08:44 UTC, Mama1emon approved these changes

2023-07-28 14:01 UTC, kozarezvlad approved these changes

2023-07-28 14:08 UTC, merged