AND-3603: log hosts switching in BlockchainSDK
tangem/tangem-app-android-old pull request #1239
Opened 2023-07-27 06:58 UTC by roman-pv

2023-07-27 07:09 UTC, iiiburnyiii submitted a review, later dismissed

2023-07-27 09:34 UTC, kozarezvlad requested changes

2023-07-27 09:34 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/common/analytics/handlers/BlockchainExceptionHandler.kt
> +        Analytics.send(
Предлагаю сразу использовать тут AnalyticsHandler который есть в DI графе.

2023-07-27 14:35 UTC, Yoggam1 approved these changes, later dismissed

2023-07-28 02:26 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/common/analytics/events/BlockchainException.kt
> +class BlockchainException(
Так как это эвент, то предлагаю явно добавить это в названии. Иначе в коде или при поиске всегда будет казаться, что это `Exception`, что сбивает с толку

2023-07-28 06:55 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/common/analytics/events/BlockchainException.kt
> +class BlockchainException(
Если смотреть по нэймингу окрестых классов, то тогда правильнее будет `BlockchainExceptionOccured` или что-то в таком духе. Что думаешь?

2023-07-28 08:37 UTC, kozarezvlad approved these changes, later dismissed

2023-07-28 08:37 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/common/analytics/events/BlockchainException.kt
> +class BlockchainException(
+ за event, это сразу дает понимание что за класс

2023-07-28 10:30 UTC, iiiburnyiii approved these changes

2023-07-28 10:41 UTC, kozarezvlad approved these changes

2023-07-28 10:41 UTC, merged