AND-4023 Updated referral models.
tangem/tangem-app-android-old pull request #1240
Opened 2023-07-27 11:04 UTC by Sateetas

2023-07-27 11:51 UTC, roman-pv commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/viewmodels/ReferralViewModel.kt
> +                                showContent(it)
вложенный it

2023-07-27 12:32 UTC, kozarezvlad commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/ReferralResponse.kt
> +            @Json(name = "currency") val currency: String,
Уточнял точно ли не может быть null? я когда делал стреляло несколько раз тут в рефералке

2023-07-27 12:36 UTC, kozarezvlad commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/AgreementBottomSheetContent.kt
> +    val isInPreviewMode = LocalInspectionMode.current
Предлагаю никак не зашивать в прод коде инфо о превью, не совсем понял зачем тут это. Типа не работала превьюшка?

2023-08-01 08:46 UTC, Mama1emon submitted a review, later dismissed

2023-08-07 08:48 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/ReferralResponse.kt
> +            @Json(name = "currency") val currency: String,
чекнем
в идеале я бы все поля dto nullable делал

2023-08-07 08:53 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/AgreementBottomSheetContent.kt
> +    val isInPreviewMode = LocalInspectionMode.current
ага, превью крешится, если внутрь вебвью лезем

2023-08-07 10:03 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/viewmodels/ReferralViewModel.kt
> +                                showContent(it)
поправил

2023-08-18 11:26 UTC, roman-pv submitted a review, later dismissed

2023-08-31 15:00 UTC, roman-pv approved these changes, later dismissed

2023-09-01 07:06 UTC, kozarezvlad approved these changes, later dismissed

2023-09-01 07:31 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/ReferralResponse.kt
> +            @Json(name = "currency") val currency: String,
Если все поля делать nullable, то тогда придется при конвертации дто делать кучу проверок. Контракт рест ручки должен быть точен и однозначен.

2023-09-01 07:42 UTC, Mama1emon requested changes

2023-09-01 07:42 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/AwardItems.kt
> +                Row {
Лишний `Row`

2023-09-01 07:42 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/AwardItems.kt
> +        Column {
Лишний `Column`?

2023-09-01 07:42 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> -        verticalArrangement = Arrangement.spacedBy(TangemTheme.dimens.spacing16),
Почему `verticalArrangement` заменен на `Spacing`?

2023-09-01 07:42 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +@Suppress("LongMethod", "MagicNumber")
Предлагаю сразу разбить функцию, чтобы детект не ругался

2023-09-01 07:42 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +
Лишний пробел

2023-09-01 14:04 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/ReferralResponse.kt
> +            @Json(name = "currency") val currency: String,
ага, я за такой подход

бонусом можно человекочитаемые ошибки выводить при конвертации

2023-09-01 14:05 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/ReferralResponse.kt
> +            @Json(name = "currency") val currency: String,
бойлерплейта, конечно, прибавится, но с другой стороны в конвертере вся логика будет досконально видна

2023-09-01 14:24 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/AwardItems.kt
> +        Column {
ага

2023-09-01 14:24 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/AwardItems.kt
> +                Row {
ага

2023-09-01 14:26 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> -        verticalArrangement = Arrangement.spacedBy(TangemTheme.dimens.spacing16),
потому что CountersAndAwards у нас композитный, состоит из кучи айтемов

если вернуть обратно, verticalArrangement будет распространяться и на них, и выйдет вот так

![image](https://github.com/tangem/tangem-app-android/assets/13484957/93686bfc-214d-4f50-86f5-2311694411f8)

2023-09-01 14:30 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> -        verticalArrangement = Arrangement.spacedBy(TangemTheme.dimens.spacing16),
я пока не сильно крутой спец в компоузе, это моя первая фича в прод на нем

если подскажешь, как можно обойти это, (если возможно, мб есть какой-то verticalArrangement, который распростаняется только на айтемы той же компоуз-функции, но не прокидывается вглубь) будет здорово

2023-09-01 14:52 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +@Suppress("LongMethod", "MagicNumber")
окей

2023-09-02 02:07 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/ReferralResponse.kt
> +            @Json(name = "currency") val currency: String,
Moshi - сериализатор от народа. Выводит человекочитаемые ошибки.
Такой подход меня смущает тем, что придется самому всегда писать проверку на каждое поле. Хотя контракт реста может предполагать, что все поля приходят. Если что то Moshi обработает этот ошибочный кейс

2023-09-02 02:07 UTC, Mama1emon commented on features/referral/data/src/main/java/com/tangem/feature/referral/converters/ReferralConverter.kt
> +private class ExpectedAwardsConverter : Converter<ReferralResponse.ExpectedAwards, ExpectedAwards> {
Не получится переиспользовать мой конвертер или форматтер?

2023-09-02 02:07 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> -        verticalArrangement = Arrangement.spacedBy(TangemTheme.dimens.spacing16),
Аа, понял проблему. `CounterAndAwards` должен быть обернут в свой `Column`

2023-09-02 02:07 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +    initialItems.forEachIndexed { index, expectedAward ->
Сколько таких элементов будет?
Если не ограничено их кол-во, то надо оптимизировать

2023-09-02 02:07 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +    if (expectedAwards.expectedAwards.size > elementsCountToShowInLessMode) {
AnimatedVisibility?

2023-09-04 19:07 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/ReferralResponse.kt
> +            @Json(name = "currency") val currency: String,
ну, тут depends on

да, нужно учитывать как "топорность" десериализатора, так и возможную гибкость

к примеру, у нас есть класс с енумом из 3 значений и тремя nullable-полями, в зависимости от значения enum ненулевым будет первое, второе или третье, ну и в какой-нить sealed class для красоты мапим

в таких случаях автоматическая сериализация не справится

2023-09-04 19:17 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> -        verticalArrangement = Arrangement.spacedBy(TangemTheme.dimens.spacing16),
ага, спасибо!

2023-09-04 19:19 UTC, Sateetas commented on features/referral/data/src/main/java/com/tangem/feature/referral/converters/ReferralConverter.kt
> +private class ExpectedAwardsConverter : Converter<ReferralResponse.ExpectedAwards, ExpectedAwards> {
не понял вопрос, какой именно конвертер или форматтер?

2023-09-04 19:23 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +    initialItems.forEachIndexed { index, expectedAward ->
по количеству upcoming payments, я не думаю что на практике будет длиннее даже половины экрана

2023-09-04 19:38 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +    if (expectedAwards.expectedAwards.size > elementsCountToShowInLessMode) {
не нужно, кнопка Less/More должна всегда показываться, если имеем  больше трех expected awards

2023-09-05 06:37 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/models/ReferralResponse.kt
> +            @Json(name = "currency") val currency: String,
Для таких кейсов пишется кастомный моши адаптер

2023-09-05 06:42 UTC, Mama1emon commented on features/referral/data/src/main/java/com/tangem/feature/referral/converters/ReferralConverter.kt
> +private class ExpectedAwardsConverter : Converter<ReferralResponse.ExpectedAwards, ExpectedAwards> {
Если я правильно понял, то `dateFormatter` был позаимствован с конвертера, который я писал для истории транзакций

2023-09-05 06:42 UTC, Mama1emon commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +
Я имею ввиду, что хорошо бы от него избавиться

2023-09-06 11:24 UTC, Sateetas commented on features/referral/data/src/main/java/com/tangem/feature/referral/converters/ReferralConverter.kt
> +private class ExpectedAwardsConverter : Converter<ReferralResponse.ExpectedAwards, ExpectedAwards> {
ага, решил пока что просто взять копипастой, вынос этого в свой модуль — отдельная задача

2023-09-07 08:47 UTC, Mama1emon approved these changes, later dismissed

2023-09-07 09:49 UTC, kozarezvlad approved these changes, later dismissed

2023-09-07 09:52 UTC, Sateetas commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ui/ParticipateBottomBlock.kt
> +
ага, убрал

2023-09-07 09:55 UTC, kozarezvlad approved these changes

2023-09-07 09:56 UTC, Mama1emon approved these changes

2023-09-07 10:04 UTC, merged