AND-4082 Updated use case for apply token list sorting
tangem/tangem-app-android-old pull request #1241
Opened 2023-07-28 07:20 UTC by iiiburnyiii

2023-07-28 14:24 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/ApplyTokenListSortingUseCase.kt
> +        unsortedTokens.forEachIndexed { index, token ->
немного тяжело читается логика — сначала создаем из сета лист, потом из листа удаляем элементы, потом добавляем..

мб сделать в 49 строке `val sortedTokens = mutableListOf()` и в цикле наполнять его?

2023-07-28 17:22 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/ApplyTokenListSortingUseCase.kt
> +        unsortedTokens.forEachIndexed { index, token ->
Поправил, вроде стало чуть попроще

2023-07-31 08:45 UTC, Mama1emon requested changes

2023-07-31 08:45 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/ApplyTokenListSortingUseCase.kt
> +        return withContext(dispatchers.io) {
А почему юзкейс решает, на каком потоке должен работать репозиторий?

2023-07-31 11:54 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/ApplyTokenListSortingUseCase.kt
> +        return withContext(dispatchers.io) {
Уже обсуждали это в другом МРе с use case'ом, я говрил в 90‰ это IO и решили оставить так. Все use case'ы, что я написал, переопределяют поток на IO для работы с репозиторем. Го лучше вынсем это на общее обсуждение и я поправлю (или нет) сразу всё

2023-07-31 13:52 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/ApplyTokenListSortingUseCase.kt
> +        return withContext(dispatchers.io) {
Не помню, на чем мы тогда остановились. Но по сути ты за репозиторий определяешь, на чем он основывается, то бишь раскрываешь его логику. А это неправильно

2023-07-31 14:11 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/ApplyTokenListSortingUseCase.kt
> +        return withContext(dispatchers.io) {
Согласен, поправил

2023-07-31 14:12 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/ApplyTokenListSortingUseCase.kt
> +        return withContext(dispatchers.io) {
Если вызов IO потому что репозиторий идет в сеть - это не ок, потому что мы в юзкейсе делаем привязку на репозиторий, если вызов io потому что сам юз кейс делает сложные вычесления - это ок.
https://developer.android.com/kotlin/coroutines/coroutines-best-practices#create-coroutines-data-layer
Предлагаю придерживаться описанных подходов.

2023-07-31 14:15 UTC, Mama1emon approved these changes

2023-07-31 16:05 UTC, Sateetas approved these changes

2023-07-31 18:01 UTC, merged