AND-4082 Updated wallet screen logic for opening organize tokens screen
tangem/tangem-app-android-old pull request #1242
Opened 2023-07-28 07:31 UTC by iiiburnyiii

2023-07-28 08:35 UTC, kozarezvlad submitted a review, later dismissed

2023-07-28 11:48 UTC, roman-pv submitted a review, later dismissed

2023-07-31 08:40 UTC, Mama1emon requested changes

2023-07-31 08:40 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/router/DefaultWalletRouter.kt
> +                val userWalletIdValue = requireNotNull(it.arguments?.getString(WalletRoute.userWalletIdKey)) {
Вообще по хорошему аргументы надо объявлять внутри `composable` и получать сразу во вью моделе с помощью SaveStateHandle

2023-07-31 09:28 UTC, kozarezvlad approved these changes, later dismissed

2023-07-31 12:02 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/router/DefaultWalletRouter.kt
> +                val userWalletIdValue = requireNotNull(it.arguments?.getString(WalletRoute.userWalletIdKey)) {
Так он же сохраняет данные только при `onStop` у Activity
![Uploading изображение.png…]()

2023-07-31 12:17 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/router/DefaultWalletRouter.kt
> +                val userWalletIdValue = requireNotNull(it.arguments?.getString(WalletRoute.userWalletIdKey)) {
Данные будут записаны сразу как только ты их туда положишь.
Не совсем понял смысл отрывка из доки. Мб это касается только вью модели, привязанной к активити?

2023-08-01 06:40 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/router/WalletRoute.kt
> +internal sealed class WalletRoute(val route: String) {
Хорошо бы в некст МР добавить параметр в доку для полноты доки

2023-08-01 08:46 UTC, Mama1emon submitted a review, later dismissed

2023-08-02 13:51 UTC, kozarezvlad approved these changes

2023-08-02 15:02 UTC, Mama1emon approved these changes

2023-08-02 16:14 UTC, merged