AND-4082 Implemented holder for the organize tokens state
tangem/tangem-app-android-old pull request #1243
Opened 2023-07-28 07:54 UTC by iiiburnyiii

2023-07-28 07:55 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +internal data class OrganizeTokensState(
Этот файл можно не смотреть, он раньше назывался `OrganizeTokensStateHolder`. Git почему-то посчитал, что это новый файл. Разве что можно обратить внимание на кофиги, там добавились новые поля

2023-07-28 07:56 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +internal class OrganizeTokensStateHolder(
Начинать лучше отсюда, здесь используются все новые файлы

2023-07-31 08:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/WalletPreviewData.kt
> +        dndConfig = OrganizeTokensState.DragAndDropConfig(
Dungeon and Dragons? :D

2023-07-31 08:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +        override val items: PersistentList<DraggableItem>,
Почему именно `PersistentList`, а не `ImmutableList`, как и везде?

2023-07-31 08:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +internal data class OrganizeTokensState(
А чем отличается данный класс от state holder?

2023-07-31 08:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +internal class OrganizeTokensStateHolder(
Совершенно не понял идею твоего разделения. Выглядит как что-то совершенно новое, что лучше обсудить с командой

2023-07-31 12:05 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +        override val items: PersistentList<DraggableItem>,
`PersistentList` переопределяет мутабельные методы, но в отличии от обычного мутабельного списка, возвращет новую копию себя, а не изменяется, тут это нужно для DnD

2023-07-31 12:07 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +internal data class OrganizeTokensState(
Это стейт экрана, не совсем понимаю почему мы решили называть подобные классы state holder'ами.

2023-07-31 12:10 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +internal class OrganizeTokensStateHolder(
На одном из созвонов решили wallet экран сделать на колбеках, а organize tokens на state flow
В данном случае `StateHolder` берет на себя роль обновления и хранения состояния экрана, через конвертеры

2023-07-31 12:15 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +internal data class OrganizeTokensState(
По моей памяти это было согласовано при формировании архитектуры зимой. Где-то в гугловских доках было это замечено и заиспользовано.
Думаю @kozarezvlad точнее скажет

2023-07-31 13:56 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +internal data class OrganizeTokensState(
Насчет state holder не помню как повелось, но holder подразумевает больше логики чем просто хранение стейта, поэтому просто state тут самое то

2023-08-01 13:14 UTC, kozarezvlad submitted a review, later dismissed

2023-08-03 06:32 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +    data class HeaderConfig(
а напомните, что именно ломается в компоузе, если data-класс не использовать? как-то поднимали этот вопрос

я всё про функции как проперти внутри дата-класса

2023-08-03 06:48 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    @Volatile
не обойтись без volatile?

он все же медленнее работает

2023-08-03 06:49 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/common/DraggableItemOperations.kt
> +internal fun DraggableItem.roundingMode(mode: RoundingMode): DraggableItem = when (this) {
зачем экстеншн?
 
и по неймингу — я бы назвал tryApplyRoundingMode, или withRoundingMode

2023-08-03 06:50 UTC, Sateetas requested changes

2023-08-03 06:50 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/common/DraggableItemOperations.kt
> +internal fun DraggableItem.showShadow(show: Boolean): DraggableItem = when (this) {
здесь аналогично

2023-08-03 09:44 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    @Volatile
Не понятно что он решает тут.
Потоки он не синканет и если есть опасение что 2+ потока будут писать, то он все равно крашнет и лучше заюзать потокобезопасную коллекцию

2023-08-07 07:33 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensState.kt
> +    data class HeaderConfig(
data class stable по умолчанию, если его не использовать, то сломается рекомпозиция. 
Можно использовать и обычный класс, но тогда его нужно будет вречную помечать как `@Immutable`. Там с лямбдами тоже есть траблы, но compose считает их stable. В дальнейшем хочу подумать, что можно вместо них исползовать, но пока сошлись на них

2023-08-07 07:34 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/common/DraggableItemOperations.kt
> +internal fun DraggableItem.roundingMode(mode: RoundingMode): DraggableItem = when (this) {
Тут есть строгий тип, а не какая-нибудь стринга, так что не вижу проблем с расширением, это просто удобнее. 
Нейминг поправил

2023-08-07 07:43 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/common/DraggableItemOperations.kt
> +internal fun DraggableItem.roundingMode(mode: RoundingMode): DraggableItem = when (this) {
не понял про строгий тип/стринга, можешь пояснить?

все еще не понял зачем экстеншн нужен

2023-08-07 07:52 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/common/DraggableItemOperations.kt
> +internal fun DraggableItem.roundingMode(mode: RoundingMode): DraggableItem = when (this) {
Если делать расширение от простого типа, например стринги, то тогда становиться не очевидным, что функция расширяет. Расширять лучше менее абстрактные типы
Расширение здесь для того, что-бы не нагружать саму модельку `DraggableItem` логикой обновления, так как расширение можно вынести в другой файл

2023-08-07 14:58 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/common/DraggableItemOperations.kt
> +internal fun DraggableItem.roundingMode(mode: RoundingMode): DraggableItem = when (this) {
а в чем проблема нагрузить `DraggableItem` логикой обновления?
я могу ничего не знать про экстеншн-методы и написать свои, например
неочевидно же

я бы или занес в DraggableItem, или сделал бы отдельной сущностью вроде DraggableItemModifier

2023-08-09 17:54 UTC, Sateetas approved these changes

2023-08-09 17:58 UTC, kozarezvlad approved these changes

2023-08-09 17:58 UTC, merged