AND-3969 new error when twins incompatible
tangem/tangem-app-android-old pull request #1275
Opened 2023-08-07 11:33 UTC by kozarezvlad

2023-08-07 11:48 UTC, Mama1emon requested changes

2023-08-07 11:48 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/twins/IncompatibleTwinCard.kt
> +object IncompatibleTwinCard : TangemError(code = 50005) {
Предлагаю сразу в доменный модуль кинуть

2023-08-07 11:48 UTC, Mama1emon commented on domain/legacy/src/main/java/com/tangem/domain/common/TwinsHelper.kt
> +        if (firstCardId.startsWith(firstCardSeries[1]) && secondCardId.startsWith(secondCardSeries[1])) {
Если я правильно понял, то мы гарантируем то, что в захордкоженном списке эти id будут всегда на одном и том же месте?

2023-08-07 11:55 UTC, iiiburnyiii approved these changes, later dismissed

2023-08-07 11:56 UTC, kozarezvlad commented on domain/legacy/src/main/java/com/tangem/domain/common/TwinsHelper.kt
> +        if (firstCardId.startsWith(firstCardSeries[1]) && secondCardId.startsWith(secondCardSeries[1])) {
Да, правильно

2023-08-07 11:56 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/twins/IncompatibleTwinCard.kt
> +object IncompatibleTwinCard : TangemError(code = 50005) {
В какой именно?

2023-08-07 11:58 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/twins/IncompatibleTwinCard.kt
> +object IncompatibleTwinCard : TangemError(code = 50005) {
Это не доменная ошибка, так как операции с SDK это слой данных для приложения, лучше пускай пока тут лежит

2023-08-08 14:18 UTC, roman-pv approved these changes

2023-08-09 07:39 UTC, Mama1emon approved these changes

2023-08-09 16:21 UTC, merged