AND-4098 Added data layer for tx history.
tangem/tangem-app-android-old pull request #1279
Opened 2023-08-08 04:13 UTC by Yoggam1

AND-4206 Moved implementation for tx history to WalletManagersFacade.

2023-08-08 05:02 UTC, Mama1emon requested changes

2023-08-08 05:02 UTC, Mama1emon commented on data/txhistory/src/main/kotlin/com/tangem/data/txhistory/repository/DefaultTxHistoryRepository.kt
> +                    loadPage = { page: Int, pageSize: Int ->
Мб логику загрузки инкапсулировать внутри `TxHistoryPagingSource`?

2023-08-08 05:02 UTC, Mama1emon commented on gradle/dependencies.toml
> +tangemBlockchainSdk = "0.0.1" # Keep it! - used for local builds
?

2023-08-08 05:48 UTC, iiiburnyiii requested changes

2023-08-08 05:48 UTC, iiiburnyiii commented on data/txhistory/src/main/kotlin/com/tangem/data/txhistory/repository/DefaultTxHistoryRepository.kt
> +        val userWallet = requireNotNull(walletsStateHolder.userWalletsListManager?.selectedUserWalletSync) {
Стоит закинуть метод `getSelectedUserWalletSyncOrNull()` в `UserWalletsStore`, а не использовать холдер напрямую

2023-08-08 06:00 UTC, iiiburnyiii commented on domain/legacy/src/main/java/com/tangem/domain/walletmanager/DefaultWalletManagersFacade.kt
> +        }
Лучше новый метод для получения кошелька создать, и юзать его здесь и в `update(...)`, логика получения кошелька и ошибка та же

2023-08-08 06:00 UTC, iiiburnyiii commented on domain/legacy/src/main/java/com/tangem/domain/walletmanager/utils/SdkTransactionHistoryItemConverter.kt
> +        amount = requireNotNull(value.amount.value) { "Amount value must not be null" },
Так легче будет ошибку потом найти
```suggestion
        amount = requireNotNull(value.amount.value) { "Transaction amount value must not be null" },
```

2023-08-08 06:00 UTC, iiiburnyiii commented on domain/legacy/src/main/java/com/tangem/domain/walletmanager/utils/SdkTransactionHistoryStateConverter.kt
> +        TransactionHistoryState.NotImplemented -> TxHistoryState.NotImplemented
nit: Кажется так покросивше
```suggestion
        is TransactionHistoryState.Success.Empty -> TxHistoryState.Success.Empty
        is TransactionHistoryState.Success.HasTransactions -> TxHistoryState.Success.HasTransactions(value.txCount)
        is TransactionHistoryState.Failed.FetchError -> TxHistoryState.Failed.FetchError(value.exception)
        is TransactionHistoryState.NotImplemented -> TxHistoryState.NotImplemented
```

2023-08-08 06:00 UTC, iiiburnyiii commented on libs/crypto/src/main/java/com/tangem/lib/crypto/models/ProxyPaginationWrapper.kt
> +data class ProxyPaginationWrapper<T>(
`Proxy` и `Wrapper` странно вместе смотряться. Мб что-то одно оставить?

2023-08-08 07:19 UTC, Yoggam1 commented on gradle/dependencies.toml
> +tangemBlockchainSdk = "0.0.1" # Keep it! - used for local builds
Временно. Ждал мерджа ПРа в блокчейн сдк

2023-08-09 03:59 UTC, Yoggam1 commented on data/txhistory/src/main/kotlin/com/tangem/data/txhistory/repository/DefaultTxHistoryRepository.kt
> +                    loadPage = { page: Int, pageSize: Int ->
Нужно будет прокидывать walletManagersFacade. А там кроме загрузки есть еще много чего. Поэтому вынес в лямбду

2023-08-09 05:21 UTC, Yoggam1 commented on domain/legacy/src/main/java/com/tangem/domain/walletmanager/DefaultWalletManagersFacade.kt
> +        }
Сделал

2023-08-09 05:21 UTC, Yoggam1 commented on data/txhistory/src/main/kotlin/com/tangem/data/txhistory/repository/DefaultTxHistoryRepository.kt
> +        val userWallet = requireNotNull(walletsStateHolder.userWalletsListManager?.selectedUserWalletSync) {
сделал

2023-08-09 05:21 UTC, Yoggam1 commented on libs/crypto/src/main/java/com/tangem/lib/crypto/models/ProxyPaginationWrapper.kt
> +data class ProxyPaginationWrapper<T>(
Перенес

2023-08-09 08:05 UTC, iiiburnyiii approved these changes

2023-08-09 08:08 UTC, Mama1emon approved these changes

2023-08-09 08:09 UTC, merged