AND-4209 Moved transactions composables to core module
tangem/tangem-app-android-old pull request #1284
Opened 2023-08-09 06:19 UTC by Yoggam1

2023-08-09 07:38 UTC, Mama1emon requested changes

2023-08-09 07:38 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/Modifiers.kt
> +fun Modifier.walletContentItemDecoration(currentIndex: Int, lastIndex: Int): Modifier = composed {
1) Лучше переименовать тогда, чтобы явно было понятно, что данный модифаер типо "упаковывает" итемы списка в формочку со скругленными краями
2) Предлагаю отдельный пакет для этого выделить, как это было раньше
3) Название файла ооочень универсальное, а тут узкоспециализированная штука

2023-08-09 07:38 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionList.kt
> -/**
Дока не понравилась?

2023-08-09 07:38 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryGroupTitle.kt
> +internal fun TxHistoryGroupTitle(config: TxHistoryState.TxHistoryItemState.GroupTitle, modifier: Modifier = Modifier) {
Для улучшения читаемости кода предлагаю импортнуть именно `TxHistoryItemState`

2023-08-09 07:38 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryState.kt
> -/**
?

2023-08-09 07:38 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryState.kt
> +sealed interface TxHistoryState {
Предлагаю вынести в отдельный пакет, а то теряется среди вьюшек

2023-08-09 07:38 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryTitle.kt
> +            androidx.compose.material3.Icon(
?

2023-08-09 07:38 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/wallet/WalletLockedContentState.kt
> +interface WalletLockedContentState
А зачем это вынесено?

2023-08-09 09:08 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/wallet/WalletLockedContentState.kt
> +interface WalletLockedContentState
Используется в стейте для транзакций

2023-08-10 10:22 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionList.kt
> -/**
Переводил копипастой, а не перемещением файлов. Поэтому какие-то комментарии может выпали.

2023-08-10 10:22 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryState.kt
> -/**
https://github.com/tangem/tangem-app-android/pull/1284#discussion_r1289910566

2023-08-10 10:30 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryTitle.kt
> +            androidx.compose.material3.Icon(
Исправил

2023-08-10 10:31 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryGroupTitle.kt
> +internal fun TxHistoryGroupTitle(config: TxHistoryState.TxHistoryItemState.GroupTitle, modifier: Modifier = Modifier) {
Исправил

2023-08-10 10:31 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/Modifiers.kt
> +fun Modifier.walletContentItemDecoration(currentIndex: Int, lastIndex: Int): Modifier = composed {
Сделал

2023-08-10 11:45 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryState.kt
> +sealed interface TxHistoryState {
Перенес

2023-08-10 11:57 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TransactionList.kt
> -/**
Тогда лучше переместить и доку тоже

2023-08-10 11:57 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryContentItem.kt
> +internal fun TxHistoryContentItem (state: TxHistoryState.TxHistoryItemState, modifier: Modifier = Modifier) {
Лишний пробел перед скобкой конструктора

2023-08-10 11:57 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryGroupTitle.kt
> -/**
Дока

2023-08-10 11:57 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryTitle.kt
> -/**
Дока

2023-08-10 11:57 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/wallet/WalletLockedContentState.kt
> +interface WalletLockedContentState
Вообще выносить такое не очень хорошо. Тем более это было sealed классом. Точно не получится обойтись без него?

2023-08-10 12:02 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/wallet/WalletLockedContentState.kt
> +interface WalletLockedContentState
`TxHistoryState.Loaded` наследуется от него. Поэтому никак не мог изменить его. Либо надо будет пересмотреть стейт wallet скрина и рефакторить его.

2023-08-10 12:03 UTC, iiiburnyiii commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryContentItem.kt
> +internal fun TxHistoryContentItem(state: TxHistoryState.TxHistoryItemState, modifier: Modifier = Modifier) {
Лучше так думаю
```suggestion
internal fun TxHistoryListItem(state: TxHistoryState.TxHistoryItemState, modifier: Modifier = Modifier) {
```

2023-08-10 12:09 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryGroupTitle.kt
> -/**
Добавил

2023-08-10 12:10 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/transactions/TxHistoryContentItem.kt
> +internal fun TxHistoryContentItem(state: TxHistoryState.TxHistoryItemState, modifier: Modifier = Modifier) {
Сделал

2023-08-10 12:16 UTC, Mama1emon approved these changes

2023-08-10 12:16 UTC, kozarezvlad approved these changes

2023-08-10 12:28 UTC, merged