AND-4237 Implemented domain logic for app currency
tangem/tangem-app-android-old pull request #1297
Opened 2023-08-10 19:20 UTC by iiiburnyiii

2023-08-11 05:55 UTC, gbixahue submitted a review, later dismissed

2023-08-11 07:28 UTC, kozarezvlad submitted a review, later dismissed

2023-08-11 07:53 UTC, Mama1emon requested changes

2023-08-11 07:53 UTC, Mama1emon commented on app/build.gradle.kts
> +    implementation(projects.domain.appCurrency)
Предлагаю отсортировать 🙏

2023-08-11 07:53 UTC, Mama1emon commented on app/build.gradle.kts
> +    implementation(projects.data.appCurrency)
Тоже обсуждали с Владом подобную тему. Кажется, что это относится к `settings`, который уже есть

2023-08-11 07:53 UTC, Mama1emon commented on data/appCurrency/build.gradle.kts
> +    /** Project - Domain */
Ты когда-то region предлагал для этого использовать)

2023-08-11 07:53 UTC, Mama1emon commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/GetSelectedAppCurrencyUseCase.kt
> +            .flowOn(dispatchers.io)
Вроде здесь нет тяжелой работы для переключения потока

2023-08-13 09:11 UTC, Sateetas commented on data/appCurrency/build.gradle.kts
> +    /** Project - Domain */
думаю, регион излишним тут будет

2023-08-13 09:12 UTC, Sateetas commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
зачем data class?

2023-08-13 09:15 UTC, Sateetas requested changes

2023-08-13 09:15 UTC, Sateetas commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
зачем data class?

2023-08-14 06:23 UTC, iiiburnyiii commented on data/appCurrency/build.gradle.kts
> +    /** Project - Domain */
Тут он лишний, да. Не много зависимостей

2023-08-14 06:24 UTC, iiiburnyiii commented on app/build.gradle.kts
> +    implementation(projects.domain.appCurrency)
А где здесь форточка?)

2023-08-14 06:26 UTC, iiiburnyiii commented on app/build.gradle.kts
> +    implementation(projects.data.appCurrency)
Его стоит использовать из репо, но лучше все таки новый написать. Это быстро сделать, а код сильно чище становится.

2023-08-14 06:28 UTC, iiiburnyiii commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
Давно ещё договаривались ошибки и намерения делать либо объектом, либо data классом. Так как стоит `equals` поддерживать, на всякий.

2023-08-14 06:32 UTC, iiiburnyiii commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/GetSelectedAppCurrencyUseCase.kt
> +            .flowOn(dispatchers.io)
Поправил

2023-08-14 07:00 UTC, Mama1emon commented on app/build.gradle.kts
> +    implementation(projects.data.appCurrency)
Не понял, что ты имеешь ввиду.
Мой коммент в том, что кажется создавать отдельный модуль для app currency очень жирно + она подходит под домейн с натройками приложения

2023-08-14 07:11 UTC, Sateetas commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
так `equals` же неверно отработает, т.к. мы не можем сравнивать исключения

2023-08-14 07:11 UTC, Sateetas commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
зачем маскировать ошибку?

2023-08-14 08:04 UTC, iiiburnyiii commented on app/build.gradle.kts
> +    implementation(projects.data.appCurrency)
Если бы мы просто хранили какие-то флаги, то мб в этом и был бы смысл, но та же логика для app currency подразумевает ещё и запрос на бек, респонз которого нужно маппить, хранить и кешировать. Плюс там свои логические ошибки.
Можно, конечно, создать один доменный модуль где будут use case'ы для манипуляции над настройками и кучка репозиториев. Но мне кажется, что лучше это все таки разбить на несколько небольших модулей - так это будет легче поддерживать.

2023-08-14 08:09 UTC, iiiburnyiii commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
> зачем маскировать ошибку?

Для типизации ошибок use case'а. Сюда будут попадать все ошибки из дата слоя, с которыми доменный слой не знает что делать. 

> так equals же неверно отработает, т.к. мы не можем сравнивать исключения

В данном случае да, но смысла отходить от использование data class'а не вижу, так как его использование не сильно влияет на compile time, и есть плюсы в виде уже нормально переопределенных `equals` и `toString`

2023-08-14 08:29 UTC, kozarezvlad commented on app/build.gradle.kts
> +    implementation(projects.data.appCurrency)
Сначала подумал что норм, что создаем модуль отдельно под это, но потом пересмотрел, что это 1 запрос, кешировние и чуть логики. Отделить это пакетом в настройках выглядит проще чем делать отдельный модуль, логически это также похоже на настройки. Типа выставляешь валюту приложения в конфиге приложения

2023-08-14 08:31 UTC, Sateetas commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
не, я под маскировкой имел ввиду ложную надежду на equals, хотя он отрабатывать нормально не будет, эксепшны же по ссылке сравниваются, не по полям

data class же не может нормально переопределять equals и hashCode, если у его полей это сравнение адресов в памяти и адрес в памяти

в чем тогда профит data? это же вводит в заблуждение

2023-08-14 08:34 UTC, Sateetas commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
то есть на "одинаковых" объектах, equals будет выдавать false, причем неважно, является ли DataError data-классом или нет

<img width="465" alt="image" src="https://github.com/tangem/tangem-app-android/assets/13484957/4f6c71b3-cf4a-4859-b0eb-0e4a973143c4">

2023-08-14 09:31 UTC, iiiburnyiii commented on app/build.gradle.kts
> +    implementation(projects.data.appCurrency)
Сейчас тут один use case, но в дальнейшем их станет, на вскидку, 3:
- Получение доступных для выбора валют
- Получение текущей валюты
- Изменение текущей валюты

Кажется, что для остальных настроек будет плюс-минус такая же история и общий модуль с настройкаи раздуется, его будет не удобно поддерживать. Плюс, по хорошему, для каждого типа настроек будут свои репозитории. 
Так же не во всех фичах нужны все настроки разом - немного теряется смысл разбиения на модули.

2023-08-14 09:36 UTC, iiiburnyiii commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
В данном случае плюс в консистентности с другими ошибками и в красивом `toString`

<img width="1888" alt="изображение" src="https://github.com/tangem/tangem-app-android/assets/26351057/13e99555-8a28-4508-88c5-d00452535ce1">

2023-08-14 09:39 UTC, Mama1emon commented on app/build.gradle.kts
> +    implementation(projects.data.appCurrency)
С учетом такого решения у меня вопрос отпал. 
Единственное - я не согласен с наименование модуля. CamelCase не используется в названиях зависимостей

2023-08-14 09:41 UTC, Sateetas commented on domain/appCurrency/src/main/kotlin/com/tangem/domain/appcurrency/error/AppCurrencyError.kt
> +    data class DataError(val cause: Throwable) : AppCurrencyError()
да, красиво получается
с другой стороны equals и hashCode не работают, и эта ошибка маскируются

2023-08-14 09:46 UTC, iiiburnyiii commented on app/build.gradle.kts
> +    implementation(projects.data.appCurrency)
Для названий модулей, мне кажется, camelCase норм заходит, а вот для пакетов лучше его не юзать. Либо, для модулей, можно kebab-case использовать, обычно его как раз и используют для зависимостей

2023-08-14 12:00 UTC, gbixahue approved these changes

2023-08-14 13:05 UTC, Sateetas approved these changes

2023-08-14 14:43 UTC, Mama1emon approved these changes

2023-08-14 15:05 UTC, merged