AND-4180 added support EdSlip to app. Added CardConfig
tangem/tangem-app-android-old pull request #1306
Opened 2023-08-11 13:55 UTC by kozarezvlad

AND-4223 extended mandatory curves.
Fixes to support last sdk version

2023-08-11 14:25 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/domain/OnboardingModuleError.kt
>      data class InvalidWords(val words: Set<String>) : SeedPhraseError(subCode = 7)
Здесь тогда нужно поднять до 8

2023-08-14 11:11 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/tasks/product/CreateWalletsTask.kt
> +            AnyMasterKeyFactory(it, "").makeMasterKey(curve)
naming args. Не совсем понятно, что за пустая строка

2023-08-14 11:11 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/domain/DefaultCustomTokenInteractor.kt
> +        // val derivationDataList = listOfNotNull(
Удалить?

2023-08-14 11:11 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/tokens/impl/domain/DefaultTokensListInteractor.kt
> +        // val derivationDataList = listOfNotNull(
Удалить?

2023-08-14 11:27 UTC, roman-pv commented on domain/legacy/src/main/java/com/tangem/domain/common/util/ScanResponseExtensions.kt
> +        when { // TODO
todo без пояснения и номера задачи, должна здесь оставаться?

2023-08-14 11:28 UTC, roman-pv commented on domain/legacy/src/main/java/com/tangem/domain/common/configs/Wallet2CardConfig.kt
> +        // todo check this logic ??
какая-то временная todo, удалишь или сформулируешь понятнее?

2023-08-14 11:31 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/domain/DefaultCustomTokenInteractor.kt
> +            curve?.let { getDerivations(curve, scanResponse, currencyList) }
тут получается теперь по каждой currency вызывается метод, который работает с целым списком валют (ограничиваясь только кривой)

2023-08-14 11:33 UTC, kozarezvlad commented on domain/legacy/src/main/java/com/tangem/domain/common/util/ScanResponseExtensions.kt
> +        when { // TODO
оставлял пометку, поправил

2023-08-14 11:33 UTC, kozarezvlad commented on domain/legacy/src/main/java/com/tangem/domain/common/configs/Wallet2CardConfig.kt
> +        // todo check this logic ??
удалил, временно было пока тестил

2023-08-14 11:35 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/domain/DefaultCustomTokenInteractor.kt
> +            curve?.let { getDerivations(curve, scanResponse, currencyList) }
да, тут временно проверял, забыл исправить нормально чтобы было, хорошо что заметил

2023-08-14 11:39 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/tokens/impl/domain/DefaultTokensListInteractor.kt
> +            curve?.let { getDerivations(curve, scanResponse, currencies) }
мб логированием покрыть else-случай?

2023-08-14 11:42 UTC, Sateetas requested changes

2023-08-14 11:42 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/tokens/legacy/redux/TokensMiddleware.kt
> +        // val derivationDataList = listOfNotNull(
закомментированный код остался

2023-08-14 11:44 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/tokens/impl/domain/DefaultTokensListInteractor.kt
> +            curve?.let { getDerivations(curve, scanResponse, currencies) }
немного перепишу это

2023-08-14 11:57 UTC, gbixahue approved these changes, later dismissed

2023-08-14 13:08 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/tokens/impl/domain/DefaultTokensListInteractor.kt
> +            curve?.let { getDerivations(curve, scanResponse, currencies) }
Пока оставил в итоге, но поднял логгирование в месте откуда идет curve, это будет достаточно чтобы понять

2023-08-14 13:09 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/tokens/legacy/redux/TokensMiddleware.kt
> +        // val derivationDataList = listOfNotNull(
убрал

2023-08-14 13:10 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/domain/DefaultCustomTokenInteractor.kt
> +            curve?.let { getDerivations(curve, scanResponse, currencyList) }
В общем пытался переписать, но есть риск сломать + такая же штука еще в 2х местах используется, надо системно это поправить вынеся в одно место какого либо менеджера. Сделаю отдельной таской в рамках рефакторинга
Сейчас фактически осталось как и было ранее, просто вместо хардкода 2х кривые вызывается для динамического списка

2023-08-14 13:44 UTC, Sateetas approved these changes

2023-08-14 13:48 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/customtoken/impl/domain/DefaultCustomTokenInteractor.kt
> +            curve?.let { getDerivations(curve, scanResponse, currencyList) }
так вызывался же 2х, теперь получается currencyList.size*x 
но я согласен, что можно отдельно поправить и что сейчас лучше не ломать

2023-08-14 13:48 UTC, roman-pv approved these changes

2023-08-14 13:59 UTC, merged