AND-4230 onboarding2: fixed opening web uri
tangem/tangem-app-android-old pull request #1307
Opened 2023-08-14 05:44 UTC by gbixahue

2023-08-14 06:57 UTC, Mama1emon commented on data/common/src/main/kotlin/com/tangem/data/common/locale/DefaultLocaleProvider.kt
> +class DefaultLocaleProvider : LocaleProvider {
internal?

2023-08-14 06:57 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/proxy/di/ProxyModule.kt
> +            override fun getWebViewAuthCredentialsProvider(): Provider<String?> = Provider {
Может быть null?

2023-08-14 06:57 UTC, Mama1emon commented on data/common/src/main/kotlin/com/tangem/data/common/locale/LocaleProvider.kt
> +    fun getLocale(): Locale
А зачем нужна обертка над получением локали? Locale же из любого места доступен

2023-08-14 07:53 UTC, gbixahue commented on data/common/src/main/kotlin/com/tangem/data/common/locale/DefaultLocaleProvider.kt
> +class DefaultLocaleProvider : LocaleProvider {
Нельзя, т.к. будет не доступен для фич

2023-08-14 07:54 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/proxy/di/ProxyModule.kt
> +            override fun getWebViewAuthCredentialsProvider(): Provider<String?> = Provider {
Может, если это продовская сборка

2023-08-14 07:59 UTC, gbixahue commented on data/common/src/main/kotlin/com/tangem/data/common/locale/LocaleProvider.kt
> +    fun getLocale(): Locale
Доступ к единственному провайдеру локали хорош тем, что дает возможность, в будущем, легко сделать переключение языка в приложения вне зависимости от локали устройства.

Чем больше языков мы будем поддерживать, тем больше вероятность такого сценария.

2023-08-14 09:31 UTC, Mama1emon commented on data/common/src/main/kotlin/com/tangem/data/common/locale/DefaultLocaleProvider.kt
> +class DefaultLocaleProvider : LocaleProvider {
Он не через DI поставляется?

2023-08-14 09:36 UTC, Mama1emon commented on data/common/src/main/kotlin/com/tangem/data/common/locale/LocaleProvider.kt
> +    fun getLocale(): Locale
Данная функциональность выглядит достаточно узкоспециализированно и как будто нужна только для одной конкретной ссылки. Реализация никак не отражает действительность. У нас поддерживает не только русский, белорусский и английский. Поэтому говорить, что данный компонент покроет будущее кейсы нельзя

2023-08-14 09:41 UTC, gbixahue commented on data/common/src/main/kotlin/com/tangem/data/common/locale/LocaleProvider.kt
> +    fun getLocale(): Locale
Данный функционал уже используется в 2х фичах
- Onboarding 2.0
- Learn2earn

2023-08-14 09:42 UTC, gbixahue commented on data/common/src/main/kotlin/com/tangem/data/common/locale/DefaultLocaleProvider.kt
> +class DefaultLocaleProvider : LocaleProvider {
На данный момент нет

2023-08-14 10:53 UTC, Sateetas requested changes

2023-08-14 10:53 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +        seedPhraseViewModel.setWebUriLocaleLanguageProvider(
а зачем этот провайдер через фрагмент затаскивать?
почему мы не можем в его DI засунуть и через конструктор вьюмодели получить к нему доступ?

2023-08-14 11:43 UTC, gbixahue commented on data/common/src/main/kotlin/com/tangem/data/common/locale/DefaultLocaleProvider.kt
> +class DefaultLocaleProvider : LocaleProvider {
Теперь через DI

2023-08-14 11:44 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +        seedPhraseViewModel.setWebUriLocaleLanguageProvider(
исправил

2023-08-14 18:40 UTC, kozarezvlad commented on app/src/main/assets/tangem-app-config
не обновлен локально сабмодуль?

2023-08-15 07:46 UTC, gbixahue commented on app/src/main/assets/tangem-app-config
Обновил до последнего

2023-08-15 08:19 UTC, Sateetas approved these changes

2023-08-15 08:20 UTC, kozarezvlad approved these changes

2023-08-15 08:44 UTC, merged