AND-4187 Connected balance with real data
tangem/tangem-app-android-old pull request #1332
Opened 2023-08-16 10:19 UTC by Yoggam1

2023-08-16 13:38 UTC, kozarezvlad submitted a review, later dismissed

2023-08-16 13:46 UTC, Mama1emon requested changes

2023-08-16 13:46 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +        return currentStateProvider()
Не будет состояния с ошибкой?

2023-08-16 13:46 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +                onMoreClick = clickIntents::onMoreClick,
?

2023-08-16 13:46 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +                TokenDetailsPreviewData.disabledActionButtons,
todo

2023-08-16 13:46 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +    data class SkeletonModel(val cryptoCurrency: CryptoCurrency)
Можно не делать обертку для cryptoCurrency

2023-08-16 13:46 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +        return getSelectedWalletUseCase()
Зачем нужен текущий кошелек?

2023-08-17 05:12 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +        return currentStateProvider()
Неа. Стейт этого экрана не `sealed`. Это обычный класс который собрал в себя несколько подстейтов

2023-08-17 05:14 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +    data class SkeletonModel(val cryptoCurrency: CryptoCurrency)
в след ПРах тут все измениться

2023-08-17 05:15 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +        return getSelectedWalletUseCase()
Чтобы получить карренси, смотрим несколько строчек низ

2023-08-17 05:15 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +                onMoreClick = clickIntents::onMoreClick,
?

2023-08-17 05:16 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +                TokenDetailsPreviewData.disabledActionButtons,
TODO висит в `disabledActionButtons`. Думаю этого хватить

2023-08-17 06:32 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +        return currentStateProvider()
Я не именно про то, что должен быть отдельный стейт экрана, а про то, как пользователь поймет, что при загрузке баланса произошла ошибка?

2023-08-17 06:32 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +                TokenDetailsBalanceBlockState.Loading(TokenDetailsPreviewData.disabledActionButtons)
TODO?

2023-08-17 06:32 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +            -> {
TODO?

2023-08-17 06:32 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +                onMoreClick = clickIntents::onMoreClick,
Сорри, я имел ввиду, откуда на экране TokenDetails переход на Details?

2023-08-17 06:32 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +        return getSelectedWalletUseCase()
Кажется, что userWalletId, как и CryptoCurrency должно передавать через Bundle с нового мейна.
Но сейчас это не так критично

2023-08-17 06:32 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +        return getSelectedWalletUseCase()
Можно закрывать

2023-08-17 07:59 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +                onMoreClick = clickIntents::onMoreClick,
more -> троеточии в тулбаре.

2023-08-17 09:24 UTC, kozarezvlad commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsSkeletonStateConverter.kt
> +                onMoreClick = clickIntents::onMoreClick,
Там будут действия с валютой, например скрыть токен

2023-08-17 11:30 UTC, Mama1emon submitted a review, later dismissed

2023-08-17 11:34 UTC, kozarezvlad approved these changes

2023-08-17 11:34 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +        return currentStateProvider()
добавил todo, пока не ясно как отобрадать

2023-08-17 11:34 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +            -> {
добавил

2023-08-17 12:26 UTC, Mama1emon approved these changes

2023-08-17 12:26 UTC, merged