AND-4192 Implemented current transactions retrieving
tangem/tangem-app-android-old pull request #1333
Opened 2023-08-16 11:18 UTC by iiiburnyiii

2023-08-16 11:51 UTC, Yoggam1 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/CryptoCurrencyStatus.kt
> +        override val hasCurrentNetworkTransactions: Boolean,
Предлагаю добавить `pending` к переменной. С докой понятно, но на месте вызова не очень то и понятно будет

2023-08-16 14:04 UTC, iiiburnyiii commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/CryptoCurrencyStatus.kt
> +        override val hasCurrentNetworkTransactions: Boolean,
Pending (отложенный/ожидающий) это не совсем то слово, кмк current (текущий) лучше подходит.

2023-08-17 06:21 UTC, Mama1emon submitted a review, later dismissed

2023-08-17 06:21 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/utils/NetworkStatusFactory.kt
> +                        it is CryptoCurrencyTransaction.Token &&
Хорошо бы заменить it

2023-08-17 08:13 UTC, Sateetas requested changes

2023-08-17 08:13 UTC, Sateetas commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/utils/NetworkStatusFactory.kt
> +    ): CurrentTransaction? {
зачем return type nullable, возвращается же всегда not-null транзакция

2023-08-17 08:13 UTC, Sateetas commented on domain/legacy/src/main/java/com/tangem/domain/walletmanager/model/UpdateWalletManagerResult.kt
> +        val addresses: Set<String>?,
а почему может быть nullable?

2023-08-17 08:13 UTC, Sateetas commented on domain/legacy/src/main/java/com/tangem/domain/walletmanager/model/UpdateWalletManagerResult.kt
> +        val addresses: Set<String>?,
и здесь, аналогично

2023-08-17 08:13 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/CryptoCurrencyStatus.kt
> +        override val hasCurrentNetworkTransactions: Boolean,
я за pending, это один из вариантов нормы

когда говорят pending transaction, подразумевается висящая, подвисшая, происходящая в данный момент

current менее емко тут смотрится, будто что-то в моменте, нерастянутое по времени
можно еще над waiting подумать

2023-08-17 21:58 UTC, iiiburnyiii commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/utils/NetworkStatusFactory.kt
> +    ): CurrentTransaction? {
Не всегда, если не удалось узнать направление транзакции, то вернётся null.
<img width="617" alt="изображение" src="https://github.com/tangem/tangem-app-android/assets/26351057/9cb7182a-035a-4e8a-9da7-08c8484d9a64">

2023-08-22 08:10 UTC, Sateetas approved these changes

2023-08-22 14:49 UTC, Yoggam1 approved these changes

2023-08-22 16:05 UTC, merged