AND-4317 Created GetButtonsStateUseCase with mock impl.
tangem/tangem-app-android-old pull request #1346
Opened 2023-08-18 13:27 UTC by Sateetas

2023-08-18 15:24 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetButtonsStateUseCase.kt
> +        userWalletId: UserWalletId,
тут стоит id конкретного токена еще докинуть, т.к. для разных токенов могут быть доступны либо нет кнопки. CryptoCurrency.ID думаю можно. @iiiburnyiii как думаешь?

2023-08-21 06:43 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetButtonsStateUseCase.kt
> +    internal val dispatchers: CoroutineDispatcherProvider,
Почему `internal`, а не `private`

2023-08-21 06:43 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetButtonsStateUseCase.kt
> +        }.flowOn(dispatchers.io)
Вроде не происходит никакой сложной работы, зачем переключать поток

2023-08-21 06:43 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/ButtonsState.kt
> +sealed class ButtonState {
1) На мой взгляд, лучше перенести в скоуп `WalletButtonsState`, так как при использовании в проекте сразу по названию не поймешь, что это за кнопки и для чего.
2) `Swap`?

2023-08-21 06:45 UTC, iiiburnyiii commented
А почему домен вообще что-то знает о каких-то кнопках? Кажется лучше что-то более абстрактное возвращать.

2023-08-21 08:55 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetButtonsStateUseCase.kt
> +        }.flowOn(dispatchers.io)
пока не сильно углубился в немоковую реализацию, но там вроде не только рантайм кеш будет

2023-08-21 09:00 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/ButtonsState.kt
> +sealed class ButtonState {
1) да, можно и так 
2) exchange разве не есть swap?

2023-08-21 09:01 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetButtonsStateUseCase.kt
> +    internal val dispatchers: CoroutineDispatcherProvider,
просмотрел, готово

2023-08-21 09:07 UTC, Sateetas commented
> А почему домен вообще что-то знает о каких-то кнопках? Кажется лучше что-то более абстрактное возвращать.

хорошее замечание, поправил

2023-08-22 05:57 UTC, Yoggam1 requested changes

2023-08-22 05:57 UTC, Yoggam1 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/ButtonsState.kt
> +data class WalletActionsState(
Почему wallet? У нас же не по воллету а по токену генеряться кнопки. Предлагаю заменить префикс wallet на token.

2023-08-22 05:57 UTC, Yoggam1 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetWalletActionsUseCase.kt
> +        userWalletId: UserWalletId,
не хватает TokenID

2023-08-22 05:58 UTC, Yoggam1 requested changes

2023-08-22 05:58 UTC, Yoggam1 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetWalletActionsUseCase.kt
> +class GetWalletActionsUseCase(
Так же стоит переименовать юзкейс

2023-08-22 08:55 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetWalletActionsUseCase.kt
> +class GetWalletActionsUseCase(
готово

2023-08-22 08:55 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetWalletActionsUseCase.kt
> +        userWalletId: UserWalletId,
готово

2023-08-22 08:55 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/ButtonsState.kt
> +data class WalletActionsState(
готово

2023-08-22 09:31 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/ButtonsState.kt
> +sealed class ButtonState {
А кнопка Send?

2023-08-22 09:32 UTC, Mama1emon commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetTokenActionsUseCase.kt
> +class GetTokenActionsUseCase(
По неймингу договаривались, что называем `CryptoCurrency`

2023-08-22 10:58 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/ButtonsState.kt
> +    class Exchange(override val enabled: Boolean) : ButtonState()
И когда добавлять Send будешь, надо будет Exchange переименовать в Swap. Общепринято swap для этого + в ios эпл не пропускают что то со словами Exchange

2023-08-22 11:03 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/ButtonsState.kt
> +    class Exchange(override val enabled: Boolean) : ButtonState()
переименовал, но в проекте куча сущностей называется exchange
это ок?

2023-08-22 11:15 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/model/ButtonsState.kt
> +    class Exchange(override val enabled: Boolean) : ButtonState()
не очень ок, это какое то легаси по моему. Тот своп что есть он со swap

2023-08-22 11:18 UTC, kozarezvlad approved these changes

2023-08-22 11:19 UTC, Mama1emon approved these changes

2023-08-22 11:40 UTC, Yoggam1 approved these changes

2023-08-22 11:41 UTC, merged