AND-4348 Add DeleteWalletUseCase and UpdateWalletUseCase
tangem/tangem-app-android-old pull request #1363
Opened 2023-08-22 12:41 UTC by Mama1emon

2023-08-22 14:25 UTC, Yoggam1 requested changes

2023-08-22 14:25 UTC, Yoggam1 commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/UpdateWalletUseCase.kt
> +        userWalletsListManager.update(userWalletId, update)
можно использовать `return userWalletsListManager.update(userWalletId, update).fold`?

2023-08-22 14:25 UTC, Yoggam1 commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/DeleteWalletUseCase.kt
> +        userWalletsListManager.delete(userWalletIds = listOf(userWalletId))
можно использовать `return userWalletsListManager.update(userWalletId, update).fold?`

2023-08-23 06:55 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/UpdateWalletUseCase.kt
> +        userWalletsListManager.update(userWalletId, update)
Этот метод возвращает `CompletionResult`из CardSDK (скажем так это танжемовский резалт). У этой обертки нет функции `fold`

2023-08-23 06:55 UTC, Mama1emon commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/DeleteWalletUseCase.kt
> +        userWalletsListManager.delete(userWalletIds = listOf(userWalletId))
Этот метод возвращает `CompletionResult`из CardSDK (скажем так это танжемовский резалт). У этой обертки нет функции `fold`

2023-08-23 07:15 UTC, kozarezvlad approved these changes

2023-08-23 08:51 UTC, Yoggam1 approved these changes

2023-08-23 08:52 UTC, merged