AND-4329 Implemented the ability to change theme modes for compose screens
tangem/tangem-app-android-old pull request #1376
Opened 2023-08-24 14:30 UTC by iiiburnyiii

2023-08-24 14:36 UTC, kozarezvlad submitted a review, later dismissed

2023-08-24 14:36 UTC, kozarezvlad commented on core/ui/src/main/java/com/tangem/core/ui/screen/ComposeScreen.kt
> +internal fun ComposeScreen.createComposeView(context: Context): ComposeView {
А чего не просто метод интерфейса ComposeScreen? ну или в его companion логично смотрится

2023-08-24 14:55 UTC, iiiburnyiii commented on core/ui/src/main/java/com/tangem/core/ui/screen/ComposeScreen.kt
> +internal fun ComposeScreen.createComposeView(context: Context): ComposeView {
Компаньон не подойдет - инстанс нужен. Можно и внутрь положить, но так сам интрефейс грязней будет, и этот метод попадет в конечные имплементации, что не очень круто

2023-08-25 07:30 UTC, roman-pv submitted a review, later dismissed

2023-08-25 07:56 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/common/apptheme/MutableAppThemeModeHolder.kt
> +internal object MutableAppThemeModeHolder : AppThemeModeHolder {
А зачем нужен данный компонент?

2023-08-25 07:58 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/ThemeModule.kt
> +    fun provideMutableAppThemeModeHolder(): MutableAppThemeModeHolder {
Добавление в DI как таковое не имеет смысла, так как компонент является `internal object`, его можно в рамках модуля откуда угодно вызвать

2023-08-25 07:59 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/apptheme/MutableAppThemeModeHolder.kt
> +internal object MutableAppThemeModeHolder : AppThemeModeHolder {
Он держит состояние типа темы приложения для `ComposeScreen`, там это состояние обсеривится. В интерфейсе есть дока, если что.

2023-08-25 08:06 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/screen/ComposeBottomSheetFragment.kt
> +    override val backgroundColor: Color
Задумка интересная, но она коррелирует с material design.
Материал компоненты, в идеальном случае, сами знают, какой цвет использовать. Но помимо этого, мы хотим сами всегда его переопределять

2023-08-25 08:06 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/screen/ComposeScreen.kt
> +    val appThemeModeHolder: AppThemeModeHolder
В каждом скрине переопределять данное поле очень муторно. Мб создать компоузовский провайде, а в MainActivity его запровайдить. А потом из лдюбого места будет доступен

2023-08-25 08:19 UTC, Mama1emon requested changes

2023-08-25 08:19 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/WalletFragment.kt
> -                        setSystemBarsColor(systemBarsColor)
А какая судьба со статус баром?

2023-08-25 13:32 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/WalletFragment.kt
> -                        setSystemBarsColor(systemBarsColor)
Цвет выставляется в базовом `ComposeScreen`

2023-08-25 13:34 UTC, iiiburnyiii commented on core/ui/src/main/java/com/tangem/core/ui/screen/ComposeScreen.kt
> +    val appThemeModeHolder: AppThemeModeHolder
К сожалению так не прокатит, так как тема создается для каждого экрана, как и провайдеры, так как у нас, пока-что, большая часть экранов на фрагментах

2023-08-26 00:47 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/screen/ComposeScreen.kt
> +    val appThemeModeHolder: AppThemeModeHolder
Да, ты прав. Я уже летаю мыслями в проекте без фрагментов))
Можно закрывать

2023-08-28 08:27 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/common/apptheme/MutableAppThemeModeHolder.kt
> +    override val appThemeMode: MutableState<AppThemeMode> = mutableStateOf(AppThemeMode.DEFAULT)
мб дефолтное значение передавать в параметре конструктора?

2023-08-28 08:45 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/apptheme/MutableAppThemeModeHolder.kt
> +    override val appThemeMode: MutableState<AppThemeMode> = mutableStateOf(AppThemeMode.DEFAULT)
Это объект, а не класс. Пробовал с классом, но почему-то тогда изменения стейта не подхватываются на экране.

2023-08-29 03:25 UTC, Mama1emon approved these changes

2023-08-29 06:31 UTC, roman-pv approved these changes

2023-08-29 06:33 UTC, kozarezvlad approved these changes

2023-08-29 06:42 UTC, merged