AND-4329 Implemented observation of theme mode changes
tangem/tangem-app-android-old pull request #1377
Opened 2023-08-24 15:03 UTC by iiiburnyiii

2023-08-29 07:12 UTC, Sateetas requested changes

2023-08-29 07:12 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/MainState.kt
> +internal sealed class MainState {
мб как-то переназвать класс? `MainState` достаточно абстрактно выглядит

2023-08-29 07:52 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/MainState.kt
> +internal sealed class MainState {
Есть такое, но лучше не придумал, есть идеи?

2023-08-29 07:53 UTC, kozarezvlad approved these changes, later dismissed

2023-08-30 04:09 UTC, Yoggam1 requested changes

2023-08-30 04:09 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +    private var mainState: MainState by mutableStateOf(MainState.Loading)
Почему переменная обернута в `MutableState`? Не вижу чтобы она была использована в компоузе

2023-08-30 04:09 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +            }
если переменную mainState сделать boolean, то не придется играться вот с такими when, if`ами.

2023-08-30 10:01 UTC, Sateetas commented on features/tester/impl/src/main/java/com/tangem/feature/tester/presentation/actions/TesterActionsContentState.kt
> +internal data class ToggleAppThemeConfig(
зачем data?

2023-08-30 10:02 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/MainState.kt
> +internal sealed class MainState {
не, но я скорее про то, а нужен ли нам прям MainState, который в себе всё собирает?
мб завести AppThemeState с параметрами Undef/Content?

2023-08-30 10:03 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/MainState.kt
> +internal sealed class MainState {
или Unknown/Content

2023-08-30 10:34 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/MainState.kt
> +internal sealed class MainState {
Ну, пока тут только тема прилы лежит, но мб дальше что-то ещё будет, язык, например. Предлагаю пока так оставить, с заделом на будущее.

2023-08-30 14:23 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/MainState.kt
> +internal sealed class MainState {
давай тогда GlobalSettingsState?

2023-08-31 02:04 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +                        isInitializing = state is MainState.Loading
Разве `isInitializing` не всегда будет `false`. Ведь ты обрабатываешь `state is MainState.Content` ветку

2023-08-31 02:04 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/MainState.kt
> +internal sealed class MainState {
Да, коррелирует с главным экраном.
Вариант Ильи мне нрав

2023-08-31 02:04 UTC, Mama1emon commented on features/tester/impl/src/main/java/com/tangem/feature/tester/presentation/actions/TesterActionsViewModel.kt
> +        val newAppThemeMode = when (currentAppThemeMode) {
А почему просто три кнопки не сделать?)

2023-08-31 07:28 UTC, iiiburnyiii commented on features/tester/impl/src/main/java/com/tangem/feature/tester/presentation/actions/TesterActionsViewModel.kt
> +        val newAppThemeMode = when (currentAppThemeMode) {
Сделал первое что в голову пришло)

2023-08-31 07:46 UTC, Yoggam1 approved these changes

2023-08-31 08:15 UTC, Sateetas approved these changes

2023-08-31 10:11 UTC, merged