AND-4286 Updated stories UI
tangem/tangem-app-android-old pull request #1387
Opened 2023-08-25 13:28 UTC by iiiburnyiii

2023-08-28 07:54 UTC, kozarezvlad approved these changes

2023-08-29 03:30 UTC, Mama1emon requested changes

2023-08-29 03:30 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/compose/content/CurrenciesWeb3Content.kt
> +                .height(TangemTheme.dimens.size164 + bottomInsetsPx.dp)
Кажется, что это не будет тяжелой операцией, но лучше любые вычисления в `derivedStateOf` делать

2023-08-29 03:30 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/compose/content/CurrenciesWeb3Content.kt
> +private val BottomGradient: Brush = Brush.verticalGradient(
Хорошо бы вынести и переиспользовать для разных компоуз функций

2023-08-29 03:30 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/compose/content/CurrenciesWeb3Content.kt
> +private val BottomGradient: Brush = Brush.verticalGradient(
Возможно, даже переиспользовать не просто градиент, а сам `Box`

2023-08-29 05:11 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/home/compose/content/CurrenciesWeb3Content.kt
> +                .height(TangemTheme.dimens.size164 + bottomInsetsPx.dp)
Его тут нет смысла использовать, частых изменений нет, как и сложных вычислений. Разве что можно в remember вынести

2023-08-29 05:14 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/home/compose/content/CurrenciesWeb3Content.kt
> +private val BottomGradient: Brush = Brush.verticalGradient(
Кажется, что это слишком абстрактный и, при этом, простой компонент чтобы его в систему выносить

2023-08-29 07:50 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/home/compose/content/CurrenciesWeb3Content.kt
> +private val BottomGradient: Brush = Brush.verticalGradient(
Вот эти три компоуз функции используют один и тот же градиент. И, как я понимаю, если придется менять градиент, то придется менять везде. То есть об этом нужно помнить. 
Поэтому я и предлагаю положить данный бокс рядом с ними, чтобы переиспользовать
<img width="253" alt="изображение" src="https://github.com/tangem/tangem-app-android/assets/29564668/b4e7e62b-9f28-40a3-821c-027e2363b3b2">

2023-08-29 07:56 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/home/compose/content/CurrenciesWeb3Content.kt
> +private val BottomGradient: Brush = Brush.verticalGradient(
Там разные градиенты) Для первого он высокий и белый, для второго он высокий и чёрный, для третьего он низкий и белый

2023-08-30 07:19 UTC, Mama1emon approved these changes

2023-08-30 10:43 UTC, merged