AND-3957 Remove old custom tokens screens
tangem/tangem-app-android-old pull request #1408
Opened 2023-08-29 13:46 UTC by Mama1emon

2023-08-29 15:01 UTC, roman-pv approved these changes

2023-08-29 20:49 UTC, iiiburnyiii approved these changes

2023-08-30 08:44 UTC, kozarezvlad requested changes
Го вольем после среза

2023-08-30 09:45 UTC, Sateetas approved these changes

2023-09-01 07:24 UTC, kozarezvlad approved these changes

2023-09-01 07:49 UTC, merged