AND-4272 Improved pull-to-refresh logic in the wallet screen
tangem/tangem-app-android-old pull request #1415
Opened 2023-08-31 10:25 UTC by iiiburnyiii

2023-08-31 12:48 UTC, Mama1emon requested changes

2023-08-31 12:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletLoadedTokensListConverter.kt
> +                tokenListStateConverter.convert(it)
method reference на твое усмотрение

2023-08-31 12:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletRefreshStateConverter.kt
> +    private fun getRefreshedState(): WalletState {
Объявление новых функций идет не по порядку их использования. Код тяжелее читается

2023-08-31 12:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletRefreshStateConverter.kt
> -    private fun WalletState.ContentState.createWalletsListConfig(): WalletsListConfig {
А почему эти поля больше не обновляются?

2023-08-31 12:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    private val tokenListErrorConverter by lazy {
А почему они передаются через конструткор?

2023-09-01 06:13 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletRefreshStateConverter.kt
> -    private fun WalletState.ContentState.createWalletsListConfig(): WalletsListConfig {
Тут при вызове рефреша отображался шиммер, так не должно быть. Обычно при вызове рефреша контент не меняет состояние, о загрузке говорит только спиннер вверху экрана

2023-09-01 08:06 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletRefreshStateConverter.kt
> -    private fun WalletState.ContentState.createWalletsListConfig(): WalletsListConfig {
Да, согласен с мыслью. Но обновлять все равно нужно. Но уже не в состояние загрузки, а сразу в контент

2023-09-01 08:29 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletRefreshStateConverter.kt
> +            else -> state
мб явно прописать else?
тогда при возможном расширении отстрелит CE

2023-09-01 08:33 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletRefreshStateConverter.kt
> +                    is WalletManageButton.Buy -> button.copy(enabled = true)
мб объединить через запятую три, где `button.copy(enabled = true)`?

или ты намеренно соблюдал порядок их объявления в `WalletManageButton`?

2023-09-01 10:09 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    private val tokenListErrorConverter by lazy {
Что-бы в каждом конвертере его отдельно не добавлять

2023-09-01 10:13 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletRefreshStateConverter.kt
> +                    is WalletManageButton.Buy -> button.copy(enabled = true)
Не прокатит через запятую, это поле не у всех подклассов есть

2023-09-01 10:57 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletRefreshStateConverter.kt
> +                    is WalletManageButton.Buy -> button.copy(enabled = true)
ага, посмотрел, оно не абстрактное

2023-09-01 10:58 UTC, Sateetas approved these changes, later dismissed

2023-09-01 11:06 UTC, Sateetas submitted a review, later dismissed

2023-09-04 10:17 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +        tokensJobHolder.update(job = null)
Мб тогда это делать сразу при смене кошелька?

2023-09-04 10:17 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    private fun refreshMultiCurrencyContent(walletIndex: Int) {
Хорошо бы отсортировать объявление рефреш функций, а то они  сейчас объвлены над местом, где вызываются

2023-09-05 06:15 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +        tokensJobHolder.update(job = null)
Обновление джоб может произойти при повторной инициализации, в `updateWallets`, и при смене кошелька в `onWalletChange`. Оба эти метода вызывают этот (`getContentItemsUpdates`), думаю логично отменять джобы тут, а не в двух местах

2023-09-05 06:25 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    private fun refreshMultiCurrencyContent(walletIndex: Int) {
Перенес все приватные методы ниже переписанных

2023-09-05 06:53 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    private fun updateWallets(sourceList: List<UserWallet>) {
Эта функция вызывается в `onCreate`, в следствии чего, она идет сразу после нее. Теперь она в самом низу. Читать код становится затруднительнее

2023-09-05 07:37 UTC, Mama1emon approved these changes

2023-09-05 07:58 UTC, Sateetas approved these changes

2023-09-05 07:58 UTC, merged