AND-4322 Added observation of theme mode changes to settings screens
tangem/tangem-app-android-old pull request #1421
Opened 2023-08-31 15:18 UTC by iiiburnyiii

2023-08-31 15:33 UTC, roman-pv approved these changes, later dismissed

2023-09-01 08:13 UTC, Mama1emon requested changes

2023-09-01 08:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appsettings/AppSettingsFragment.kt
> +class AppSettingsFragment : ComposeFragment(), StoreSubscriber<DetailsState> {
`internal`?

2023-09-01 08:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appsettings/AppSettingsFragment.kt
> -                TangemTheme {
`ScreenContent` оборачивается в `TangemTheme` автоматом?

2023-09-01 08:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/cardsettings/CardSettingsFragment.kt
> +class CardSettingsFragment : ComposeFragment(), StoreSubscriber<DetailsState> {
`internal`?

2023-09-01 08:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/details/DetailsFragment.kt
> +class DetailsFragment : ComposeFragment(), StoreSubscriber<DetailsState> {
`internal`?

2023-09-01 08:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appsettings/AppSettingsFragment.kt
> +    override fun ScreenContent(modifier: Modifier) {
Я заметил, что для каждого экрана передается `modifier`, но он нигде не испольузется

2023-09-01 08:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/details/DetailsFragment.kt
> -        Analytics.send(Settings.ScreenOpened())
А где теперь аналитика отправляется?

2023-09-01 08:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/details/DetailsScreen.kt
> +private fun Content(state: DetailsScreenState, modifier: Modifier = Modifier) {
А зачем `modifier` передается? Он же не испольузется нигде

2023-09-01 08:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/securitymode/SecurityModeFragment.kt
> +class SecurityModeFragment : ComposeFragment(), StoreSubscriber<DetailsState> {
`internal`?

2023-09-01 08:27 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/ui/walletconnect/WalletConnectFragment.kt
> +        enterTransition = inflateTransition(android.R.transition.fade)
можно без android

2023-09-01 09:05 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/appsettings/AppSettingsFragment.kt
> -                TangemTheme {
Да

2023-09-01 11:16 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/appsettings/AppSettingsFragment.kt
> +    override fun ScreenContent(modifier: Modifier) {
Поправил это, теперь везде используется

2023-09-01 11:16 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/details/DetailsFragment.kt
> -        Analytics.send(Settings.ScreenOpened())
Вернул

2023-09-04 05:40 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appsettings/AppSettingsFragment.kt
> +    override fun ScreenContent(modifier: Modifier) {
А какие атрибуты сеттятся через этот модифаер?

2023-09-04 07:24 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/appsettings/AppSettingsFragment.kt
> +    override fun ScreenContent(modifier: Modifier) {
Базовые атрибуты экрана, в случае `ComposeFragment` это просто `fillMaxSize()`

2023-09-04 11:37 UTC, Mama1emon approved these changes

2023-09-04 13:26 UTC, kozarezvlad approved these changes

2023-09-04 13:50 UTC, merged