AND-4007 Added patching wallet screen state by "hidden balance" events.
tangem/tangem-app-android-old pull request #1442
Opened 2023-09-06 09:48 UTC by Sateetas

2023-09-06 10:00 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +            val fiatAmount: String,
тут у меня есть консерн по поводу следования принципу отсечения лишнего, лучше голосом обсудить @Mama1emon

2023-09-06 20:32 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +            val fiatAmount: String,
обсудили

2023-09-08 03:25 UTC, Mama1emon requested changes

2023-09-08 03:25 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +        val balanceHidden: Boolean,
Предлагаю назвать `isBalanceHidden`, чтобы явно подчеркнуть, что это `Boolean` поле

2023-09-08 03:25 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +        fun updateHiddenState(hideBalance: Boolean): TokenOptionsState {
Кажется, что данная логика не должна быть частью стейта

2023-09-08 03:25 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/components/WalletCardState.kt
> +    private fun contentToHidden(content: Content) : HiddenContent {
Здесь тоже выполняется конвертация. Это ответственность отдельной сущности, а не стейта

2023-09-08 03:25 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
Мы пишем отдельные конвертер под формирование нового стейта. Иначе фабрика раздуется.

2023-09-08 03:25 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    private val isBalanceHiddenFlow: StateFlow<Boolean> = isBalanceHiddenUseCase.invoke().stateIn(
Предлагаю сделать, как с `selectedAppCurrencyFlow`, чтобы не раздувать список свойств вью моделей

2023-09-08 03:25 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/TokenListToWalletStateConverter.kt
> +            isBalanceHidden = isBalanceHiddenProvider(),
Лучше при конвертации ориентироваться на текущее состояние экрана, а не на значение use case.
Таким образом, мы сохраним единость при формировании стейта. Например, если мы скрываем контент, то мы делаем это только во флоу, а не размазываем по разным конвертерам.
Здесь же можно просто сделать проверку текущей карточки. Если она уже Hidden, то просто заммапить нужные поля, иначе создать контент

2023-09-08 07:58 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +        val balanceHidden: Boolean,
ok

2023-09-08 08:10 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
именно конвертер? конвертер же обычно для конвертации между слоями, тут что-то вроде патчера нужно

2023-09-08 09:41 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +    private val isBalanceHiddenFlow: StateFlow<Boolean> = isBalanceHiddenUseCase.invoke().stateIn(
ок

2023-09-08 09:45 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/TokenListToWalletStateConverter.kt
> +            isBalanceHidden = isBalanceHiddenProvider(),
здесь ты вроде немного не про то, идет конвертация из FiatBalance, а не из предыдущего стейта карточки

но я сделал под стать остальной логике, прокидывая провайдер вглубь

2023-09-08 09:47 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +        fun updateHiddenState(hideBalance: Boolean): TokenOptionsState {
ок

2023-09-08 10:57 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
назвал апдейтером, более точно отображает суть, чем конвертер

2023-09-08 10:57 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/components/WalletCardState.kt
> +    private fun contentToHidden(content: Content) : HiddenContent {
ок

2023-09-11 07:47 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
Конвертеры могут конвертировать не только модели между слоями. В данном случае они конвертируют из одного стейта в другой.
В целом я согласен с тем, что стоит назвать эти сущности по другому. Но не сейчас, в будущем. Когда выпустим фичу и будем причесывать. Иначе новый нейминг будет выделять среди других конвертеров. Код другим разрабам будет сложнее понимать

2023-09-11 07:51 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +        const val DOTS = "***"
`STARS`?

2023-09-11 07:51 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/TokenListToWalletStateConverter.kt
> +            isBalanceHidden = isBalanceHiddenProvider(),
Ок, давай тогда пока так оставим. 
В будущем тоже возьму в работу.

2023-09-12 11:32 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +        const val DOTS = "***"
ага, я это в следующем PR переделал

2023-09-12 11:37 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
вообще неинтуитивно, я вот пришел в фичу, смотрю на конвертеры и сразу думаю, что они выдают presentation state не на основе предыдущего presentation state, а на основе чего-то другого

это где-то формализовано, или на уровне ощущений?

как по мне, `converter` это про `map`, а `updater`/`patcher` это про `patch`/`update`/`apply`, а здесь именно `patch`/`update`/`apply`, 

давай оставим апдейтером чтобы задел был на будущее?

2023-09-13 09:11 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
На мой взгляд, `updater`/`patcher` не должен ничего возвращать наружу,а делать обновление непосредственно внутри себя. Иначе какой это `updater`, если он просто мапит стейт и возвращает его.

А где это должно быть формализовано? Я стараюсь писать доку почти всегда, но сейчас реально на это времени нет. 

Сейчас почти все действия используют сущность конвертера для преобразования стейта.

2023-09-13 09:24 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
а по мне норм апдейтер/патчер, который возвращает измененное состояние
давай на обсуждение вынесем

2023-09-13 17:37 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
Плюсану за то, что updater/patcher предполагает изменение внутри. Предлагаю единого нейминга придерживаться

2023-09-18 13:55 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getHiddenBalanceState(hiddenBalance: Boolean): WalletState {
ок, переделал обратно в конвертер

2023-09-18 18:39 UTC, kozarezvlad commented on core/res/src/main/res/values/strings.xml
> +    <string name="details_row_title_flip_to_hide">Flip-to-Hide Balances</string>
а где ru строки?

2023-09-18 18:41 UTC, kozarezvlad commented on domain/balance-hiding/src/main/kotlin/com/tangem/domain/balancehiding/ListenToFlipsUseCase.kt
> +            flow { }
emptyFlow<Unit>() ?

2023-09-19 03:49 UTC, Mama1emon requested changes

2023-09-19 03:49 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/DefaultDeviceFlipDetector.kt
> +    override fun deviceFlipEvents(): Flow<Unit> = callbackFlow {
Предлагаю функции называть, начиная с глагола

2023-09-19 03:49 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/DefaultDeviceFlipDetector.kt
>          val listener = object : SensorEventListener {
Создание анонимного объекта внутри функции очень перегружает её.
Хорошей практикой, на мой взгляд, является вынос реализации анонимного объекта в качестве внутреннего класса.

2023-09-19 03:49 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/DefaultDeviceFlipDetector.kt
> +class DefaultDeviceFlipDetector(context: Context) : DeviceFlipDetector {
`internal`?

2023-09-19 03:49 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsReducer.kt
> +            isHidingEnabled = runBlocking {
Ничего не заблокирует, пока функция исполняется?

2023-09-19 03:49 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/send/ui/SendViewModel.kt
> +            .flowOn(dispatchers.io)
Не так давно обсуждали с командой, что "заранее" сами не переключаем поток на `io`. Только там, где это реально нужно

2023-09-19 03:49 UTC, Mama1emon commented on common/src/main/java/com/tangem/common/Strings.kt
> +object Strings {
На мой взгляд, штука узко специализированная, и если все-таки выносить, то в домейн модуль

2023-09-19 03:49 UTC, Mama1emon commented on data/balance-hiding/build.gradle.kts
> +
Лишние строки

2023-09-19 03:49 UTC, Mama1emon commented on data/balance-hiding/src/main/java/com/tangem/data/balancehiding/DefaultBalanceHidingRepository.kt
> +    override fun balanceHidingSettingsEvents(): Flow<BalanceHidingSettings> {
Предлагаю называть функции с глагола

2023-09-19 03:49 UTC, Mama1emon commented on data/balance-hiding/src/main/java/com/tangem/data/balancehiding/DefaultBalanceHidingRepository.kt
> +        balanceHidingSettingsStore.store(balanceHidingSettings)
Такие штуки должны быть потокобезопасны. Явно переключаться на io тред

2023-09-19 03:49 UTC, Mama1emon commented on domain/balance-hiding/src/main/kotlin/com/tangem/domain/balancehiding/DeviceFlipDetector.kt
> +interface DeviceFlipDetector {
Данная сущность очень похожа на дата сущность, а не домейн, а именно на источник данных

2023-09-19 03:49 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +        viewModelScope.launch {
Данный код дублируется на многих вью моделях.
Хотя процесс выглядит так, что нам нужно подписаться на ЖЦ фрагмент и начать слушать данные. Мб пойти путем реализации контракта `LifecycleObserver`

2023-09-19 07:19 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsReducer.kt
> +            isHidingEnabled = runBlocking {
обсуждали в другом ПР, решение плохое, но вариантов тут не много, это сейчас меньшее зло, заблокировать не должно

2023-09-19 08:41 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsReducer.kt
> +            isHidingEnabled = runBlocking {
да, тут либо на старых префах делать, либо в каком-то месте юзать runBlocking, так как новое хранилище не поддерживает синхронное получение данных (только suspend и flow), поэтому решил что runBlocking является более оптимальным вариантом, чем костыльное расширение хранилища методом под один случай

2023-09-19 08:43 UTC, Sateetas commented on core/res/src/main/res/values/strings.xml
> +    <string name="details_row_title_flip_to_hide">Flip-to-Hide Balances</string>
пока нет, я в локалайз сейчас буду заливать вместе со строками по флоу сброса
или какой флоу должен быть, по-русски обязательно рыбу какую-то надо запилить? или дождаться нормального перевода из локалайза?

2023-09-19 09:04 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/DefaultDeviceFlipDetector.kt
>          val listener = object : SensorEventListener {
можно, но я тогда классом сделаю, потому что мы будем вне скопа flow (tryEmit будет недоступен), и надо будет передавать туда некий triggerAction

2023-09-19 09:10 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/send/ui/SendViewModel.kt
> +            .flowOn(dispatchers.io)
в целом политика такая, что в репах переключаемся?

2023-09-19 10:06 UTC, Sateetas commented on domain/balance-hiding/src/main/kotlin/com/tangem/domain/balancehiding/DeviceFlipDetector.kt
> +interface DeviceFlipDetector {
почему? по аналогии с репами — интерфейсы в domain

2023-09-19 13:24 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +        viewModelScope.launch {
ты про подписку на флипы или на подписку на флажок?

2023-09-19 17:11 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/send/ui/SendViewModel.kt
> +            .flowOn(dispatchers.io)
Придерживаемся
https://developer.android.com/kotlin/coroutines/coroutines-best-practices#main-safe

Считаем что репозиторий майн сейф, в юзкейсах переключаем по необходимости

2023-09-19 19:21 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +        viewModelScope.launch {
давай в следующем PR сделаем, вроде не сильно кртичино, да и кодовую базу не особо уменьшит

2023-09-20 10:03 UTC, kozarezvlad commented on core/res/src/main/res/values/strings.xml
> +    <string name="details_row_title_flip_to_hide">Flip-to-Hide Balances</string>
обычно сразу ru и en льем, по отдельности не держим

2023-09-20 10:29 UTC, Mama1emon commented on domain/balance-hiding/src/main/kotlin/com/tangem/domain/balancehiding/DeviceFlipDetector.kt
> +interface DeviceFlipDetector {
Потому что оно создает/генерит данные, как и любой другой дата сорс.
Тут больше коммент заключается в том, что это должно быть частью модуля `datasource`

2023-09-20 10:39 UTC, Sateetas commented on domain/balance-hiding/src/main/kotlin/com/tangem/domain/balancehiding/DeviceFlipDetector.kt
> +interface DeviceFlipDetector {
не совсем понял, в чем концептуальная разница с интерфейсами привычных репозиториев, которые находятся в domain-модулях?

2023-09-20 10:41 UTC, Mama1emon requested changes

2023-09-20 10:41 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsReducer.kt
> +                store.state.daggerGraphState.balanceHidingRepository?.getBalanceHidingSettings()
Есть удобная функция `get` у `daggerGraphState`, чтобы не делать дефолтное значение

2023-09-20 10:41 UTC, Mama1emon commented on data/balance-hiding/src/main/java/com/tangem/data/balancehiding/FlipListener.kt
> +class FlipListener(private val action: () -> Unit) : SensorEventListener {
internal?

2023-09-20 10:41 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/TokenItemHiddenStateUpdater.kt
> +internal class TokenItemHiddenStateUpdater {
Converter

2023-09-20 10:41 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +        return when (val state = currentStateProvider() as? WalletState.ContentState) {
Нужно вынести в отдельеный конвертер

2023-09-20 10:41 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/WalletHiddenBalanceStateConverter.kt
> +internal class WalletHiddenBalanceStateConverter {
Хорошо бы унаследоваться от Converter

2023-09-20 12:48 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/WalletHiddenBalanceStateConverter.kt
> +internal class WalletHiddenBalanceStateConverter {
тогда надо будет провайдер флажка тянуть в конструкторе, это не очень хорошо ложится на использование в HiddenStateConverter

2023-09-20 14:27 UTC, kozarezvlad approved these changes

2023-09-20 15:11 UTC, Mama1emon approved these changes

2023-09-20 15:48 UTC, merged