AND-4484 Added patching token screen state by "hidden balance" events.
tangem/tangem-app-android-old pull request #1447
Opened 2023-09-06 20:32 UTC by Sateetas

2023-09-07 07:27 UTC, iMaks99 approved these changes

2023-09-08 03:30 UTC, Mama1emon requested changes

2023-09-08 03:30 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenDetailsBalanceBlockState.kt
> +        val hidden: Boolean
Предлагаю `isBalanceHidden`, чтобы везде было однообразие

2023-09-08 03:30 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +                    hidden = isBalanceHiddenProvider()
Лучше ориентироваться на текущее состояние карточки при обновлении баланса

2023-09-08 11:06 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/TokenDetailsBalanceBlockState.kt
> +        val hidden: Boolean
ok

2023-09-08 11:12 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsLoadedBalanceConverter.kt
> +                    hidden = isBalanceHiddenProvider()
аналогично
https://github.com/tangem/tangem-app-android/pull/1442#discussion_r1319634704

2023-09-11 07:52 UTC, Mama1emon approved these changes

2023-09-11 09:04 UTC, merged