AND-4097 Implement send bottom sheet
tangem/tangem-app-android-old pull request #1465
Opened 2023-09-11 15:52 UTC by iMaks99

2023-09-12 17:32 UTC, Yoggam1 requested changes
Также нужно добавить этот боттомшит на главную в контексное меню при длительном тапе в монету

2023-09-12 17:32 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/bottomsheets/tokenreceive/TokenReceiveBottomSheet.kt
> +    val qrCodes = remember { content.addresses.map { it.toQrCode() } }
Лучше вынести в отдельную функцию генерацию QR кода. А вообще было бы лучше в отдельный remember вынести. [Пример](https://dev.to/devniiaddy/qr-code-with-jetpack-compose-47e)

2023-09-12 17:32 UTC, Yoggam1 commented on core/ui/src/main/java/com/tangem/core/ui/components/bottomsheets/TangemBottomSheet.kt
> +fun TangemBottomSheet(
А нам точно нужен такой general боттомшит?

2023-09-12 17:32 UTC, Yoggam1 commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/GetWalletAddressUseCase.kt
> +    suspend operator fun invoke(userWallet: UserWallet): Either<GetWalletAddressError, Address> {
Either в правой стороне вполне себе может держать `List<String>`. Зачем нужна обертка в лишний сущность, если на месте вызова опят разворачивается в List?

2023-09-12 17:32 UTC, Yoggam1 commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/GetWalletAddressUseCase.kt
> +    private val walletManagersRepository: WalletManagersRepository,
Нужно использовать `WalletMangersFacade`

2023-09-13 12:12 UTC, iMaks99 commented on core/ui/src/main/java/com/tangem/core/ui/components/bottomsheets/TangemBottomSheet.kt
> +fun TangemBottomSheet(
Выносится дублирующий код, поэтому нужен

2023-09-14 13:50 UTC, Yoggam1 approved these changes

2023-09-14 15:24 UTC, kozarezvlad approved these changes

2023-09-14 15:24 UTC, merged