AND-4494: add dark theme support for Settings
tangem/tangem-app-android-old pull request #1467
Opened 2023-09-12 08:25 UTC by roman-pv

2023-09-12 09:45 UTC, iiiburnyiii requested changes

2023-09-12 09:45 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/common/DetailsComposeElements.kt
> +                selectedColor = colorResource(id = R.color.accent),
Тут, и ниже для compose компонентов, стоит цвета из `TangemTheme` использовать

2023-09-12 10:57 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/details/ui/common/DetailsComposeElements.kt
> +                selectedColor = colorResource(id = R.color.accent),
да, точно

2023-09-12 11:57 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/common/TangemSwitch.kt
> +    checkedColor: Color = colorResource(id = R.color.accent),
Тут тож цвета надо поправить

2023-09-12 11:57 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/walletconnect/WalletConnectScreen.kt
> +            color = colorResource(id = R.color.accent),
И тут

2023-09-12 11:57 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/walletconnect/WalletConnectScreen.kt
> +            color = colorResource(id = R.color.accent),
И вот)

2023-09-12 11:57 UTC, iiiburnyiii commented on app/src/main/res/values/styles.xml
> +    <style name="BaseAppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar" />
Приложение нормально себя ведет, если в приложении выставить темную тему, а в системе светлую, и наоборот?

2023-09-12 11:57 UTC, iiiburnyiii commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ReferralFragment.kt
> +    override fun ScreenContent(modifier: Modifier) {
Тут ещё стоит цвета системных баров выставить. Или они дальше выставляются?

2023-09-12 15:36 UTC, roman-pv commented on app/src/main/res/values/styles.xml
> +    <style name="BaseAppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar" />
да, только с этой темой нормально себя ведет

2023-09-13 07:25 UTC, roman-pv commented on features/referral/presentation/src/main/java/com/tangem/feature/referral/ReferralFragment.kt
> +    override fun ScreenContent(modifier: Modifier) {
Они там подходящие, потому что на прошлом экране были выставлены. То есть да, стоит проставить

2023-09-13 11:37 UTC, iiiburnyiii approved these changes

2023-09-13 17:37 UTC, kozarezvlad approved these changes

2023-09-13 18:03 UTC, merged