AND-4441 Implemented presentation logic for app currency selector
tangem/tangem-app-android-old pull request #1478
Opened 2023-09-13 09:47 UTC by iiiburnyiii

2023-09-14 08:08 UTC, Mama1emon requested changes

2023-09-14 08:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorStateController.kt
> +internal class AppCurrencySelectorStateController(
У нас с каждым разом все больше и больше видов сущностей для работы со стейтом появляются

2023-09-14 08:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorStateController.kt
> +    private val onSubscription: () -> Unit,
`onSubscribe`?

2023-09-14 08:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorStateController.kt
> +    private val currencyConverter = CurrencyConverter()
`lazy {...}` ?

2023-09-14 08:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorViewModel.kt
> +        reduxNavController.popBackStack()
Хорошо бы навигацию экрана инкапсулировать в роутере

2023-09-14 08:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorViewModel.kt
> +                .onRight { reduxNavController.popBackStack() }
По желанию можно method reference

2023-09-14 08:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorViewModel.kt
> +        viewModelScope.launch(dispatchers.io) {
Договаривались, что будем переключать поток там, где это реально нужно. Плюс не будет раскрытие деталей реализации данного `use case`

2023-09-14 08:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorViewModel.kt
> +    private fun bootstrapCurrencies() {
Если я правильно перевел, то `bootstrap` - существительное. Лучшей практикой считается называть функции с глагола

2023-09-15 06:36 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorViewModel.kt
> +        viewModelScope.launch(dispatchers.io) {
Ты же до этого говорил, что во view model поток стоит везде указывать, для тестов)

2023-09-15 06:38 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorViewModel.kt
> +        reduxNavController.popBackStack()
Тут это излишне - этот экран открывается из redux логики, соответственно своего роутера у фичи нет, а пилить его ради одного метода как-то странно

2023-09-15 06:51 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorStateController.kt
> +    private val onSubscription: () -> Unit,
Как подсказывают мне мои знания англицкого, то все таки `onSubscription` - `onSubscribe` скорее значит, что эта сущность на что-то где-то подписалась, `onSubscription` же говорит о том, что появилась полписка на эту сущность. А тут как раз происходит подписка на состояние, а не состояние на что-то подписывается

2023-09-15 06:54 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorStateController.kt
> +internal class AppCurrencySelectorStateController(
Это та же сущность, что и `StateHolder` для organize tokens, просто `Controller` больше подходит. Но переименовал, для единообразия

2023-09-15 08:14 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/appcurrency/AppCurrencySelectorViewModel.kt
> +        viewModelScope.launch(dispatchers.io) {
Да, все верно. Должно быть явное указание `main` потока)

2023-09-15 08:17 UTC, Mama1emon approved these changes

2023-09-15 09:38 UTC, Sateetas approved these changes

2023-09-15 10:35 UTC, roman-pv approved these changes

2023-09-15 10:50 UTC, merged