AND-4293 Fixed crash on CryptoCurrency converter
tangem/tangem-app-android-old pull request #1482
Opened 2023-09-13 13:44 UTC by Yoggam1

2023-09-13 13:45 UTC, Sateetas approved these changes

2023-09-13 14:02 UTC, kozarezvlad approved these changes

2023-09-13 16:25 UTC, kozarezvlad requested changes
Пока не понятна причина почему могло быть null не будем лить

2023-09-14 13:44 UTC, kozarezvlad approved these changes

2023-09-14 14:03 UTC, kozarezvlad commented
Изучим пока краш на следующем релизе

2023-10-16 06:21 UTC, closed without merging