AND-4520 Redesign Scan: the wallet doesn't opened  if scan card on the main screen when biomerty off
tangem/tangem-app-android-old pull request #1496
Opened 2023-09-18 08:07 UTC by Mama1emon

2023-09-18 09:50 UTC, iiiburnyiii requested changes

2023-09-18 09:50 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/components/WalletTopBarState.kt
> +        val onAddCardClick: () -> Unit,
Дык решили только в настройках добавления кошелька оставить

2023-09-18 09:58 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/components/WalletTopBarState.kt
> +        val onAddCardClick: () -> Unit,
Если биометрия включена, то будет плюсик
https://www.figma.com/file/Vs6SkVsFnUPsSCNwlnVf5U/Android-%E2%80%93-UI?type=design&node-id=3045-11326&mode=design&t=cIqg61N290Myhf1X-4

2023-09-18 15:00 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                getContentItemsUpdates(index = action.selectedWalletIndex)
Почему тут больше этот метод не используется?

2023-09-18 17:49 UTC, Yoggam1 approved these changes, later dismissed

2023-09-19 03:06 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/components/WalletTopBarState.kt
> +        val onAddCardClick: () -> Unit,
Плюсика не будет))

2023-09-19 03:07 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                getContentItemsUpdates(index = action.selectedWalletIndex)
При инициализации воллетов нам не нужно делать скролл на определенный элемент, так как `rememberLazyList` сам установит правильный элемент

2023-09-19 08:17 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                getContentItemsUpdates(index = action.selectedWalletIndex)
Тут логика почти дублирует метод `loadAndUpdateState()`, хочется как-то более аккуратно это сделать. Плюс в целом эту логику стоит в отдельный метод вынести, что-бы when не перегружать

2023-09-19 08:35 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletViewModel.kt
> +                getContentItemsUpdates(index = action.selectedWalletIndex)
Согласен, некрасиво выглядит. Улучшил

2023-09-19 08:39 UTC, iiiburnyiii approved these changes

2023-09-19 09:03 UTC, kozarezvlad approved these changes

2023-09-19 09:03 UTC, merged