AND-4570 Implemented UI for warnings in TokenDetails
tangem/tangem-app-android-old pull request #1499
Opened 2023-09-19 05:33 UTC by Yoggam1

2023-09-19 06:09 UTC, Mama1emon commented
А почему сразу не в девелоп?

2023-09-19 06:16 UTC, Mama1emon requested changes

2023-09-19 06:16 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/components/TokenDetailsNotification.kt
> +                text = TextReference.Str("Buy"),
`common_buy`

2023-09-19 06:16 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/components/TokenDetailsNotification.kt
> +    data class RentInfoNotification(
На мой взгляд, нет смысла добавлять в конце `Notification`, так как данные классы лежат в скоупе `TokenDetailsNotification`, из чего явно понятно, что они из себя представляют

2023-09-19 06:16 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +@Suppress("LongMethod")
Можно сразу разнести на функции, чтобы не блочить ворнинг.
Так как у нас экраны похожи, можешь глянуть на новой главной, как можно упростить по быстрому. Я с этой проблемой уже намаялся)

2023-09-19 06:16 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +                    key = { it.config.title.hashCode() },
Заголовки могут повторяться. Это не уникальное значение

2023-09-19 06:16 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +        viewModelScope.launch {
Хорошо бы диспатчер указать

2023-09-19 08:22 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +                    key = { it.config.title.hashCode() },
Тут ничего другого уникального не придумаешь. Но одинаковых ворнингов нету, посмотрел на главной там тоже такая логика для ключа

2023-09-19 15:33 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +                    key = { it.config.title.hashCode() },
а мб в `Notification` id положить?

2023-09-20 06:10 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +                    key = { it.config.title.hashCode() },
какой ID? откуда взять этот id? все же намерен оставить как есть и на это есть два причины.
1. Сейчас нотификация о том что сеть недоступна может сыпаться из двух мест. В текущем имплементации все отработает как надо.
2. Если менять, то нужно будет придумать что-то уникальное чтобы в главной тоже использовать такую же логику для айдишников.

Заголовки у нотификаций не одинаковый

2023-09-20 06:11 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/components/TokenDetailsNotification.kt
> +    data class RentInfoNotification(
сделано

2023-09-20 06:11 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/components/TokenDetailsNotification.kt
> +                text = TextReference.Str("Buy"),
исправил

2023-09-20 06:12 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +        viewModelScope.launch {
Добавил

2023-09-20 07:28 UTC, roman-pv commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/components/TokenDetailsNotification.kt
> +    data class NetworkFeeFee(
`FeeFee`

2023-09-20 08:19 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/components/TokenDetailsNotification.kt
> +    data class NetworkFeeFee(
Исправил

2023-09-20 08:21 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +                    key = { it.config.title.hashCode() },
мб уникальный на тип генерить?
или при создании генерить уникальный?

2023-09-20 08:26 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/TokenDetailsScreen.kt
> +@Suppress("LongMethod")
Решили добавить туду и вернуться чуть похже

2023-09-21 05:46 UTC, Mama1emon approved these changes

2023-09-21 06:46 UTC, roman-pv approved these changes

2023-09-21 07:14 UTC, merged