AND-4542 Reset card rework
tangem/tangem-app-android-old pull request #1500
Opened 2023-09-19 05:40 UTC by Sateetas

2023-09-19 06:01 UTC, Yoggam1 requested changes

2023-09-19 06:01 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsAction.kt
> +        data class AcceptCondition2(val accepted: Boolean) : ResetToFactory()
Может лучше `AcceptFirstCondition` и `AcceptSecondCondition`

2023-09-19 06:01 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +                        val doAfterErase = {
Не понял, зачем нужны эти переменные? Чем отличается от вызова на месте?

2023-09-19 06:01 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +    checkedStateProvider: () -> Boolean,
`isChecked: Boolean`

2023-09-19 06:01 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +                onClick = { onCheckedChange.invoke(!checkedStateProvider()) },
`onCheckedChange(...)`

2023-09-19 06:06 UTC, Mama1emon requested changes

2023-09-19 06:06 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +                            tangemSdkManager.setUserCodeRequestPolicy(policy)
А зачем сохранять в локальной переменной?
Она же только в одном месте используется

2023-09-19 06:06 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsReducer.kt
> +        warning1Checked = false,
Я не совсемпонял контекст, но сразу можно сказать, что нейминг выбивается. В одном месте `condition`, в другом `warning`. По этогу что это такое?)

2023-09-19 06:06 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +                onCheckedChange = { state.onAcceptWarning1ToggleClick(it) },
Чтобы не создавать новую лямбду, можно упростить до 
`onCheckedChange = state.onAcceptWarning1ToggleClick`

2023-09-19 06:06 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +    checkedStateProvider: () -> Boolean,
А почему провайдер используется?

2023-09-19 06:06 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +            .padding(top = 16.dp, bottom = 16.dp),
`dimens`

2023-09-19 06:06 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +        }
Так как иконка будет меняться по тогглу, то обязательно нужно использовать анимацию

2023-09-19 11:58 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsAction.kt
> +        data class AcceptCondition2(val accepted: Boolean) : ResetToFactory()
мне показалось, что числами нагляднее

2023-09-19 11:59 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +                        val doAfterErase = {
наглядностью, мы "патчим" и "анпатчим", хотел акцентировать на этом внимание

2023-09-19 12:02 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +                onClick = { onCheckedChange.invoke(!checkedStateProvider()) },
это формализовано? я обычно invoke использую, более явно выходит

2023-09-19 12:02 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +    checkedStateProvider: () -> Boolean,
да, тут можно без lazy

2023-09-19 12:04 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +                            tangemSdkManager.setUserCodeRequestPolicy(policy)
мы сохраняем policy до doBeforeErase, делаем erase и возвращаем обратно

как ты предлагаешь?

2023-09-19 12:35 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsReducer.kt
> +        warning1Checked = false,
скорее warning

2023-09-19 12:35 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +    checkedStateProvider: () -> Boolean,
ага, убрал, здесь lazy необязателен

2023-09-19 12:36 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +        }
давай отдельной таской?

2023-09-20 09:21 UTC, Yoggam1 approved these changes, later dismissed

2023-09-20 12:44 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +        }
Тут работы на самом деле совсем немного.
Нужно просто обернуть в `AnimatedContent`, где сделать ветвление на две разны вьюхи. Компоуз все сам красиво сделает :)

2023-09-20 12:47 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +                            tangemSdkManager.setUserCodeRequestPolicy(policy)
Мой коммент заключается в том, что реализация многострочных анонимных функций внутри локальной функции ухудшает читаемость. В таком кейсе лучше их тоже сделать локальными

2023-09-20 14:05 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +                            tangemSdkManager.setUserCodeRequestPolicy(policy)
почему внутри локальной, у нас handle не локальная же

2023-09-20 14:25 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/ui/resetcard/ResetCardScreen.kt
> +        }
ок, на кнопку тоже добавил

2023-09-21 04:31 UTC, Yoggam1 approved these changes

2023-09-22 08:01 UTC, Mama1emon approved these changes

2023-09-22 08:36 UTC, merged