AND-4631 Added address selector for explorer
tangem/tangem-app-android-old pull request #1523
Opened 2023-09-25 07:32 UTC by Sateetas

2023-09-25 08:02 UTC, iMaks99 submitted a review, later dismissed

2023-09-25 11:20 UTC, kozarezvlad commented on core/res/src/main/res/values/strings.xml
> +    <string name="token_details_choose_address">Choose address</string>
Давай сразу строку в ru, чтобы не было рассинка

2023-09-25 11:32 UTC, kozarezvlad requested changes
Давай сразу строку в ru, чтобы не было рассинка

2023-09-26 09:02 UTC, Sateetas commented on core/res/src/main/res/values/strings.xml
> +    <string name="token_details_choose_address">Choose address</string>
готово

2023-09-26 09:07 UTC, roman-pv approved these changes

2023-09-26 09:22 UTC, kozarezvlad approved these changes

2023-09-26 09:23 UTC, merged