AND-4659 Implemented hidden balance in transaction history.
tangem/tangem-app-android-old pull request #1526
Opened 2023-09-25 10:32 UTC by Sateetas

2023-09-25 13:45 UTC, iiiburnyiii commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/txhistory/TokenDetailsTxHistoryTransactionStateConverter.kt
> +                amount = if (isBalanceHiddenProvider()) STARS else item.amount.toCryptoCurrencyFormat(),
Лучше в отдельный метод закинуть

2023-09-25 13:45 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/txhistory/WalletTxHistoryTransactionStateConverter.kt
> +                amount = if (isBalanceHiddenProvider()) STARS else item.amount.toCryptoCurrencyFormat(),
Тут тоже про отдельный метод

2023-09-26 08:13 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/txhistory/TokenDetailsTxHistoryTransactionStateConverter.kt
> +                amount = if (isBalanceHiddenProvider()) STARS else item.amount.toCryptoCurrencyFormat(),
ok

2023-09-26 08:14 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/txhistory/WalletTxHistoryTransactionStateConverter.kt
> +                amount = if (isBalanceHiddenProvider()) STARS else item.amount.toCryptoCurrencyFormat(),
ok

2023-09-26 09:47 UTC, iiiburnyiii submitted a review, later dismissed

2023-09-26 09:53 UTC, kozarezvlad submitted a review, later dismissed

2023-09-26 10:40 UTC, kozarezvlad approved these changes, later dismissed

2023-09-26 10:56 UTC, iiiburnyiii submitted a review, later dismissed

2023-09-26 14:09 UTC, kozarezvlad submitted a review, later dismissed

2023-09-27 07:51 UTC, kozarezvlad submitted a review, later dismissed

2023-09-27 09:07 UTC, Yoggam1 requested changes

2023-09-27 09:07 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
>      private var isBalanceHidden = true
Нужно убрать эти поля

2023-09-27 21:16 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
>      private var isBalanceHidden = true
ок, обсудили, убрал

2023-09-28 11:37 UTC, Yoggam1 approved these changes

2023-09-28 12:43 UTC, kozarezvlad approved these changes

2023-09-28 12:43 UTC, merged