AND-4723 Added balance hiding in organize.
tangem/tangem-app-android-old pull request #1544
Opened 2023-09-27 07:09 UTC by Sateetas

2023-09-27 07:26 UTC, iiiburnyiii requested changes

2023-09-27 07:26 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +        fun resolve(): String {
Думаю этот метод в отдельный файл лучше вынести

2023-09-27 07:26 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/dnd/DragAndDropAdapter.kt
> +    fun updateHiddenState(isBalanceHidden: Boolean) {
Эта логика должна быть в стейт холдере

2023-09-27 08:33 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/dnd/DragAndDropAdapter.kt
> +    fun updateHiddenState(isBalanceHidden: Boolean) {
здесь у нас логика другая, не такая как в других местах со скрытием

здесь меняем не domain-модели, а presentation-модели, иначе у нас после drap-n-drop и флипа порядок будет сбиваться на initial

и у нас как раз стейт холдер апдейтит domain-модель, а адаптер presentation-модель

2023-09-27 11:10 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/common/state/TokenItemState.kt
> +        fun resolve(): String {
ok

2023-09-27 11:50 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/dnd/DragAndDropAdapter.kt
> +    fun updateHiddenState(isBalanceHidden: Boolean) {
Это адаптер для работы именно с днд (он только со стейтом списока работает), операции над стейтом экрана просходят в `OrganizeTokensStateHolder`

2023-09-27 13:30 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/dnd/DragAndDropAdapter.kt
> +    fun updateHiddenState(isBalanceHidden: Boolean) {
ок, перенес

но кмк немного странно получилось, что одна сущность работает и с presentation-моделями, и с domain-моделями

2023-09-29 10:06 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +        )
Можешь эту логику в конвертер положить, плиз, что-бы холдер не перегружать

2023-10-04 11:29 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/error/TokenListHiddenStateConverter.kt
> +    override fun convert(input: Pair<OrganizeTokensListState, Boolean>): OrganizeTokensListState {
А зачем стейт извне передавать? Лучше его через провайдер кинуть, пример `TokenListToStateConverter` в пакете с конвертерами

2023-10-04 11:37 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/error/TokenListHiddenStateConverter.kt
> +    override fun convert(input: Pair<OrganizeTokensListState, Boolean>): OrganizeTokensListState {
как по мне если есть возможность передавать явно, лучше передавать явно, а не лениво

2023-10-04 11:40 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/error/TokenListHiddenStateConverter.kt
> +    override fun convert(input: Pair<OrganizeTokensListState, Boolean>): OrganizeTokensListState {
Тож не нравится тема со всеми этими конвертерами, как то это пока сыро выглядит, но лучше сейчас единообразно сделать, что-бы потом обновлять легче было

2023-10-04 11:45 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/error/TokenListHiddenStateConverter.kt
> +    override fun convert(input: Pair<OrganizeTokensListState, Boolean>): OrganizeTokensListState {
ну не, lazy не надо тащить туда, где без него можно обойтись, потом по ногам стрелять будет при рефакторинге

да и не сказать что все единообразно сделано, `InProgressStateConverter` к примеру сделан без провайдеров, туда кусок стейта напрямую передается

2023-10-04 11:49 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/error/TokenListHiddenStateConverter.kt
> +    override fun convert(input: Pair<OrganizeTokensListState, Boolean>): OrganizeTokensListState {
Я про lazy не говорю ничего, от этого можно отказаться, да. Я чисто про провайдер стейта сейчас, в `InProgressStateConverter` провадер не используется так как там только сам стейт конвертируется, там больше нет аргументов. Тут же решение через `Pair` выяглядит несколько костыльно

2023-10-04 12:15 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/error/TokenListHiddenStateConverter.kt
> +    override fun convert(input: Pair<OrganizeTokensListState, Boolean>): OrganizeTokensListState {
не, я про `lazy` говорю в контексте провайдера, это же lazy-получение стейта по сути

думал о твоем варианте, но тогда получится, что на инпут в конвертер пойдет Boolean, а возвращать будем State)
как по мне, это выглядит максимально странно, словно хвост виляет собакой
решил так не делать

2023-10-06 17:04 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/error/TokenListHiddenStateConverter.kt
> +    override fun convert(input: Pair<OrganizeTokensListState, Boolean>): OrganizeTokensListState {
Тут скорее просто сущность конвертера названа (или используется) не совсем корректно, но в любом случае вариант с передачей pair для меня выглядит не очень круто, просто по причине того, что это потом рефакторить будет чуть больнее. Предлагаю позвать ребят, что-бы нас рассудили.

2023-10-06 17:07 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/OrganizeTokensStateHolder.kt
> +    }
Тут, кста, если остановимся на твоем варианте, `itemState` не стоит передавать снаружи. Метод `updateState` передает стейт экран как this, стоит оттуда вытащить стейт списка.

2023-10-08 18:13 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/organizetokens/utils/converter/error/TokenListHiddenStateConverter.kt
> +    override fun convert(input: Pair<OrganizeTokensListState, Boolean>): OrganizeTokensListState {
Плюсую за провайдер, чтобы было везде одинаково. Pair тут и правда смотрится не очень, если так, то лучше уж обернуть во что то было бы. Но в любом случае плюс за провайдер стейта, поскольку сейчас такой подход в 90% мест

2023-10-09 13:05 UTC, kozarezvlad approved these changes

2023-10-09 13:40 UTC, iiiburnyiii approved these changes

2023-10-09 13:51 UTC, merged