AND-4712 Redesign: If you create a backup via warning on the main, it doesn't disappear AND-4707 Redesign: Warning about Rent for solanа blockchain doesn't appear if you do pull to refresh
tangem/tangem-app-android-old pull request #1554
Opened 2023-09-28 21:44 UTC by iMaks99

AND-4712 Redesign: If you create a backup via warning on the main, it doesn't disappear
AND-4707 Redesign: Warning about Rent for solanа blockchain doesn't appear if you do pull to refresh

2023-09-29 03:47 UTC, Yoggam1 submitted a review, later dismissed

2023-09-29 08:32 UTC, Mama1emon requested changes

2023-09-29 08:32 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +            userWalletsListManager.selectedUserWalletSync?.walletId?.let {
Это не только для нового мейна должно быть?

2023-09-29 08:32 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletsUpdateActionResolver.kt
> +                (this as? WalletCardState.Content)?.cardCount != selectedWallet.getCardsCount() ||
1) У карточки одинаковые айди, но разное кол-во карт - значит выбранный кошелек изменился. В таком кейсе нам не нужно перерисовывать полностью экран, лишь `additionalText` у карточки. Предлагаю сделать отдельный стейт на обновление карточки.
2) Хранить cardsCount в UI модели необязательно, так как ты знаешь id предыдущего кошелька, то можешь найти в массиве `UserWallet`

2023-09-29 08:41 UTC, iMaks99 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletsUpdateActionResolver.kt
> +                (this as? WalletCardState.Content)?.cardCount != selectedWallet.getCardsCount() ||
1. Это правило обновляет карточку инотификацию с бэкапом, обновление нотификации завивисит от типа волета и списка токенов
2. Я сравниваю текущий стейт экрана с данными из массива, в массиве уже хранятся актуальные значения. "Предыдущий волет" играет роль прошлого состояния экрана

2023-10-02 08:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletsUpdateActionResolver.kt
> +                (this as? WalletCardState.Content)?.cardCount != selectedWallet.getCardsCount() ||
1. А что за нотификация? После бекапа, что должно произойти с нотификацией?
2. Понял, согл

2023-10-02 08:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletsUpdateActionResolver.kt
> +            previousWalletState is WalletCardState.Content || previousWalletState is WalletCardState.HiddenContent &&
Скобки здесь не нужны?

2023-10-02 08:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletStateFactory.kt
> +    fun getStateWithUpdatedWalletCardCount(): WalletState = walletRefreshCardCountConverter.convert(Unit)
На мой взгляд, лучше вместо `Refresh` использовать глагол `Update`, так как это создает небольшую путаницу с действием на `pull-to-refresh`

2023-10-02 08:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletSingleCurrencyLoadedBalanceConverter.kt
> +                    cardCount = currentWalletProvider().getCardsCount(),
А почему не у selectedWallet?

2023-10-02 08:48 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/FiatBalanceToWalletCardConverter.kt
> +                cardCount = currentWalletProvider().getCardsCount(),
Почему не из `currentState`?

2023-10-02 08:48 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsNotificationConverter.kt
> +    fun removeRentInfo(currentState: TokenDetailsState): ImmutableList<TokenDetailsNotification> {
А на TokenDetails не надо использовать UseCase?

2023-10-02 09:03 UTC, iMaks99 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/WalletsUpdateActionResolver.kt
> +            previousWalletState is WalletCardState.Content || previousWalletState is WalletCardState.HiddenContent &&
Детект на них ругался

2023-10-02 09:06 UTC, iMaks99 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsNotificationConverter.kt
> +    fun removeRentInfo(currentState: TokenDetailsState): ImmutableList<TokenDetailsNotification> {
В данном кейсе нет, нотификация появляется всегда после пулл ту рефреш, даже после скрытия. А само отображение вынес как раз в UseCase вместо флага isVisible

2023-10-02 09:33 UTC, iMaks99 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/factory/WalletSingleCurrencyLoadedBalanceConverter.kt
> +                    cardCount = currentWalletProvider().getCardsCount(),
Потому что card count есть только когда WalletCardState.Content, в Loading и других его нет

2023-10-02 09:35 UTC, iMaks99 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/utils/FiatBalanceToWalletCardConverter.kt
> +                cardCount = currentWalletProvider().getCardsCount(),
Аналогично что и выше

2023-10-02 10:00 UTC, iiiburnyiii requested changes

2023-10-02 10:00 UTC, iiiburnyiii commented on domain/wallets/src/main/java/com/tangem/domain/wallets/usecase/IsNeedToBackupUseCase.kt
> +    operator fun invoke(id: UserWalletId): Flow<Boolean> {
Use case'ы должны возвращять `Either`, но так как сроки горят, добавь TODO плиз

2023-10-02 10:04 UTC, Mama1emon commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +            fetchCurrencyStatusUseCase.invoke(
А почему это запускается по delay, а не по результату загрузки транзакций?
А что если транзакции не загрузились?

2023-10-02 10:10 UTC, iMaks99 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +            fetchCurrencyStatusUseCase.invoke(
Здесь не история транзакций, а обновление данных для нотификации о исходящий транзакций в процессе. Текстовку поправлю. А по delay потому flow network status иначе не возвращает актуальные значения. Обсудили это с @iiiburnyiii

2023-10-02 10:11 UTC, kozarezvlad commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +            fetchCurrencyStatusUseCase.invoke(
Неявная штука конечно выходит. @iiiburnyiii сейчас нет вариантов иначе, вроде вы обсуждали с Максом?

2023-10-02 10:19 UTC, Mama1emon approved these changes

2023-10-02 10:21 UTC, iiiburnyiii commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +            fetchCurrencyStatusUseCase.invoke(
Раньше логика такая была, только задержка была то ли в 2 секунды, то ли в 10, @roman-pv поправит если что.
По хорошему надо как-то слушать изменения в самом блокчейне, но так мы сейчас не умеем.

2023-10-02 10:21 UTC, iiiburnyiii approved these changes

2023-10-02 10:28 UTC, merged