AND-4742: change some UI elements for dark theme
tangem/tangem-app-android-old pull request #1565
Opened 2023-10-03 10:46 UTC by roman-pv

2023-10-03 11:50 UTC, kozarezvlad commented on core/ui/src/main/res/drawable-night/card_placeholder_black.xml
Такой сложный вектор лучше webp положить. Можешь ради интереса собрать апк на этой ветке и в студии архив посмотреть в какой размер он конвертнется в сборке

2023-10-03 11:52 UTC, kozarezvlad requested changes
Проверить размер вектора и положить webp на cardPlaceholder

2023-10-03 13:31 UTC, roman-pv commented on core/ui/src/main/res/drawable-night/card_placeholder_black.xml
Я добавил его для темной темы, с другим цветом фона он уже давно такой. 
Вроде проблема же не в размере файла, а во времени отрисовки больших векторов (больших в плане длины/ширины).

2023-10-03 18:40 UTC, kozarezvlad commented on core/ui/src/main/res/drawable-night/card_placeholder_black.xml
Я натыкался на такое как-то, во время сборки апк эти векторы преобразуются в png и раскладываются в директории по dpi. Однажды добавление картинки в сложном векторе увеличило размер апк таким образом на 20мб.
В доке нигде не нашел описания, есть предположение, что для обратной совместимости, но такое есть.

2023-10-03 18:44 UTC, kozarezvlad commented on core/ui/src/main/res/drawable-night/card_placeholder_black.xml
Проверил в последней апк, векторы не конвертяся на сборке вроде бы, видимо действительно связано под какой targetApi собирать.
Но тем не менее, предлагаю договорится сложные складывать в webp, это широко распространенная практика

2023-10-04 06:05 UTC, roman-pv commented on core/ui/src/main/res/drawable-night/card_placeholder_black.xml
Да, я согласен. Дока гугла рекомендует уходить с векторов, когда понятно, что размер в месте использования становится больше 200 dp, и в принципе когда понятно, что ресурс будет использоваться не как иконка, а как картинка.

2023-10-04 08:11 UTC, Mama1emon submitted a review, later dismissed

2023-10-04 10:48 UTC, kozarezvlad commented on core/ui/src/main/res/drawable-night/card_placeholder_black.xml
Добавишь тогда сразу мб? или таску хотя бы

2023-10-05 07:35 UTC, roman-pv commented on core/ui/src/main/res/drawable-night/card_placeholder_black.xml
Да, конечно, я там просто несколько вещей проверил и поискал, откуда его в таком формате проще взять (в фигме уже не было). Я тоже по обсуждению вроде понял, что решили, что я добавлю )

2023-10-05 07:39 UTC, roman-pv commented on core/ui/src/main/res/drawable-night/card_placeholder_black.xml
Готово

2023-10-05 07:40 UTC, kozarezvlad approved these changes

2023-10-05 08:02 UTC, iMaks99 approved these changes

2023-10-05 08:02 UTC, merged