AND-4786 Transaction history: the history does not load when internet access is available
tangem/tangem-app-android-old pull request #1577
Opened 2023-10-05 11:42 UTC by iMaks99

2023-10-06 05:59 UTC, Yoggam1 approved these changes

2023-10-06 09:20 UTC, Yoggam1 requested changes

2023-10-06 09:20 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/txhistory/TokenDetailsTxHistoryItemFlowConverter.kt
> +        val txHistoryContent = state as? TxHistoryState.Content
А что будет если контент будет Error?

2023-10-06 09:43 UTC, iMaks99 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/txhistory/TokenDetailsTxHistoryItemFlowConverter.kt
> +        val txHistoryContent = state as? TxHistoryState.Content
Будет null и вернется стейт который был, но по идее этого быть не должно, так как я вызов стейтов поменял на error -> loading -> content. раньше было error -> content и состояние loading не вызывалось корректно или когда нужно

2023-10-09 13:02 UTC, closed without merging

2023-10-09 13:03 UTC, iMaks99 commented
Исправлен в рамках https://tangem.atlassian.net/browse/AND-4803 https://github.com/tangem/tangem-app-android/pull/1581