AND-4882 Added chucker
tangem/tangem-app-android-old pull request #1620
Opened 2023-10-12 19:56 UTC by Sateetas

2023-10-13 06:44 UTC, Yoggam1 requested changes

2023-10-13 06:44 UTC, Yoggam1 commented on core/datasource/src/main/java/com/tangem/datasource/utils/HttpClientExt.kt
>      return if (BuildConfig.DEBUG) {
```
    return if (BuildConfig.DEBUG && context != null) {
        addInterceptor(interceptor = ChuckerInterceptor(context))
```

2023-10-13 08:12 UTC, Mama1emon submitted a review, later dismissed

2023-10-13 08:34 UTC, roman-pv submitted a review, later dismissed

2023-10-13 10:41 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/utils/HttpClientExt.kt
>      return if (BuildConfig.DEBUG) {
Почему? там же еще логгер для тимбера есть, который не зависит от контекста
Сделал опциональным контекст для `TangemTechService`, который в DI надо занести, там контекст достаточно сложно прокидывать контекст (не хотел лепить костылей типа `App.context` или засовывать его в GlobalState)
Вызовов апи из этого сервиса не словил при беглом смоуке

кстати, а корректно ли, что мы везде на `BuildConfig.DEBUG` завязываемся, а не на `BuildConfig.LOG_ENABLED`?
посмотрел — флажок есть, но нигде в проекте не используется, хотя сеттится корректно (true для debug- и external-сборок)

мы не юзаем, потому что забыли про него или по каким-то другим причинам?

2023-10-16 14:03 UTC, Yoggam1 approved these changes, later dismissed

2023-10-17 10:25 UTC, Mama1emon submitted a review, later dismissed

2023-10-17 13:20 UTC, kozarezvlad approved these changes

2023-10-18 06:53 UTC, Mama1emon approved these changes

2023-10-18 06:53 UTC, merged