AND-4251: create add/edit token button for Manage Tokens items
tangem/tangem-app-android-old pull request #1659
Opened 2023-10-18 13:21 UTC by roman-pv

<img width="219" alt="Screenshot 2023-10-18 at 17 19 42" src="https://github.com/tangem/tangem-app-android/assets/25419290/069139fe-d6ed-4b69-8b58-14cb49b325b4">

2023-10-18 16:02 UTC, Mama1emon requested changes

2023-10-18 16:02 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> + * https://www.figma.com/file/14ISV23YB1yVW1uNVwqrKv/Android?type=design&node-id=68%3A20&mode=design&t=fjwUkRtMUA4Q4s5r-1
Хорошо бы добавить как ссылку, тогда из документации можно будет сразу открывать ссылку в браузере

2023-10-18 16:02 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +    val primary: Boolean,
Предлагаю назвать `isPrimary`, так будет однозначно понятно, что это булиан поле

2023-10-18 16:02 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +            .size(height = TangemTheme.dimens.size24, width = TangemTheme.dimens.size46)
А как будет работать с увеличением шрифта?

2023-10-18 16:02 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +    Row(
Row для одного элемента?

2023-10-18 16:02 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +            maxLines = 1,
А если текст большой, то как это будет хендлиться? Просто обрываться?

2023-10-18 16:02 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +private fun Preview_SmallButton_Light_sample(
Зачем нужна приставка `_sample`? Обычно без этого именовали

2023-10-18 16:02 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +    val primary: Boolean,
А вообще мы в ДС обычно такие вещи делим на две функции: SmallButtonPrimary, SmallButtonSecondary

2023-10-18 16:02 UTC, Mama1emon commented on features/manage-tokens/impl/src/main/java/com/tangem/managetokens/presentation/managetokens/ui/components/TokenButton.kt
> +                onClick = { onClick() },
Лучше не создавать новую лямбду
```suggestion
                onClick = onClick,
```

2023-10-18 16:02 UTC, Mama1emon commented on features/manage-tokens/impl/src/main/java/com/tangem/managetokens/presentation/managetokens/ui/components/TokenButton.kt
> +                text = TextReference.Res(R.string.manage_tokens_add),
Появились удобные функции `resourceReference`. Но это так, если захочется упростить

2023-10-18 16:02 UTC, Mama1emon commented on features/manage-tokens/impl/src/main/java/com/tangem/managetokens/presentation/managetokens/ui/components/TokenButton.kt
> +                    .clickable { onClick() },
Как будет рипл работать? Не надо шейп круга добавить?

2023-10-18 16:02 UTC, Mama1emon commented on features/manage-tokens/impl/src/main/java/com/tangem/managetokens/presentation/managetokens/ui/components/TokenButton.kt
> +private data class TokenButtonConfig(
А зачем это нужно?

2023-10-19 04:45 UTC, roman-pv commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +    val primary: Boolean,
Хорошо, давай тогда сделаю, чтобы было как обычно

2023-10-19 04:49 UTC, roman-pv commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +            .size(height = TangemTheme.dimens.size24, width = TangemTheme.dimens.size46)
Упс, я почему-то прям перед ПР когда просматривал, поменял minSize на обычный. Не понял, что на меня нашло, я даже обсуждал с дизайнерами, что кнопка может увеличиваться, если текст не влезает.

2023-10-19 04:49 UTC, roman-pv commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +            maxLines = 1,
Ответил выше, кнопка должна увеличиваться

2023-10-19 08:44 UTC, roman-pv commented on features/manage-tokens/impl/src/main/java/com/tangem/managetokens/presentation/managetokens/ui/components/TokenButton.kt
> +                    .clickable { onClick() },
Я смотрел разные варианты, все немного странно. Но еще подумал, в итоге на другом варианте остановился, кругленький из центра

2023-10-19 08:53 UTC, Mama1emon approved these changes, later dismissed

2023-10-19 08:53 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +private fun ButtonsSample() {
Блочить не буду сейчас, но на мой взгляд написание семплов вредит пониманию реальной картины вьюхи.
Заходишь в компонент, смотришь на превью, а оно отличается от реальной реализации.
До этого подход с провайдером был, вот он, на мой взгляд, отлично отражает картину.

2023-10-19 09:05 UTC, roman-pv commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +private fun ButtonsSample() {
Но если как сейчас я поменял, что два типа кнопок - это разные функции, а не флаг у ButtonConfig, то конфиг провайдер не поможет. Если не добавлять column, то тогда надо отдельные превью функции на каждый тип кнопки.

2023-10-19 09:07 UTC, roman-pv commented on core/ui/src/main/java/com/tangem/core/ui/components/buttons/SmallButton.kt
> +private fun ButtonsSample() {
А чем на твой взгляд здесь превью отличается от реализации? Тот только добавлена Column с бэкграундом, который можно и через параметры превью добавлять

2023-10-19 09:36 UTC, Mama1emon approved these changes

2023-10-19 12:33 UTC, Yoggam1 approved these changes

2023-10-19 12:56 UTC, merged