AND-4765 Replace zxing scanner with ml kit
tangem/tangem-app-android-old pull request #1752
Opened 2023-10-27 14:31 UTC by Sateetas

2023-10-29 17:44 UTC, kozarezvlad commented on app/build.gradle.kts
> +    implementation("com.google.guava:guava:30.0-android") {
забыл вынести com.google.guava:guava:30.0-android в deps?

2023-10-30 13:11 UTC, iiiburnyiii commented on app/src/main/res/layout/layout_qr_scanning.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Может есть вариант сразу на compose написать?

2023-10-30 13:11 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/walletconnect/dialogs/PreviewBinder.kt
> +class PreviewBinder {
internal?

2023-10-30 13:11 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/ui/walletconnect/QrScanFragment.kt
> +class QrScanFragment : Fragment(R.layout.layout_qr_scanning) {
internal?

2023-10-30 13:11 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/qrCodeScan/ViewFinderOverlay.kt
> +        val boxHeight = overlayHeight * 36 / 100
Пердлагаю в константы закинуть

2023-10-31 12:04 UTC, iMaks99 requested changes
Вынеси пожалуйста из app, нужен доступ к сканеру из feature слоя

2023-11-01 12:25 UTC, Sateetas commented on app/build.gradle.kts
> +    implementation("com.google.guava:guava:30.0-android") {
тут непонятно, стоит ли

хотел акцентировать внимание на exclude, т.к. сама guava тянется как транзитивная зависимость, то есть ее в dependencies.toml не особо имеет смысл класть

2023-11-01 12:43 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/ui/walletconnect/dialogs/PreviewBinder.kt
> +class PreviewBinder {
ок

2023-11-01 12:43 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/details/ui/walletconnect/QrScanFragment.kt
> +class QrScanFragment : Fragment(R.layout.layout_qr_scanning) {
ок

2023-11-01 12:43 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/common/qrCodeScan/ViewFinderOverlay.kt
> +        val boxHeight = overlayHeight * 36 / 100
ага, заодно сам подсчет поправил

2023-11-01 12:43 UTC, Sateetas commented
> Вынеси пожалуйста из app, нужен доступ к сканеру из feature слоя

обсудили голосом, создал https://tangem.atlassian.net/jira/software/c/projects/AND/issues/AND-5130

2023-11-01 12:44 UTC, Sateetas commented on app/src/main/res/layout/layout_qr_scanning.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
подумал что не стоит обвязывать, когда одна из двух вьюх — библиотечная android view

2023-11-08 08:51 UTC, iMaks99 submitted a review, later dismissed

2023-11-09 11:46 UTC, kozarezvlad commented on app/build.gradle.kts
> +    implementation("com.google.guava:guava:30.0-android") {
режет глаз когда все implementation(deps....
а тут хардкодом

2023-11-09 11:53 UTC, kozarezvlad submitted a review, later dismissed

2023-11-09 12:45 UTC, iMaks99 submitted a review, later dismissed

2023-11-09 13:13 UTC, iMaks99 approved these changes

2023-11-10 06:43 UTC, kozarezvlad approved these changes

2023-11-10 09:00 UTC, merged