AND-5207 [Wallet] Added UI state for VISA wallet
tangem/tangem-app-android-old pull request #1965
Opened 2023-12-06 14:43 UTC by iiiburnyiii

2023-12-06 18:59 UTC, Yoggam1 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state2/WalletScreenState.kt
> +                                state = TransactionState.Locked(txHash = "LOCKED_TX_HASH"),
Мне кажется уже где-то была константа. Если нет, то стоит вынести в константу

2023-12-06 18:59 UTC, Yoggam1 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state2/transformers/converter/VisaWalletCardStateConverter.kt
> +            fiatCurrencySymbol = "€",
Может стоит использовать `java.util.Currency` вместо хардкода?

2023-12-07 06:30 UTC, kozarezvlad requested changes
Будем лить после среза экспресса, на всякий случай. Завтра в районе обеда будет +-.
Тоггл получится сразу?

2023-12-07 06:32 UTC, iiiburnyiii commented
> Будем лить после среза экспресса, на всякий случай. Завтра в районе обеда будет +-. Тоггл получится сразу?

А зачем тогл? Пользователь без карты не получит доступ к изменениям.

2023-12-07 08:09 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state2/transformers/converter/VisaWalletCardStateConverter.kt
> +            fiatCurrencySymbol = "€",
Поправил

2023-12-07 08:17 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state2/WalletScreenState.kt
> +                                state = TransactionState.Locked(txHash = "LOCKED_TX_HASH"),
Поправил тут https://github.com/tangem/tangem-app-android/pull/1968

2023-12-07 08:28 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state2/transformers/converter/VisaWalletCardStateConverter.kt
> +            is CryptoCurrencyStatus.Custom,
custom точно в error state мапится?

2023-12-07 08:29 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state2/transformers/converter/VisaWalletCardStateConverter.kt
> +            value = buildString {
может, через ресурс сделать в угоду RTL?

2023-12-07 08:30 UTC, Sateetas commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/intents/VisaWalletIntents.kt
> +internal class VisaWalletIntentsImplementor @Inject constructor(
`DefaultVisaWalletIntents`?

2023-12-07 08:51 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state2/transformers/converter/VisaWalletCardStateConverter.kt
> +            is CryptoCurrencyStatus.Custom,
Ага, он не должен приходить для одновалюток

2023-12-07 08:52 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/intents/VisaWalletIntents.kt
> +internal class VisaWalletIntentsImplementor @Inject constructor(
Тож так хотел, но остальные подобные классы так называются, так что лучше сразу все переименовать

2023-12-07 08:53 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/intents/VisaWalletIntents.kt
> +internal class VisaWalletIntentsImplementor @Inject constructor(
Внес этот вопрос к правкам по рефакторингу главного экрана

2023-12-07 08:53 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state2/transformers/converter/VisaWalletCardStateConverter.kt
> +            value = buildString {
Тогда для остальных кошельков тоже нужно поправить, лучше отдельно обсудить

2023-12-07 11:50 UTC, kozarezvlad approved these changes

2023-12-07 13:47 UTC, Yoggam1 approved these changes

2023-12-07 13:47 UTC, Sateetas approved these changes

2023-12-07 15:52 UTC, merged