Feature/and 5872 send screen added network fee coverage notification
tangem/tangem-app-android-old pull request #2156
Opened 2024-01-19 16:02 UTC by iMaks99

2024-01-22 14:00 UTC, Yoggam1 commented
@iMaks99 Мне кажется у этого ПРа таргет бренч должен быть другой. Тогда изменения во файлах не будут дублироваться. Когда #2153 будет замерджен, таргет автоматически поменяется

2024-01-22 14:19 UTC, iMaks99 commented
Буду знать на будущее, спасибо

2024-01-23 01:43 UTC, Yoggam1 requested changes

2024-01-23 01:43 UTC, Yoggam1 commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/state/fee/FeeNotificationFactory.kt
> +        if (cryptoAmount <= value + feeValue && feeState.isSubtract && !feeState.isUserSubtracted) {
Не подходит для вичейна

2024-01-23 07:35 UTC, Mama1emon approved these changes

2024-01-23 08:34 UTC, iMaks99 commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/state/fee/FeeNotificationFactory.kt
> +        if (cryptoAmount <= value + feeValue && feeState.isSubtract && !feeState.isUserSubtracted) {
Я пока не дошел до проверки отдельных блокчейнов

2024-01-23 08:35 UTC, iMaks99 commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/state/fee/FeeNotificationFactory.kt
> +        if (cryptoAmount <= value + feeValue && feeState.isSubtract && !feeState.isUserSubtracted) {
Там много где вичейн может стрельнуть, пока не было что проверять, я сделал как есть

2024-01-23 10:30 UTC, Yoggam1 approved these changes

2024-01-23 10:53 UTC, merged