AND-5937 [Send screen] Added VeChain & Terra fee support
tangem/tangem-app-android-old pull request #2191
Opened 2024-01-29 13:57 UTC by iMaks99

2024-01-30 07:36 UTC, Mama1emon approved these changes, later dismissed

2024-01-30 09:16 UTC, Yoggam1 requested changes

2024-01-30 09:16 UTC, Yoggam1 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetBalanceNotEnoughForFeeWarningUseCase.kt
> +            }
А тут учтен `FeePaidCurrency.SameCurrency`?

2024-01-30 09:16 UTC, Yoggam1 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetBalanceNotEnoughForFeeWarningUseCase.kt
> +                it is CryptoCurrency.Token && it.contractAddress.equals(feePaidToken.contractAddress, ignoreCase = true)
тут еще нужно добавить сравнение дериваций. Изначально я забыл добавить это, но исправил в след фиксах

2024-01-30 09:17 UTC, iMaks99 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetBalanceNotEnoughForFeeWarningUseCase.kt
> +            }
Да, он тут не нужен

2024-01-30 09:17 UTC, iMaks99 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetBalanceNotEnoughForFeeWarningUseCase.kt
> +                it is CryptoCurrency.Token && it.contractAddress.equals(feePaidToken.contractAddress, ignoreCase = true)
поправлю

2024-01-30 15:56 UTC, Yoggam1 approved these changes

2024-01-31 08:41 UTC, Mama1emon approved these changes

2024-01-31 08:41 UTC, merged