AND-5952 [Send screen] Added fee approximate symbol
tangem/tangem-app-android-old pull request #2209
Opened 2024-01-31 13:05 UTC by iMaks99

2024-01-31 13:08 UTC, kozarezvlad commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/state/fee/FeeStateFactory.kt
> +    private val walletManagerFacade: WalletManagersFacade,
решили что фасад будет разбить на репозитории, тянуть напрямую в presentation не стоит его

2024-01-31 13:08 UTC, kozarezvlad requested changes
решили что фасад будет разбит на репозитории, тянуть напрямую в presentation не стоит его

2024-02-01 11:50 UTC, kozarezvlad approved these changes

2024-02-01 11:54 UTC, Mama1emon approved these changes

2024-02-01 11:54 UTC, merged