AND-5991 Combine runtime and biometric of user wallets list manager implementations
tangem/tangem-app-android-old pull request #2275
Opened 2024-02-13 15:41 UTC by Mama1emon

2024-02-14 08:41 UTC, kozarezvlad requested changes
Предлагаю это лить после того как ветка 5.7 будет отведена

2024-02-20 10:32 UTC, kozarezvlad submitted a review, later dismissed

2024-02-20 10:37 UTC, kozarezvlad submitted a review, later dismissed

2024-02-20 10:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/extensions/Store.kt
> +inline fun <reified T> Store<AppState>.getFromDagger(getDependency: DaggerGraphState.() -> T?): T {
nit: Можно назвать `inject`, кмк так просто приятней будет

2024-02-20 10:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/redux/global/GlobalReducer.kt
> +                val generalUserWalletsListManager = store.getFromDagger(DaggerGraphState::generalUserWalletsListManager)
Разве нельзя его тут из параметров action взять? Он же там передаётся.

2024-02-20 10:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/GeneralUserWalletsListManager.kt
> +        }
Вроде тут, и ниже, можно упростить, через `flatMapLatest`:

```suggestion
        get() = implementation
            .flatMapLatest { it.userWallets }
```

2024-02-20 10:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +                    preferencesStorage.shouldShowSaveUserWalletScreen = false // TODO: зачем?
Что-бы не показывать bottom sheet с предложением сохранять кошельки каждый раз)

2024-02-20 10:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +            // TODO: для чего это нужно?
Что-бы получить контекст для менеджера

2024-02-20 13:17 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/common/extensions/Store.kt
> +inline fun <reified T> Store<AppState>.getFromDagger(getDependency: DaggerGraphState.() -> T?): T {
Согласен

2024-02-20 13:22 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/common/redux/global/GlobalReducer.kt
> +                val generalUserWalletsListManager = store.getFromDagger(DaggerGraphState::generalUserWalletsListManager)
Немного не понял идею. Это сделано для того, чтобы можно было закрыть фича тогглом.
При включенном тоггле мы всего лишь один раз в TapApplication устанавливаем версию из даггера. Это помогает не рефачить код во многих местах. После внедрения данного рефакторинга мы избавимся от данного экшена.

2024-02-20 13:24 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/GeneralUserWalletsListManager.kt
> +        }
Отличная замечание, спасибо

2024-02-20 13:25 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/details/redux/DetailsMiddleware.kt
> +                    preferencesStorage.shouldShowSaveUserWalletScreen = false // TODO: зачем?
Странно, что мы попали на экран Details и ни разу не скрыли боттом щит

2024-02-20 13:34 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/GeneralUserWalletsListManager.kt
> +            }
Стоит убрать `map` делать все и `onEach`. Эти операции достаточно дорого стоят и под капотом создают новый `Flow`.

2024-02-20 13:34 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/GeneralUserWalletsListManager.kt
> +            .flowOn(dispatchers.main)
Тут точно main диспатчер нужен?

2024-02-20 13:36 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/GeneralUserWalletsListManager.kt
> +            .flowOn(dispatchers.main)
В целом можно и IO указать. Особо никакой роли не сыграет. ДатаСтор потокобезопасен.

2024-02-20 13:36 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/GeneralUserWalletsListManager.kt
> +            }
Хорошее замечание

2024-02-20 13:38 UTC, iiiburnyiii approved these changes

2024-02-20 13:42 UTC, kozarezvlad approved these changes

2024-02-20 14:14 UTC, merged