AND-6076 Update compose and kotlin versions
tangem/tangem-app-android-old pull request #2296
Opened 2024-02-19 10:53 UTC by iMaks99

2024-02-19 10:53 UTC, kozarezvlad commented
Вливаем после отведения 5.7

2024-02-19 10:59 UTC, Yoggam1 requested changes
А нам во всех модулях нужен BuildConfig? Давай включить его только в тех модулях, где это нужно. Это оптимизирует билд

2024-02-19 13:40 UTC, iMaks99 commented
Это не зависимость на BuildGradle, а включение опции в целом. Его требует build сборки на уровне module-level

2024-02-19 16:24 UTC, Yoggam1 approved these changes, later dismissed

2024-02-19 16:39 UTC, Yoggam1 approved these changes

2024-02-19 16:40 UTC, MasterBin approved these changes

2024-02-19 16:44 UTC, kozarezvlad requested changes
чтобы случайно не влить пока

2024-02-20 13:27 UTC, kozarezvlad approved these changes

2024-02-20 13:28 UTC, merged