AND-6138 [Send screen] Added 'read more' link
tangem/tangem-app-android-old pull request #2304
Opened 2024-02-20 08:11 UTC by iMaks99

2024-02-20 09:54 UTC, MasterBin requested changes

2024-02-20 09:54 UTC, MasterBin commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/ui/fee/SendSpeedSelector.kt
> +    }
В `remember` обернуть бы

2024-02-20 09:54 UTC, MasterBin commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        val locale = if (Locale.getDefault().language == "ru") RU_LOCALE else EN_LOCALE
В `if` тоже бы `RU_LOCALE` использовать

2024-02-20 15:56 UTC, MasterBin approved these changes

2024-02-21 09:05 UTC, Mama1emon approved these changes

2024-02-21 09:06 UTC, merged