AND-6112 Fixed focus.
tangem/tangem-app-android-old pull request #2324
Opened 2024-02-22 15:35 UTC by Sateetas

2024-02-26 08:11 UTC, MasterBin requested changes

2024-02-26 08:11 UTC, MasterBin commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/ui/AutosizeTextField.kt
> +            }
Не думаю, что поместить эту логику в компонент с названием ..TextField - хорошая идея 
Даже учитывая то, что этот компонент используется только в одном месте

Лучше вынести focusRequester в параметр

2024-02-28 13:20 UTC, Sateetas commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/ui/AutosizeTextField.kt
> +            }
ага, вынес каскадно до уровня экрана

2024-02-28 17:55 UTC, MasterBin commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/ui/AutosizeTextField.kt
> +            }
Я имел в виду, LaunchedEffect должен быть на уровне, где используется компонент

2024-03-01 09:31 UTC, Yoggam1 approved these changes

2024-03-01 10:02 UTC, MasterBin approved these changes

2024-03-01 10:02 UTC, merged