AND-5958 Add swap notifications
tangem/tangem-app-android-old pull request #2340
Opened 2024-02-27 20:16 UTC by Sateetas

2024-02-28 08:28 UTC, Mama1emon commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/models/SwapStateHolder.kt
> +    val ignoreAmountReduce: Boolean,
Нейминг немного непонятный, из-за глагола. Что такое amout reduce?

2024-02-28 11:10 UTC, Sateetas commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/models/SwapStateHolder.kt
> +    val ignoreAmountReduce: Boolean,
игнорируем возможность срезать 0.01 xtz, чтобы комиссия чуть поменьше была (если игнорируем, становится больше)

2024-02-29 10:49 UTC, iiiburnyiii commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/models/SwapStateHolder.kt
> +    val ignoreAmountReduce: Boolean,
Надо бы доку добавить

2024-02-29 10:49 UTC, iiiburnyiii commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/viewmodels/SwapViewModel.kt
> +        private val TEZOS_FEE_THRESHOLD = BigDecimal("0.01")
nit: Что-бы не указывать модификатор видимости для всех констант, можно просто компаньон приватным сделать

2024-02-29 10:49 UTC, iiiburnyiii commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/models/UiActions.kt
> +    val onAmountReduceIgnoreClick: () -> Unit,
`onIngoreAmountReduceClick`?

2024-02-29 16:11 UTC, Sateetas commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/models/UiActions.kt
> +    val onAmountReduceIgnoreClick: () -> Unit,
переименовал везде в `ReduceAmount`/`ReduceAmountIgnore`

2024-03-01 18:05 UTC, kozarezvlad commented on features/swap/presentation/build.gradle.kts
> +    implementation(deps.tangem.blockchain)
договаривались в presentation не тащить blockchain зависимость

2024-03-01 18:08 UTC, kozarezvlad commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/ui/StateBuilder.kt
> +        val isTezos = quoteModel.fromTokenInfo.cryptoCurrencyStatus.currency.network.id.value == Blockchain.Tezos.id
вот по этой причине чтобы не держать Blockchain в presentation и костыли тут не делать, добавлял manageWarnings в интерактор. Это уведомление тоже стоит перенести вместе с проверкой введенной суммы туда же, а тут можно оставить только внешнее условие ignoreAmountReduce

2024-03-01 18:09 UTC, kozarezvlad requested changes
стоит перенести в интерактор к другим блокчейн зависимым ворнингам

2024-03-05 12:21 UTC, Sateetas commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/ui/StateBuilder.kt
> +        val isTezos = quoteModel.fromTokenInfo.cryptoCurrencyStatus.currency.network.id.value == Blockchain.Tezos.id
вынес

2024-03-05 14:25 UTC, kozarezvlad commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/viewmodels/SwapViewModel.kt
> +                value = balance.value - TEZOS_FEE_THRESHOLD,
TEZOS_FEE_THRESHOLD же есть в самом ворнинге, кажется лучше оттуда прокинуть, а то одну константу размазываем

2024-03-06 10:36 UTC, kozarezvlad approved these changes, later dismissed

2024-03-06 14:11 UTC, Sateetas commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/viewmodels/SwapViewModel.kt
> +                value = balance.value - TEZOS_FEE_THRESHOLD,
удалил + поправил ресурсы + потер лишний метод

2024-03-07 15:42 UTC, kozarezvlad submitted a review, later dismissed

2024-03-11 18:54 UTC, iiiburnyiii approved these changes

2024-03-12 10:51 UTC, kozarezvlad approved these changes

2024-03-12 10:51 UTC, merged