AND-6217 Added the first ui test
tangem/tangem-app-android-old pull request #2362
Opened 2024-03-04 02:32 UTC by tnagmetulla

ui testing stuff and the first ui test

2024-03-04 02:36 UTC, tnagmetulla commented
https://github.com/tangem/tangem-app-android/assets/35967117/ef2fffdb-dfaf-4db6-b304-c9ccc157adb1

2024-03-04 08:36 UTC, Yoggam1 requested changes
Давайте добавим экзекюшен этих тестов в пайплайн? А то сейчас чекаются только юнит тесты в тестах

2024-03-04 09:37 UTC, tnagmetulla commented
> Давайте добавим экзекюшен этих тестов в пайплайн? А то сейчас чекаются только юнит тесты в тестах

да, сразу сделать не получилось, надо поизучать мне где у нас сборки собираются и есть ли там эмуляторы и тд), создал отдельную задачку под это https://tangem.atlassian.net/browse/AND-6279

2024-03-05 09:49 UTC, kozarezvlad commented
> Давайте добавим экзекюшен этих тестов в пайплайн? А то сейчас чекаются только юнит тесты в тестах

Давай пока не будем на сборку тянуть, чтобы пока не замедлять. Попозже сделаем отдельные ночные билды гоняться

2024-03-05 09:50 UTC, kozarezvlad approved these changes

2024-03-06 07:57 UTC, Yoggam1 approved these changes

2024-03-06 08:30 UTC, merged