AND-6287 Added firebase push notifications
tangem/tangem-app-android-old pull request #2400
Opened 2024-03-11 14:56 UTC by iMaks99

2024-03-11 16:55 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/TangemMessagingService.kt
> +internal class TangemMessagingService : FirebaseMessagingService() {
мб переименовать как-то чтобы `push` было в названии?

например `TangemPushService` или `TangemPushNotificationService`

мне кажется, так немножко проще будет при поиске по проекту, пуши они везде пуши, а messaging более абстрактная штука

2024-03-12 02:08 UTC, Mama1emon requested changes

2024-03-12 02:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/TangemMessagingService.kt
> +    companion object {
nit: можно заюзать один общий модификатор приват. Все равно паблик статики не предполагаются

2024-03-12 02:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/TangemMessagingService.kt
> +        private const val TANGEM_CHANNEL_ID = "Tangem"
Предлагаю channel id назвать информативно – что именно это за сервис. Через настройки пушей вроде можно пробить это. И тогда возникают вопросы, что именно за нотификации это

2024-03-12 02:08 UTC, Mama1emon commented on core/notifications/build.gradle.kts
> +plugins {
1) Зачем модуль, если в нем нет файлов?
2) Почему новый модуль не добавлен в settings?

2024-03-12 02:08 UTC, Mama1emon commented on core/notifications/build.gradle.kts
> +plugins {
Хорошо бы сюда файл из аппки перенсти

2024-03-13 08:42 UTC, iMaks99 commented on core/notifications/build.gradle.kts
> +plugins {
случайно попал, да собирался как раз вынести из аппки

2024-03-13 14:58 UTC, iMaks99 commented on core/notifications/build.gradle.kts
> +plugins {
Пока не буду выносить. Чтобы вынести нужно сперва разобраться с диплинками и навигацией в рамках отдельной задачи

2024-03-14 02:26 UTC, Mama1emon commented on core/notifications/build.gradle.kts
> +plugins {
Закинь задачку плиз в беклог с тудушкой, чтобы не потерялось

2024-03-14 02:27 UTC, Mama1emon approved these changes, later dismissed

2024-03-19 08:54 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/pushes/TangemPushNotificationService.kt
> +        Timber.d("FCM: $token")
Предлагаю чуть более развернутое сообщение сделать, сейчас просто как тег выглядит. Что-то типа: `New FCM token received: $token`

2024-06-10 16:12 UTC, MasterBin approved these changes

2024-06-10 17:55 UTC, kozarezvlad approved these changes

2024-06-10 18:13 UTC, Sateetas approved these changes

2024-06-11 09:56 UTC, merged