AND-6208 [Wallet] Made "Details" screen unavailable for locked wallets
tangem/tangem-app-android-old pull request #2405
Opened 2024-03-12 15:36 UTC by iiiburnyiii

2024-03-12 15:48 UTC, iMaks99 approved these changes

2024-03-12 16:12 UTC, MasterBin approved these changes

2024-03-13 02:14 UTC, Mama1emon requested changes

2024-03-13 02:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/model/holder/LockedWalletStateHolder.kt
> +    override val bottomSheetConfig: TangemBottomSheetConfig?,
В состоянии заблокировано всегда же будет боттом щит. Мб тогда сделать not null?

2024-03-13 02:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/transformers/CloseBottomSheetTransformer.kt
> +            is WalletState.MultiCurrency.Content -> prevState.copy(
По текущей логике любой `WalletState` – это `WalletStateHolder`. А любой `WalletStateHolder` имеет поле bottomSheet. Получается можно не расписывать when со всеми ветками

2024-03-13 02:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/transformers/InitializeWalletsTransformer.kt
> +            onDetailsClick = clickIntents::onDetailsClick,
А зачем эту логику выносить отсюда в клик интент?
Каждый трансформер выполняется для конкретного кошелька. Стейт заблокированного кошелька заранее четко определен. Зачем нам теперь дополнительно запускать корутину, которая будет выяснять, что это за кошелек? Если мы при формировании стейта и так это знаем

2024-03-13 09:23 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/model/holder/LockedWalletStateHolder.kt
> +    override val bottomSheetConfig: TangemBottomSheetConfig?,
Он не всегда будет, а будет только при клике на точечки в топ баре и на ворнинг

2024-03-13 09:25 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/transformers/CloseBottomSheetTransformer.kt
> +            is WalletState.MultiCurrency.Content -> prevState.copy(
Тут он для `copy` расписан. Нужно либо пилить `copySealed`, либо так.

2024-03-14 02:25 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/model/holder/LockedWalletStateHolder.kt
> +    override val bottomSheetConfig: TangemBottomSheetConfig?,
Смысл нулабилити был в том, чтобы в разблокированном состоянии мы явно могли указать, что сейчас никакого боттом щита быть не может (так как приходится выбирать среди нескольких в зависимости от ситуации). А в заблокированном состоянии у нас может быть только один боттом щит и он изначально уже определен.

2024-03-14 16:43 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/transformers/InitializeWalletsTransformer.kt
> +            onDetailsClick = clickIntents::onDetailsClick,
Тут intent выставляется в зависимости от кошелька который был выбран в момент открытия экрана. Т.е. если юзер вошел по скану карты, а потом переключился на залоченный кошелёк, то этот трансформер не вызовется и юзер сможет перейти в деталку.

2024-03-14 16:48 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/model/holder/LockedWalletStateHolder.kt
> +    override val bottomSheetConfig: TangemBottomSheetConfig?,
Сейчас эта логика в целом немного странно для меня выглядит - у нас есть 2 состояния, которые говорят об одном и том же (отсутсвие BS), это `null` и `TangemBottomSheetConfig(isShown = false)`. Не хочется вносить дополнительную путанницу и делать поведение этого поля в разных стейтах различным.

2024-03-15 07:52 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/model/holder/LockedWalletStateHolder.kt
> +    override val bottomSheetConfig: TangemBottomSheetConfig?,
Во-первых, `null` и `TangemBottomSheetConfig(isShown = false)` имеют разную ответственность. Если поле `null`, то значит у стейта на данный момент не предполагается никакого боттом щита, а если боттом щит предполагается, но он не должен быть виден, то ставим `false`. Этот механизм нужен для того, чтобы стейт с несколькими боттом щитами мог правильно работать.

Во-вторых, мы говорим немного про разные вещи. Если есть нужда сделать поле not null, то это можно сделать непосредственно при переопределении поля в стейте заблокированного кошелька. Я же говорю в целом про организацию стейта. При его формировании изначально известно, что это за кошелек. И мы изначально знаем, что делать, когда пользователь нажмет на три точки. Так зачем нам эту логику выносить в отдельный коллбек, в котором мы будем дополнительно узнавать, что сейчас за кошелек, чтобы потом сказать какое поведение нам нужно. Это подобно полю `onBackClick`. Если я заранее знаю, что это поле однозначно, то я его сразу и инициализирую.

2024-03-15 07:55 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/state/transformers/InitializeWalletsTransformer.kt
> +            onDetailsClick = clickIntents::onDetailsClick,
Не понимаю, почему "этот трансформер не вызовется"?
Это трансформер вызывается всегда при старте экрана воллета. Он смотрит на все кошельки и формирует из них стейты. НЕ ТОЛЬКО ТЕКУЩЕГО кошелька, а ВСЕ.

2024-03-15 11:44 UTC, Mama1emon approved these changes

2024-03-15 11:46 UTC, merged