AND-6556 [Polkadot] Implemented wallet address check and analytics sending
tangem/tangem-app-android-old pull request #2462
Opened 2024-03-25 08:56 UTC by iMaks99

- [ ] https://github.com/tangem/blockchain-sdk-kotlin/pull/533

2024-03-25 09:10 UTC, Yoggam1 requested changes

2024-03-25 09:10 UTC, Yoggam1 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +    override fun subscribeToHasImmortalResults() = hasImmortalTransaction
`hasImmortalTransaction.asSharedFlow()`

2024-03-25 09:10 UTC, Yoggam1 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +    override fun subscribeToHasResetResults() = hasResetTransaction
`hasResetTransaction.asSharedFlow`

2024-03-25 13:57 UTC, Yoggam1 approved these changes

2024-03-25 13:59 UTC, Sateetas commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +            val accountCheckProvider = walletManager as? AccountCheckProvider ?: return
можно логирование добавить на такие штуки, в планах сделать отправку прерываний сценария вида `val a = xxx as? YYY ?: return` в крашлитикс

2024-03-25 15:43 UTC, kozarezvlad commented
Давай тут сделаем отдельную ветку hotfix/5.8.1

2024-03-25 16:33 UTC, kozarezvlad commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +            val walletManager = walletManagersFacade.getOrCreateWalletManager(userWalletId, network)
тут бы проверку, чтобы только 1 раз за весь рантайм запускать, т.к. метод fetchNetworkStatus вызывается несколько раз и каждый раз триггернем тут вызов

2024-03-25 16:34 UTC, kozarezvlad commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultNetworksRepository.kt
> +        if (Blockchain.fromId(network.id.value) == Blockchain.Polkadot) {
может вынести запуск этого выше на уровень юз кейса где стартует первый апдейт? чтобы не делать зависимость репозиторий на репозиторий, как будто смешиваем ответственности

2024-03-26 06:27 UTC, iMaks99 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultNetworksRepository.kt
> +        if (Blockchain.fromId(network.id.value) == Blockchain.Polkadot) {
С одной стороны да, можно вынести в CurrenciesStatusesOperations, но это затронет много других юз кейсов, которым не нужно знать об этом. И сейчас выглядит так, что проще и понятнее будет тут оставить. Как вариант можно вынести вызов во вью модель, где вызывается юз кейс

2024-03-26 06:56 UTC, iMaks99 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultNetworksRepository.kt
> +        if (Blockchain.fromId(network.id.value) == Blockchain.Polkadot) {
Вынести запуск в юз кейс нужный не получится, там flow без suspend вызова, запустить в фоне и не остановить данные для ui не получится. В CurrenciesStatusesOperations вынести тоже не вариант, он затронет много юз кейсов, которым не нужно знать об этом репозитории. Тут либо во вью модель вынести или в оставить в репозитории.

2024-03-26 08:43 UTC, iMaks99 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +            val walletManager = walletManagersFacade.getOrCreateWalletManager(userWalletId, network)
Если проверка идет, вызовы не остановят и не запустят новые, методы проверки внутри mutex. Если проверка завершилась и у нас есть результат, то у нас есть проверка ниже на каждый из кейсов

2024-03-26 08:49 UTC, iMaks99 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultNetworksRepository.kt
> +        if (Blockchain.fromId(network.id.value) == Blockchain.Polkadot) {
Вынес во вью модель

2024-03-26 09:14 UTC, kozarezvlad approved these changes

2024-03-26 09:14 UTC, merged