AND-6480 Unlock token action buttons
tangem/tangem-app-android-old pull request #2488
Opened 2024-03-29 00:37 UTC by Sateetas

2024-03-29 09:00 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="onboarding_seed_generate_message">Запишите эти 12 слов в порядке, указанном ниже, и сохраните их в надежном месте.</string>
это нужно удалить, лишнее после добавления сида из разного количества слов

2024-03-29 09:01 UTC, iMaks99 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCryptoCurrencyActionsUseCase.kt
> +                ScenarioUnavailabilityReason.PendingTransaction(coinStatus?.currency?.symbol ?: "")
nit: orEmpty

2024-03-29 09:02 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="token_button_unavailability_reason_buy_unavailable">Покупка %s не доступна. Но мы работаем над его добавлением.</string>
в данном контексте "не доступна" нужно слитно

2024-03-29 09:04 UTC, iMaks99 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +            // this!
Что значит коммент?)

2024-03-29 09:04 UTC, kozarezvlad commented on core/res/src/main/res/values/strings.xml
> +  <string name="onboarding_seed_generate_message">Write these 12 words down in the order given below and store them in a safe and secret place.</string>
также удалил с локалайза

2024-03-29 15:03 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCryptoCurrencyActionsUseCase.kt
> +                actionsList.add(TokenActionsState.ActionState.Swap(ScenarioUnavailabilityReason.None))
ScenarioUnavailabilityReason.None - предполагает что недоступен? По логике же тут доступен должен быть

2024-03-29 15:03 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCryptoCurrencyActionsUseCase.kt
> +                        unavailabilityReason = ScenarioUnavailabilityReason.SellUnavailable(cryptoCurrency.name),
Почему SellUnavailable если проверка по свопу?

2024-03-29 15:10 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCryptoCurrencyActionsUseCase.kt
> +                actionsList.add(TokenActionsState.ActionState.Swap(ScenarioUnavailabilityReason.None))
мб вместо None сделать Available, как по мне понятнее

2024-03-29 22:57 UTC, Sateetas commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="onboarding_seed_generate_message">Запишите эти 12 слов в порядке, указанном ниже, и сохраните их в надежном месте.</string>
обновил текстовки

2024-03-29 22:57 UTC, Sateetas commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="token_button_unavailability_reason_buy_unavailable">Покупка %s не доступна. Но мы работаем над его добавлением.</string>
обновил текстовки

2024-03-29 22:58 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/viewmodels/TokenDetailsViewModel.kt
> +            // this!
сделал временный bookmark руками, а не функционалом студии)
удалил

2024-03-29 22:58 UTC, Sateetas commented on core/res/src/main/res/values/strings.xml
> +  <string name="onboarding_seed_generate_message">Write these 12 words down in the order given below and store them in a safe and secret place.</string>
обновил текстовки

2024-03-29 22:58 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCryptoCurrencyActionsUseCase.kt
> +                        unavailabilityReason = ScenarioUnavailabilityReason.SellUnavailable(cryptoCurrency.name),
глаз-алмаз! 
поправил

2024-03-29 23:08 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCryptoCurrencyActionsUseCase.kt
> +                actionsList.add(TokenActionsState.ActionState.Swap(ScenarioUnavailabilityReason.None))
мне кажется наоборот, `Available` по смыслу не может являться причиной недоступности сценария

2024-04-02 10:13 UTC, iMaks99 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsStateFactory.kt
> +    private fun getUnavailabilityReasonText(unavailabilityReason: ScenarioUnavailabilityReason): TextReference {
nit: Можно вынести в отдельный файл, чтобы проще было ориентироваться

2024-04-02 10:15 UTC, iMaks99 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/viewmodels/intents/WalletCurrencyActionsClickIntents.kt
> +    private fun getUnavailabilityReasonText(unavailabilityReason: ScenarioUnavailabilityReason): TextReference {
nit: Тоже можно вынести, потенцианльно в будущем в один и тот же файл, что и выше. Чтобы не менять и там, и тут

2024-04-02 18:59 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsStateFactory.kt
> +    private fun getUnavailabilityReasonText(unavailabilityReason: ScenarioUnavailabilityReason): TextReference {
а у нас есть какой-то общедоступный модуль для презентейшн сенда и свапа?

думал над этим, в общую кучу совсем не хочется тащить, и создавать отдельный модуль на такую вещь тоже не хочется

2024-04-03 09:37 UTC, iMaks99 requested changes
Есть изменение логики доступности кнопки Send https://github.com/tangem/tangem-app-android/pull/2507

2024-04-03 14:25 UTC, iMaks99 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsStateFactory.kt
> +    private fun getUnavailabilityReasonText(unavailabilityReason: ScenarioUnavailabilityReason): TextReference {
есть модуль транзакций, но не думаю что здесь это будет уместно. Мб можно в ui слой, как common компонент

2024-04-03 15:44 UTC, Sateetas commented
> Есть изменение логики доступности кнопки Send #2507

поправил

2024-04-08 09:04 UTC, Sateetas commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsStateFactory.kt
> +    private fun getUnavailabilityReasonText(unavailabilityReason: ScenarioUnavailabilityReason): TextReference {
ты предлагаешь в ui core вынести?

2024-04-09 10:16 UTC, iMaks99 approved these changes

2024-04-12 09:18 UTC, iMaks99 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/state/factory/TokenDetailsStateFactory.kt
> +    private fun getUnavailabilityReasonText(unavailabilityReason: ScenarioUnavailabilityReason): TextReference {
давай сейчас как есть, потом посмотрим

2024-04-12 09:35 UTC, kozarezvlad approved these changes

2024-04-12 09:35 UTC, merged