Hotfix/5.8.1
tangem/tangem-app-android-old pull request #2504
Opened 2024-04-02 18:06 UTC by kozarezvlad

2024-04-03 01:51 UTC, Mama1emon requested changes

2024-04-03 01:51 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +            getPolkadotCheckHasResetUseCase()
1) Могут ли тут быть заэмичены сразу несколько значений? Будет ли нам нужно на каждое значение писать в аналитику или достаточно только последнее?
2) Если будут заэмичены два одинаковых значения, то надо ли каждое писать в аналитику?

2024-04-03 01:51 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/preferences/PreferencesKeys.kt
> +    }
Предлагаю использовать такой же формат нейминга, как и другие ключи. НАЗВАНИЕ_KEY

2024-04-03 01:51 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +            val accountCheckProvider = requireNotNull(walletManager as AccountCheckProvider) {
requireNotNull не отработает. Быстрее CastException упадет

2024-04-03 01:51 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +        mutex.withLock {
Я так понял это защита от гонки. Но есть ли нам вообще смысл ждать когда закончится выполнение старых значений, если у нас уже пришли с новыми?

2024-04-03 01:51 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +                    }
nit: Хорошо бы в отдульную функцию вынести, а то читается тяжеловато с такой вложенностью

2024-04-03 01:51 UTC, Mama1emon commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +    }
Функции идентичны, за исключением названий ключей. Мб сделать общую функцию просто?

2024-04-03 01:51 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/subscribers/BasicTokenListSubscriber.kt
> +                runPolkadotAccountHealthCheckUseCase(userWallet.walletId, it.currency.network)
Получается по текущей реализации: получение данных по каждой карренси будет идти в одном потоке из-за мьютекса в репозиториий??

2024-04-03 01:53 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/subscribers/BasicTokenListSubscriber.kt
> +                runPolkadotAccountHealthCheckUseCase(userWallet.walletId, it.currency.network)
А если это вообще не полкадот? То мы все равно начинаем делать какую-то работу?

2024-04-03 05:44 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +            getPolkadotCheckHasResetUseCase()
Сразу два заэмичено не может, в момент времени работает только одна обработка

2024-04-03 05:46 UTC, iMaks99 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +        mutex.withLock {
Это защита от вызова не только от новых данных, но и повторного вызова для одного и того же кошелька

2024-04-03 05:48 UTC, iMaks99 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/subscribers/BasicTokenListSubscriber.kt
> +                runPolkadotAccountHealthCheckUseCase(userWallet.walletId, it.currency.network)
В самом репозитории есть проверка на блокчейн, который проверяем

2024-04-03 06:29 UTC, iMaks99 commented on data/tokens/src/main/kotlin/com/tangem/data/tokens/repository/DefaultPolkadotAccountHealthCheckRepository.kt
> +    }
Да, не заметил, глаз замылился

2024-04-03 06:36 UTC, iMaks99 commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/wallet/subscribers/BasicTokenListSubscriber.kt
> +                runPolkadotAccountHealthCheckUseCase(userWallet.walletId, it.currency.network)
Проверка на Polkadot блокчейн находится вне мьютекса

2024-04-04 09:37 UTC, Mama1emon approved these changes

2024-04-04 10:12 UTC, iMaks99 approved these changes

2024-04-04 10:40 UTC, merged