AND-6849 Fixed the animation of the screens  transition, the progress…
tangem/tangem-app-android-old pull request #2590
Opened 2024-04-19 07:28 UTC by MasterBin

… bar of the recipient's field icon, and delays in processing quick text changes in fields.

2024-04-19 08:55 UTC, Yoggam1 submitted a review, later dismissed

2024-04-19 09:52 UTC, iMaks99 requested changes
пока не заливать

2024-04-24 00:48 UTC, Mama1emon commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
Почему проставление диспатчера убрал?

2024-04-24 08:18 UTC, MasterBin commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
Филд адреса не обновляется нормально при вводе тескта, если откладывать таску

2024-04-24 08:20 UTC, MasterBin commented
Много чего поменял, посмотрите плз

2024-04-24 08:37 UTC, iMaks99 approved these changes

2024-04-24 08:40 UTC, Mama1emon commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
Не понимаю, как явное проставление диспатчера аффектит

2024-04-24 08:50 UTC, MasterBin commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
`Dispatchers.Main` - это почти что просто `Handler.post`, а `viewModelScope` работает на `Dispatchers.Main.immediate`.
Если корутина запущена на мейнтреде и с диспатчером `Dispatchers.Main.immediate`, то код в корутине выполнится синхронно, без возможных задержек. 
А когда мы используем `Dispatchers.Main`, то мы кидаем `Message` в `Handler` мейн треда, и она выполнится в порядке очереди

2024-04-24 08:53 UTC, Mama1emon commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
Тогда стоит заюзать `CoroutineDispatcherProvider.mainImmediate`

2024-04-24 08:59 UTC, MasterBin commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
Почему?

2024-04-24 09:02 UTC, Mama1emon commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
Потому что он позволит реализовать необходимую логику без ухудшения тестируемости кода.

Я в целом не блочу ПР, если нужно вливайте, это не крит

2024-04-24 09:04 UTC, MasterBin commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
Для тестов есть `Dispatchers.setMain()`

2024-04-24 09:19 UTC, Mama1emon commented on features/send/impl/src/main/java/com/tangem/features/send/impl/presentation/viewmodel/SendViewModel.kt
> +        viewModelScope.launch {
Интересно. Не знал, что можно делать подмену захордкоженных диспатчеров

2024-04-24 10:17 UTC, kozarezvlad approved these changes

2024-04-24 10:17 UTC, merged