AND-6811 [Accounts] Implemented new REST API methods
tangem/tangem-app-android-old pull request #2610
Opened 2024-04-23 14:21 UTC by iiiburnyiii

2024-04-23 19:00 UTC, Yoggam1 approved these changes, later dismissed

2024-04-24 08:42 UTC, Mama1emon requested changes

2024-04-24 08:42 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +        return provideTangemTechApiInternal(moshi, context, appVersionProvider, PROD_TANGEM_TECH_BASE_URL)
Нельзя убирать таймаут здесь

2024-04-24 08:42 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +        const val PROD_V2_TANGEM_TECH_BASE_URL = "https://api.tangem-tech.com/v2/"
Не помешало бы фабрику сделать

2024-04-24 08:43 UTC, kozarezvlad commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/TangemTechApi.kt
> +    @PUT("account/{account_id}/archive")
а это не на v2 будет лежать?

2024-04-24 08:48 UTC, kozarezvlad commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +        return provideTangemTechApiInternal(moshi, context, appVersionProvider, PROD_TANGEM_TECH_BASE_URL)
Добавлю почему. Этот сервис блокирует главный поток на время своей работы, в связи решением по реализации настроек порядка апи сетей. 
Решено было сделать таймаут 5 сек, это максимальное время на которое готовы блочить запуск аппа, если за это время не загрузился конфиг, берем локальный.
В целевом виде конечно лучше сделать нормальный splash и управлять таймаутом руками, дропать запрос если прошло больше 5 сек, а не на уровне дата слоя

2024-04-24 09:04 UTC, iiiburnyiii commented on core/datasource/src/main/java/com/tangem/datasource/api/tangemTech/TangemTechApi.kt
> +    @PUT("account/{account_id}/archive")
В v2 только новые методы для токенов https://www.notion.so/tangem/API-5e8e6e4170bc4a929d3598b0c357f0b0?pvs=4

2024-04-24 09:43 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkModule.kt
> +        return provideTangemTechApiInternal(moshi, context, appVersionProvider, PROD_TANGEM_TECH_BASE_URL)
У нас уже нормальный сплеш))
Ну вообще можно попробовать реализовать на стороне вью модели

2024-04-24 13:52 UTC, Yoggam1 submitted a review, later dismissed

2024-04-25 09:16 UTC, kozarezvlad submitted a review, later dismissed

2024-04-25 09:27 UTC, Mama1emon approved these changes, later dismissed

2024-04-25 10:03 UTC, Mama1emon approved these changes

2024-04-25 10:04 UTC, Yoggam1 approved these changes

2024-04-25 15:01 UTC, merged