AND-6860 Token button fixes
tangem/tangem-app-android-old pull request #2611
Opened 2024-04-23 15:16 UTC by Sateetas

2024-04-23 19:43 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="rate_app_sheet_positive_response_button_title">Оцените приложение 🙌</string>
то что с rate не нужно, мы не будем это делать

2024-04-23 19:44 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="story_learn_description">Пройдите 3 урока, получите скидку на покупку Tangem Wallet и 1INCH токены</string>
это давно же снесли уже. Случайно что не то подтянулось с локалайза?

2024-04-23 19:44 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="swapping_permit_and_swap">Разрешить и обменять</string>
это кажется тоже сносили раньше

2024-04-23 19:45 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="voice_over_close_network_fee_settings">Закрыть настройки комиссии</string>
не иосные строки?

2024-04-23 19:45 UTC, kozarezvlad requested changes
Чекнуть выгрузку строк

2024-04-23 19:53 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="manage_tokens_number_of_wallets_ios">%d из %#@total_wallets@</string>
да, выгрузились ios specific

2024-04-23 20:55 UTC, Sateetas commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="manage_tokens_number_of_wallets_ios">%d из %#@total_wallets@</string>
да, лишние залетели, перезалил
давай в ближней перспективе возьму автоматизацию этого процесса

2024-04-24 08:37 UTC, kozarezvlad approved these changes

2024-04-24 10:17 UTC, MasterBin approved these changes

2024-04-25 09:16 UTC, Yoggam1 approved these changes

2024-04-25 09:35 UTC, merged