AND-6951 Updated strings and replaced blockchain coin symbol with network name.
tangem/tangem-app-android-old pull request #2645
Opened 2024-04-27 15:44 UTC by Sateetas

2024-05-02 05:00 UTC, iMaks99 submitted a review, later dismissed

2024-05-02 07:30 UTC, Yoggam1 submitted a review, later dismissed

2024-05-02 08:18 UTC, kozarezvlad requested changes
а это есть уже в 5.9, может лучше мерж в дев сделать?

2024-05-02 12:18 UTC, Sateetas commented
> а это есть уже в 5.9, может лучше мерж в дев сделать?

этой функциональности (с buttons unavailability reason) нет в 5.9

2024-05-03 08:58 UTC, kozarezvlad commented
> > а это есть уже в 5.9, может лучше мерж в дев сделать?
> 
> этой функциональности (с buttons unavailability reason) нет в 5.9

Я про то, что проще правильно помержить будет

2024-05-06 11:15 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="send_satoshi_per_byte_title">Сатоши / вбайт</string>
а что такое вбайт? не опечатка?

2024-05-06 11:16 UTC, kozarezvlad commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCurrencyWarningsUseCase.kt
> -                        if (currenciesRepository.hasPendingTransactions(tokenStatus, coinStatus)) {
а почему это убралось?

2024-05-06 11:19 UTC, Yoggam1 approved these changes

2024-05-06 11:26 UTC, Sateetas commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="send_satoshi_per_byte_title">Сатоши / вбайт</string>
нет
https://en.bitcoin.it/wiki/Satoshi_per_byte

2024-05-06 11:27 UTC, Sateetas commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCurrencyWarningsUseCase.kt
> -                        if (currenciesRepository.hasPendingTransactions(tokenStatus, coinStatus)) {
разгрузили нотификации, оставили информацию об этом при нажатии на кнопку сенда

2024-05-06 11:28 UTC, kozarezvlad commented on core/res/src/main/res/values-ru/strings.xml
> +  <string name="send_satoshi_per_byte_title">Сатоши / вбайт</string>
на англ ок, на русском странно выглядит

2024-05-06 11:28 UTC, kozarezvlad approved these changes

2024-05-06 14:37 UTC, merged