AND-7087 Add a new Snacbar's design
tangem/tangem-app-android-old pull request #2702
Opened 2024-05-16 08:28 UTC by Mama1emon

2024-05-16 09:20 UTC, iMaks99 approved these changes

2024-05-16 10:55 UTC, MasterBin requested changes

2024-05-16 10:55 UTC, MasterBin commented on core/ui/src/main/java/com/tangem/core/ui/components/snackbar/CopiedTextSnackbar.kt
> +            .background(color = TangemTheme.colors.icon.secondary, shape = TangemTheme.shapes.roundedCorners8)
А бек разве не должен быть прозрачным?

2024-05-16 12:01 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/snackbar/CopiedTextSnackbar.kt
> +            .background(color = TangemTheme.colors.icon.secondary, shape = TangemTheme.shapes.roundedCorners8)
Нет. [Ссылка](https://www.figma.com/design/14ISV23YB1yVW1uNVwqrKv/Android?node-id=2001-728&t=kDzSZDx0m0sk4iYz-4) на компонент

2024-05-17 08:00 UTC, MasterBin approved these changes

2024-05-17 08:20 UTC, merged