Merge/5.10 pre release to develop
tangem/tangem-app-android-old pull request #2709
Opened 2024-05-16 13:05 UTC by MasterBin

2024-05-16 13:13 UTC, iMaks99 approved these changes

2024-05-16 13:48 UTC, iiiburnyiii approved these changes

2024-05-16 14:11 UTC, kozarezvlad requested changes
Лучше отвести мерж ветку от релиза и не будет лишних конфликтов и проблем

2024-05-17 07:05 UTC, kozarezvlad approved these changes

2024-05-17 07:06 UTC, merged