AND-7165 [Details] Implemented screen logic
tangem/tangem-app-android-old pull request #2782
Opened 2024-05-31 11:04 UTC by iiiburnyiii

2024-06-03 08:18 UTC, iMaks99 approved these changes

2024-06-03 10:48 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultUserWalletListComponent.kt
> +    private val state: MutableStateFlow<UserWalletListUM> = MutableStateFlow(
Лучше будет формировать стейт в Model. В такой реализации получается, что state будет пересоздаваться после смены конфигурации (потому что все компоненты пересоздаются после смены конфигурации), и получится так, что будет промежуток времени, когда стейт не тот

2024-06-03 10:48 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultUserWalletListComponent.kt
> +    private val state: MutableStateFlow<UserWalletListUM> = MutableStateFlow(
Аналогично в DefaultDetailsComponent

2024-06-03 10:52 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +            items = itemsBuffer.buldAll(),
тоже к вопросу о формировании стейта, сейчас получается при пересоздании компонента будет вызываться вот эта тяжелая функция для его формирования

2024-06-03 10:54 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +    private fun initState() = componentScope.launch(dispatchers.io) {
Почему мы используем dispatchers.io? Видел во вьюмодельках, но думал, что это просто легаси. Объясните плз зачем нужен диспатчер и почему IO

2024-06-03 10:59 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +        context = child(key = "wallet_connect"),
Мб переименовать в appChild, например? Можно ошибиться и взять не тот extension кмк

2024-06-03 11:21 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +            messageSender.send(SnackbarMessage(stringReference("DetailsComponent destroyed")))
Нужно?

2024-06-03 12:51 UTC, iiiburnyiii commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +        context = child(key = "wallet_connect"),
Тут не получится ошибится в методе - тип контекста другой

2024-06-03 12:55 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +        context = child(key = "wallet_connect"),
А у ComponentContext метод с другим названием, понял

2024-06-04 16:32 UTC, kozarezvlad approved these changes
Лайк с учетом комментов выше

2024-06-05 08:01 UTC, iiiburnyiii commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +            items = itemsBuffer.buldAll(),
Вынес в model

2024-06-05 08:01 UTC, iiiburnyiii commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultUserWalletListComponent.kt
> +    private val state: MutableStateFlow<UserWalletListUM> = MutableStateFlow(
Тоже вынес

2024-06-05 08:20 UTC, MasterBin requested changes

2024-06-05 08:20 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/model/DetailsModel.kt
> +        walletConnectComponent: WalletConnectComponent,
У компонентов жц активити. Передача компонента в Model = потенциальная утечка памяти.

2024-06-05 08:24 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +        DetailsScreen(
Вот здесь кажется единственное место где можно безопасно вызвать walletConnectComponent.View() и userWalletListComponent.View()

2024-06-06 10:10 UTC, iiiburnyiii commented on features/details/impl/src/main/kotlin/com/tangem/features/details/model/DetailsModel.kt
> +        walletConnectComponent: WalletConnectComponent,
Именно в этом случае утечки бы не было, но согласен, что передача компонента в модель история не очень

2024-06-06 10:15 UTC, MasterBin approved these changes

2024-06-06 10:15 UTC, MasterBin commented on features/details/impl/src/main/kotlin/com/tangem/features/details/component/impl/DefaultDetailsComponent.kt
> +        model.provideUserWalletId(params.selectedUserWalletId)
nit: можно потом сделать механизм передачи аргументов в конструктор

2024-06-06 11:26 UTC, merged