AND-7233 Added staking action
tangem/tangem-app-android-old pull request #2787
Opened 2024-06-03 09:14 UTC by Sateetas

2024-06-04 05:43 UTC, iMaks99 commented on domain/tokens/src/main/kotlin/com/tangem/domain/tokens/GetCryptoCurrencyActionsUseCase.kt
> +        // if ()
Лишнее?

2024-06-04 15:41 UTC, kozarezvlad requested changes
опять ios специфик строки попали

2024-06-04 15:43 UTC, iMaks99 approved these changes

2024-06-04 18:04 UTC, kozarezvlad commented on data/staking/src/main/java/com/tangem/data/staking/DefaultStakingRepository.kt
>      override suspend fun getEntryInfo(integrationId: String): StakingEntryInfo {
Тут надо явно указать withContext(dispatchers.io) т.к. все вызовы репозитория должны быть main safe

2024-06-04 21:21 UTC, Sateetas commented on data/staking/src/main/java/com/tangem/data/staking/DefaultStakingRepository.kt
>      override suspend fun getEntryInfo(integrationId: String): StakingEntryInfo {
указал везде

2024-06-04 21:21 UTC, Sateetas commented
> опять ios специфик строки попали

поправил

2024-06-05 11:51 UTC, kozarezvlad commented on data/staking/src/main/java/com/tangem/data/staking/DefaultStakingRepository.kt
> +        private val integrationIdMap = setOf(
вроде уже не map

2024-06-05 11:56 UTC, kozarezvlad commented on data/staking/src/main/java/com/tangem/data/staking/DefaultStakingRepository.kt
> +    override suspend fun getStakingAvailabilityForActions(currencyId: String, symbol: String): StakingAvailability {
предлагаю тут прокидывать id не стрингу, а объект CurrencyId иначе будет путаница что за id, coin, blockchain, network или тот coin что приходит с бэка. Лазить искать по всему проекту, лучше в одном месте где уже будет явно сравнение с integrationIdMap это распаковать кмк

2024-06-05 12:30 UTC, Sateetas commented on data/staking/src/main/java/com/tangem/data/staking/DefaultStakingRepository.kt
> +        private val integrationIdMap = setOf(
да

2024-06-05 12:35 UTC, Sateetas commented on data/staking/src/main/java/com/tangem/data/staking/DefaultStakingRepository.kt
> +    override suspend fun getStakingAvailabilityForActions(currencyId: String, symbol: String): StakingAvailability {
думал не делать этот модуль андроидным, но в целом соглашусь, что избежать путаницы более приоритетно

поправил

2024-06-05 13:27 UTC, kozarezvlad approved these changes

2024-06-05 15:23 UTC, merged