AND-7392 Added staking balance banner ui
tangem/tangem-app-android-old pull request #2862
Opened 2024-06-20 13:13 UTC by iMaks99

![image](https://github.com/tangem/tangem-app-android/assets/45900939/068c3176-f138-4718-ab1f-d411e1739939)
![image](https://github.com/tangem/tangem-app-android/assets/45900939/0507a3aa-7fe8-4cae-8ed3-6ff578a864e2)

2024-06-20 15:09 UTC, Yoggam1 requested changes

2024-06-20 15:09 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/staking/StakingBalanceBlock.kt
> +                    text = "•",
Может стоит вынести в константы?

2024-06-20 15:09 UTC, Yoggam1 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenDetailsBalanceBlock.kt
> +        initialSelectedItem = state.balanceSegmentedButtonConfig.first { it.type == selectedType },
1. Этот кусок кода может вызвать креш приложения
2. Стоит вынести вов вьюмодель

2024-06-20 15:11 UTC, iMaks99 commented on features/tokendetails/impl/src/main/kotlin/com/tangem/feature/tokendetails/presentation/tokendetails/ui/components/TokenDetailsBalanceBlock.kt
> +        initialSelectedItem = state.balanceSegmentedButtonConfig.first { it.type == selectedType },
Остался с тестов, не заметил

2024-06-20 15:18 UTC, kozarezvlad commented
в превью просто не thin space?

2024-06-20 16:43 UTC, kozarezvlad approved these changes

2024-06-21 11:19 UTC, Yoggam1 approved these changes

2024-06-21 11:19 UTC, merged