AND-7491 Added OKX Promotion
tangem/tangem-app-android-old pull request #2922
Opened 2024-07-03 13:39 UTC by iMaks99

![image](https://github.com/tangem/tangem-app-android/assets/45900939/7b3f473e-4a43-404b-b385-cf1f077ddeb8)
![image](https://github.com/tangem/tangem-app-android/assets/45900939/43ad19af-cf17-4a89-8d4d-8b2a30279c5e)

2024-07-03 14:13 UTC, kozarezvlad approved these changes, later dismissed

2024-07-03 14:18 UTC, MasterBin requested changes

2024-07-03 14:18 UTC, MasterBin commented on core/ui/src/main/java/com/tangem/core/ui/res/TangemColorPalette.kt
> +    val OxkPromo = Color(0xFFBCFF2F)
Не лучшая идея править дизайн систему ради одного промо

2024-07-03 14:30 UTC, iMaks99 commented on core/ui/src/main/java/com/tangem/core/ui/res/TangemColorPalette.kt
> +    val OxkPromo = Color(0xFFBCFF2F)
Дизайн система находится в TangemTheme, здесь набор цветов, лучше места не нашел. Это бренд цвет okx

2024-07-03 14:33 UTC, MasterBin commented on core/ui/src/main/java/com/tangem/core/ui/res/TangemColorPalette.kt
> +    val OxkPromo = Color(0xFFBCFF2F)
`TangemColorPallete` в core модуле, это точно не место для промо. Можно просто рядом с вьюхой положить, даже удобнее удалять будет.

2024-07-03 15:23 UTC, MasterBin commented on core/ui/src/main/java/com/tangem/core/ui/res/TangemColors.kt
> +        var constant by mutableStateOf(constant)
это надо?

2024-07-03 15:24 UTC, iMaks99 commented on core/ui/src/main/java/com/tangem/core/ui/res/TangemColors.kt
> +        var constant by mutableStateOf(constant)
надо

2024-07-03 15:25 UTC, iMaks99 commented on core/ui/src/main/java/com/tangem/core/ui/res/TangemColors.kt
> +        var constant by mutableStateOf(constant)
иначе не достать его)

2024-07-03 15:28 UTC, MasterBin approved these changes, later dismissed

2024-07-03 15:32 UTC, kozarezvlad submitted a review, later dismissed

2024-07-03 15:34 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/notifications/OkxPromoNotification.kt
> +private val OxkPromo = Color(0xFFBCFF2F)
okxPromoColor

2024-07-03 15:34 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/notifications/OkxPromoNotification.kt
> +            Icon(
Анимация нужна?

2024-07-03 15:36 UTC, iMaks99 commented on core/ui/src/main/java/com/tangem/core/ui/components/notifications/OkxPromoNotification.kt
> +            Icon(
Нет, динамически не меняется

2024-07-03 15:36 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/notifications/OkxPromoNotification.kt
> +    button?.let {
Анимация?

2024-07-03 15:39 UTC, iMaks99 commented on core/ui/src/main/java/com/tangem/core/ui/components/notifications/OkxPromoNotification.kt
> +    button?.let {
и снова нет) баннеры динамически не изменяют внешний вид

2024-07-03 16:23 UTC, kozarezvlad approved these changes

2024-07-04 08:37 UTC, Mama1emon approved these changes

2024-07-04 09:03 UTC, merged