AND-7711 Finalize stake flow part 2
tangem/tangem-app-android-old pull request #3037
Opened 2024-07-29 21:11 UTC by Sateetas

2024-07-30 07:30 UTC, iMaks99 commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/StakingStateController.kt
> +            title = TextReference.Str(""),
nit: TextReference.Empty

2024-07-30 07:31 UTC, iMaks99 submitted a review, later dismissed

2024-07-30 07:43 UTC, Mama1emon requested changes

2024-07-30 07:43 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/list/RoundedListWithDividers.kt
> +    rows: List<RoundedListWithDividersItemData>,
`ImmutableList`

2024-07-30 07:43 UTC, Mama1emon commented on core/ui/src/main/java/com/tangem/core/ui/components/list/RoundedListWithDividers.kt
> +    rows: List<RoundedListWithDividersItemData>,
`ImmutableList`

2024-07-30 07:43 UTC, Mama1emon commented on data/staking/src/main/java/com/tangem/data/staking/DefaultStakingRepository.kt
> +            // Blockchain.Polkadot.toCoinId() to POLKADOT_INTEGRATION_ID,
Расскоментить не надо?

2024-07-30 07:43 UTC, Mama1emon commented on domain/staking/models/src/main/kotlin/com/tangem/domain/staking/model/StakingEntryInfo.kt
> +    val interestRate: SerializedBigDecimal,
Если здесь важно использовать `SerializedBigDecimal`, почему сам класс не Serializable?

2024-07-30 07:43 UTC, Mama1emon commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/StakingNotification.kt
> +        data class Common(val subtitle: String) : Error(
nit: для Common, наверное, лучше сразу сделать TextReference, так как этот компонент даже по названию говорит о том, что он может быть использован в любых ситуация, поэтому мы не можем явно знать, откуда бужет строка браться

2024-07-30 07:43 UTC, Mama1emon commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/transformers/AddStakingErrorTransformer.kt
> +            // TODO staking
Это на будущее или надо было сделать в рамках ПР?

2024-07-30 07:43 UTC, Mama1emon commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/ui/block/NotificationsBlock.kt
>  internal fun NotificationsBlock(notifications: List<StakingNotification>) {
Проверь, пожалуйста, метрики на используемых composable для стейкинга.
Как видно из кода, уже сейчас есть не skippable функции

2024-07-30 07:43 UTC, Mama1emon commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/ui/block/NotificationsBlock.kt
> +        Notification(
Нужно доббавить `key()`

2024-07-30 09:03 UTC, Yoggam1 submitted a review, later dismissed
Аппрув с учетом комментов @Mama1emon

2024-08-02 08:41 UTC, Sateetas commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/StakingStateController.kt
> +            title = TextReference.Str(""),
готово

2024-08-02 08:41 UTC, Sateetas commented on core/ui/src/main/java/com/tangem/core/ui/components/list/RoundedListWithDividers.kt
> +    rows: List<RoundedListWithDividersItemData>,
готово

2024-08-02 08:41 UTC, Sateetas commented on core/ui/src/main/java/com/tangem/core/ui/components/list/RoundedListWithDividers.kt
> +    rows: List<RoundedListWithDividersItemData>,
готово

2024-08-02 08:42 UTC, Sateetas commented on data/staking/src/main/java/com/tangem/data/staking/DefaultStakingRepository.kt
> +            // Blockchain.Polkadot.toCoinId() to POLKADOT_INTEGRATION_ID,
пока не надо, специально закрыл
будем открывать по мере реализации стейкинга на том или ином блокчейне

2024-08-02 08:42 UTC, Sateetas commented on domain/staking/models/src/main/kotlin/com/tangem/domain/staking/model/StakingEntryInfo.kt
> +    val interestRate: SerializedBigDecimal,
да, лишнее задел

2024-08-02 08:42 UTC, Sateetas commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/StakingNotification.kt
> +        data class Common(val subtitle: String) : Error(
готово

2024-08-02 08:43 UTC, Sateetas commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/transformers/AddStakingErrorTransformer.kt
> +            // TODO staking
на будущее, для ошибок, специфичных для других блокчейнов

2024-08-02 08:43 UTC, Sateetas commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/ui/block/NotificationsBlock.kt
>  internal fun NotificationsBlock(notifications: List<StakingNotification>) {
прогнал, поправил

2024-08-02 08:43 UTC, Sateetas commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/ui/block/NotificationsBlock.kt
> +        Notification(
готово

2024-08-02 08:47 UTC, Mama1emon commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/FeeState.kt
> +    @Immutable
А почему дата класс Immutable, а не родительский sealed?
Все-таки этот хак может привести к неяным проблемам с отрисовкой

2024-08-02 09:21 UTC, Sateetas commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/FeeState.kt
> +    @Immutable
да, можно и на родительский повесить на случай если Loading или Error наполнятся unstable-данными

поправил

2024-08-02 10:40 UTC, Mama1emon submitted a review, later dismissed

2024-08-02 11:35 UTC, iMaks99 commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/InnerYieldBalanceState.kt
> +enum class BalanceGroupType {
Это уже не нужно

2024-08-02 11:37 UTC, iMaks99 commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/ui/StakingInitialInfoContent.kt
>  private const val METRICS_BLOCK_KEY = "MetricsBlock"
Мб лучше закомментить?

2024-08-02 12:03 UTC, Sateetas commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/InnerYieldBalanceState.kt
> +enum class BalanceGroupType {
убрал

2024-08-02 12:03 UTC, Sateetas commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/ui/StakingInitialInfoContent.kt
>  private const val METRICS_BLOCK_KEY = "MetricsBlock"
можно и так, закомментил

2024-08-02 12:14 UTC, iMaks99 approved these changes

2024-08-02 13:12 UTC, Mama1emon approved these changes

2024-08-02 13:16 UTC, merged