AND-7823 Added ManageTokens in Onboarding flow
tangem/tangem-app-android-old pull request #3143
Opened 2024-08-16 07:04 UTC by Yoggam1

Пришлось много что костылить, добавлять разные флаги в компонент ManageTokens, чтобы добавить его в онбординг. Все это сделано на быструю руку, будем переделывать потом

2024-08-19 14:03 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/details/ui/details/DetailsViewModel.kt
> +        store.dispatch(GlobalAction.Onboarding.Start(scanResponse, canSkipBackup = true))
скипать можно в зависимости от карты, просто так ставить флаг нельзя

2024-08-19 14:03 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/onboarding/OnboardingHelper.kt
> +    fun saveWallet(
тоже самое что trySaveWalletAndNavigateToWalletScreen только без навигации? мб вынести кусок без навигации методом и заюзать там где навигация, если это оно?

2024-08-19 14:03 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> -            if (scanResponse == null) {
scanResponse == null если продолжить прерванный бэкап, после закрытия прилы. Вижу логика переехали ниже, но суть не сломалась?

2024-08-19 14:03 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletState.kt
> +        val baseProgress = 7
это не зависит от типа карты, это юзается только для воллета?

2024-08-21 09:13 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletState.kt
> +        val baseProgress = 7
Используется только в том флоу, где добавлен онбординг. В других онбордингах не используется

2024-08-21 09:15 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/OnboardingHelper.kt
> +    fun saveWallet(
метод `trySaveWalletAndNavigateToWalletScreen` используется много где. Поэтому решили разделить методы, чтобы избежать каши

2024-08-21 09:16 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/details/ui/details/DetailsViewModel.kt
> +        store.dispatch(GlobalAction.Onboarding.Start(scanResponse, canSkipBackup = true))
Точно, я это сделал для себя, чтобы кнопка скип показывалась всегда. Верну как было

2024-08-21 09:19 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> -            if (scanResponse == null) {
Нет, так как у нас создания кошелька делается не в финише онбординга, поэтому логика перенеслась вниз. Ничего не сломалось в этом смысле

2024-08-23 08:26 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/features/onboarding/OnboardingHelper.kt
> +                Log.e("ddk9499", "proceedWithScanResponse: wallet save error: ${error.message}", error)
Timber? Или с разработки осталось?

2024-08-23 08:26 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/features/onboarding/OnboardingHelper.kt
> +                Log.d("ddk9499", "proceedWithScanResponse: wallet saved successfully")
И тут Timber

2024-08-23 08:27 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletReducer.kt
> +        Log.d("ddk9499", "internalReduce: $action")
Timber?

2024-08-23 08:27 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletState.kt
> +        Log.d("ddk9499", "getMaxProgress: ${getWallet2Progress() + baseProgress}")
Timber?

2024-08-23 08:28 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletState.kt
> +        Log.d("ddk9499", "getProgressStep: ${getWallet2Progress() + progressByStep}")
Timber?

2024-08-23 08:28 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingSeedPhraseStateHandler.kt
> +        Log.d("ddk9499", "OnboardingSeedPhraseStateHandler newState")
Timber?

2024-08-23 08:28 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingSeedPhraseStateHandler.kt
> +            Log.d("ddk9499", "OnboardingSeedPhraseStateHandler newState")
Timber?

2024-08-23 08:28 UTC, kozarezvlad requested changes
Помечу как RC, поскольку пока фича ветка т.к. нет возможности закрыть это тогглом и будем лить в дев только после тестов

2024-08-23 08:28 UTC, iMaks99 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +        Log.d("ddk9499", "OnboardingWalletFragment: $wallet")
Timber?

2024-08-23 08:31 UTC, iMaks99 commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "0.0.0"
Забыл удалить?

2024-08-23 08:31 UTC, iMaks99 commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "0.0.0"
Забыл удалить?

2024-08-23 08:32 UTC, iMaks99 commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/model/AppConfig.kt
> +    const val versionName = "5.15.0-SNAPSHOT"
Забыл удалить?

2024-09-10 07:16 UTC, iMaks99 submitted a review, later dismissed

2024-09-10 20:56 UTC, MasterBin requested changes

2024-09-10 20:56 UTC, MasterBin commented on common/routing/src/main/kotlin/com/tangem/common/routing/AppRoute.kt
> +        val onSaved: () -> Unit,
Можно сделать без лямбды в Route? Это не совсем по контракту декомпоз конфигураций, плюс потенциально может привести к тому, что лямбда не отработает, (класс serializable) и к мемори лику (конфигурация переживает пересоздание вьюшек и активити, а лямбда потенциально может захватить их контекст)

Если router.replaceAll единственное зачем нужен этот коллбек, то можно вызвать этот метод прямо в RoutingComponent на коллбеке параметра компонента (в месте, где создается компонент ManageTokens)

Или если еще проще, то вызывать router.rwplaceAll прям в ManageTokensModel

2024-09-10 21:08 UTC, MasterBin commented on common/routing/src/main/kotlin/com/tangem/common/routing/AppRoute.kt
> +        val onSaved: () -> Unit,
Но лучше первый вариант

2024-09-15 11:26 UTC, Yoggam1 commented on common/routing/src/main/kotlin/com/tangem/common/routing/AppRoute.kt
> +        val onSaved: () -> Unit,
@MasterBin Если посмотреть внимательно, то в онбординге не делается никакая навигация. Навигация нужна в зависимости от экрана открытыя. Так что то что ты предлагаешь в текущей конфигурации вещей недостижимо.

2024-09-16 17:06 UTC, nzeeei commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +        }
Может так?
```
with(binding) { ... }
with(bindingManageTokens) { ... }
pbBinding.pbState.show()
```

2024-09-16 17:06 UTC, nzeeei commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +            }
Может вынести это в отдельный метод и переиспользовать?

2024-09-16 17:06 UTC, nzeeei commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +            delay(timeMillis = 1_800)
Эмпирически?

2024-09-26 12:49 UTC, MasterBin approved these changes, later dismissed
Апрув с учетом исправлений по комментам Жени

2024-09-27 11:58 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/card/DefaultDerivationsRepository.kt
> +                        blockchain = Blockchain.fromNetworkId(networkId.value.lowercase()) ?: return@mapNotNull null,
неправильный маппинг, в  networkId лежит blockchain.id, надо маппит как Blockchain.fromId(networkId.value)

2024-10-02 16:07 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +        }
done

2024-10-02 16:08 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +            delay(timeMillis = 1_800)
это копипаста из текущего кода. Я сам тоже не знаю откуда такое значение.

2024-10-02 16:09 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +            }
Переиспользовать не получиться. Не вижу смысла выводить. 
1. Да и не понятно как себя поведет после рефакторинга. 
2. Это все временный костыл, онбординг полностью будет отрефачен

2024-10-02 16:50 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/domain/card/DefaultDerivationsRepository.kt
> +                        blockchain = Blockchain.fromNetworkId(networkId.value.lowercase()) ?: return@mapNotNull null,
Обсудили голосом. Решили пока сюда в этот метод не передавать Network.ID, это не правильно. А передавать сюда строку(а-ля backend id)

2024-10-04 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +                    userWallet = createUserWallet(requireNotNull(scanResponse), backupState)
Стоит ещё текст ошибки добавить, что-бы легче искать потом было

2024-10-04 09:50 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +                                scanResponse = requireNotNull(scanResponse),
Тут тоже про текст

2024-10-04 09:50 UTC, iiiburnyiii commented on features/manage-tokens/impl/src/main/kotlin/com/tangem/features/managetokens/model/OnboardingManageTokensModel.kt
> +internal class OnboardingManageTokensModel @Inject constructor(
Точно нет возможности переиспользовать старую модель? Вроде они почти не отличаются по логике. Ну или хотя-бы одинаковый код вынести в один файл.

2024-10-04 09:50 UTC, iiiburnyiii commented on features/manage-tokens/impl/src/main/kotlin/com/tangem/features/managetokens/ui/OnboardingManageTokensContent.kt
> +internal fun OnboardingManageTokensContent(state: OnboardingManageTokensUM, modifier: Modifier = Modifier) {
Тут тоже разница как-будто только в топ баре. Предлагю чуть расширить `ManageTokensScreen` и его использовать.

2024-10-04 09:54 UTC, Yoggam1 commented on features/manage-tokens/impl/src/main/kotlin/com/tangem/features/managetokens/ui/OnboardingManageTokensContent.kt
> +internal fun OnboardingManageTokensContent(state: OnboardingManageTokensUM, modifier: Modifier = Modifier) {
в топбаре, в кнопках, в логике. Декомпозиция в текущем онбординге никак не ложиться. Декомпозиция может помочь, если сам менедж разбить на под-компоненты и собирать разные реализации. А это требует много времени и рефакторинга самого менеджа.

Поэтому решили сделать так(создать отдельный компонент и переиспользовать только UI компоненты)

2024-10-04 10:35 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +                    userWallet = createUserWallet(requireNotNull(scanResponse), backupState)
Добавил

2024-10-04 10:35 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +                                scanResponse = requireNotNull(scanResponse),
Добавил

2024-10-04 10:39 UTC, iiiburnyiii submitted a review, later dismissed

2024-10-04 10:40 UTC, kozarezvlad submitted a review, later dismissed

2024-10-04 11:05 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +                            userWallet = createUserWallet(newScanResponse, backupState)
Если обновлять userWallet в корутине, то у тебя сама функция быстрее исполнится, чем корутина что-либо вернет

2024-10-04 11:31 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +                            userWallet = createUserWallet(newScanResponse, backupState)
точно, видимо в этом косяк был в апдейте

2024-10-04 11:56 UTC, Yoggam1 commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +                            userWallet = createUserWallet(newScanResponse, backupState)
Исправил

2024-10-04 11:56 UTC, Mama1emon approved these changes

2024-10-04 12:04 UTC, iiiburnyiii approved these changes

2024-10-04 12:29 UTC, merged