AND-8544 [Swap] Refactored notifications using common NotificationUM
tangem/tangem-app-android-old pull request #3472
Opened 2024-09-30 12:20 UTC by iMaks99

2024-10-03 09:21 UTC, kozarezvlad requested changes
Предлагаю взять в 5.18, чтобы куа успели норм потестить и мы потом с спешке не правили, вольем в конце спринта после среза

2024-10-09 09:16 UTC, Sateetas submitted a review, later dismissed

2024-10-29 10:15 UTC, kozarezvlad commented on features/swap/domain/src/main/java/com/tangem/feature/swap/domain/SwapInteractorImpl.kt
> -            val minAvailableAmount = nativeBalance.value - existentialDeposit - fee
а вот эта логика какой минимальный amount сохранена в CryptoCurrencyCheck?

2024-10-29 10:16 UTC, kozarezvlad commented on features/swap/domain/src/main/java/com/tangem/feature/swap/domain/SwapInteractorImpl.kt
> +            is TxFeeState.MultipleFeeState -> feeState.normalFee.feeValue
тут специально стояла priorityFee чтобы посчитать максимум, т.к. после перевыбора fee не идет перерасчет

2024-11-05 11:17 UTC, iMaks99 commented on features/swap/domain/src/main/java/com/tangem/feature/swap/domain/SwapInteractorImpl.kt
> -            val minAvailableAmount = nativeBalance.value - existentialDeposit - fee
поправил

2024-11-11 07:57 UTC, kozarezvlad commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/transformers/notifications/AddStakingNotificationsTransformer.kt
> +            minAdaValue = (feeState?.fee as? Fee.CardanoToken)?.minAdaValue,
но тут если будет не токен кардано, а монета, то это поле будет null, это ок?

2024-11-11 10:06 UTC, iMaks99 commented on features/staking/impl/src/main/java/com/tangem/features/staking/impl/presentation/state/transformers/notifications/AddStakingNotificationsTransformer.kt
> +            minAdaValue = (feeState?.fee as? Fee.CardanoToken)?.minAdaValue,
Да, все будет ок, эта логика изначально была внутри метода, вынес, чтобы можно было в свопе пользоваться

2024-12-09 07:58 UTC, kozarezvlad approved these changes, later dismissed

2024-12-10 07:50 UTC, Mama1emon approved these changes

2024-12-10 07:51 UTC, kozarezvlad approved these changes

2024-12-10 07:55 UTC, merged