AND-8842 [Actions] Add SelectTokenComponent
tangem/tangem-app-android-old pull request #3618
Opened 2024-10-25 12:46 UTC by Mama1emon

2024-10-25 14:44 UTC, MasterBin requested changes

2024-10-25 14:44 UTC, MasterBin commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/selecttoken/SelectTokenComponent.kt
> +interface SelectTokenComponent : ComposableContentComponent {
- Думаю SelectTokenComponent слишком общее название, как и TokenListComponent. Можно OnrampSelectTokenComponent. 
- почему не отдельный модуль?

2024-10-28 07:51 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/selecttoken/SelectTokenComponent.kt
> +interface SelectTokenComponent : ComposableContentComponent {
1) Как я вижу, это и есть общий компонент, который будет использоваться для построения экранов Buy и Sell. Не хотел привязываться к названию `MainActions`, так как компонент предполагает переиспользуемость.
2) Пока основные компоненты реализовывал в модуле wallet, из-за доступности internal компонентов. В новой сторе буду уже переносить. Скорее всего, в onramp

2024-10-28 08:01 UTC, MasterBin approved these changes

2024-10-28 09:22 UTC, kozarezvlad approved these changes

2024-10-28 09:22 UTC, merged