AND-8374 [Excluded Blockchains] Implemented ExcludedBlockchainsManager
tangem/tangem-app-android-old pull request #3643
Opened 2024-10-30 10:18 UTC by iiiburnyiii

2024-10-30 10:45 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/common/extensions/Blockchain.kt
> -fun Blockchain.getNetworkStandardName(): String {
А куда это переместилось? в диффе не нашел

2024-10-30 10:47 UTC, kozarezvlad commented on core/toggles/build.gradle.kts
> +    namespace = "com.tangem.core.toggles"
а зачем переименование? в целом конечно пофиг, но тогглами может быть что угодно, условно либа с ui где разные виды тогглов, а фича тогглы говоряще сразу

2024-10-30 10:48 UTC, Mama1emon requested changes

2024-10-30 10:48 UTC, Mama1emon commented on app/build.gradle.kts
> +    implementation(projects.core.toggles)
Как мне кажется, лучше оставить прошлое наименование. Оно наиболее явно отражает, что это за модуль

2024-10-30 10:48 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/local/preferences/utils/AppPreferencesStoreExt.kt
> +
Preferences поддерживают тип ключа `stringSetPreferencesKey`

2024-10-30 10:48 UTC, Mama1emon commented on core/toggles/src/main/assets/configs/excluded_blockchains_config.json
> +    }
Мб переиспользовать уже существующий конфиг с фича тогглами? Зачем разбивать на два?

2024-10-30 10:48 UTC, Mama1emon commented on core/toggles/src/main/kotlin/com/tangem/core/toggle/storage/Toggle.kt
> +internal data class Toggle(
Здесь тоже название размазывается

2024-10-30 10:50 UTC, Yoggam1 commented on core/toggles/src/main/assets/configs/excluded_blockchains_config.json
> +    }
В этом случае разделение хорошо, имхо. Не получиться огромный файл, где собраны все конфиги

2024-10-30 10:53 UTC, kozarezvlad commented on core/toggles/src/main/assets/configs/excluded_blockchains_config.json
> +    }
плюсую Достону, разделение имеет смысл и с точки зрения проверок и "ок" на релиз

2024-10-30 11:03 UTC, iiiburnyiii commented on core/toggles/build.gradle.kts
> +    namespace = "com.tangem.core.toggles"
Раньше там лежала логика только для фича-тоглов, сейчас ещё и для тоглов для блокчейнов, название featuretoggle не покрывает эти две штуки. Как вариант ещё можно назвать configtoggle, например.

2024-10-30 11:03 UTC, iiiburnyiii commented on app/build.gradle.kts
> +    implementation(projects.core.toggles)
Ответил тут: https://github.com/tangem/tangem-app-android/pull/3643#discussion_r1822384070

2024-10-30 11:28 UTC, Mama1emon commented on core/toggles/src/main/assets/configs/excluded_blockchains_config.json
> +    }
У нас не бывает много исключенных блокчейнов или блокчейнов, которые релизим. Файл фича тогглов всегда поддерживается в актуальном состоянии. Зачем делать разделение из-за трех-четырех тогглов? 
Мы просто создаем еще один компонент, который при старте прилки будет параллельно что-то делать. Это чревато гонкой и тд

2024-10-30 11:29 UTC, Mama1emon commented on core/toggles/build.gradle.kts
> +    namespace = "com.tangem.core.toggles"
ExcludedBlockchdins тоже некорректное название, потому что по факту это фича тоггл для интеграции блокчейна

2024-10-30 12:46 UTC, kozarezvlad commented on core/toggles/build.gradle.kts
> +    namespace = "com.tangem.core.toggles"
configtoggle норм
блокчейн == фича по сути тоже

2024-10-30 12:52 UTC, kozarezvlad commented on core/toggles/src/main/assets/configs/excluded_blockchains_config.json
> +    }
логически это немного разные вещи, не хочется мешать эти файлы, как постоянный чекатель фичей перед релизом говорю

2024-11-26 08:47 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/TangemApplication.kt
> +        runBlocking(dispatchers.io) {
тут важно было блочить main thread, чтобы успели загрузится все конфиги до попадания в фичи

2024-11-26 09:55 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/TangemApplication.kt
> +        runBlocking(dispatchers.io) {
Выставил явно main диспатчер и прила перестала запускаться, так что просто откатил как было

2024-11-26 10:33 UTC, kozarezvlad approved these changes

2024-11-26 10:42 UTC, Mama1emon approved these changes

2024-11-26 11:39 UTC, merged