AND-8814 Handle crashes when string params is not match format
tangem/tangem-app-android-old pull request #3888
Opened 2024-12-06 12:40 UTC by Mama1emon

2024-12-06 12:44 UTC, iMaks99 approved these changes, later dismissed

2024-12-06 12:45 UTC, kozarezvlad requested changes
После отведения 5.19

2024-12-06 12:46 UTC, Mama1emon commented
Да, пока не вливаем. Чисто чтобы команда успела посмотреть

2024-12-09 09:09 UTC, kozarezvlad approved these changes

2024-12-09 09:20 UTC, iMaks99 approved these changes

2024-12-09 09:20 UTC, merged