AND-9064 Added events sending after app start from push
tangem/tangem-app-android-old pull request #4006
Opened 2024-12-20 16:23 UTC by Sateetas

2024-12-24 05:55 UTC, iMaks99 approved these changes, later dismissed

2024-12-24 08:27 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +        intentProcessor.handleIntent(intentWhichStartedActivity, false)
скорее всего тут логика неправильная будет, если мы идем на welcome и карты залочены, то не нужно хендлить интент

2024-12-24 08:27 UTC, kozarezvlad requested changes
проверить логику и поведение для диплинком walletConnect

2025-01-14 09:12 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +        intentProcessor.handleIntent(intentWhichStartedActivity, false)
переписал

2025-01-14 14:05 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/intentHandler/IntentProcessor.kt
> +            .run { if (skipNavigationHandlers) filterNot { it is AffectsNavigation } else this }
почему не map?

2025-01-14 19:44 UTC, kozarezvlad approved these changes

2025-01-16 09:53 UTC, Mama1emon approved these changes

2025-01-16 09:53 UTC, merged