AND-2488 Fix wallet selector scroll and add shimmer effect
tangem/tangem-app-android-old pull request #401
Opened 2022-12-01 11:56 UTC by iiiburnyiii

2022-12-01 12:52 UTC, MamaLemon requested changes

2022-12-01 12:52 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/features/walletSelector/ui/components/WallectSelectorScreenContent.kt
> +    Column(
Это мелочь, но как мне кажется стилистически лучше оставить как было

2022-12-01 12:52 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/features/walletSelector/ui/components/WallectSelectorScreenContent.kt
> +                if (state.isLocked) Column {
Как мне кажется, лучше не пренебрегать с brackets в if-else, так как данная конструкция может стать потенциально опасным местом. Такой синтаксис больше подходит для однострочных if-else.

2022-12-01 12:52 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/features/walletSelector/ui/components/WallectSelectorScreenContent.kt
> +            item { SpacerH24() }
Как мне кажется, делать пустой итем в LazyList - это не самый лучший метод. Конструкция подобно RecyclerView, поэтому добавлять такие итемы - это заставлять его делать лишнюю работу. Предлагаю использовать Column.

2022-12-02 07:47 UTC, kozarezvlad approved these changes

2022-12-02 07:52 UTC, MamaLemon approved these changes

2022-12-02 07:53 UTC, merged