AND-9410 [UI] Implemented new types of UI message
tangem/tangem-app-android-old pull request #4026
Opened 2024-12-26 11:42 UTC by iiiburnyiii

2024-12-26 12:26 UTC, iMaks99 requested changes
Не думаю, что имеет смысл делать отдельную абстракцию под MessageBottomSheet. У нас уже есть ComposableBottomSheetComponent. Пусть будет единый способ работы с щитами

2024-12-26 13:07 UTC, iiiburnyiii commented
@iMaks99 Компоненты не всегда подходят из-за кол-ва кода и сложности, временами лучше и легче просто прокинуть сообщение, а не создавать новый компонент. На примере с диалогами: простые алерты лучше выводить через сообщение, но если в диалоге есть логика, то лучше создать подкомпонент, для разгрузки основного компонента и переиспользования (как диалог переименования кошелька в WalletSettings).
По поводу того, что это не кор UI компонент, в целом согласен, мест использования такого BS достаточно мало, разве что можно в маркетсах ещё его заюзать, но я не вижу проблемы с тем, что-бы оставить его тут.
Одна из идей этого рефака в том, что-бы удалить ContentMessage, так как это потенциально опасная штука.

2024-12-26 13:14 UTC, iMaks99 approved these changes

2024-12-28 08:50 UTC, nemelianov-tangem approved these changes

2024-12-28 08:51 UTC, Mama1emon approved these changes

2024-12-28 08:58 UTC, Yoggam1 approved these changes

2024-12-28 09:00 UTC, merged