AND-2616 Save twins cards after re-twin
tangem/tangem-app-android-old pull request #482
Opened 2022-12-15 12:36 UTC by iiiburnyiii

2022-12-15 13:27 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/onboarding/products/twins/redux/TwinCardsMiddleware.kt
> +                        OnboardingHelper.trySaveWalletAndNavigateToWalletScreen(scanResponse)
А после trySaveWalletAndNavigateToWalletScreen не нужно на Home вернуться?

2022-12-15 13:28 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/BiometricUserWalletsListManager.kt
> +        if (walletIds.isEmpty()) return CompletionResult.Success(Unit)
Предлагаю всё же всегда {} ставить, хорошая практика, чтобы никто случайно не сломал

2022-12-15 13:58 UTC, MamaLemon requested changes

2022-12-15 13:58 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/twins/TwinCardsManager.kt
> +            firstCardId = currentCardId,
Здесь нельзя передавать current, туда явно надо firstCardId

2022-12-15 13:58 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/BiometricUserWalletsListManager.kt
> +        if (walletIds.isEmpty()) return CompletionResult.Success(Unit)
Вроде здесь норм

2022-12-15 13:58 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/features/onboarding/products/twins/redux/TwinCardsMiddleware.kt
> +                        OnboardingHelper.trySaveWalletAndNavigateToWalletScreen(scanResponse)
Как мне кажется, такие длинные названия ухудшают читаемость.
ATTENTION: Полное прочтение названия грозит написанием собственного реп альбома)

2022-12-15 13:59 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/twins/TwinCardsManager.kt
> +            firstCardId = currentCardId,
Иначе проверка сломается - первая это карта или вторая?

2022-12-15 14:03 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/onboarding/products/twins/redux/TwinCardsMiddleware.kt
> +                        OnboardingHelper.trySaveWalletAndNavigateToWalletScreen(scanResponse)
Нет, там же переход на экране кошелька с уже обновленным твином

2022-12-15 14:09 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/twins/TwinCardsManager.kt
> +            firstCardId = currentCardId,
Как ты говорил таски не подвязаны на саму карту, first и second это порядок вызова тасок, а не номер карты
Соответсвенно тут current означает просто первую отсканенную карту, это более логичное назване как мне кажется

2022-12-15 14:25 UTC, roman-pv approved these changes

2022-12-16 06:35 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/twins/TwinCardsManager.kt
> +            firstCardId = currentCardId,
Это работает следующим образом: firstCardId - это card id первой отсканенной карты, а какая она по номеру уже неважно. А card.cardId - это текущая приложенная карта, таким образом при РЕТВИНЕ, если firstCardId является первой картой, а ты прикладываешь card.cardId с номером второй, то проверка явно скажет, что ты прикладываешь другую. Код прикладываю.

<img width="650" alt="изображение" src="https://user-images.githubusercontent.com/29564668/208037354-d8f0cddc-0d44-485b-8506-6b156cb779dd.png">

2022-12-16 15:56 UTC, MamaLemon approved these changes

2022-12-16 15:58 UTC, merged