AND-2748 added token in wallet balance and calculate fiat amount
tangem/tangem-app-android-old pull request #571
Opened 2023-01-11 15:49 UTC by kozarezvlad

2023-01-11 21:22 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/proxy/UserWalletManagerImpl.kt
> +    }
Может быть так?

```
private fun getActualWalletManager(blockchain: Blockchain): WalletManager {
                        val card = appStateHolder.getActualCard() ?: error("card not found")
                        val blockchainNetwork = BlockchainNetwork(blockchain, card)
                        val walletManager = appStateHolder.walletState?.getWalletManager(blockchainNetwork)
                        return walletManager ?: error("no wallet manager found")
                    }
```

2023-01-11 21:22 UTC, gbixahue commented on core/utils/src/main/java/com/tangem/utils/FormatExtensions.kt
> +fun BigDecimal.formatWithSpaces(): String {
Вот эту вещь нужно, в будущем, переделать на нормальный конвертер завязанный на локаль.
Сейчас эта конструкция работает не правильно.

2023-01-12 07:04 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/proxy/UserWalletManagerImpl.kt
> +    }
да, так лучше будет, скопипастил не обратил внимания

2023-01-12 07:05 UTC, kozarezvlad commented on core/utils/src/main/java/com/tangem/utils/FormatExtensions.kt
> +fun BigDecimal.formatWithSpaces(): String {
Это все перетащил просто в utils, но в исходном месте тоже оставил. Перепишем как доберемся

2023-01-12 07:26 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/proxy/UserWalletManagerImpl.kt
> +    }
переписал

2023-01-12 07:28 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/proxy/UserWalletManagerImpl.kt
> +    }
Можно даже упростить до конструкции requireNotNull() { }, так как идет сравнение на null

2023-01-12 07:44 UTC, MamaLemon requested changes

2023-01-12 07:44 UTC, MamaLemon commented on features/swap/presentation/src/main/java/com/tangem/feature/swap/ui/StateBuilder.kt
>                  type = (uiStateHolder.sendCardData.type as TransactionCardType.SendCard)
Лучше использовать безопасный кастинг `as?` с явной обработкой или просто добавить requireNotNull, если другого состояния быть не может

2023-01-12 07:44 UTC, MamaLemon commented on core/utils/src/main/java/com/tangem/utils/FormatExtensions.kt
> +fun BigDecimal.toFiatString(
Как мне кажется, данный код имеет свою специфику, чтобы существовать в рамках core/utils модуля. В будущем просто напросто не найдем его.

2023-01-12 10:15 UTC, kozarezvlad commented on core/utils/src/main/java/com/tangem/utils/FormatExtensions.kt
> +fun BigDecimal.toFiatString(
мне кажется это утилиты для форматирования? куда бы ты его положил в core-ui?

2023-01-12 13:06 UTC, MamaLemon commented on core/utils/src/main/java/com/tangem/utils/FormatExtensions.kt
> +fun BigDecimal.toFiatString(
Когда нам требуется этот метод? Когда работаем с блокчейном?

2023-01-12 13:28 UTC, kozarezvlad commented on core/utils/src/main/java/com/tangem/utils/FormatExtensions.kt
> +fun BigDecimal.toFiatString(
когда хотим форматировать bigdecimal в определенное отображение, не обязательно это работа с блокчейном

2023-01-12 13:34 UTC, kozarezvlad commented on core/utils/src/main/java/com/tangem/utils/FormatExtensions.kt
> +fun BigDecimal.toFiatString(
@gbixahue test

2023-01-12 13:37 UTC, gbixahue commented on core/utils/src/main/java/com/tangem/utils/FormatExtensions.kt
> +fun BigDecimal.toFiatString(
@gbixahue test

2023-01-12 14:06 UTC, MamaLemon approved these changes

2023-01-12 14:08 UTC, merged