AND-2931: Add support for WC 2.0
tangem/tangem-app-android-old pull request #759
Opened 2023-03-06 08:41 UTC by roman-pv

Посмотрите, стоит ли это как-то рефакторить еще. Но тут оно пересекается со старым кодом wc 1.0, который пока не хотелось бы переписывать, учитывая, что летом его можно будет выпилить. Поэтому возможно лучше подождать лета. 
И я продолжаю еще правки вносить по мере того, как поддержку Соланы добавляю.

2023-03-13 09:17 UTC, kozarezvlad commented on app/build.gradle.kts
> +        configurations {
Надо помержить с изменениями Антона в грэдле

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +lateinit var walletConnectInteractor: WalletConnectInteractor
получится сразу в DI граф положить?

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +lateinit var walletConnect2Repository: com.tangem.tap.domain.walletconnect2.domain.WalletConnectRepository
с этими зависимостями тоже, сразу все через DI поставлять можно

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        walletConnect2Repository.init("")
а в обычном init {} имплементации не получится сделать?

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/TapWalletManager.kt
> +        setupWalletConnectV2(userWallet)
Можно сразу добавить тоггл, чтобы в дев не попал не закрытый функционал. Ну и везде где развилка есть

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/walletconnect/BnbHelper.kt
> +    fun WcBinanceTradeOrder.toWCBinanceTradeOrder(): WCBinanceTradeOrder {
Как предложение, сделать это не статиком, а например какой то абстрактный TradeOrderFactory и его реализация BnbTradeOrderFactory

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/walletconnect/WalletConnectSdkHelper.kt
> +        data: EthTransactionData,
а WalletConnectSdkHelper только с эфиром работает? не совсем понятно почему в метод именно EthTransactionData приходит

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/walletconnect/extensions/WcPeerMeta.kt
> +fun WCEthereumTransaction.toWcEthTransaction(): WcEthereumTransaction {
тут коммент аналогично про factory для сборки транзакции можно было бы сделать, чтобы не через статик методы все было

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/data/WalletConnectRepositoryImpl.kt
> +        val walletDelegate = object : Web3Wallet.WalletDelegate {
это можно вынести из метода чтобы разгрузить его, скорее всего тут и так detekt ругается

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/data/WalletConnectSessionsRepositoryImpl.kt
> +    private fun Context.readFileText(fileName: String): String =
уже где то есть похожие ext только для json, можно было бы сложить все рядом

2023-03-13 09:17 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/domain/WalletConnectInteractor.kt
> +    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
лучше провайдить 
private val coroutineDispatcher: CoroutineDispatcherProvider

2023-03-13 09:18 UTC, kozarezvlad commented
Дальше интерактора не дошел(

2023-03-13 12:04 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        walletConnect2Repository.init("")
Там в будущем скорее всего для разных карт заново будет инициализироваться этим методом, поэтому он отдельно от создания класса

2023-03-13 12:05 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +lateinit var walletConnectInteractor: WalletConnectInteractor
Я делал ПР до того, как Андрей доку по DI в старом коде сделал. Могу посмотреть, но наверное как раз уже отдельным ПР лучше

2023-03-13 13:49 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect/WalletConnectSdkHelper.kt
> +        data: EthTransactionData,
Изначально WC работал только с EVM сетями. Другие сети в любом случае с другими методами WC и здесь тоже будут через другие методы хелпера.

2023-03-15 08:11 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect/extensions/WcPeerMeta.kt
> +fun WCEthereumTransaction.toWcEthTransaction(): WcEthereumTransaction {
Тут простое перемапливание из библиотечного класса в наш класс, и оно временное (только для wc 1, который мы все-таки надеюсь скоро выпилим, если он правда после лета закончится)

2023-03-15 08:13 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect/BnbHelper.kt
> +    fun WcBinanceTradeOrder.toWCBinanceTradeOrder(): WCBinanceTradeOrder {
Тут тоже временная тема, связанная с интеропом между библиотекой для wc 1, плюс бинанс на wc 2 еще не работает.

2023-03-15 08:33 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +lateinit var walletConnectInteractor: WalletConnectInteractor
это не DI в старом коде, тут же новые классы провайдится будут, а сюда в активити просто внедрить через @Inject

2023-03-15 11:27 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +lateinit var walletConnectInteractor: WalletConnectInteractor
Но эти классы используется в редаксе, то есть это все равно про DI в старом коде. Это как раз DaggerGraphState, из доки Андрея, про который я говорил. Это не проблема, но это еще увеличит текущий ПР, поэтому предлагал в дополнительном сделать

2023-03-16 07:05 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +lateinit var walletConnectInteractor: WalletConnectInteractor
Давайте тогда задачку заведем и тудушку в коде тыкнем)

2023-03-16 07:07 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +lateinit var walletConnectSessionsRepository: WalletConnectSessionsRepositoryImpl
Как мне кажется, если использовать тип интерфейса, то так код будет гибче и переиспользуемей. Всегда будет возможность подменить реализации и тд.

2023-03-16 07:10 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/walletconnect/WalletConnectSdkHelper.kt
> +    // private fun getWalletManager(session: WalletConnectSession): WalletManager? {
Можно выпилить?

2023-03-16 07:11 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/data/WalletConnectSessionsRepositoryImpl.kt
> +    private fun Context.readFileText(fileName: String): String =
У нас такое есть для файлов из assets

2023-03-16 07:11 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/domain/WalletConnectEventsHandler.kt
> +    // val onProposalApproved: () -> Unit,
Можно удалить?

2023-03-16 07:12 UTC, MamaLemon commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/model/AppConfig.kt
> +    const val minSdkVersion = 23
Это требование для WC2?

2023-03-16 07:12 UTC, MamaLemon commented on buildSrc/src/main/java/Versions.kt
> +object Versions {
Вроде же выпилили?

2023-03-16 07:14 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/features/details/redux/walletconnect/WalletConnectMiddleware.kt
> +                when (action.wcUri[index + 1]) {
Данная функция `[]` не кинет ли исключение, если не найдет значение?

2023-03-16 07:15 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/features/details/redux/walletconnect/WalletConnectMiddleware.kt
> +                    '1' -> {
Предлагаю добавить константы. Так код будет легче читать

2023-03-16 07:15 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/domain/models/binance/WcBinanceTradePair.kt
> +                val firstParts = pair[0].split("-")
Данный код выбросит исключение, если не найдется данный индекс

2023-03-16 07:21 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +lateinit var walletConnectSessionsRepository: WalletConnectSessionsRepositoryImpl
Да, согласен, это случайно осталось с Impl

2023-03-16 07:21 UTC, roman-pv commented on plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/model/AppConfig.kt
> +    const val minSdkVersion = 23
Да

2023-03-16 07:22 UTC, roman-pv commented on buildSrc/src/main/java/Versions.kt
> +object Versions {
Видимо при ребэйзе сохранилось

2023-03-16 07:30 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/domain/models/binance/WcBinanceTradePair.kt
> +                val firstParts = pair[0].split("-")
Это временная копия кода из библиотеки бинанса. Для WC1 эта либа работала отлично.  Пока у нас нет поддержки бинанса для WC 2.0, поэтому пока можно вообще не трогать

2023-03-16 07:33 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/details/redux/walletconnect/WalletConnectMiddleware.kt
> +                when (action.wcUri[index + 1]) {
У меня не кидает и на WC ссылках, и на нерабочих ссылках

2023-03-16 07:37 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/details/redux/walletconnect/WalletConnectMiddleware.kt
> +                    '1' -> {
Мне кажется неоправданным добавлять константы в таком контексте - тут только по одному символу, и все чисто функционально. Как называть константу собаки? VERSION_IDENTIFIER?
Но если остальные тоже поддержат, то вынесу в константу

2023-03-16 07:59 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +lateinit var walletConnectInteractor: WalletConnectInteractor
Я уже сделал это, могу даже в этот ПР все-таки закинуть, раз он все равно такой неспешный

2023-06-08 14:40 UTC, Mama1emon requested changes

2023-06-08 14:40 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +    lateinit var walletConnect2Repository: com.tangem.tap.domain.walletconnect2.domain.WalletConnectRepository
Предлагаю добавить импорт

2023-06-08 14:40 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        walletConnect2Repository.init(projectId = configManager.config.walletConnectProjectId)
А почему не через DI передается параметр `configManager.config.walletConnectProjectId`?

2023-06-08 14:40 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/common/DialogManager.kt
> +import com.tangem.tap.features.details.ui.walletconnect.dialogs.ApproveWcSessionDialog
Импорты настроены?

2023-06-09 07:59 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/common/redux/StateDialog.kt
> +
А вот это не подойдет?
```
SimpleAlertDialog
SimpleCancelableAlertDialog
```

2023-06-09 07:59 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/app/TangemWcBlockchainHelper.kt
> +    override fun getNamespaceFromFullChainId(chainId: String): String? {
Может и здесь добавить суффикс orNull для единообразия интерфейса?
getNamespaceFromFullChainId`OrNull`

2023-06-09 07:59 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/data/WalletConnectRepositoryImpl.kt
> +    override val events: Flow<WalletConnectEvents> = _events.filterNotNull()
Может здесь лучше использовать  MutableSharedFlow, тогда мы избавимся от необходимости отправлять null  при инициализации и его же отфильтровывать?

2023-06-09 08:12 UTC, Sateetas requested changes

2023-06-09 08:12 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/domain/models/binance/WcBinanceCancelOrder.kt
> +    @Json(name = "chain_id")
я бы везде аннотации поставил

ок, обфускации у нас нет, но при рефакторинге кто-нибудь случайно филд переименует, и всё, баста

2023-06-09 08:24 UTC, Sateetas requested changes

2023-06-09 08:24 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletconnect/BnbHelper.kt
> +    fun WcBinanceTransferOrder.toWCBinanceTransferOrder(): WCBinanceTransferOrder {
давай переименуем наш `WcBinanceTransferOrder` чтобы коллизий именования не было

2023-06-09 08:30 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletconnect/BnbHelper.kt
> +    private fun WcBinanceTradeOrder.Message.toWCBinanceTradeOrderMessage(): WCBinanceTradeOrder.Message {
я бы половину методов из этого класса вынес в сущность вроде WCBinanceConverter
helper в названии малоинформативен

2023-06-09 08:38 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletconnect/WalletConnectSdkHelper.kt
>  class WalletConnectSdkHelper {
тут тоже разнес бы на несколько классов, чтобы было SRP
sign, send, prepare data

2023-06-09 08:42 UTC, Sateetas requested changes

2023-06-09 08:42 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/domain/models/WalletConnectError.kt
> +    data class ExternalApprovalError(override val message: String?) : WalletConnectError()
почему переносы строк неравномерно расставлены?

2023-06-09 09:20 UTC, Sateetas commented on core/datasource/src/main/java/com/tangem/datasource/files/AndroidFileReader.kt
> +class AndroidFileReader @Inject constructor(@ApplicationContext private val context: Context) : FileReader {
в com.tangem.tap.common.extensions.Context остались экстеншны, их нужно удалить
чч
<img width="919" alt="image" src="https://github.com/tangem/tangem-app-android/assets/13484957/57060886-5580-4add-b643-b7753256283b">

2023-06-09 11:28 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect/BnbHelper.kt
> +    private fun WcBinanceTradeOrder.Message.toWCBinanceTradeOrderMessage(): WCBinanceTradeOrder.Message {
Я старые классы не рефакторил, очень многое исчезнет при выпиливании WC 1, WC перейдет в отдельный модуль и тд. Сейчас очень много будет лишней работы, если рефакторить старые классы. Плюс в принципе цель была минимально затронуть код WC 1, потому что он пока работает, не хочется его ломать, а потом мы его полностью выпилим.

2023-06-09 11:29 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect/BnbHelper.kt
> +    fun WcBinanceTransferOrder.toWCBinanceTransferOrder(): WCBinanceTransferOrder {
Тут тоже - коллизии исчезнут, когда мы перестанем использовать либу для первого WC

2023-06-09 11:35 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect/WalletConnectSdkHelper.kt
>  class WalletConnectSdkHelper {
тоже пока не рефакторил этот класс, глобальные переделки старого после выпиливания WC 1

2023-06-09 14:01 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        walletConnect2Repository.init(projectId = configManager.config.walletConnectProjectId)
А у нас куда-то уже передавался конфиг через DI? он будет создаваться же позже, чем DI сгенерит репозиторий. Это тогда надо менять то, как мы инициализируем конфиг

2023-06-09 14:03 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/common/redux/StateDialog.kt
> +
Так они же для разных целей, это дата классы для редукса, с данными. А те - уже создают диалоги сами

2023-06-13 06:58 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/walletconnect2/domain/models/WalletConnectError.kt
> +    data class ExternalApprovalError(override val message: String?) : WalletConnectError()
поправил

2023-06-13 10:24 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/TapApplication.kt
> +        walletConnect2Repository.init(projectId = configManager.config.walletConnectProjectId)
Если я правильно понимаю, то ты можешь запровайдить конфиг менеджер в свой репо, и уже из него достать конфиг

2023-06-13 10:24 UTC, Mama1emon approved these changes

2023-06-13 13:51 UTC, Sateetas approved these changes

2023-06-13 14:04 UTC, merged