AND-3233 Fix invalidated key exception handling
tangem/tangem-app-android-old pull request #833
Opened 2023-04-07 00:56 UTC by iiiburnyiii

2023-04-24 10:26 UTC, Mama1emon requested changes

2023-04-24 10:26 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/common/analytics/TangemSdkErrorMapper.kt
> +            is TangemSdkError.BiometricCryptographyOperationFailed -> error
Как думаешь, мб зарефачить сразу, чтобы не на каждую ошибку возврат делать, а перечислить иих и сделать один возврат?

2023-04-24 10:26 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/BiometricUserWalletsListManager.kt
> +                if (changeSelectedUserWallet) {
Не совсем понял, как это работает. Если if ветка не отработает, то что на вывод функции map пойдет?

2023-04-24 13:06 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/common/analytics/TangemSdkErrorMapper.kt
> +            is TangemSdkError.BiometricCryptographyOperationFailed -> error
Этот файл не используется нигда - удалил

2023-04-24 13:07 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/BiometricUserWalletsListManager.kt
> +                if (changeSelectedUserWallet) {
В обоих случаях будет Unit

2023-04-25 08:09 UTC, Mama1emon requested changes

2023-04-25 08:09 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/BiometricUserWalletsListManager.kt
> +            .map {
Можно ли два вышестоящих flatMap объединить в один?

2023-04-25 08:09 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/BiometricUserWalletsListManager.kt
> +                if (changeSelectedUserWallet) {
В таком случае получается немного путаница при чтении код, так как `map` имеет другое предназначение.
Здесь точно можно использовать фильтр.

Не получится ли данную цепочку вызовов заменить на `forEach`. Кажется, что это избыточно

2023-04-25 08:22 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/BiometricUserWalletsListManager.kt
> +                if (changeSelectedUserWallet) {
Это методы не листа, а `CompletitionResult`'a, у него нет `forEach`

2023-04-25 08:24 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/userWalletList/implementation/BiometricUserWalletsListManager.kt
> +            .map {
Нет, операция производиться не над списком, а над результатом

2023-04-25 08:34 UTC, MamaLemon approved these changes

2023-04-25 08:36 UTC, kozarezvlad approved these changes

2023-04-25 08:38 UTC, roman-pv approved these changes

2023-04-25 09:22 UTC, merged