AND-3353 Main Screen: the card picture does not load, after turning on the Internet
tangem/tangem-app-android-old pull request #851
Opened 2023-04-12 13:27 UTC by MamaLemon

2023-04-12 14:40 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                    userWalletsListManager.update(
вот тут ничего не сломается? tapWalletManager.loadData не тянул за собой еще какую то логику скрытую?

2023-04-13 01:32 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                    userWalletsListManager.update(
Давай расскажу о проблеме и как ее решил: рефреш главного экрана не обновлял ссылку на изображение. Поэтому в кейсе, когда ты вырубаешь интернет, после сканирования у тебя в стейт сохраняется ссылка на дефолтное изображение и все. И больше она никак не могла обновиться.
Исправил я это с помощью обновления userWallet и вызовом loadData уже с правильной ссылкой.

2023-04-13 03:38 UTC, Yoggam1 approved these changes

2023-04-13 07:14 UTC, kozarezvlad approved these changes

2023-04-13 07:20 UTC, iiiburnyiii requested changes

2023-04-13 07:20 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                                    globalState.tapWalletManager.loadData(userWallet = it, refresh = true)
Тут refresh должен быть не всегда же, раньше было `refresh = action is WalletAction.LoadData.Refresh`

2023-04-13 07:20 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                                    globalState.tapWalletManager.loadData(userWallet = it, refresh = true)
И кажется этот метод стоит вызывать ассинхронно с обновлением картинки, что-бы они не ждали друг друга

2023-04-13 07:30 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                                    globalState.tapWalletManager.loadData(userWallet = it, refresh = true)
1) Ты прав, упустил
2) Ассинхронно не получится, так как load надо вызывать уже с картинкой, иначе не обновится

2023-04-13 07:40 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                                    globalState.tapWalletManager.loadData(userWallet = it, refresh = true)
По идее, для наблюдения за кошельком, можно подписаться в `WalletViewModel` на изменения выбранного кошелька (`userWalletsListManager.selectedUserWallet`), и на каждое его изменене кидать экшн `UserWalletChanged`

2023-04-13 09:22 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                    userWalletsListManager.update(
Думаю тут стоит убрать диспатч экшена из лямбды и диспатчить его при успешном обновлении, что-то типа:
```
userWalletsListManager.update(...)
 .doOnSuccess { 
   store.dispatchOnMain(WalletAction.UserWalletChanged(it))
  }
```

2023-04-13 12:54 UTC, iiiburnyiii approved these changes

2023-04-13 13:52 UTC, merged