AND-3262 #5 Wallet2: Import: mark invalid words, show error
tangem/tangem-app-android-old pull request #862
Opened 2023-04-16 18:24 UTC by gbixahue

2023-04-17 10:35 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/InvalidWordsColorTransformation.kt
> +        private const val WORD_SEPARATOR = "_$@-*"
Искусственно придуманный символ упрощающий разбиение строки на список слов и обратную сборку, т.к. обычный сплит по " " давал не корректные результаты если подряд попадаются несколько пробелов

2023-04-17 10:35 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +            }
На первый взгляд этот when бессмысленный, но в пследующем ПРе они обретут код перед выходом из метода

2023-04-17 11:41 UTC, MamaLemon requested changes

2023-04-17 11:41 UTC, MamaLemon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseErrorConverter.kt
> +    override fun convert(message: SeedPhraseError?): String? {
Возможно, возвращать идентификатор ресурса будет лучшим решением, так как не будем лишний раз контект хранить в объектах никак не связанных с ЖЦ

2023-04-17 11:41 UTC, MamaLemon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/ui/ImportSeedPhraseScreen.kt
> +            val message = SeedPhraseErrorConverter(LocalContext.current).convert(state.error)
Как мне кажется, данное сообщение должно приходить в рамках стейта.
По-хорошему, компоуз не должен заниматься ничем, кроме отрисовки

2023-04-17 12:01 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/InvalidWordsColorTransformation.kt
> +        private const val WORD_SEPARATOR = "_$@-*"
Можно глянуть в реализации parse в DefaultBIP39
` val regex = Regex(pattern = "\\p{L}+")
        val matches = regex.findAll(mnemonicString)
        val components = matches.map { result ->
            result.value.trim().lowercase()
        }.toList()`

2023-04-17 12:16 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/InvalidWordsColorTransformation.kt
> +        private const val WORD_SEPARATOR = "_$@-*"
Это не подойдёт, т.к. мне нужно сохранять формат написанного

2023-04-17 12:18 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseErrorConverter.kt
> +    override fun convert(message: SeedPhraseError?): String? {
Конвертер позволяет правильно сконвертировать ошибку в строку даже если потребуются использовать данные из ошибки для форматирования. Для этой возможности возвращая ресурс - придется ещё что-то конструировать

2023-04-17 12:26 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/ui/ImportSeedPhraseScreen.kt
> +            val message = SeedPhraseErrorConverter(LocalContext.current).convert(state.error)
Можно было-бы это перенести во viewModel, но тогда пришлось-бы держать актуальный контекст внутри viewModel т.к. ошибка, по сути может быть результатом любого действия и может содержать дополнительные данные для построения сообщения.

Если же использовать в качестве ошибки готовый ресурс, то все равно необходим какой-то конвертер, который замапит данные ошибки в ресурс.

Предлагаю рассмотреть вариант, который приводил Достон

https://tangem.slack.com/archives/C03DG0P5NDQ/p1681123066710539?thread_ts=1681123066.710539&cid=C03DG0P5NDQ

2023-04-17 12:56 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseErrorConverter.kt
> +    override fun convert(message: SeedPhraseError?): String? {
в таком случае можно сделать weak ссылку на контекст на всякий случай, для перестраховки.
Но вообще это ведь домейн слой, он не должен никак знать про контекст. Лучше прокинуть наружу тип ошиби и разобрать уже в presentation

2023-04-19 12:45 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/ui/ImportSeedPhraseScreen.kt
> +            val message = SeedPhraseErrorConverter(LocalContext.current).convert(state.error)
Обсудили в личке

2023-04-19 12:55 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseErrorConverter.kt
> +    override fun convert(message: SeedPhraseError?): String? {
Переделал немного - ушел от хранения контекста

2023-04-19 13:01 UTC, MamaLemon approved these changes

2023-04-19 13:01 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/ui/ImportSeedPhraseScreen.kt
> +            val message = SeedPhraseErrorConverter(LocalContext.current).convert(state.error)
поставь еще плз сюда todo чтобы заменить на TextReference

2023-04-19 13:04 UTC, kozarezvlad approved these changes

2023-04-19 13:06 UTC, merged