AND- 3176 #6 Wallet2: Import: show suggestions and insert on tap
tangem/tangem-app-android-old pull request #863
Opened 2023-04-16 18:56 UTC by gbixahue

2023-04-19 15:44 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/domain/PartWordFinder.kt
> +internal class PartWordFinder {
было бы хорошо доку на этот класс

2023-04-19 15:47 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    private var suggestionWordInserted: AtomicBoolean = AtomicBoolean(false)
он меняется из разных потоков? не может тогда случится состояния неверного?

2023-04-19 15:47 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +        viewModelScope.launchSingle {
на launchSingle стоит указать явно диспатчер, это позволит тестировать

2023-04-19 16:29 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +        viewModelScope.launchSingle {
```
 private fun CoroutineScope.launchSingle(block: suspend CoroutineScope.() -> Unit): Job {
        return viewModelScope.launch(dispatchers.single, block = block)
 }
```

2023-04-19 16:29 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    private var suggestionWordInserted: AtomicBoolean = AtomicBoolean(false)
не может, т.к. работает на `dispatchers.single`

2023-04-19 16:29 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/domain/PartWordFinder.kt
> +internal class PartWordFinder {
Ок, напишем

2023-04-19 17:40 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +        viewModelScope.launchSingle {
Понял о чем тут, как раз тот диспатчер что ранее всплывал.
Теперь из ПР больше понятно где используется и тогда вопрос такой, чем не подходит тут main? Корутина на main не будет блокировать UI в то же время работа будет на одном потоке.

2023-04-19 17:40 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    private var suggestionWordInserted: AtomicBoolean = AtomicBoolean(false)
А зачем тогда Atomic?

2023-04-19 17:47 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    private var suggestionWordInserted: AtomicBoolean = AtomicBoolean(false)
Удобно было использовать для
'suggestionWordInserted.getAndSet(false)'

2023-04-19 17:57 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +        viewModelScope.launchSingle {
А разве main диспатчер корутины работает на каком то другом ui потоке? На сколько я помню - это один и тот же поток.

2023-04-20 07:10 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +        viewModelScope.launchSingle {
да этот тот же UI поток, но поскольку это корутина он не будет фризить UI т.к. функции будут suspend'ится. Также это 1 поток и не потребуется кастомных диспатчеров. Просто тут не видно тяжелых операций каких то

2023-04-20 11:00 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +        viewModelScope.launchSingle {
Сейчас не видно, а завтра появится. Я против того, чтобы вообще как-то трогать UI поток - пусть занимается анимацией и отображением, а все остальное подальше от него.

2023-04-20 14:04 UTC, MamaLemon requested changes

2023-04-20 14:04 UTC, MamaLemon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/domain/PartWordFinder.kt
> +        if (cursorPosition > charText.size || cursorPosition < 0) {
Как мне кажется, было бы хорошо объединить данные ифы следующим образом: под каждое условие создается локальная переменная, название которой учитывает смысл условия (комменты внутри ифа), а потом просто это все складывается в один иф.

2023-04-20 14:04 UTC, MamaLemon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +                // do nothing
Если будет дополняться, то хорошо бы указать TODO

2023-04-21 07:23 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +                // do nothing
Нет, не будет. На это условии просто должно остановится. Можно прописать return

2023-04-21 15:24 UTC, kozarezvlad approved these changes

2023-04-21 15:50 UTC, MamaLemon approved these changes

2023-04-21 15:56 UTC, merged