AND-3251 Implement use case for card scanning on :domain:card module
tangem/tangem-app-android-old pull request #885
Opened 2023-04-19 16:17 UTC by iiiburnyiii

- Добавил :domain:core модуль, все общие штуки (базовые интерфейсы/утилиты/etc.) стоит складывать сюда
- Добавил :domain:card модуль, пока что-то тут только UseCase для сканирования карты. Тут стоит подумать об архитектуре, насколько мелко мы будем дробить domain модули:
   - один модуль - один UseCase
   - один модуль - много UseCase`ов
   - один модуль - одна domain модель (e.g. CardInteractor или CardModel) с кучкой методов

2023-04-21 14:06 UTC, kozarezvlad commented on domain/core/src/main/kotlin/com/tangem/domain/core/chain/ChainProcessor.kt
> +                .onRight {
все забываю onRight это ошибка?

2023-04-21 14:07 UTC, kozarezvlad commented on gradle/dependencies.toml
> +arrow = "1.2.0-RC"
мб стабильную версию, раз уж тянем?

2023-04-21 14:09 UTC, kozarezvlad commented
Насчет деления по модулям предлагаю вариант 2 (один модуль - много UseCase`ов), но UseCase'ы принадлежат одной предметной области

2023-04-21 14:26 UTC, iiiburnyiii commented on domain/core/src/main/kotlin/com/tangem/domain/core/chain/ChainProcessor.kt
> +                .onRight {
Так, тут уже я лоханулся, спасибо, что заметил
- `Either.Left` - ошибка
- `Either.Right` - успех

2023-04-21 14:42 UTC, iiiburnyiii commented on gradle/dependencies.toml
> +arrow = "1.2.0-RC"
Она считается стабильной, хз почему так назвали. В этой версии кучу ненужного задипрекейтили, и подготавливаются к 2.0

2023-04-24 09:47 UTC, kozarezvlad approved these changes

2023-04-24 23:51 UTC, MamaLemon commented
Если я правильно помню, то мы пока не обсуждали данный вопрос, как все это хранить и использовать.
Мб проведем созвон, где расскажешь свое видение?

2023-04-24 23:58 UTC, MamaLemon commented on domain/card/build.gradle.kts
> +    api(project(":domain:core"))
1) api метод не считается устаревшим?
2) Если я правильном помню, то domain модули не должны зависеть от чего либо

2023-04-25 00:01 UTC, MamaLemon requested changes

2023-04-25 00:01 UTC, MamaLemon commented on domain/card/src/main/kotlin/com/tangem/domain/card/model/ScanCardParams.kt
> +class ScanCardParams(
Это не будет дата классом?

2023-04-25 08:02 UTC, iiiburnyiii commented on domain/card/build.gradle.kts
> +    api(project(":domain:core"))
1. Нет, это `compile` устаревший, `api` работает так же как и `implementation`, но прокидывает этот модуль на уровень дальше. То есть модуль подключающий в себя `:domain:card` получит доступ и к `:domain:core`. Но в данном случае это не нужно, поправлю на `implementation`
2. `:domain:core` не содержит логики, только сущности, которые могут быть переиспользованы другими domain модулями, отписал это в описании МРа

2023-04-25 08:05 UTC, iiiburnyiii commented on domain/card/src/main/kotlin/com/tangem/domain/card/model/ScanCardParams.kt
> +class ScanCardParams(
Тут дата не нужен, этот класс не нужно будет копировать или сравнивать, тут просто параметры для use case`а лежат

2023-04-25 08:35 UTC, MamaLemon approved these changes

2023-04-25 09:34 UTC, merged