AND-3426 core Ui notification item
tangem/tangem-app-android-old pull request #904
Opened 2023-04-24 15:42 UTC by kozarezvlad

2023-04-24 23:49 UTC, MamaLemon requested changes

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +package com.tangem.core.ui.components
Ошибка в названии файла

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +    iconColor: Color,
Как предложение, я бы переименовал в `tint`, так как в базовых компонентах это называется так, но дело вкуса

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +                        start = TangemTheme.dimens.spacing28,
horizontal?

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +                    .clickable { onCloseClick.invoke() },
Кажется, такой вариант более читабельный
.clickable(onClick = onCloseClick)

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +                        start = TangemTheme.dimens.spacing28,
horizontal?

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +            Text(
Элемент может быть больше чем в одну строчку?

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +            Icon(
Мб обернуть в `IconButton()` из материал дизайн?
Отличный компонент, который из коробки сделает эту иконку удобной для пользователя. Например, clip и padding

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +                Text(
Элемент может быть не в одну строчку?

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +                Icon(
IconButton?

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +        shape = RoundedCornerShape(TangemTheme.dimens.size18),
Под радиус есть отдельный тип дименсов.
Странно, что он такой большой, хм

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +private fun NotificationCardTemplate(onClick: (() -> Unit)? = null, content: @Composable () -> Unit) {
Можно дабавить лямбде ресивер BoxScope, чтобы потом в унаследованных элементах не добавлять еще один слой Box {}

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +                    start = TangemTheme.dimens.spacing12,
horizontal, vertical?

2023-04-24 23:49 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +        SpacerH32()
Можно проставить `verticalArrangement = Arrangement.spacedBy(...)` у `Column`, чтобы после каждого эл-та не писать отступ, но это дело вкуса

2023-04-25 06:13 UTC, kozarezvlad commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +    iconColor: Color,
в Image например colorFilter, как по мне iconColor явно говорит что ты передашь цвет иконки, а как уже под капотом там через tint или будет использоваться не Icon и не tint уже не важно снаружи. Главное явно понимать, что передал цвет

2023-04-25 06:15 UTC, kozarezvlad commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +            Text(
да по идее, не вижу препятствий

2023-04-25 06:20 UTC, kozarezvlad commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +                Text(
может. Плюс как оказалось достаточно много юзеров с увеличенным шрифтом ходит и надо переносить в любом случае

2023-04-25 06:36 UTC, kozarezvlad commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +                Icon(
она не кликабельна, просто иконка, кликается весь элемент нотификации

2023-04-25 06:51 UTC, kozarezvlad commented on core/ui/src/main/java/com/tangem/core/ui/components/Nottifications.kt
> +        SpacerH32()
посколько превью, не так важно

2023-04-25 08:43 UTC, MamaLemon approved these changes

2023-04-27 11:59 UTC, merged