AND-3423 wallet header
tangem/tangem-app-android-old pull request #911
Opened 2023-04-26 06:44 UTC by kozarezvlad

В превью заглушка какая есть, сами карты будут тянутся с бэка

<img width="372" alt="Снимок экрана 2023-04-26 в 09 42 50" src="https://user-images.githubusercontent.com/8160279/234491419-0100be55-c8f7-4c78-a2e8-18930271338b.png">
<img width="368" alt="Снимок экрана 2023-04-26 в 09 43 08" src="https://user-images.githubusercontent.com/8160279/234491431-db630ab6-59ec-41ec-b650-e071023ba4d2.png">

2023-04-27 07:04 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/BalanceUIState.kt
> +enum class BalanceUIState {
internal?

2023-04-27 07:14 UTC, MamaLemon requested changes

2023-04-27 07:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +fun WalletHeaderCard(walletHeaderConfig: WalletHeaderConfig) {
Мб использовать название config вместо полного названия? В контексте использования внутри функции не так важно, что это именно WalletHeader

2023-04-27 07:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                        horizontal = TangemTheme.dimens.spacing12,
all?

2023-04-27 07:14 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .fillMaxWidth()
Вроде как избыточно из-за weight

2023-04-27 07:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .padding(end = TangemTheme.dimens.spacing18)
Мб совместить с отступом рутой вьюхи, чтобы это было в одном месте?

2023-04-27 07:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +            Text(
maxLines = 1?

2023-04-27 07:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +            text = walletName,
maxLines = 1?

2023-04-27 07:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                text = "•••",
maxLines = 1?

2023-04-27 07:14 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +            Text(
maxLines = 1?

2023-04-27 17:31 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                text = "•••",
тут текст не меняется и всегда ...

2023-04-27 17:32 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +            Text(
тут текст не меняется и всегда -

2023-04-27 17:34 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .padding(end = TangemTheme.dimens.spacing18)
у рутовой вьюхи есть свои отступы, all. Они дают отступ всему контенту внутри нее, у этой дочерней же отступ внутри рутовой от ее границ уже. На мой взгляд так понятнее, если вынести выше, то нужно складывать отступы считать и не очевидно, зачем такой большой будет

2023-04-27 17:35 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/BalanceUIState.kt
> +enum class BalanceUIState {
не выйдет, ругает потом в публичном config

2023-04-28 00:50 UTC, MamaLemon requested changes

2023-04-28 00:50 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .padding(end = TangemTheme.dimens.spacing18)
В принципе спорить смысла не вижу.
Меня просто засмущал этот момент тем, что может произойти ситуация, когда надо что-то поменять, а отступы от конца вьюхи разбросаны по разным места. Хотя если так подумать, то и там, и здесь - это просто отступ от края.

2023-04-28 00:50 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +        Row {
Хорошо бы добавить отступ между эл-тами с `weight()`. Некая гарантия, что если один из элементов будет очень широкий, то они не пересекутся

2023-04-28 00:50 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .weight(weight = 1f),
Интересный момент, кстати, с проставлением размера изображения как weight. Не нужно ли проставлять `contentScale` для гарантии, что изображение впишется так, как мы хотим?

2023-04-28 07:08 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .padding(end = TangemTheme.dimens.spacing18)
наоборот получается если нужно будет поменять, то скорее всего это отступ картинки, и он сразу у картинки, поэтому тебе не надо думать об отступах вьюхи рута, она живет сама по себе

2023-04-28 07:09 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +        Row {
разве в Row элементы могут налезть друг на друга? вроде нет же

2023-04-28 07:12 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .weight(weight = 1f),
вообще мне тут не нравится weight, да и стоит фиксированный размер картинки.
Насчет contentScale да, согласен, добавлю.

2023-04-28 10:32 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +        Row {
Я имел ввиду, что они будут впритык. Если это норм поведение - то ок

2023-05-02 18:41 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +        Row {
пробовал по разному, переверстаю на constraint в ПР с токенами, будет лучше.

2023-05-02 18:41 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .weight(weight = 1f),
добавил

2023-05-03 07:09 UTC, MamaLemon approved these changes

2023-05-03 07:36 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                SpacerH8()
Предлагаю вместо `Space` использовать `Modifier.spacedBy()` у родителя. Кажется это чуть более аккуратный способ работать с отступами

2023-05-03 07:36 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +fun WalletHeaderCard(config: WalletHeaderConfig) {
Может все таки модифаер наружу отпустить?)

2023-05-03 07:36 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +            SpacerW4()
Тут тож можно `spacedBy`

2023-05-03 07:36 UTC, iiiburnyiii commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +        shape = RoundedCornerShape(TangemTheme.dimens.radius16),
Уже видел такой шейп в рефералке, стоит закинуть в тему

2023-05-03 10:11 UTC, iiiburnyiii approved these changes

2023-05-03 10:28 UTC, merged