AND-3252 Move shared preferences store to :data:store:preferences module
tangem/tangem-app-android-old pull request #913
Opened 2023-04-26 12:32 UTC by iiiburnyiii

Переместил и немного отрефакторил класс `PreferencesStorage`. Теперь он лежит в новом модуле - `:data:store:preferences`
Есть небольшие изменения в `TopUpController`, `AppCurrencyMiddleware` и `GlobalMiddleware` связанные с добавление data моделей (классы с суффиксом `DM`), в остальном изменились только импорты

2023-04-26 16:58 UTC, kozarezvlad approved these changes

2023-04-26 16:58 UTC, kozarezvlad commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/model/TopupInfoDM.kt
> +    enum class CardBalanceState(val serializedName: String) {
Этот класс лежал в AnalyticsParam, а юзается для всего или только аналитики.
Аналитика пока еще не в рефакторинге конечно, но мб куда то запихнуть его отдельно хотя бы пока или пометить что к аналитике относится, если только к ней

2023-04-26 16:58 UTC, kozarezvlad commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/AppRatingLaunchObserver.kt
> +        updateNextShowing(999999999)
)))

2023-04-26 21:07 UTC, iiiburnyiii commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/model/TopupInfoDM.kt
> +    enum class CardBalanceState(val serializedName: String) {
Этот маппиться в `TopUpController` в тот, что в `AnalyticsParam` лежит. Сделал так, чтобы хоть как-то логику развязать

2023-04-26 21:08 UTC, iiiburnyiii commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/AppRatingLaunchObserver.kt
> +        updateNextShowing(999999999)
Это не я, честно) Этот класс просто копировал

2023-04-27 06:42 UTC, MamaLemon commented on data/store/preferences/src/main/AndroidManifest.xml
> +<manifest package="com.tangem.store.preferences" />
Кстати, все забываю сказать. AGP ворнинги кидает из-за того, что мы наименование пакета указываем в манифесте. Предполагается ли вынос в гредл?

2023-04-27 06:43 UTC, MamaLemon commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/di/PreferencesStoreModule.kt
> +object PreferencesStoreModule {
internal?

2023-04-27 06:51 UTC, MamaLemon requested changes

2023-04-27 06:51 UTC, MamaLemon commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/model/CurrencyDM.kt
> +data class CurrencyDM(
Как мне кажется, использование аббревиатуры ухудшает качество и понимание кода. Это примерно тоже самое, что и `Impl`. Я предлагаю все-таки избавляться от сокращений, чтобы код можно было читать без дополнительного углубления в аабревиатуру

2023-04-27 06:51 UTC, MamaLemon commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/PreferencesStore.kt
> +class PreferencesStore @Inject internal constructor(applicationContext: Context) {
А можешь, пожалуйста, подробнее рассказать об этом классе?
У нас в dataStores уже добавлены shared preferences, которые мы хотим использолвать как единое хранилище.

2023-04-27 07:39 UTC, iiiburnyiii commented on data/store/preferences/src/main/AndroidManifest.xml
> +<manifest package="com.tangem.store.preferences" />
Да, но не в этом таске

2023-04-27 07:44 UTC, iiiburnyiii commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/model/CurrencyDM.kt
> +data class CurrencyDM(
Сейчас эта модель нужна как прослойка между data и domain слоями
У нас и так 7(!) классов с названиеим `Currency`, их нужно как-то разделять

2023-04-27 07:46 UTC, iiiburnyiii commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/PreferencesStore.kt
> +class PreferencesStore @Inject internal constructor(applicationContext: Context) {
Речь о гугловской либе - [DataStore](https://developer.android.com/topic/libraries/architecture/datastore)

2023-04-28 00:19 UTC, MamaLemon commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/model/CurrencyDM.kt
> +data class CurrencyDM(
Согласен, что их надо разделять, но когда понадобится создать восьмую модель, то мы опять будем использовать аббревиатуру?
Как мне кажется, если причина только в том, что нужно разделять название, то можно добавлять приставку к названию классу виде наименования пакета. В больших проектах, где работает больше 100 человек, так и делают.

2023-04-28 00:21 UTC, MamaLemon commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/PreferencesStore.kt
> +class PreferencesStore @Inject internal constructor(applicationContext: Context) {
1) Мб в таком кейсе поместить ее в dataSource к остальным источникам?
2) Сейчас название перекликается с SharedPreferences? Есть какое-то обоснование, почему в данном нейминге тоже фигурирует Preferences?

2023-05-02 07:46 UTC, iiiburnyiii commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/model/CurrencyDM.kt
> +data class CurrencyDM(
Тут вопрос по неймингу, надо его на всеобщее обсуждение вынести

2023-05-02 08:00 UTC, iiiburnyiii commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/PreferencesStore.kt
> +class PreferencesStore @Inject internal constructor(applicationContext: Context) {
1. Не совсем понял) Это же не источник данных, а хранилище. В TODO коммент о том, что стоит в дальнейшем выпилить использование Shared Preferences на использование DataStore, как более современноий и рекомендуемой гуглом технологии
2. Потому-что сейчас там под капотом shared preferences. В дальнейшем это, пожалуй, стоит раздалеть на разные модули (:data:store:settings > AppSettingsStore, :data:store:card > ScannedCardsStore, etc.). Но это не в рамках этого таска, там много работы

2023-05-03 07:08 UTC, MamaLemon commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/PreferencesStore.kt
> +class PreferencesStore @Inject internal constructor(applicationContext: Context) {
1. Кажется, что данное хранилище также является источником данных для нас - источник локальных данных.
2. Я своим комментом хотел подметить, что из названия `PreferencesStore` не совсем понятно для чего оно. Хранилище предпочтений? 😅

2023-05-03 07:26 UTC, iiiburnyiii commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/PreferencesStore.kt
> +class PreferencesStore @Inject internal constructor(applicationContext: Context) {
1. А где разница между store и source по твоей логике? 🤔
Получается store отвечает только за вытаскивание данных из какого-то хранилища? Что-то типа:
```
class PreferencesStore {

  fun getString(key: String): String?

  fun putString(key: String, s: String)

  fun getInt(key: String): Int?

  // ...
}
```
А source уже более заточен на какую-то предметную область и уже ближе к репозиторию?
2. Сейчас сложно по другому назвать - там сейчас разные сторы свалены в кучу и их объеденяет только использование shared preferences

2023-05-03 08:47 UTC, MamaLemon commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/PreferencesStore.kt
> +class PreferencesStore @Inject internal constructor(applicationContext: Context) {
1. Я вот и хочу сказать, есть ли смысл нам их отделять? Что нам даст данное разделение? Для нас он и так, и сяк просто некоторая сущность, с которой работает репозиторий.
2. Понял

2023-05-03 08:50 UTC, iiiburnyiii commented on data/store/preferences/src/main/kotlin/com/tangem/store/preferences/PreferencesStore.kt
> +class PreferencesStore @Inject internal constructor(applicationContext: Context) {
Согл, давай тогда переименую в модуль и класс в source

2023-05-04 11:01 UTC, MamaLemon approved these changes

2023-05-04 11:59 UTC, merged