And 3424 token item component
tangem/tangem-app-android-old pull request #919
Opened 2023-04-30 15:41 UTC by kozarezvlad

2023-05-02 00:27 UTC, MamaLemon requested changes

2023-05-02 00:27 UTC, MamaLemon commented on app/src/main/java/com/tangem/tap/features/tokens/impl/presentation/ui/TokenItem.kt
> +// TODO(use CurrencyPlaceholderIcon here?)
Готов взяться, но нужно будет провести созвон

2023-05-02 00:27 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Shimmers.kt
> +fun ShimmerRectangle(width: Dp, height: Dp) {
Хорошо бы напрямую Modifier прокидывать, как обсуждали ранее

2023-05-02 00:27 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Shimmers.kt
> +            .padding(vertical = TangemTheme.dimens.spacing4)
А для чего этот отступ?

2023-05-02 00:27 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Shimmers.kt
> +fun ShimmerRectangle(width: Dp, height: Dp) {
Хорошо бы превьюхи добавить и доку написать

2023-05-02 00:27 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +package com.tangem.feature.main.presentation.ui
А пакет соответствует реальному месту расположения файла? А то вообще ничего про wallet не сказано

2023-05-02 00:27 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +        ConstraintLayout(modifier = Modifier.matchParentSize()) {
А есть разница между fillMaxSize и matchParentSize?

2023-05-02 00:27 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +    when (config.tokenUIState) {
Заметил, что некоторые стейты имеют совпадения по вьюхам. Например, иконка и тайтл. Мб сузить определение стейта до определенных кейсов вместо того, чтобы при каждом изменении перерисовывать сразу весь компонент

2023-05-02 00:27 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +            val modifier = Modifier.align(Alignment.CenterVertically)
У Row можно проставить выравнивание для всех вьюх сразу

2023-05-02 00:27 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +            Row {
Все Text могут быть многострочными в этом компоненте?

2023-05-02 00:27 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .weight(weight = 1f),
Уже был вопрос по подобному изображению: вес и contentScale

2023-05-02 00:27 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                text = "•••",
Я пока сам для себя не выявил лучшей практики, но в последний раз делал так, чтобы вьюха вообще ничего не знала о данных, даже если какой-то стейт имеет их по-умолчанию. Таким образом, если обнаружиться баг, то ты точно знаешь, что обработка данных стейта происходит во вью моделе и не придется бегать по разным слоям, выясняя потенциальное проблемное место

2023-05-02 00:27 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/config/TokenV2Config.kt
> +data class TokenV2Config(
internal?

2023-05-02 10:49 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                    .weight(weight = 1f),
тут просто не подтянуты изменения из соседнего ПР

2023-05-02 10:50 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +            Row {
да, для поддержки тех у кого большие шрифты стоят

2023-05-03 10:29 UTC, Yoggam1 approved these changes
аппрув с учетом комментов @MamaLemon

2023-05-03 11:00 UTC, kozarezvlad commented on core/ui/src/main/java/com/tangem/core/ui/components/Shimmers.kt
> +            .padding(vertical = TangemTheme.dimens.spacing4)
копипастнул, хорошо, что заметил

2023-05-03 16:49 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/tokens/impl/presentation/ui/TokenItem.kt
> +// TODO(use CurrencyPlaceholderIcon here?)
Можешь завести таску тогда под это

2023-05-03 16:49 UTC, kozarezvlad commented on core/ui/src/main/java/com/tangem/core/ui/components/Shimmers.kt
> +fun ShimmerRectangle(width: Dp, height: Dp) {
написал, переименовал

2023-05-03 16:49 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +package com.tangem.feature.main.presentation.ui
поправил

2023-05-03 16:49 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +        ConstraintLayout(modifier = Modifier.matchParentSize()) {
да, fillMaxSize растягивает на всю ширину экрана увеличивая родительские компонент, а matchParentSize только в рамках родительского ставит границы дочернего

2023-05-03 16:49 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +    when (config.tokenUIState) {
поправил, объединили несколько стейтов. Думаю далее в процессе использования еще чуть могут быть правки

2023-05-03 16:49 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/Tokens.kt
> +            val modifier = Modifier.align(Alignment.CenterVertically)
проставил

2023-05-03 16:49 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/WalletHeader.kt
> +                text = "•••",
в данном случае эти данные неразрывно связаны UI, при состоянии скрытого баланса должны быть точки, это как иконка по факту получается. В конкретном случае не думаю что правильно было бы вынести наружу это, поскольку об этом никто кроме вью знать не должен

2023-05-03 16:49 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/main/presentation/ui/config/TokenV2Config.kt
> +data class TokenV2Config(
в таком случае компоненты для кошелька будет недоступны снаружи, не уверен что мы сможем сходу в отдельном модуле этом затянуть весь новый дизайн и не придется юзать снаружи

2023-05-04 07:28 UTC, MamaLemon commented on core/ui/src/main/java/com/tangem/core/ui/components/Shimmers.kt
> +fun ShimmerRectangle(width: Dp, height: Dp) {
Мб тогда параметры размера вьюхи не передавать отдельно от Modifier?

2023-05-04 07:55 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/Tokens.kt
> +            text = "Unreachable", // TODO (conform this text)
А что с этим текстом? Он в ресах должен быть?

2023-05-04 07:56 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/Tokens.kt
> +        else -> {
Как мне кажется, если такие ветки возникают, то надо создавать sealed interface и помечать им данные стейты, а еще лучше - это вынести общий набор параметров стейтов в этот интерфейс

2023-05-04 07:56 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/Tokens.kt
> +            text = "Unreachable", // TODO (conform this text)
Да, пока так оставил, положу в ресы когда будут текстовки не только en

2023-05-04 07:57 UTC, Mama1emon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/Tokens.kt
> +        Box(
А точно Box здесь необходим? Не получится внутренние отступы проставить в Surface?

2023-05-04 07:59 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/Tokens.kt
> +        if (hasPending) {
Вроде как можно упростить данный if. У нас всегда будет Row { Text }, а если выполнятся условие, то в Row добавится еще и изображение

2023-05-04 08:00 UTC, MamaLemon commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/WalletHeader.kt
> +        // Row(
Можно удалить?

2023-05-04 08:55 UTC, kozarezvlad commented on features/wallet/impl/src/main/java/com/tangem/feature/wallet/presentation/ui/Tokens.kt
> +        else -> {
переделал чуть стейты

2023-05-04 09:23 UTC, MamaLemon approved these changes

2023-05-04 09:49 UTC, merged