AND-3179 wallet2: joining seedPhrase onboarding with wallet onboarding
tangem/tangem-app-android-old pull request #920
Opened 2023-05-02 06:57 UTC by gbixahue

2023-05-17 09:01 UTC, Mama1emon requested changes, later dismissed

2023-05-17 09:01 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +@Suppress("LongMethod", "ComplexMethod")
Предлагаю разбить новый метод на приватные функции, чтобы изначально не плодить ворнинги детекта

2023-05-17 09:01 UTC, Mama1emon commented on app/src/main/res/layout/view_onboarding_progress.xml
> +        android:progressBackgroundTint="#32000000"
Предлагаю вынести в файл colors.xml

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +class OnboardingSeedPhrase : OnboardingSeedPhraseApi {
А зачем обернуто в класс?

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +    override fun ScreenContent(viewModel: SeedPhraseViewModel, maxProgress: Int) {
Предлагаю не передавать вью модель аргументом, так как данный объект по умолчанию является unstable + к нему невозможно написать превью. Лучшей практикой считается передача непосредственно стейта

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +            progress = progress.toFloat() / maxProgress,
А зачем тут преобразовываем во float?

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +                state = viewModel.uiState.introState,
Не совсем понимаю, как это работает. Стейты для каждой вьюхи разные, но они все хранятся в разных переменных одного стейта экрана?

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseMediator.kt
> +interface SeedPhraseMediator {
Не совсем понятно, что это за компонент и к какому слою относится? Домейн?

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseRouter.kt
> +    private val onBack: () -> Unit,
Как мне кажется, здесь нарушается принцип инкапсуляции (ну или что-то типо того). Роутер в данном случае не скрывает логику навигации, а получаем из вне

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    fun setRouter(router: SeedPhraseRouter) {
Мб объединить в одну функцию? Типо инициализация зависимостей

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +        // uiState = uiBuilder.importSeedPhrase.updateCreateWalletButton(mediateState, enabled = false)
Удалить?

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    private val progressByScreen = mapOf(
А как это используется?

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +            is CompletionResult.Failure -> {
В таком случае есть ли смысл делать when?

2023-05-17 09:01 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/data/di/OnboardingDataModule.kt
> +        return DefaultMnemonicRepository(Wordlist.getWordlist(application))
А для чего мы скармливаем объект Application?

2023-05-17 09:03 UTC, kozarezvlad commented on app/src/main/res/layout/view_onboarding_progress.xml
> +        android:progressBackgroundTint="#32000000"
жду комментов что в color вчера удалился ресурс)

2023-05-17 09:13 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +@Suppress("LongMethod", "ComplexMethod")
я не вижу особого смысла, потому что тут в каждом when довольно компактно все. Но можно

2023-05-17 09:14 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/data/di/OnboardingDataModule.kt
> +        return DefaultMnemonicRepository(Wordlist.getWordlist(application))
чтобы файл можно было прочитать

2023-05-17 09:15 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    private val progressByScreen = mapOf(
вот на 65 строке

2023-05-17 09:15 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    fun setRouter(router: SeedPhraseRouter) {
да вроде без разницы

2023-05-17 09:17 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +            is CompletionResult.Failure -> {
мы много где регулярно используем when при обработке результата. удобно.

2023-05-17 09:18 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseRouter.kt
> +    private val onBack: () -> Unit,
это не общий роутер, это Антон сделал, чтобы только внутри новых compose экранов по сиду перемещаться. Он выполняет всю свою логику. Переходы за пределы него - этими внешними функциями

2023-05-17 09:20 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseMediator.kt
> +interface SeedPhraseMediator {
Связь с redux по сути, с общей логикой онбординга.

2023-05-17 09:21 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +            progress = progress.toFloat() / maxProgress,
ну так progress в LinearProgressIndicator - это float. если мы результат деления интов во float сконвертнем, то получится явно не то )

2023-05-17 09:26 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +                state = viewModel.uiState.introState,
а что непонятно? зайди посмотри. uiState содержит переменные со стейтами разных экранов. currentScreen - enum с текущим экраном

2023-05-17 09:26 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +class OnboardingSeedPhrase : OnboardingSeedPhraseApi {
@gbixahue

2023-05-17 09:27 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +    override fun ScreenContent(viewModel: SeedPhraseViewModel, maxProgress: Int) {
вроде дальше уже по конкретным экранам рассовываются стейты, а не сама viewModel

2023-05-17 09:28 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +    override fun ScreenContent(viewModel: SeedPhraseViewModel, maxProgress: Int) {
превью к самому общему экрану-контейнеру обычно и не пишут

2023-05-17 09:28 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +    override fun ScreenContent(viewModel: SeedPhraseViewModel, maxProgress: Int) {
@gbixahue

2023-05-18 07:05 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +    override fun ScreenContent(viewModel: SeedPhraseViewModel, maxProgress: Int) {
unstable данные не позволяют функции работать оптимально

2023-05-18 07:06 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +            progress = progress.toFloat() / maxProgress,
Может быть есть смысл сделать поле сразу типом Float?

2023-05-18 07:09 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +                state = viewModel.uiState.introState,
Как мне кажется, этот подход заведет весь флоу в могилу. Так как для нескольких экранов у нас один стейт и одна вью модель - чистое нарушение single responsobility. Разбираться, какая логика используется для одного, какая для другого экрана - будет тяжело. Понятно будет только тому, кто это писал

2023-05-18 07:11 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseMediator.kt
> +interface SeedPhraseMediator {
Не понял из твоего ответа, какой это слой. Если это шарит домейн логику, то, как мне кажется, компонент Interactor - это более понятная сущность, чем медиатор

2023-05-18 09:26 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> +    suspend fun resetToFactorySettings(cardId: String? = null): CompletionResult<CardDTO> {
а что будет резетится до заводских когда cardId == null? может на уровень выше обработать?

2023-05-18 09:26 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> -                maxFirmwareVersion = FirmwareVersion(major = 4, minor = 52),
а не это добавляли чтобы у старых юзеров проблем не было, почему убираем?

2023-05-18 09:26 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingSeedPhraseStateHandler.kt
> +internal class OnboardingSeedPhraseStateHandler(
в скоупе чего живет этот handler? не будет ли OnboardingWalletFragment утекать?

2023-05-18 09:26 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +                store.dispatch(OnboardingWallet2Action.ImportWallet(mnemonicComponents, callback))
а почему через action'ы, а не юзая вью модель нового онбординга?

2023-05-18 09:26 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/data/di/OnboardingDataModule.kt
> +        return DefaultMnemonicRepository(Wordlist.getWordlist(application))
мб контекста хватило бы?

2023-05-18 11:38 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> +    suspend fun resetToFactorySettings(cardId: String? = null): CompletionResult<CardDTO> {
без cardId будет любая карта ресеттиться. Это из-за кейса, когда мы ресетим бэкап карту - мы не получаем наружу ее номер, но мы предлагаем пользователем ее ресетнуть, если на ней были созданы кошельки

2023-05-18 11:39 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> -                maxFirmwareVersion = FirmwareVersion(major = 4, minor = 52),
это добавляли, чтобы нельзя было воллет 2.0 карты просканировать в старой версии приложения

2023-05-18 11:39 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/data/di/OnboardingDataModule.kt
> +        return DefaultMnemonicRepository(Wordlist.getWordlist(application))
да, можно контекст. Это будет лучше?

2023-05-18 11:39 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +            progress = progress.toFloat() / maxProgress,
зачем?

2023-05-18 11:39 UTC, roman-pv commented on app/src/main/res/layout/view_onboarding_progress.xml
> +        android:progressBackgroundTint="#32000000"
ну вот да ) так намного безопаснее)

2023-05-18 11:41 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingSeedPhraseStateHandler.kt
> +internal class OnboardingSeedPhraseStateHandler(
Он живет во фрагменте. Тут один публичный метод, в принципе можно просто туда прокидывать фрагмент, вроде не обязательно сеттить как поле класса. 
@gbixahue

2023-05-18 11:42 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +                store.dispatch(OnboardingWallet2Action.ImportWallet(mnemonicComponents, callback))
потому что это уже в рамках общего флоу онбординга хэндлится. 
@gbixahue

2023-05-18 12:24 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +@Suppress("LongMethod", "ComplexMethod")
Можно тогда создать еще один класс с методом handle, внутри которого when разберет по типам и будет вызывать приватные функции.

Нужно ли? Таким же способом обрабатывается и остальное. Тем более, что это будет сноситься - думаю пережить Suppress мы сможем

2023-05-18 12:24 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingSeedPhraseStateHandler.kt
> +internal class OnboardingSeedPhraseStateHandler(
Он живет в скоупе OnboardingWalletFragment. Там должен и умереть

2023-05-18 12:24 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +                store.dispatch(OnboardingWallet2Action.ImportWallet(mnemonicComponents, callback))
потому, что эти action'ы тригерят дефолтные события, которые ранее отрабатывали после создания кошелька

2023-05-18 12:24 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +class OnboardingSeedPhrase : OnboardingSeedPhraseApi {
Мы же хотели, чтобы наши фичи наружу выдавали интефейс OnboardingSeedPhraseApi, через который смогли бы получить view для отображения фичи.

ViewModel в нее передеается, т.к. невозможно, на данный момент, полностью инкапсулировать создание объекта в рамках фичи. (думаю тут можно дописать туду...)

2023-05-18 12:24 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +    override fun ScreenContent(viewModel: SeedPhraseViewModel, maxProgress: Int) {
Можно ViewModel разместить в конструкторе OnboardingSeedPhrase

2023-05-18 12:24 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +            progress = progress.toFloat() / maxProgress,
progress и maxProgress это репрезентация enum, которые используют int. В старом онбординге используется ProgressBar (на основе xml) и он работает на int. 

Можно переделать аргументы функции на флоат и приподнять его чуть выше, но так, чтобы старые модели не рефачить. В таком виде и композ функции станет более чистыми...

2023-05-18 12:24 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +                state = viewModel.uiState.introState,
Это решение принято на основе того, что данная модель не помешает перейти на более раздробленные стейты, при это уменьшит время на разработку (если разбивать каждый экран на отдельные viewModel всплыл бы оверхед по времени), а так же позволяет упростить вопрос с инициализацией одной viewModel и пропихиванием ее в фичу (по другому пока что сделать сложно)

2023-05-18 12:24 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseMediator.kt
> +interface SeedPhraseMediator {
Да, интерактор. Но интерактор уже есть и он работает в рамках фича модуля. А это связующая прокладка с псевдо интерактором в редуксе старого онбординга. 
Как назвать?

2023-05-18 12:24 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +    fun setRouter(router: SeedPhraseRouter) {
В дальнейшем эти оба объекта должны быть удалены. Поэтому мне кажется, что разница нет... ну удалим чуть больше

2023-05-18 12:24 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +            is CompletionResult.Failure -> {
если есть альтернативы, которыми можно было бы все упростить сделать компактней, красивее?
Учитывая тот случай, что может появится возможность обработки ошибки во viewModel

2023-05-18 13:58 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingSeedPhraseStateHandler.kt
> +internal class OnboardingSeedPhraseStateHandler(
да, можно и так

2023-05-18 14:14 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> -                maxFirmwareVersion = FirmwareVersion(major = 4, minor = 52),
и если мы сейчас уберем, то версия же приложения будет с всё еще выключенным онбордингом. Мб включить когда уже 100% готовы wallet 2.0?

2023-05-18 14:17 UTC, kozarezvlad commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/data/di/OnboardingDataModule.kt
> +        return DefaultMnemonicRepository(Wordlist.getWordlist(application))
думаю да, все таки контекст более абстрактно. Хотя там в сдк андроида в наследовании размыто всё с контекстом

2023-05-19 06:37 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/redux/OnboardingWalletMiddleware.kt
> +@Suppress("LongMethod", "ComplexMethod")
Если это будет сноситься, то ок. Можете закрыть данный тред

2023-05-19 06:44 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseMediator.kt
> +interface SeedPhraseMediator {
Спасибо за подробный ответ, @gbixahue. Как мне кажется, если ты добавишь доку, то тогда вопрос снимется

2023-05-19 06:47 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +            is CompletionResult.Failure -> {
Я увидел данное упрощение. Мне кажется, что оно упрощает код, так как не видишь лишних обработок и тд. Кратко и понятно
```
if (result is CompletionResult.Success) {
     isFinished = true
}
```

2023-05-19 06:57 UTC, roman-pv commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +            is CompletionResult.Failure -> {
@Mama1emon так Антон выше же сказал 

> Учитывая тот случай, что может появится возможность обработки ошибки во viewModel

2023-05-19 06:59 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> -                maxFirmwareVersion = FirmwareVersion(major = 4, minor = 52),
ну тогда это стоит как фича тогл делать. Но тут точно должна быть возможность wallet 2.0 сканировать

2023-05-19 07:13 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> -                maxFirmwareVersion = FirmwareVersion(major = 4, minor = 52),
тогда да, стоит заюзать тоггл. Т.к. когда вольем в дев это пойдет в 4.6, но там еще не будет wallet 2.0

2023-05-19 10:11 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +    override fun ScreenContent(viewModel: SeedPhraseViewModel, maxProgress: Int) {
Вынес ViewModel, сделал функции stable

2023-05-19 10:12 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/api/OnboardingSeedPhrase.kt
> +            progress = progress.toFloat() / maxProgress,
переделал

2023-05-19 10:13 UTC, gbixahue commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +            is CompletionResult.Failure -> {
Мне кажется, что здесь можно оставить как есть.

2023-05-19 10:17 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingSeedPhraseStateHandler.kt
> +internal class OnboardingSeedPhraseStateHandler(
поправил

2023-05-19 10:17 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/ui/OnboardingWalletFragment.kt
> +                store.dispatch(OnboardingWallet2Action.ImportWallet(mnemonicComponents, callback))
выше ответил

2023-05-19 12:28 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> +    suspend fun resetToFactorySettings(cardId: String? = null): CompletionResult<CardDTO> {
В айосе была небольшая неразбериха, но в итоге там тоже сейчас без cardId будет здесь

2023-05-19 12:28 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/domain/TangemSdkManager.kt
> -                maxFirmwareVersion = FirmwareVersion(major = 4, minor = 52),
Переговорил с iOS командой, пока оставлю просто версию прошивки, нужно будет сделать как у них - убирать в тестовых версиях приложения ограничения конфига

2023-05-22 06:52 UTC, Yoggam1 approved these changes

2023-05-22 08:08 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/viewmodel/SeedPhraseViewModel.kt
> +            is CompletionResult.Failure -> {
@roman-pv так Антон выше же сказал
В связи с чем я и предложил)
> если есть альтернативы, которыми можно было бы все упростить сделать компактней, красивее?

2023-05-22 08:14 UTC, kozarezvlad requested changes
Последний вопрос, где идет развилка покажется новый или старый онбординг? или от карты будет зависеть?

2023-05-22 08:26 UTC, roman-pv commented
> Последний вопрос, где идет развилка покажется новый или старый онбординг? или от карты будет зависеть?

От карты зависит. Это Антон делал, wallet2State инициализируется, если карта wallet2.0

2023-05-22 08:27 UTC, kozarezvlad approved these changes

2023-05-22 08:40 UTC, merged