AND-3253 Implement scan chains
tangem/tangem-app-android-old pull request #924
Opened 2023-05-02 21:37 UTC by iiiburnyiii

2023-05-05 06:55 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/AnalyticsChain.kt
> +    private val event: AnalyticsEvent?,
мб сделать тут nonnull и просто не создавать chain когда нет события, чтобы не плодить ненужные объекты? или там не получится?

2023-05-05 06:55 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/CheckForNotCreatedWalletChain.kt
> +            OnboardingHelper.isOnboardingCase(previousChainResult) -> {
Сюда попадет если Wallet а то что ниже else для твинов? Мб как то явно выделить или комменты добавить

2023-05-05 06:55 UTC, kozarezvlad commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/DisclaimerChain.kt
> +internal class DisclaimerChain(
Было бы хорошо на каждый chain добавить доку что он делает в целом

2023-05-15 07:10 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/CheckForNotCreatedWalletChain.kt
> +class CheckForNotCreatedWalletChain(
Мне кажется, что используется не очень подходящее название. Здесь больше об онбординге, чем о не созданном кошельке.
Метод ScanChainException.WalletNotCreated - на сколько я помню он всего лишь отключает прогресс на кнопке.

2023-05-16 11:30 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/CheckForNotCreatedWalletChain.kt
> +            OnboardingHelper.isOnboardingCase(previousChainResult) -> {
Добавил коммент

2023-05-16 11:30 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/CheckForNotCreatedWalletChain.kt
> +class CheckForNotCreatedWalletChain(
Переименовал

2023-05-16 14:17 UTC, kozarezvlad submitted a review, later dismissed

2023-05-17 01:25 UTC, Mama1emon requested changes

2023-05-17 01:25 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/AnalyticsChain.kt
> +        val params = event.params.toMutableMap()
Не совсем понял момент с кастингом. Мьютабельная мапа нужна в interceptor?

2023-05-17 01:25 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/AnalyticsChain.kt
> + * @param event The analytics event to be handled by this chain.
Я предлагаю следовать [кодстайлу](https://kotlinlang.org/docs/kotlin-doc.html#block-tags) котлина и использовать нижний кейс для первой буквы. Кажется, что мелочь, но когда уже привык к другому гайдлайну, то заметно выбивается

2023-05-17 01:25 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/DisclaimerChain.kt
> +        return suspendCancellableCoroutine { continuation ->
Насколько реально в будущем уйти от данного способа передачи данных? Как мне кажется, он совершенно неявный

2023-05-17 01:25 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/ScanChainException.kt
> +    data class OnboardingNeeded(val whereToNavigate: AppScreen) : ScanChainException()
Предлагаю называть переменные, как существительные. Иначе, когда видишь связку `where to navigate`, то не совсем явно, что это.
Если эта переменная используется для перехода при возникновении ошибки, то я предлагаю назвать ее `returnRoute`

2023-05-17 01:25 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/ScanChainException.kt
> +    data class OnboardingNeeded(val whereToNavigate: AppScreen) : ScanChainException()
Также, так как добавил доку, то хорошо бы указать в ней `property`

2023-05-17 09:08 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/DisclaimerChain.kt
> +        return suspendCancellableCoroutine { continuation ->
Кажется достаточно реально, но не в рамках этого таска. Тут я логику по большей части просто скопировал из `ScanCardProcessor`

2023-05-17 12:38 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/scanCard/chains/AnalyticsChain.kt
> +        val params = event.params.toMutableMap()
Ага

2023-05-17 12:53 UTC, kozarezvlad approved these changes

2023-05-17 13:04 UTC, Mama1emon approved these changes

2023-05-17 13:21 UTC, merged