AND-3253 Use card scanning use case in app
tangem/tangem-app-android-old pull request #925
Opened 2023-05-02 22:01 UTC by iiiburnyiii

2023-05-18 09:27 UTC, kozarezvlad requested changes
Предлагаю лить после этого, надо уже закончить влитие wallet 2.0
https://github.com/tangem/tangem-app-android/pull/920

2023-05-29 07:48 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/domain/scanCard/LegacyScanProcessor.kt
> +internal object LegacyScanProcessor {
Это перенос старой логики сканирования из `ScanCardProcessor`, можно особо не ревьюить

2023-05-30 07:13 UTC, Mama1emon requested changes

2023-05-30 07:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/MainActivity.kt
> +    lateinit var tangemSdkInjected: TangemSdk
Как мне кажется, лучше слова `injected` перенести в начало. Так как обычно названия полей являются существительными

2023-05-30 07:13 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/ActivityModule.kt
> +@InstallIn(ActivityComponent::class)
А данные компоненты не должны ли быть синглтонами в приложении?

2023-05-30 07:13 UTC, Mama1emon commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "4.7.0"
А почему версию поднял? Вроде как это уже в 4,6 идет?

2023-05-30 07:26 UTC, kozarezvlad commented on core/featuretoggles/src/main/assets/configs/feature_toggles_config.json
> +        "version": "4.7.0"
не, не идет, это не тестили в 4.6

2023-05-30 10:12 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/di/ActivityModule.kt
> +@InstallIn(ActivityComponent::class)
Их не получиться провайдить в приложении, так как наша SDK зависит от активити

2023-05-30 11:08 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/ActivityModule.kt
> +@InstallIn(ActivityComponent::class)
Не получиться заюзать ActivityRetainedScope?

2023-05-30 12:15 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/di/ActivityModule.kt
> +@InstallIn(ActivityComponent::class)
Не получиться, тут нужно контекст активити предоставлять

2023-05-30 12:15 UTC, kozarezvlad approved these changes, later dismissed

2023-05-31 03:59 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/di/ActivityModule.kt
> +@InstallIn(ActivityComponent::class)
Расскажи, пожалуйста, поподробнее, чем не подходит ActivityRetainedScope? Просто это позволит нам наверняка не тратить ресы на повторное создание тяжелых зависимостей

2023-05-31 06:23 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/di/ActivityModule.kt
> +@InstallIn(ActivityComponent::class)
SDK завязан на контекст и ЖЦ конкретной активити, он должен пересоздаться после пересоздания этой активити, как и все остальные сущности в этом модуле, так как они зависят от SDK. А Reatained стартует при старте первой активит и разрушается после разрушения последней, тут это не подходит

2023-05-31 08:32 UTC, Mama1emon approved these changes

2023-05-31 08:33 UTC, kozarezvlad approved these changes

2023-05-31 08:33 UTC, merged