AND-3527 Change internet connection detecting strategy
tangem/tangem-app-android-old pull request #941
Opened 2023-05-10 06:03 UTC by Yoggam1

2023-05-10 08:25 UTC, Mama1emon requested changes

2023-05-10 08:25 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/connection/RealInternetConnectionManager.kt
> +class RealInternetConnectionManager @Inject constructor(): NetworkConnectionManager {
1) internal?
2) Предлагаю не инжектить непосредственно этот компонент в DI-граф, а сразу создавать его в Dagger-модуле, чтобы не заставлять DI генерить лишнее

2023-05-10 08:25 UTC, Mama1emon commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkConnectionModule.kt
> +        realInternetConnectionManager: RealInternetConnectionManager,
AndroidNetworkConnectionManager удалишь?

2023-05-14 21:00 UTC, Yoggam1 commented on core/datasource/src/main/java/com/tangem/datasource/di/NetworkConnectionModule.kt
> +        realInternetConnectionManager: RealInternetConnectionManager,
Удалил

2023-05-14 21:00 UTC, Yoggam1 commented on core/datasource/src/main/java/com/tangem/datasource/connection/RealInternetConnectionManager.kt
> +class RealInternetConnectionManager @Inject constructor(): NetworkConnectionManager {
Исправил

2023-05-15 06:59 UTC, Mama1emon approved these changes

2023-05-15 06:59 UTC, merged