AND-3280: add analytics for Wallet 2.0 onboarding
tangem/tangem-app-android-old pull request #976
Opened 2023-05-23 06:57 UTC by roman-pv

2023-05-24 07:54 UTC, Yoggam1 submitted a review, later dismissed

2023-05-25 06:23 UTC, Mama1emon requested changes

2023-05-25 06:23 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/common/analytics/events/AnalyticsParam.kt
> +        const val CreationType = "Creation type"
Предлагаю зарефачить этот момент и использовать нейминг согласно гайдлайнам котлина
https://kotlinlang.org/docs/coding-conventions.html#property-names

2023-05-25 06:23 UTC, Mama1emon commented on features/onboarding/src/main/java/com/tangem/feature/onboarding/presentation/wallet2/analytics/SeedPhraseEvents.kt
> +    "Onboarding / Create Wallet",
Хорошо бы добавить naming args

2023-05-25 13:56 UTC, roman-pv commented on app/src/main/java/com/tangem/tap/common/analytics/events/AnalyticsParam.kt
> +        const val CreationType = "Creation type"
предложения вне задачи лучше выноси вначале на короткое обсуждение /голосовалку  в канал, там решим, нужно ли

2023-05-26 07:13 UTC, kozarezvlad approved these changes

2023-05-26 09:23 UTC, Mama1emon approved these changes

2023-05-26 10:42 UTC, merged