AND-2793 prevent showing currency selection dialog for send if nothin…
tangem/tangem-app-android-old pull request #981
Opened 2023-05-25 06:01 UTC by gbixahue

2023-05-25 06:16 UTC, Mama1emon requested changes

2023-05-25 06:16 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                        if (sendableAmounts.size != 1) {
Как предложение, можно вынести в константу, название которой объяснит смысл ее. Но на твое усмотрение

2023-05-25 06:16 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                            amount = sendableAmounts.first(),
Правильно понимаю, что если `sendableAmounts.size == 1`, то вылетит исключение?

2023-05-25 06:35 UTC, gbixahue commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                            amount = sendableAmounts.first(),
Вылетит исключение, если size будет равен 0. Проверка на 0 делается выше, на 170 строке

2023-05-26 08:19 UTC, Mama1emon approved these changes

2023-05-26 08:25 UTC, Mama1emon approved these changes, later dismissed

2023-05-26 08:25 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/wallet/redux/middlewares/WalletMiddleware.kt
> +                            amount = sendableAmounts.first(),
Там проверка на 1, что также не исключает ситуации больше 1. Мб тогда явно сделать проверку на 0

2023-06-01 07:09 UTC, Yoggam1 submitted a review, later dismissed

2023-06-01 07:17 UTC, Sateetas submitted a review, later dismissed

2023-06-01 13:45 UTC, kozarezvlad approved these changes

2023-06-01 13:46 UTC, kozarezvlad approved these changes

2023-06-01 13:53 UTC, Yoggam1 approved these changes

2023-06-01 14:48 UTC, Sateetas approved these changes

2023-06-07 05:53 UTC, merged