AND-3312 Moved app to use TransactionFee instead fees list.
tangem/tangem-app-android-old pull request #993
Opened 2023-05-29 17:28 UTC by Sateetas

2023-05-30 07:07 UTC, Mama1emon requested changes

2023-05-30 07:07 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/demo/DemoHelper.kt
> +                minimum = Amount(0.0001.toBigDecimal(), blockchain),
Предлагаю сразу вынести в константы. В blockchain sdk я пока детект не добавил, но потом точно придется исправлять.
Предлагаю назвать как-нибудь так - `MINIMAL_FEE_KOEFFECIENT`

2023-05-30 07:07 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/saltPay/GnosisRegistrator.kt
> +                        Result.Success((data as TransactionFee.Choosable).normal)
Предлагаю использовать безопасный кастинг и явную обработку

2023-05-30 07:07 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/features/send/redux/reducers/FeeReducer.kt
> +                when (fees) {
Вроде как можно совместить 57 и 58 строчку.
`when(val fees = action.fee) { }`

2023-05-30 07:07 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/proxy/TransactionManagerImpl.kt
> +                            fee = convertToProxyAmount(amount = (fee.data as TransactionFee.Single).value),
Чтобы избавиться от кастинга, можно объявить переменную в сигнатуре `when`

2023-05-30 07:07 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/network/exchangeServices/CurrencyExchangeManager.kt
> +    val fee = feeResult.data.minimum
Ренейминг ты вливал раньше? А то я пропустил этот момент...
Все круто, единственный вопрос по неймингу данной переменной - вроде как название `minimal` больше подходит. Иначе оно выделяется, так как все прилагательные, а она существительное. Плюс как-то привычно читать `minimal`.

2023-05-30 11:08 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/demo/DemoHelper.kt
> +                minimum = Amount(0.0001.toBigDecimal(), blockchain),
+ по поводу выноса

- по поводу нейминга MINIMAL_FEE_KOEFFECIENT, это же суть цены, а не коэффициент

2023-05-30 11:09 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/demo/DemoHelper.kt
> +                minimum = Amount(0.0001.toBigDecimal(), blockchain),
minimumFee
normalFee
priorityFee

будет ок

2023-05-30 11:26 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/network/exchangeServices/CurrencyExchangeManager.kt
> +    val fee = feeResult.data.minimum
не, тут как раз minimum должен быть
он про минимальное из счетного множества, а minimal более абстрактное
https://grammarhow.com/minimum-vs-minimal/

и если на нашу сферу укладывать, в гугле количество результатов по "minimum fee" в 8 раз больше, чем по "minimal fee"

2023-05-30 11:32 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/proxy/TransactionManagerImpl.kt
> +                            fee = convertToProxyAmount(amount = (fee.data as TransactionFee.Single).value),
не, тут проблема в том, что нам в любом случае придется каст делать, потому что смарткаст не работает, если используем сущности из другого модуля 
и в `when (fee.data)` тем более не получится это сделать, потому что там я бью на `Single`/`Choosable`

но для лучшей читаемости вынесу этот каст в первую строчку блока `is TransactionFee.Single -> {...}`

2023-05-30 11:34 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/onboarding/products/wallet/saltPay/GnosisRegistrator.kt
> +                        Result.Success((data as TransactionFee.Choosable).normal)
здесь ситуация аналогична
https://github.com/tangem/tangem-app-android/pull/993#discussion_r1210139223

2023-05-30 11:42 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/send/redux/reducers/FeeReducer.kt
> +                when (fees) {
ага

2023-05-31 03:57 UTC, Mama1emon commented on app/src/main/java/com/tangem/tap/network/exchangeServices/CurrencyExchangeManager.kt
> +    val fee = feeResult.data.minimum
Ой, ну все-все. Задушил... 😆

2023-06-06 01:20 UTC, Mama1emon approved these changes

2023-06-07 05:21 UTC, iiiburnyiii approved these changes

2023-06-07 05:21 UTC, iiiburnyiii commented on app/src/main/java/com/tangem/tap/features/send/redux/reducers/FeeReducer.kt
> +                //  TODO?
nit: Может описание что нужно сделать докинуть?

2023-06-07 15:48 UTC, Sateetas commented on app/src/main/java/com/tangem/tap/features/send/redux/reducers/FeeReducer.kt
> +                //  TODO?
ага, только сделал это в другой части рефакторинга
https://github.com/tangem/tangem-app-android/pull/1018/commits/2d095d7333cf0d904d5836ec4adbdff880297956

иначе конфликты будут

2023-06-15 16:39 UTC, merged